import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),ts=require('typescript');
const root=fileURLToPath(new URL('../',import.meta.url)),cache=new Map();
function load(file){const absolute=path.resolve(root,file);if(cache.has(absolute))return cache.get(absolute).exports;if(absolute.endsWith('.json'))return JSON.parse(fs.readFileSync(absolute,'utf8'));const loadedModule={exports:{}};cache.set(absolute,loadedModule);const code=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const localRequire=name=>name.startsWith('.')?load(path.resolve(path.dirname(absolute),name+(/\.(ts|json)$/.test(name)?'':'.ts'))):require(name);new Function('require','module','exports',code)(localRequire,loadedModule,loadedModule.exports);return loadedModule.exports}
const {seedCatalog,catalogForTerrain,catalogDestination,catalogGuidance,catalogSources,activeDestinations}=load('lib/catalog-seed.ts');
const {createCatalogDraft,editCatalogDraft,emptyDestination,sourceIsUsed,sourceReviewOverdue,splitTokens}=load('lib/catalog-editor-model.ts');
const {validateCatalog,validateDraft}=load('lib/catalog-validation.ts');
const {selectionFromQuery}=load('lib/explorer-location.ts');
const {catalogCopy}=load('lib/catalog-copy.ts');
test('compiled catalog is publishable and all sources resolve within the snapshot',()=>{assert.doesNotThrow(()=>validateCatalog(seedCatalog,true));for(const d of seedCatalog.destinations)for(const id of [...d.sourceIds,...d.sections.flatMap(s=>s.sourceIds),...d.species.flatMap(s=>s.sourceIds)])assert.equal(catalogSources(seedCatalog,[id]).length,1);for(const t of ['desert','mountain','forest','coast'])assert.deepEqual(catalogGuidance(seedCatalog,t).sections.map(s=>s.id),['deeper','equipment','nature','hazard']);assert.equal(catalogDestination(seedCatalog,'black-forest').timezone,'Europe/Berlin')});
test('additional destination uses its ID while legacy category links remain stable',()=>{const snapshot=structuredClone(seedCatalog),added={...structuredClone(snapshot.destinations[3]),id:'new-coast',lat:1,lon:2};snapshot.destinations.unshift(added);assert.equal(activeDestinations(snapshot).length,seedCatalog.destinations.length+1);assert.equal(catalogForTerrain(snapshot,3).id,'hurghada');assert.equal(catalogDestination(snapshot,'new-coast').terrainIndex,3);assert.deepEqual(selectionFromQuery(new URLSearchParams('destination=new-coast'),snapshot.destinations),{destinationId:'new-coast',terrainId:'coast',lat:1,lon:2});assert.doesNotThrow(()=>validateCatalog(snapshot,true))});
test('archiving removes new selection but preserves stable historical lookup',()=>{const snapshot=structuredClone(seedCatalog);snapshot.destinations[0].archived=true;assert.equal(activeDestinations(snapshot).length,seedCatalog.destinations.length-1);assert.equal(catalogDestination(snapshot,'liwa').id,'liwa');assert.equal(catalogForTerrain(snapshot,0).id,'wadi-rum');for(const d of snapshot.destinations)if(d.terrainId==='desert')d.archived=true;assert.equal(catalogForTerrain(snapshot,0),undefined)});
test('draft edits do not mutate published snapshot and invalidate reviews',()=>{const draft=createCatalogDraft(seedCatalog,'draft-1');draft.reviewedLocales=['ar','en','fr','zh','hi'];const edited=editCatalogDraft(draft,s=>{s.destinations[0].names[1]='Edited';s.sources[0].title='Changed citation'});assert.equal(seedCatalog.destinations[0].names[1],draft.snapshot.destinations[0].names[1]);assert.notEqual(edited.snapshot.destinations[0].names[1],draft.snapshot.destinations[0].names[1]);assert.deepEqual(edited.reviewedLocales,[]);assert.equal(draft.reviewedLocales.length,5);assert.doesNotThrow(()=>validateDraft(edited))});
test('missing translations block publication and unused or overdue sources are identified',()=>{const snapshot=structuredClone(seedCatalog);snapshot.destinations[0].names[4]='';assert.throws(()=>validateCatalog(snapshot,true));assert.equal(sourceIsUsed(seedCatalog,'liwa-culture'),true);assert.equal(sourceIsUsed(seedCatalog,'unknown'),false);assert.equal(sourceReviewOverdue('2025-01-01',Date.parse('2026-09-17')),true);assert.equal(sourceReviewOverdue('2026-09-17',Date.parse('2026-09-17')),false)});
test('new destinations remain unverified and all new UI states cover five languages',()=>{const d=emptyDestination(seedCatalog,'new-destination');assert.deepEqual(d.names,['','','','','']);assert.deepEqual(d.sourceIds,[]);assert.deepEqual(d.species,[]);assert.equal(d.timezone,'');assert.equal(d.terrainId,'desert');assert.deepEqual(splitTokens('walking, camping, walking, '),['walking','camping']);for(const[key,value]of Object.entries(catalogCopy))assert.ok(value.length===5&&value.every(v=>v.trim()),key)});
test('snapshot helpers return revised source and chapter together without altering baseline',()=>{const snapshot=structuredClone(seedCatalog);snapshot.revision=2;snapshot.sources[0].title='Revision two citation';snapshot.destinations[0].sections[0].body[1]='Revision two local guidance';assert.equal(catalogSources(snapshot,['liwa-culture'])[0].title,'Revision two citation');assert.equal(catalogDestination(snapshot,'liwa').sections[0].body[1],'Revision two local guidance');assert.notEqual(catalogSources(seedCatalog,['liwa-culture'])[0].title,'Revision two citation')});

