import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {IDBFactory} from 'fake-indexeddb';
const code=fs.readFileSync(new URL('../public/offline-shell.js',import.meta.url),'utf8');
class Element{constructor(tag='div'){this.tag=tag;this.children=[];this.disabled=false;this._text='';this.attributes=new Map()}set textContent(text){this._text=String(text);this.children=[]}get textContent(){return this._text}append(...children){for(const child of children){child.parent=this;this.children.push(child)}}replaceChildren(){this.children=[];this._text=''}remove(){if(this.parent)this.parent.children=this.parent.children.filter(child=>child!==this)}focus(){this.focused=true}setAttribute(key,value){this.attributes.set(key,value)}getAttribute(key){return this.attributes.get(key)}click(){return this.onclick?.()}}
function descendants(element,tag){return element.children.flatMap(child=>[...(child.tag===tag?[child]:[]),...descendants(child,tag)])}
async function harness({pending=false,locale='en',legacyOnly=false,future=false}={}){
 const indexedDB=new IDBFactory();async function open(name,stores){return new Promise((resolve,reject)=>{const req=indexedDB.open(name,1);req.onupgradeneeded=()=>{for(const store of stores)req.result.createObjectStore(store,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
 const db=await open('daroub-preparation-v2',['records','outbox','meta']),old=await open('daroub-toolkit',['records','outbox','guides']);
 const put=(store,key,value,database=db)=>new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put({key,value});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}),read=(store,key,database=db)=>new Promise((resolve,reject)=>{const req=database.transaction(store).objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}),all=(store,database=db)=>new Promise((resolve,reject)=>{const req=database.transaction(store).objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
 const entry={id:'entry-1',title:'Morning walk',activityId:'walking',place:'Trail',startTime:'08:00',timeZone:'Asia/Dubai',durationMinutes:60,transport:'on-foot',notes:'Keep this note',coordinates:{lat:23,lon:54}};
 const trip={id:'trip-1',schemaVersion:future?3:2,title:'Private trip',notes:'Private notes',terrainId:'desert',destinationId:'liwa',location:{lat:23.14,lon:53.78},startDate:'2026-09-20',endDate:'2026-09-21',groupSize:2,transport:'4x4',revision:0,updatedAt:'2026-09-17T00:00:00.000Z',activities:['walking'],suggestionDecisions:[{key:'water-rule',fingerprint:'abc',decision:'dismissed'}],catalogRevision:3,checklist:[{id:'water',label:'Water',category:'essentials',kind:'equipment',requiredQuantity:2,assignedQuantity:1,packedQuantity:0,done:false,gearId:'gear-1',gearSnapshot:{name:'Water bottles',quantity:2,condition:'ready'}},{id:'contact',label:'Contact plan',category:'task',kind:'task',done:false}],itinerary:[{id:'day-1',dayOffset:0,entries:[entry]}]},key=JSON.stringify(['owner-a','trip',trip.id]);
 const gear={id:'gear-1',schemaVersion:2,name:'Water bottles',category:'essentials',equipmentId:'water',quantity:2,condition:'ready',maintenanceDate:'',expiryDate:'',notes:'Gear notes',archived:false,revision:0,updatedAt:'2026-09-17T00:00:00.000Z'},gearKey=JSON.stringify(['owner-a','gear',gear.id]);
 await put('records',key,{owner:'owner-a',entity:'trip',record:trip,deleted:false},legacyOnly?old:db);if(!legacyOnly){await put('records',gearKey,{owner:'owner-a',entity:'gear',record:gear,deleted:false});await put('records','other-trip',{owner:'owner-b',entity:'trip',record:{...trip,title:'Other private trip'},deleted:false});await put('records','other-gear',{owner:'owner-b',entity:'gear',record:{...gear,name:'Other private gear'},deleted:false})}await put('guides','guide',{title:'Public guide',locale,html:'<h1>Guide</h1>'},old);if(pending)await put('outbox',key,{owner:'owner-a',writer:'another-tab',mutation:{operationId:'original-operation',protocol:2,entity:'trip',id:trip.id,baseRevision:0,payload:trip}});
 const values=new Map([['daroub-offline-account',JSON.stringify({userId:'owner-a'})],['daroub-account-generation','epoch-a'],['daroub-preferences',JSON.stringify({locale})]]),nodes=new Map(),listeners=new Map();const document={documentElement:{style:{}},querySelector:selector=>{if(!nodes.has(selector))nodes.set(selector,new Element());return nodes.get(selector)},createElement:tag=>new Element(tag),createTextNode:text=>{const el=new Element('#text');el.textContent=text;return el}};const localStorage={getItem:key=>values.get(key)??null};await vm.runInNewContext(code,{document,localStorage,indexedDB,crypto,Date,Intl,JSON,TextEncoder,Map,Set,Promise,Error,Number,NaN,URL,Blob,setTimeout,confirm:()=>true,location:{assign(){}},addEventListener:(name,callback)=>listeners.set(name,callback)});
 const field=(key,container='#trips')=>[...descendants(nodes.get(container),'input'),...descendants(nodes.get(container),'select'),...descendants(nodes.get(container),'textarea')].find(input=>input.getAttribute('data-field')===key);
 return{trip,gear,key,gearKey,put,read,all,old,db,values,nodes,listeners,document,field,buttons:container=>descendants(nodes.get(container),'button'),async change(key,value,container='#trips'){const input=field(key,container);assert.ok(input,key);if(input.type==='checkbox')input.checked=value;else input.value=String(value);return input.onchange()},storage(key,value){if(value===null)values.delete(key);else values.set(key,value);listeners.get('storage')?.({key})}};
}
test('offline v2 shows only current account data and immediately hides both entities on sign-out',async()=>{const h=await harness();assert.equal(descendants(h.nodes.get('#trips'),'h3').length,1);assert.equal(descendants(h.nodes.get('#gear'),'h3').length,1);assert.equal(descendants(h.nodes.get('#trips'),'h3')[0].textContent,'Private trip');const stale=h.field('check-contact');h.storage('daroub-offline-account',null);assert.equal(descendants(h.nodes.get('#trips'),'input').length,0);assert.equal(descendants(h.nodes.get('#gear'),'input').length,0);assert.equal(h.buttons('#private-actions').length,0);assert.equal(h.buttons('#guides').length,1);stale.checked=true;await stale.onchange();assert.equal((await h.all('outbox')).length,0);assert.match(h.nodes.get('#status').textContent,/Account changed/)});
test('legacy private records are not silently copied or mutated; guides remain available',async()=>{const h=await harness({legacyOnly:true});assert.equal(descendants(h.nodes.get('#trips'),'input').length,0);assert.equal(h.buttons('#guides').length,1);assert.equal((await h.all('records')).length,0);assert.equal((await h.all('records',h.old)).length,1)});
test('quantity updates remain partial until required quantity is packed',async()=>{const h=await harness();await h.change('check-water-packedQuantity',1);let saved=(await h.read('records',h.key)).value.record;assert.equal(saved.checklist[0].done,false);assert.equal(saved.checklist[0].packedQuantity,1);await h.change('check-water-packedQuantity',2);saved=(await h.read('records',h.key)).value.record;assert.equal(saved.checklist[0].done,true);assert.equal(saved.checklist[0].assignedQuantity,1);const pending=(await h.read('outbox',h.key)).value;assert.equal(pending.mutation.protocol,2);await h.change('check-water-requiredQuantity',1);assert.equal((await h.read('records',h.key)).value.record.checklist[0].requiredQuantity,2);assert.match(h.nodes.get('#status').textContent,/Invalid/)});
test('task edits merge freshest records and preserve all new schema fields',async()=>{const h=await harness();const row=await h.read('records',h.key);row.value.record.checklist[0].packedQuantity=1;row.value.record.revision=4;row.value.record.itinerary[0].entries[0].notes='Fresh schedule note';await h.put('records',h.key,row.value);await h.change('check-contact',true);const saved=(await h.read('records',h.key)).value.record;assert.equal(saved.checklist[0].packedQuantity,1);assert.equal(saved.checklist[1].done,true);assert.equal(saved.itinerary[0].entries[0].notes,'Fresh schedule note');assert.deepEqual(saved.suggestionDecisions,h.trip.suggestionDecisions);assert.equal(saved.catalogRevision,3);assert.equal((await h.read('outbox',h.key)).value.mutation.baseRevision,4)});
test('a deleted trip cannot be resurrected from a stale offline control',async()=>{const h=await harness(),input=h.field('check-contact');const row=await h.read('records',h.key);row.value.deleted=true;await h.put('records',h.key,row.value);input.checked=true;await input.onchange();assert.equal((await h.all('outbox')).length,0);assert.equal((await h.read('records',h.key)).value.deleted,true);assert.equal(descendants(h.nodes.get('#trips'),'input').length,0)});
test('other-tab pending edits survive while repeated offline edits share one conflict copy',async()=>{const h=await harness({pending:true});await h.change('check-contact',true);let rows=await h.all('outbox');assert.equal(rows.length,2);assert.equal((await h.read('outbox',h.key)).value.mutation.operationId,'original-operation');const copy=rows.find(row=>row.key!==h.key);assert.equal(copy.value.mutation.payload.conflictOf,'trip-1');await h.change('entry-entry-1-notes','My offline note');rows=await h.all('outbox');assert.equal(rows.length,2);const saved=(await h.read('outbox',copy.key)).value.mutation.payload;assert.equal(saved.itinerary[0].entries[0].notes,'My offline note');assert.equal((await h.read('records',h.key)).value.record.itinerary[0].entries[0].notes,'Keep this note')});
test('generation changes abort an in-flight private transaction',async()=>{const h=await harness(),input=h.field('check-contact');input.checked=true;const saving=input.onchange();h.storage('daroub-account-generation','epoch-b');await saving;assert.equal((await h.all('outbox')).length,0);assert.equal((await h.read('records',h.key)).value.record.checklist[1].done,false);assert.equal(descendants(h.nodes.get('#gear'),'input').length,0)});
test('gear edits remain independent of trip snapshots and reject invalid quantity',async()=>{const h=await harness();await h.change('gear-quantity',5,'#gear');await h.change('gear-archived',true,'#gear');const gear=(await h.read('records',h.gearKey)).value.record;assert.equal(gear.quantity,5);assert.equal(gear.archived,true);assert.equal((await h.read('records',h.key)).value.record.checklist[0].gearSnapshot.quantity,2);assert.equal((await h.read('outbox',h.gearKey)).value.mutation.entity,'gear');await h.change('gear-quantity',-1,'#gear');assert.equal((await h.read('records',h.gearKey)).value.record.quantity,5)});
test('itinerary edits preserve coordinates, reject bad zones and keep out-of-range days visible',async()=>{const h=await harness();await h.change('entry-entry-1-durationMinutes',90);let trip=(await h.read('records',h.key)).value.record;assert.equal(trip.itinerary[0].entries[0].durationMinutes,90);assert.deepEqual(trip.itinerary[0].entries[0].coordinates,{lat:23,lon:54});await h.change('entry-entry-1-timeZone','Not/AZone');assert.equal((await h.read('records',h.key)).value.record.itinerary[0].entries[0].timeZone,'Asia/Dubai');await h.change('day-day-1',4);trip=(await h.read('records',h.key)).value.record;assert.equal(trip.itinerary[0].dayOffset,3);assert.ok(descendants(h.nodes.get('#trips'),'p').some(p=>p.textContent.includes('outside trip dates')));assert.equal(trip.itinerary[0].entries.length,1)});
test('offline entry duplication and creation use new IDs and protocol2',async()=>{const h=await harness();await h.buttons('#trips').find(b=>b.textContent==='Duplicate').onclick();let trip=(await h.read('records',h.key)).value.record;assert.equal(trip.itinerary[0].entries.length,2);assert.notEqual(trip.itinerary[0].entries[0].id,trip.itinerary[0].entries[1].id);await h.buttons('#trips').find(b=>b.textContent==='Add day').onclick();trip=(await h.read('records',h.key)).value.record;assert.equal(trip.itinerary.length,2);await h.buttons('#private-actions').find(b=>b.textContent==='Add equipment').onclick();const records=await h.all('records');assert.equal(records.filter(r=>r.value.owner==='owner-a'&&r.value.entity==='gear').length,2);assert.equal((await h.all('outbox')).find(r=>r.value.mutation.entity==='gear').value.mutation.protocol,2)});
test('future schemas stay read-protected and offline labels cover all five locales',async()=>{const future=await harness({future:true});assert.equal(descendants(future.nodes.get('#trips'),'input').length,0);assert.match(future.nodes.get('#status').textContent,/upgrade/);for(const locale of ['ar','en','fr','zh','hi']){const h=await harness({locale});assert.equal(h.document.documentElement.lang,locale);assert.equal(h.document.documentElement.dir,locale==='ar'?'rtl':'ltr');assert.ok(h.nodes.get('#gear-title').textContent.length>0);assert.ok(h.nodes.get('#trips-title').textContent.length>0)}});
