import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const require=createRequire(import.meta.url);
async function load(file){const result=await build({entryPoints:[file],bundle:true,write:false,format:'cjs',platform:'node',packages:'external',loader:{'.css':'empty'}}),compiled={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(require,compiled,compiled.exports);return compiled.exports}
const {QuantityChecklist}=await load('components/quantity-checklist.tsx'),{PackingSuggestionRow,packingReviewItems}=await load('components/packing-panel.tsx'),{checklistWords,checklistText}=await load('lib/checklist-copy.ts'),{packingWords,packingText}=await load('lib/packing-copy.ts');
const base={id:'trip-a',title:'Trip',schemaVersion:2,terrainId:'desert',destinationId:'liwa',location:{lat:23,lon:54},startDate:'2026-11-01',endDate:'2026-11-02',groupSize:8,transport:'car',notes:'',checklist:[],activities:[],itinerary:[],revision:1,updatedAt:'2026-09-17T00:00:00Z',suggestionDecisions:[]};
const row={id:'lamp',label:'Headlamp',category:'essentials',kind:'equipment',done:false,requiredQuantity:4,assignedQuantity:0,packedQuantity:1};
const suggestion={key:'equipment:water',fingerprint:'fingerprint',equipmentId:'water',label:'Water containers',category:'essentials',quantity:8,quantityBasis:'person',available:0,reason:'Refill points are far apart on this route.',sourceIds:['source'],catalogRevision:1,coverage:'terrain-example',destinationSpecific:true};
const catalog={schemaVersion:1,revision:1,publishedAt:'2026-09-17',destinations:[],packingRules:[],terrainGuidance:[],sources:[{id:'source',title:'Official guide',url:'https://example.org/guide',reviewedAt:'2026-09-17'}]};
const checklist=(trip,locale='en')=>renderToStaticMarkup(React.createElement(QuantityChecklist,{trip,locale,onChange:()=>{},gear:[],trips:[trip]}));
const suggestionHtml=(item=suggestion,trip=base,locale='en',busy=false)=>renderToStaticMarkup(React.createElement(PackingSuggestionRow,{suggestion:item,trip,locale,catalog,gear:[],onAccept:()=>{},onDismiss:()=>{},busy,formOwner:'external-draft-form'}));

test('packing progress counts completed entries while row labels explain physical packing',()=>{const equipment=checklist({...base,checklist:[row]});assert.match(equipment,/<progress[^>]*value="0"[^>]*max="1"/);assert.match(equipment,/Packed 1 of 4/);assert.match(equipment,/Actually packed/);assert.match(equipment,/2 packed out of 3 means one unit still needs packing/);assert.doesNotMatch(equipment,/No inventory link/);const task=checklist({...base,checklist:[{id:'phone',label:'Charge phone',kind:'task',category:'custom',done:true}]});assert.match(task,/<progress[^>]*value="1"[^>]*max="1"/);const empty=checklist(base);assert.doesNotMatch(empty,/<progress/)});
test('invalid transient target values remain editable with safe numeric bounds',()=>{const html=checklist({...base,checklist:[{...row,requiredQuantity:NaN,packedQuantity:NaN}]});assert.match(html,/id="kit-detail-lamp"/);assert.match(html,/max="10000"/);assert.doesNotMatch(html,/max="NaN"/);assert.match(html,/Check quantities in item details/);assert.match(html,/Quantity I plan to bring/)});
test('an invalid reservation without linked equipment has an explicit recovery control',()=>{const html=checklist({...base,checklist:[{...row,assignedQuantity:NaN}]});assert.match(html,/<details class="kit-inventory" open="">/);assert.match(html,/Clear inventory reservation/);assert.doesNotMatch(checklist({...base,checklist:[row]}),/Clear inventory reservation/)});
test('water reason and quantity basis are visible before any optional inventory or source disclosure',()=>{const html=suggestionHtml();const firstDisclosure=html.indexOf('<details');assert.ok(html.indexOf(suggestion.reason)>0&&html.indexOf(suggestion.reason)<firstDisclosure);assert.ok(html.indexOf('1 per person × 8 people = 8')<firstDisclosure);assert.ok(html.indexOf('This count is not litres of water')<firstDisclosure);assert.match(html,/<details class="packing-adjust">/);assert.match(html,/<div class="packing-inventory">/);assert.equal((html.match(/<details/g)||[]).length,1);assert.match(html,/form="external-draft-form"/);assert.match(html,/aria-describedby="[^"]+-basis [^"]+-supply"/)});
test('food, group and old-catalog fallbacks explain counts without claiming supply sufficiency',()=>{assert.match(suggestionHtml({...suggestion,equipmentId:'food'}),/not a meal count or a sufficient food allowance/);assert.match(suggestionHtml({...suggestion,equipmentId:'tent',quantity:1,quantityBasis:'group'}),/whole group: 1, not per person/);assert.match(suggestionHtml({...suggestion,equipmentId:'tent',quantityBasis:undefined}),/starting planning count/)});
test('updating an existing item explicitly replaces the target and retains its current inventory assignment',()=>{const html=suggestionHtml(suggestion,{...base,checklist:[{...row,equipmentId:'water',requiredQuantity:3,gearId:'owned',assignedQuantity:2}]});assert.match(html,/New total target/);assert.match(html,/replaces the item/);assert.match(html,/<option value="__keep__" selected="">Keep current assignment/);assert.match(html,/Update total/);assert.doesNotMatch(html,/<form/)});
test('destination targeting controls initial ordering while evidence coverage remains unchanged',()=>{const common=Array.from({length:5},(_,i)=>({...suggestion,key:'item-'+i,equipmentId:'item-'+i,destinationSpecific:false})),tailored={...suggestion,key:'tailored',destinationSpecific:true,coverage:'terrain-example'},items=[...common,tailored],original=structuredClone(items);const short=packingReviewItems(items,base);assert.equal(short.visible.length,4);assert.equal(short.visible[0].key,'tailored');assert.equal(short.visible[0].coverage,'terrain-example');assert.deepEqual(items,original);assert.equal(packingReviewItems(items,base,false,true).visible.length,6);const reviewed={...base,suggestionDecisions:[{key:'tailored',fingerprint:'fingerprint',decision:'accepted'}]};assert.equal(packingReviewItems(items,reviewed).visible.some(s=>s.key==='tailored'),false);assert.equal(packingReviewItems(items,reviewed,true).visible[0].key,'tailored');const changed={...reviewed,suggestionDecisions:[{key:'tailored',fingerprint:'old',decision:'accepted'}]};assert.equal(packingReviewItems(items,changed).visible[0].key,'tailored')});
test('all five languages render human-readable count guidance without missing template markers',()=>{for(const locale of ['ar','en','fr','zh','hi']){const html=suggestionHtml(suggestion,base,locale);assert.doesNotMatch(html,/\{(?:people|total|each|count)\}/);assert.ok(html.includes(packingText(locale,'waterCount')));assert.ok(checklist({...base,checklist:[row]},locale).includes(checklistText(locale,'countExample')))}for(const words of [checklistWords,packingWords])for(const [key,values] of Object.entries(words)){assert.equal(values.length,5,key);assert.ok(values.every(text=>typeof text==='string'&&text.trim()),key)}});
