import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),ts=require('typescript');
const root=fileURLToPath(new URL('../',import.meta.url)),cache=new Map();
function load(file){const absolute=path.resolve(root,file);if(cache.has(absolute))return cache.get(absolute).exports;if(absolute.endsWith('.json'))return JSON.parse(fs.readFileSync(absolute,'utf8'));const compiledModule={exports:{}};cache.set(absolute,compiledModule);const result=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText;const localRequire=name=>name.startsWith('@/')?load(name.slice(2)+(/\.(ts|tsx|json)$/.test(name)?'':'.ts')):name.startsWith('.')?load(path.resolve(path.dirname(absolute),name+(/\.(ts|json)$/.test(name)?'':'.ts'))):require(name);new Function('require','module','exports',result)(localRequire,compiledModule,compiledModule.exports);return compiledModule.exports;}
const {newTrip,newGear,validTrip,copyTrip,parsePreparationImport,parseTripImport,exportPreparation,exportTrips,defaultChecklist}=load('lib/trip-preparation.ts');
const {seedCatalog}=load('lib/catalog-seed.ts');
const {normalizeTrip,validateGear}=load('lib/preparation-schema.ts');
const {tripItineraryHtml,buildGuideHtml}=load('lib/fieldbook.ts');
const {dayDate,moveItem,duplicateDay,emptyEntry,itineraryWarnings,checklistProgress,allocationWarnings}=load('lib/itinerary.ts');
const {releaseText}=load('lib/preparation-release-copy.ts');
const locales=['ar','en','fr','zh','hi'];
function preparedTrip(){return {...newTrip('en'),checklist:defaultChecklist('desert','en')}}
function owned(){return {...newGear(),name:'Headlamp',equipmentId:'light',quantity:2}}
function linked(trip,g,assigned=1){return {...trip,checklist:[{id:crypto.randomUUID(),label:'Light',category:'essentials',kind:'equipment',done:false,equipmentId:'light',gearId:g.id,requiredQuantity:2,assignedQuantity:assigned,packedQuantity:1,gearSnapshot:{name:g.name,quantity:g.quantity,condition:g.condition}}]}}

test('new plans need explicit packing acceptance, use the supplied catalog and preserve five locales',()=>{const catalog=structuredClone(seedCatalog);catalog.revision=19;catalog.destinations.push({...catalog.destinations[0],id:'new-place',names:['جديد','New place','Nouveau','新地点','नई जगह']});for(const locale of locales){const trip=newTrip(locale,'new-place',catalog);assert.equal(validTrip(trip),true);assert.equal(trip.destinationId,'new-place');assert.equal(trip.catalogRevision,19);assert.deepEqual(trip.checklist,[]);assert.deepEqual(trip.itinerary,[]);for(const key of ['inventory','packingNote','itinerary','importError','saveGear'])assert.notEqual(releaseText(locale,key),key)}for(const row of defaultChecklist('desert','en')){assert.equal(row.packedQuantity,0);assert.equal(row.assignedQuantity,0)}});
test('structural validation rejects malformed dates, quantities and timed zones without clamping',()=>{const t=preparedTrip();for(const patch of [{location:{lat:91,lon:0}},{title:' '},{startDate:'2026-02-30'},{startDate:'2026-05-01',endDate:'2026-04-30'},{groupSize:0},{id:'bad/id'},{transport:'x'.repeat(201)},{revision:-1},{checklist:[t.checklist[0],t.checklist[0]]},{checklist:[{...t.checklist[0],requiredQuantity:2,assignedQuantity:3}]},{itinerary:[{id:'day',dayOffset:0,entries:[{...emptyEntry('Invalid/Zone'),title:'Walk',startTime:'09:00'}]}]}])assert.equal(validTrip({...t,...patch}),false);assert.equal(validTrip({...t,startDate:'2024-02-29',endDate:'2024-03-01'}),true);assert.doesNotThrow(()=>normalizeTrip({...t,checklist:[{...t.checklist[0],requiredQuantity:2,assignedQuantity:0,packedQuantity:2}]}));assert.throws(()=>validateGear({...owned(),quantity:-1}));assert.throws(()=>validateGear({...owned(),expiryDate:'2026-02-30'}))});
test('legacy boolean packing converts to quantities and its dates stay optional',()=>{const t={...newTrip('en'),checklist:[{id:'old',label:'Water',category:'custom',done:true}]};delete t.schemaVersion;const [imported]=parseTripImport(JSON.stringify({format:'daroub-trips',version:1,trips:[t]}));assert.equal(imported.schemaVersion,2);assert.equal(imported.checklist[0].requiredQuantity,1);assert.equal(imported.checklist[0].packedQuantity,1);assert.equal(imported.startDate,'')});
test('bundle remaps gear links and every nested identity without losing quantities',()=>{const g=owned(),original=linked(preparedTrip(),g);original.itinerary=[{id:'day',dayOffset:2,entries:[{...emptyEntry('Asia/Dubai'),id:'entry',title:'Walk'}]}];original.revision=9;const imported=parsePreparationImport(exportPreparation([original],[g])),trip=imported.trips[0],gear=imported.gear[0];assert.notEqual(gear.id,g.id);assert.notEqual(trip.id,original.id);assert.notEqual(trip.checklist[0].id,original.checklist[0].id);assert.notEqual(trip.itinerary[0].id,'day');assert.notEqual(trip.itinerary[0].entries[0].id,'entry');assert.equal(trip.checklist[0].gearId,gear.id);assert.equal(trip.checklist[0].assignedQuantity,1);assert.equal(trip.checklist[0].packedQuantity,1);assert.equal(trip.revision,0);assert.equal(gear.revision,0);assert.equal(trip.itinerary[0].dayOffset,2)});
test('trip-only imports clear unavailable inventory links but retain reviewed snapshots and packing',()=>{const g=owned(),original=linked(preparedTrip(),g),trip=parseTripImport(exportTrips([original]))[0];assert.equal(trip.checklist[0].gearId,undefined);assert.equal(trip.checklist[0].assignedQuantity,0);assert.equal(trip.checklist[0].packedQuantity,1);assert.deepEqual(trip.checklist[0].gearSnapshot,original.checklist[0].gearSnapshot);const copy=copyTrip(original);assert.equal(copy.checklist[0].gearId,g.id);copy.checklist[0].gearSnapshot.name='Changed';assert.equal(original.checklist[0].gearSnapshot.name,'Headlamp')});
test('atomic imports reject oversized, invalid or duplicate records before creating a usable batch',()=>{const trip=preparedTrip(),gear=owned();for(const data of [{format:'daroub-preparation',version:2,trips:[],gear:[]},{format:'daroub-preparation',version:2,trips:[trip,trip],gear:[]},{format:'daroub-preparation',version:2,trips:[],gear:[gear,gear]},{format:'daroub-preparation',version:2,trips:[trip],gear:[{...gear,quantity:0.5}]},{format:'daroub-trips',version:2,trips:[trip]},{format:'daroub-preparation',version:2,trips:Array.from({length:51},()=>newTrip('en')),gear:[]}])assert.throws(()=>parsePreparationImport(JSON.stringify(data)));assert.throws(()=>parsePreparationImport(' '.repeat(4*1024*1024+1)));assert.equal(parsePreparationImport(exportPreparation(Array.from({length:50},()=>newTrip('en')))).trips.length,50)});
test('quantity progress counts packed equipment plus completed tasks without counting ownership',()=>{assert.deepEqual(checklistProgress([{kind:'equipment',requiredQuantity:4,assignedQuantity:4,packedQuantity:1},{kind:'task',done:true}]),{done:2,total:5});assert.deepEqual(checklistProgress([{kind:'equipment',requiredQuantity:2,assignedQuantity:2,packedQuantity:0}]),{done:0,total:2})});
test('calendar offsets are stable across leap years and daylight-saving boundaries',()=>{assert.equal(dayDate('2024-02-28',1),'2024-02-29');assert.equal(dayDate('2026-03-28',1),'2026-03-29');assert.equal(dayDate('2026-12-31',1),'2027-01-01');assert.equal(dayDate('',4),'');assert.equal(dayDate('2026-01-01',NaN),'')});
test('record-count bounds are separate from day offsets and do not silently truncate',()=>{const trip=newTrip('en'),entry=()=>({...emptyEntry(''),title:'Stop'}),days=(n,entries=0)=>Array.from({length:n},(_,i)=>({id:'day-'+i,dayOffset:i,entries:Array.from({length:entries},entry)}));assert.doesNotThrow(()=>normalizeTrip({...trip,itinerary:[{id:'last',dayOffset:3650,entries:[]}]}));assert.throws(()=>normalizeTrip({...trip,itinerary:[{id:'last',dayOffset:3651,entries:[]}]}));assert.doesNotThrow(()=>normalizeTrip({...trip,itinerary:days(60)}));assert.throws(()=>normalizeTrip({...trip,itinerary:days(61)}));assert.doesNotThrow(()=>normalizeTrip({...trip,itinerary:days(15,40)}));assert.throws(()=>normalizeTrip({...trip,itinerary:days(16,40)}));assert.throws(()=>normalizeTrip({...trip,itinerary:days(1,41)}));assert.doesNotThrow(()=>validateGear({...owned(),quantity:0,name:'x'.repeat(160),notes:'x'.repeat(5000)}));assert.doesNotThrow(()=>validateGear({...owned(),quantity:10000}));assert.throws(()=>validateGear({...owned(),quantity:10001}));assert.throws(()=>validateGear({...owned(),name:'x'.repeat(161)}));assert.throws(()=>validateGear({...owned(),notes:'x'.repeat(5001)}))});
test('reorder and duplicate preserve content with independent identities',()=>{const a=emptyEntry('Europe/Berlin');a.title='Walk';const day={id:'day',dayOffset:0,entries:[a]},copy=duplicateDay(day,2);assert.equal(copy.dayOffset,2);assert.notEqual(copy.id,day.id);assert.notEqual(copy.entries[0].id,a.id);assert.equal(copy.entries[0].timeZone,a.timeZone);assert.deepEqual(moveItem(['a','b','c'],1,-1),['b','a','c']);assert.deepEqual(moveItem(['a'],0,-1),['a'])});
test('date-range warnings retain entries and detect overnight overlaps in the same time zone',()=>{const a={...emptyEntry('Asia/Dubai'),title:'Night',startTime:'23:30',durationMinutes:120},b={...emptyEntry('Asia/Dubai'),title:'Morning',startTime:'00:30',durationMinutes:30},trip={...newTrip('en'),startDate:'2026-09-01',endDate:'2026-09-01',itinerary:[{id:'a',dayOffset:0,entries:[a]},{id:'b',dayOffset:1,entries:[b]}]};assert.ok(itineraryWarnings(trip).some(w=>w.dayId==='b'&&w.key==='dayOutside'));assert.equal(itineraryWarnings(trip).filter(w=>w.key==='timeOverlap').length,2);assert.equal(trip.itinerary[1].entries.length,1);assert.ok(itineraryWarnings({...trip,startDate:''}).some(w=>w.key==='dateUnknown'))});
test('inventory warnings detect drift, maintenance, deletion and genuine allocation conflicts',()=>{const g=owned(),trip=linked({...newTrip('en'),startDate:'2026-09-01',endDate:'2026-09-10'},g),other=linked({...newTrip('en'),startDate:'2026-09-02',endDate:'2026-09-03'},g,2);assert.ok(allocationWarnings(trip,trip.checklist[0],[g],[trip,other]).includes('overAllocated'));assert.ok(allocationWarnings(trip,trip.checklist[0],[{...g,quantity:1,maintenanceDate:'2026-01-01'}],[]).includes('snapshotChanged'));assert.ok(allocationWarnings(trip,trip.checklist[0],[{...g,maintenanceDate:'2026-01-01'}],[]).includes('maintenanceDue'));assert.deepEqual(allocationWarnings(trip,trip.checklist[0],[],[]),['gearUnavailable']);assert.ok(allocationWarnings(trip,trip.checklist[0],[g],[{...other,startDate:''}]).includes('unknownOverlap'))});
test('sequential allocations within one long trip do not cause a false overlap warning',()=>{const g=owned(),trip=linked({...newTrip('en'),startDate:'2026-09-01',endDate:'2026-09-10'},g),a=linked({...newTrip('en'),startDate:'2026-09-02',endDate:'2026-09-03'},g),b=linked({...newTrip('en'),startDate:'2026-09-04',endDate:'2026-09-05'},g);assert.ok(!allocationWarnings(trip,trip.checklist[0],[g],[a,b]).includes('overAllocated'))});
test('expiry remains valid through its date while maintenance is due on its date',()=>{const g=owned(),trip=linked({...newTrip('en'),startDate:'2026-09-01',endDate:'2026-09-10'},g);assert.ok(!allocationWarnings(trip,trip.checklist[0],[{...g,expiryDate:'2026-09-10'}],[]).includes('expired'));assert.ok(allocationWarnings(trip,trip.checklist[0],[{...g,maintenanceDate:'2026-09-10'}],[]).includes('maintenanceDue'))});
test('download includes every day, quantities, time zone and escaped private text in every locale',()=>{const g=owned(),trip=linked({...newTrip('en'),startDate:'2026-09-17'},g);trip.title='<script>alert(1)</script>';trip.notes='<iframe src=evil>';trip.itinerary=[{id:'d',dayOffset:1,entries:[{...emptyEntry('Asia/Dubai'),title:'PRIVATE STOP',startTime:'08:00',durationMinutes:60,notes:'<img src=x onerror=evil>'}]}];for(const locale of locales){const html=tripItineraryHtml(trip,locale,seedCatalog);assert.ok(html.includes('PRIVATE STOP'));assert.ok(html.includes('Asia/Dubai'));assert.ok(html.includes('2026-09-18'));assert.ok(html.includes('Headlamp'));assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<iframe'));assert.ok(html.includes('lang="'+locale+'"'));assert.ok(html.includes('dir="'+(locale==='ar'?'rtl':'ltr')+'"'))}});
test('fieldbooks use the supplied published snapshot consistently and remain text-complete offline',async()=>{const realFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('offline')};try{const catalog=structuredClone(seedCatalog);catalog.revision=42;catalog.destinations[0].sections[0].body.fill('PUBLISHED CHAPTER');catalog.terrainGuidance[0].sections[0].body.fill('PUBLISHED GENERAL');const local=await buildGuideHtml({locale:'en',index:0,destinationId:'liwa',catalog}),generic=await buildGuideHtml({locale:'en',index:0,point:{lat:12,lon:14},catalog});assert.ok(local.includes('PUBLISHED CHAPTER'));assert.ok(local.includes('Date palms'));assert.ok(local.includes('abudhabiculture.ae'));assert.ok(local.includes('42'));assert.ok(generic.includes('PUBLISHED GENERAL'));assert.ok(generic.includes('12.000, 14.000'));assert.ok(!generic.includes('Date palms'));assert.ok(!generic.includes('Liwa'))}finally{globalThis.fetch=realFetch}});
test('rendered timed-entry errors identify the invalid field in all five locales',()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{ItineraryEditor}=load('components/itinerary-editor.tsx'),trip={...newTrip('en'),itinerary:[{id:'day',dayOffset:0,entries:[{...emptyEntry('Invalid/Zone'),id:'entry',title:'Walk',startTime:'08:00'}]}]};for(const locale of locales){const html=renderToStaticMarkup(React.createElement(ItineraryEditor,{trip,locale,catalog:seedCatalog,onChange:()=>{}}));assert.match(html,/aria-invalid="true"/);assert.match(html,/aria-describedby="zone-entry"/);assert.match(html,/id="zone-entry"/);assert.ok(html.includes(releaseText(locale,'invalidZone')));assert.ok(!html.includes('NaN'));}const valid=structuredClone(trip);valid.itinerary[0].entries[0].timeZone='Asia/Dubai';assert.ok(!renderToStaticMarkup(React.createElement(ItineraryEditor,{trip:valid,locale:'en',catalog:seedCatalog,onChange:()=>{}})).includes('aria-invalid="true"'))});
test('compact checklist exposes partial progress and flags inventory changes for review',()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{QuantityChecklist}=load('components/quantity-checklist.tsx'),g=owned(),trip=linked(newTrip('en'),g);const html=renderToStaticMarkup(React.createElement(QuantityChecklist,{trip,gear:[{...g,name:'Updated headlamp',quantity:3}],trips:[],locale:'en',onChange:()=>{}}));assert.match(html,/<progress[^>]*value="0"[^>]*max="1"/);assert.ok(html.includes('Needs review'));assert.ok(!html.includes('Updated headlamp'));assert.ok(html.includes('Edit'));assert.ok(html.includes('Packed 1 of 2'));assert.ok(html.includes('aria-expanded="false"'))});
test('standalone trip download retains dated destination sources from its explicit snapshot',()=>{const catalog=structuredClone(seedCatalog);catalog.revision=37;catalog.sources.find(source=>source.id===catalog.destinations[0].sourceIds[0]).reviewedAt='2026-08-04';const source=catalog.sources.find(source=>source.id===catalog.destinations[0].sourceIds[0]),html=tripItineraryHtml(newTrip('en',catalog.destinations[0].id,catalog),'en',catalog);assert.ok(html.includes('Destination references'));assert.ok(html.includes(source.url.replaceAll('&','&amp;')));assert.ok(html.includes('2026-08-04'));assert.ok(html.includes('37'))});
test('transient empty quantity inputs never render NaN bounds or silently change the draft',()=>{const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{QuantityChecklist}=load('components/quantity-checklist.tsx'),trip=preparedTrip();trip.checklist[0].requiredQuantity=NaN;const html=renderToStaticMarkup(React.createElement(QuantityChecklist,{trip,gear:[],trips:[],locale:'en',onChange:()=>{throw Error('Render must not mutate a draft')}}));assert.ok(!html.includes('NaN'));assert.equal(Number.isNaN(trip.checklist[0].requiredQuantity),true)});
test('focus recovery waits for the updated DOM and uses an enabled fallback after removals',()=>{const {focusAfterRender}=load('lib/preparation-focus.ts'),oldFrame=globalThis.requestAnimationFrame,oldDocument=globalThis.document;let frame,focused='';try{globalThis.requestAnimationFrame=callback=>{frame=callback;return 1};globalThis.document={getElementById:id=>id==='removed'?null:{matches:()=>id==='disabled-add',focus:()=>{focused=id}}};focusAfterRender('next-row');assert.equal(focused,'');frame();assert.equal(focused,'next-row');focusAfterRender('removed','section');frame();assert.equal(focused,'section');focusAfterRender('disabled-add','section');frame();assert.equal(focused,'section')}finally{globalThis.requestAnimationFrame=oldFrame;globalThis.document=oldDocument}});
test('every preparation dictionary entry has five translations and static UI keys cannot fall back to machine labels',()=>{const {preparationReleaseWords}=load('lib/preparation-release-copy.ts');for(const [key,values] of Object.entries(preparationReleaseWords)){assert.equal(values.length,5,key);assert.ok(values.every(value=>typeof value==='string'&&value.trim()),key)}for(const file of ['components/inventory-view.tsx','components/trips-view.tsx','components/quantity-checklist.tsx','components/itinerary-editor.tsx','lib/fieldbook.ts']){const source=fs.readFileSync(path.resolve(root,file),'utf8');for(const match of source.matchAll(/\br\('([^']+)'\)/g))assert.ok(preparationReleaseWords[match[1]],file+': '+match[1])}for(const locale of locales){for(const key of ['importPreparation','gearNotes','inventorySignIn','inventoryLocalNote','retainedType','preparation','ready','needs-maintenance','unavailable','itemAdded','entryRemoved','dayMoved'])assert.notEqual(releaseText(locale,key),key)}});
