import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createLoader} from './helpers/load-ts.mjs';
const load=createLoader(),{seedCatalog}=load('lib/catalog-seed.ts'),{packingSuggestions}=load('lib/packing-engine.ts'),{newTrip,defaultChecklist}=load('lib/trip-preparation.ts'),{selectionFromQuery}=load('lib/explorer-location.ts'),{buildGuideHtml}=load('lib/fieldbook.ts');
const locales=['ar','en','fr','zh','hi'];
test('assistant retrieves the new destination season chapter with citations in all languages',()=>{const {retrieveGuide}=load('lib/assistant-guide.ts');for(const d of seedCatalog.destinations)for(const [i,locale]of locales.entries()){const answer=retrieveGuide({question:'Weather?',topic:'seasons',locale,destinationId:d.id,terrainIndex:d.terrainIndex},seedCatalog),chapter=d.sections.find(s=>s.id==='season');assert.ok(answer.text.includes(chapter.body[i]),d.id);assert.ok(chapter.sourceIds.every(id=>answer.sourceIds.includes(id)))}});
test('brief preview recognizes Hindi and Chinese sentence boundaries',()=>{const {advicePreview}=load('lib/destination-advice.ts');assert.equal(advicePreview('गरम कपड़े रखें। मौसम देखें।'),'गरम कपड़े रखें।');assert.equal(advicePreview('带保暖层。查看天气。'),'带保暖层。')});
async function component(file){const result=await build({entryPoints:[file],bundle:true,write:false,format:'cjs',platform:'node',packages:'external',loader:{'.css':'empty'}}),compiled={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),compiled,compiled.exports);return compiled.exports}
test('four existing and ten additional destinations have five-language practical chapters and stable selection',()=>{assert.equal(seedCatalog.destinations.length,14);assert.equal(new Set(seedCatalog.destinations.map(d=>d.id)).size,14);for(const d of seedCatalog.destinations){for(const id of ['place','equipment','visit','clothing','transport','season','nature','hazard']){const s=d.sections.find(s=>s.id===id);assert.ok(s,`${d.id}: ${id}`);assert.equal(s.body.length,5);assert.ok(s.body.every(v=>v.trim().length>20));assert.ok(s.sourceIds.every(id=>seedCatalog.sources.some(s=>s.id===id)))}assert.doesNotThrow(()=>new Intl.DateTimeFormat('en',{timeZone:d.timezone}));const selected=selectionFromQuery(new URLSearchParams({destination:d.id}),seedCatalog.destinations);assert.equal(selected.destinationId,d.id);assert.equal(selected.lat,d.lat)}});
test('each destination gets tailored advice in every language, with correct quantities and no automatic packing',async()=>{for(const d of seedCatalog.destinations)for(const locale of locales){const trip={...newTrip(locale,d.id),groupSize:3,activities:['walking','boating','swimming','camping'],startDate:'2026-11-10',endDate:'2026-11-12'},items=await packingSuggestions(trip,[],seedCatalog,locale);assert.deepEqual(trip.checklist,[]);assert.ok(items.filter(i=>i.destinationSpecific).length>=2,d.id);assert.equal(new Set(items.map(i=>i.equipmentId)).size,items.length);for(const item of items){assert.ok(['group','person'].includes(item.quantityBasis));assert.ok(item.quantity>=1);assert.ok(item.sourceIds.every(id=>seedCatalog.sources.some(s=>s.id===id)))}}});
test('arbitrary coordinates and terrain templates never inherit destination rules',async()=>{for(const terrainId of ['desert','mountain','forest','coast']){const trip={...newTrip('en'),destinationId:null,terrainId,location:{lat:10,lon:10},activities:['walking','boating','swimming','camping']};const items=await packingSuggestions(trip,[],seedCatalog,'en');assert.ok(items.every(i=>!i.destinationSpecific&&i.coverage==='terrain-example'));const baseline=defaultChecklist(terrainId,'en');for(const row of baseline)assert.ok(seedCatalog.packingRules.some(r=>!r.destinationIds.length&&r.equipmentId===row.equipmentId))}});
test('mixed rule quantity basis follows maximum quantity while destination explanation stays first',async()=>{const catalog=structuredClone(seedCatalog),base=catalog.packingRules[0];catalog.packingRules=[{...base,id:'generic',equipmentId:'probe',baseQuantity:5,perPerson:false},{...base,id:'specific',equipmentId:'probe',baseQuantity:1,perPerson:true,destinationIds:['liwa'],reason:Array(5).fill('Destination reason')}];const trip={...newTrip('en'),groupSize:3},[item]=await packingSuggestions(trip,[],catalog,'en');assert.equal(item.quantity,5);assert.equal(item.quantityBasis,'group');assert.equal(item.destinationSpecific,true);assert.ok(item.reason.startsWith('Destination reason'));catalog.packingRules[1].baseQuantity=2;const[next]=await packingSuggestions(trip,[],catalog,'en');assert.equal(next.quantity,6);assert.equal(next.quantityBasis,'person')});
test('briefs suppress local advice for unselected coordinates and archived selection remains honest',async()=>{const {DestinationBrief}=await component('components/destination-brief.tsx'),{TripDetails}=await component('components/trip-details.tsx');for(const locale of locales){assert.equal(renderToStaticMarkup(React.createElement(DestinationBrief,{catalog:seedCatalog,locale,destinationId:null})), '');for(const d of seedCatalog.destinations){const html=renderToStaticMarkup(React.createElement(DestinationBrief,{catalog:seedCatalog,locale,destinationId:d.id,compact:true}));assert.ok(html.includes('/regions?destination='+d.id));assert.equal((html.match(/class="destination-advice-card"/g)||[]).length,4)}const catalog=structuredClone(seedCatalog);catalog.destinations[0].archived=true;const html=renderToStaticMarkup(React.createElement(TripDetails,{catalog,locale,trip:newTrip(locale,'liwa',catalog),creating:true,onChange:()=>{}}));assert.match(html,/<option value="liwa" selected="">/);assert.match(html,/class="journey-selected-place"/)}});
test('offline guide downloads retain destination chapters and sources for all fourteen locations',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('offline')};try{for(const d of seedCatalog.destinations){const html=await buildGuideHtml({locale:'en',index:d.terrainIndex,destinationId:d.id,catalog:seedCatalog});assert.ok(html.includes(d.names[1].replaceAll('&','&amp;')),d.id);assert.ok(html.includes(d.sections.find(s=>s.id==='clothing').body[1].slice(0,30).replaceAll('&','&amp;')));assert.ok(html.includes(seedCatalog.sources.find(s=>s.id===d.sourceIds[0]).url.replaceAll('&','&amp;')))}}finally{globalThis.fetch=oldFetch}});
