import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createLoader} from './helpers/load-ts.mjs';
function setup(){const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(s=>s.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
 const db={prepare(query){const wrap=values=>({query,values,bind(...next){return wrap(next)},async first(){return sql.prepare(query).get(...values)??null},async all(){return {results:sql.prepare(query).all(...values)}},async run(){return sql.prepare(query).run(...values)}});return wrap([])},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>sql.prepare(s.query).run(...s.values));sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};
 const env={DB:db,DAROUB_OWNER_IDS:'owner-a',DAROUB_EDITOR_IDS:'editor-a'},session={user:{userId:'owner-a',displayName:'Owner'}};const load=createLoader({'cloudflare:workers':{env},'@/app/chatgpt-auth':{getChatGPTUser:async()=>session.user}});return{sql,db,load,env,session,catalog:load('lib/catalog-server.ts'),schema:load('lib/preparation-schema.ts'),validation:load('lib/sync-validation.ts'),sync:load('lib/sync-server.ts'),seed:load('lib/catalog-seed.ts').seedCatalog}}
const trip=()=>({id:'trip-a',title:'Trip A',destinationId:'liwa',terrainId:'desert',location:{lat:23,lon:53},startDate:'2026-10-01',endDate:'2026-10-03',groupSize:2,transport:'car',notes:'',checklist:[{id:'lamp',label:'Lamp',category:'essentials',done:false}],revision:0,updatedAt:'2026-09-17T00:00:00Z'});
const mutation=(h,id,base,payload,protocol)=>h.validation.validateMutation({operationId:id,entity:'trip',id:payload?.id??'trip-a',baseRevision:base,payload,...(protocol?{protocol}: {})});
test('v2 itinerary/packing survive conflicts while legacy writes and deletes cannot truncate them',async()=>{const h=setup(),t=h.schema.normalizeTrip(trip());t.itinerary=[{id:'day-a',dayOffset:0,entries:[{id:'stop-a',title:'Rest',activityId:'rest',place:'Camp',startTime:'10:00',timeZone:'Asia/Dubai',durationMinutes:30,transport:'',notes:''}]}];await h.sync.applyMutation('A',mutation(h,'create',0,t,2));await assert.rejects(()=>h.sync.applyMutation('A',mutation(h,'old',1,trip())),h.sync.UpgradeRequired);await assert.rejects(()=>h.sync.applyMutation('A',mutation(h,'old-delete',1,null)),h.sync.UpgradeRequired);assert.equal((await h.sync.snapshot('A',1)).length,0);await h.sync.applyMutation('A',mutation(h,'one',1,{...t,title:'First'},2));await h.sync.applyMutation('A',mutation(h,'two',1,{...t,title:'Second'},2));assert.equal((await h.sync.snapshot('A')).length,2);assert.ok((await h.sync.snapshot('A')).every(r=>r.record.itinerary[0].entries[0].id==='stop-a'));assert.equal(await h.sync.loadOwnedTrip('B','trip-a'),null);h.sql.close()});
test('an already acknowledged legacy operation replays after the record upgrades without a new recovery copy',async()=>{const h=setup(),old=mutation(h,'legacy-create',0,trip()),receipt=await h.sync.applyMutation('A',old);await h.sync.applyMutation('A',mutation(h,'upgrade',1,h.schema.normalizeTrip(trip()),2));assert.deepEqual(await h.sync.applyMutation('A',old),receipt);assert.equal((await h.sync.snapshot('A')).length,1);h.sql.close()});
test('catalog publication requires reviewed translations, preserves drafts and offers atomic history/rollback',async()=>{const h=setup();assert.equal((await h.catalog.readCatalog()).revision,0);let d={id:'draft-a',revision:0,baseCatalogRevision:0,snapshot:structuredClone(h.seed),reviewedLocales:['ar','en','fr','zh','hi'],updatedAt:''};d.snapshot.destinations[0].summary[1]='Updated local summary';d=await h.catalog.saveCatalogDraft('owner-a',d);assert.equal(d.reviewedLocales.includes('en'),false);assert.equal((await h.catalog.readCatalog()).destinations[0].summary[1],h.seed.destinations[0].summary[1]);await assert.rejects(()=>h.catalog.publishCatalogDraft('owner-a',d.id,d.revision,0),h.catalog.CatalogInvalid);d=await h.catalog.saveCatalogDraft('owner-a',{...d,reviewedLocales:['ar','en','fr','zh','hi']});const published=await h.catalog.publishCatalogDraft('owner-a',d.id,d.revision,0);assert.equal(published.revision,1);assert.equal((await h.catalog.editorState()).drafts.length,0);await assert.rejects(()=>h.catalog.rollbackCatalog('owner-a',0,0),h.catalog.CatalogConflict);const restored=await h.catalog.rollbackCatalog('owner-a',0,1);assert.equal(restored.revision,2);assert.equal(restored.destinations[0].summary[1],h.seed.destinations[0].summary[1]);assert.deepEqual((await h.catalog.editorState()).history.map(h=>h.revision),[2,1]);h.sql.close()});
test('editor APIs deny ordinary accounts, forged roles, foreign origins and editor publication',async()=>{const h=setup(),route=h.load('app/api/editor/route.ts');h.session.user={userId:'outsider'};assert.equal((await route.GET()).status,403);const request=body=>new Request('https://daroub.test/api/editor',{method:'POST',headers:{origin:'https://daroub.test','content-type':'application/json'},body:JSON.stringify(body)});assert.equal((await route.POST(request({role:'owner',action:'rollback',revision:0,expectedCatalogRevision:0}))).status,403);h.session.user={userId:'editor-a'};assert.equal((await route.POST(request({action:'rollback',revision:0,expectedCatalogRevision:0}))).status,403);h.session.user={userId:'owner-a'};assert.equal((await route.POST(new Request('https://daroub.test/api/editor',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'}))).status,403);assert.equal((await route.GET()).status,200);h.session.user=null;assert.equal((await route.GET()).status,401);h.sql.close()});
test('catalog and equipment validation reject missing translations, dangerous links and impossible quantities',()=>{const h=setup(),validate=h.load('lib/catalog-validation.ts').validateCatalog;const bad=structuredClone(h.seed);bad.destinations[0].names[4]='';assert.throws(()=>validate(bad,true));bad.destinations[0].names[4]='Name';bad.sources[0].url='javascript:alert(1)';assert.throws(()=>validate(bad,true));const t=trip();t.checklist[0]={...t.checklist[0],kind:'equipment',requiredQuantity:2,packedQuantity:1,assignedQuantity:0};const normalized=h.schema.normalizeTrip(t);assert.equal(normalized.checklist[0].done,false);assert.throws(()=>h.schema.normalizeTrip({...t,checklist:[{...t.checklist[0],packedQuantity:3}]}));assert.throws(()=>h.schema.normalizeTrip({...t,startDate:'2026-02-29'}));h.sql.close()});
test('shared five-item arrays invalidate every language review while a localized edit affects its language',()=>{const h=setup(),fingerprint=h.load('lib/catalog-validation.ts').localeContent,a=structuredClone(h.seed);a.packingRules[0].activities=['walking','camping','boating','swimming','hiking'];const b=structuredClone(a);b.packingRules[0].activities[3]='climbing';for(const locale of ['ar','en','fr','zh','hi'])assert.notEqual(fingerprint(a,locale),fingerprint(b,locale));const c=structuredClone(a);c.destinations[0].summary[3]='新内容';for(const locale of ['ar','en','fr','hi'])assert.equal(fingerprint(a,locale),fingerprint(c,locale));assert.notEqual(fingerprint(a,'zh'),fingerprint(c,'zh'));h.sql.close()});

test('an upgrade between legacy preflight and its atomic batch creates no copy or receipt',async()=>{for(const deleted of [false,true]){const h=setup();await h.sync.applyMutation('A',mutation(h,'seed',0,trip()));const batch=h.db.batch;let inject=true;h.db.batch=async statements=>{if(inject){inject=false;await h.sync.applyMutation('A',mutation(h,'concurrent-upgrade',1,h.schema.normalizeTrip(trip()),2))}return batch(statements)};await assert.rejects(()=>h.sync.applyMutation('A',mutation(h,'raced-old',1,deleted?null:trip())),h.sync.UpgradeRequired);assert.equal((await h.sync.snapshot('A')).length,1);assert.equal(h.sql.prepare('SELECT count(*) AS n FROM sync_receipts WHERE operation_id=?').get('raced-old').n,0);h.sql.close()}});
test('v2 tombstones remain protected and protocol changes cannot reuse receipts',async()=>{const h=setup(),t=h.schema.normalizeTrip(trip());await h.sync.applyMutation('A',mutation(h,'create-v2',0,t,2));await h.sync.applyMutation('A',mutation(h,'delete-v2',1,null,2));await assert.rejects(()=>h.sync.applyMutation('A',mutation(h,'legacy-delete',2,null)),h.sync.UpgradeRequired);assert.equal((await h.sync.snapshot('A',1)).length,0);const original=mutation(h,'receipt-identity',0,{...t,id:'trip-b'},2);await h.sync.applyMutation('A',original);await assert.rejects(()=>h.sync.applyMutation('A',{...original,replacesOperationId:'different-recovery'}),h.sync.MutationReuseError);await assert.rejects(()=>h.sync.applyMutation('A',{...original,protocol:undefined}),h.sync.MutationReuseError);h.sql.close()});
test('draft base revision cannot be forged to bypass stale publication',async()=>{const h=setup();const draft=await h.catalog.saveCatalogDraft('owner-a',{id:'stale',revision:0,baseCatalogRevision:0,snapshot:h.seed,reviewedLocales:['ar','en','fr','zh','hi']});await h.catalog.rollbackCatalog('owner-a',0,0);await assert.rejects(()=>h.catalog.saveCatalogDraft('owner-a',{...draft,baseCatalogRevision:1}),h.catalog.CatalogConflict);h.sql.close()});
test('compatible read-only recovery preserves reads and blocks all writes without receipts',async()=>{const h=setup(),t=h.schema.normalizeTrip(trip());await h.sync.applyMutation('owner-a',mutation(h,'before-recovery',0,t,2));h.env.DAROUB_READ_ONLY='true';const route=h.load('app/api/sync/route.ts'),editor=h.load('app/api/editor/route.ts'),session=h.load('app/api/session/route.ts');const headers={origin:'https://daroub.test','content-type':'application/json','X-Daroub-Account':'owner-a','X-Daroub-Protocol':'2'};assert.equal((await route.GET(new Request('https://daroub.test/api/sync',{headers}))).status,200);const res=await route.POST(new Request('https://daroub.test/api/sync',{method:'POST',headers,body:JSON.stringify(mutation(h,'paused',1,t,2))}));assert.equal(res.status,503);assert.equal(res.headers.get('Retry-After'),'300');assert.equal((await editor.GET()).status,200);assert.equal((await editor.POST(new Request('https://daroub.test/api/editor',{method:'POST',headers,body:'{}'}))).status,503);assert.equal((await(await session.GET()).json()).readOnly,true);assert.equal(h.sql.prepare('SELECT count(*) AS n FROM sync_receipts WHERE operation_id=?').get('paused').n,0);h.env.DAROUB_READ_ONLY='false';assert.equal((await route.POST(new Request('https://daroub.test/api/sync',{method:'POST',headers,body:JSON.stringify(mutation(h,'paused',1,t,2))}))).status,200);h.sql.close()});
async function publish(h,id,snapshot,base){let draft=await h.catalog.saveCatalogDraft('owner-a',{id,revision:0,baseCatalogRevision:base,snapshot,reviewedLocales:[],updatedAt:''});draft=await h.catalog.saveCatalogDraft('owner-a',{...draft,reviewedLocales:['ar','en','fr','zh','hi']});return h.catalog.publishCatalogDraft('owner-a',draft.id,draft.revision,base);}
async function reviewed(h,id,snapshot,base){let draft=await h.catalog.saveCatalogDraft('owner-a',{id,revision:0,baseCatalogRevision:base,snapshot,reviewedLocales:[],updatedAt:''});return h.catalog.saveCatalogDraft('owner-a',{...draft,reviewedLocales:['ar','en','fr','zh','hi']});}
test('published destination identity cannot disappear or change terrain, including through new drafts',async()=>{
 const h=setup(),snapshot=structuredClone(h.seed);snapshot.destinations.push({...structuredClone(snapshot.destinations[0]),id:'new-oasis'});const current=await publish(h,'publish-new',snapshot,0);
 const omitted=structuredClone(current);omitted.destinations=omitted.destinations.filter(d=>d.id!=='new-oasis');const draft=await reviewed(h,'omit-draft',omitted,1);await assert.rejects(()=>h.catalog.publishCatalogDraft('owner-a',draft.id,draft.revision,1),h.catalog.CatalogInvalid);
 const changed=structuredClone(current),destination=changed.destinations.find(d=>d.id==='new-oasis');destination.terrainId='forest';destination.terrainIndex=2;const changedDraft=await reviewed(h,'terrain-draft',changed,1);await assert.rejects(()=>h.catalog.publishCatalogDraft('owner-a',changedDraft.id,changedDraft.revision,1),h.catalog.CatalogInvalid);
 assert.equal((await h.catalog.readCatalog()).revision,1);assert.equal((await h.catalog.editorState()).drafts.length,2);h.sql.close();
});
test('rollback archives later destinations and remaps source collisions while existing trips remain editable',async()=>{
 const h=setup(),snapshot=structuredClone(h.seed),source=snapshot.sources.find(s=>s.id==='essentials');source.title='Updated essentials for later destination';source.url='https://example.com/new-essentials';
 const extra={...structuredClone(snapshot.destinations[0]),id:'new-oasis',sourceIds:['essentials']};snapshot.destinations.push(extra);await publish(h,'new-with-source',snapshot,0);
 const t=h.schema.normalizeTrip({...trip(),destinationId:'new-oasis'});await h.sync.applyMutation('owner-a',mutation(h,'new-destination-trip',0,t,2));const restored=await h.catalog.rollbackCatalog('owner-a',0,1),archived=restored.destinations.find(d=>d.id==='new-oasis');assert.equal(archived.archived,true);assert.notEqual(archived.sourceIds[0],'essentials');assert.equal(restored.sources.find(s=>s.id===archived.sourceIds[0]).title,source.title);assert.equal(restored.sources.find(s=>s.id==='essentials').title,h.seed.sources.find(s=>s.id==='essentials').title);
 const route=h.load('app/api/sync/route.ts'),request=new Request('https://daroub.test/api/sync',{method:'POST',headers:{origin:'https://daroub.test','content-type':'application/json','X-Daroub-Account':'owner-a','X-Daroub-Protocol':'2'},body:JSON.stringify({operationId:'after-rollback-edit',entity:'trip',id:t.id,protocol:2,baseRevision:1,payload:{...t,revision:1,notes:'Edit survives rollback'}})});assert.equal((await route.POST(request)).status,200);assert.equal((await h.sync.loadOwnedTrip('owner-a',t.id)).notes,'Edit survives rollback');
 const again=await h.catalog.rollbackCatalog('owner-a',0,2);assert.equal(again.destinations.filter(d=>d.id==='new-oasis').length,1);assert.equal(again.sources.length,restored.sources.length);h.sql.close();
});
test('continuity includes identities missing from an older published head, not just its latest payload',async()=>{
 const h=setup(),snapshot=structuredClone(h.seed);snapshot.destinations.push({...structuredClone(snapshot.destinations[0]),id:'historical-oasis'});await publish(h,'historical',snapshot,0);
 h.sql.prepare('INSERT INTO catalog_versions(revision,payload,actor,published_at,operation) VALUES(?,?,?,?,?)').run(2,JSON.stringify({...h.seed,revision:2}),'owner-a','2026-09-17T00:00:00Z','old-code-publication');h.sql.prepare('UPDATE catalog_heads SET revision=2 WHERE id=1').run();
 const restored=await h.catalog.rollbackCatalog('owner-a',0,2);assert.equal(restored.destinations.find(d=>d.id==='historical-oasis').archived,true);assert.equal(restored.revision,3);h.sql.close();
});
test('rollback exceeding the 300-source limit fails before changing the head or history',async()=>{
 const h=setup(),old=structuredClone(h.seed);for(let i=old.sources.length;i<300;i++)old.sources.push({id:'old-source-'+i,title:'Old unused source '+i,url:'https://example.com/old/'+i,reviewedAt:'2026-09-17'});const first=await publish(h,'full-sources',old,0),later=structuredClone(first);later.sources=later.sources.filter(s=>!s.id.startsWith('old-source-'));
 const newIds=[];for(let i=0;i<100;i++){const id='later-source-'+i;newIds.push(id);later.sources.push({id,title:'Later required source '+i,url:'https://example.com/later/'+i,reviewedAt:'2026-09-17'});}later.destinations.push({...structuredClone(later.destinations[0]),id:'later-oasis',sourceIds:newIds});await publish(h,'later-sources',later,1);
 await assert.rejects(()=>h.catalog.rollbackCatalog('owner-a',1,2),h.catalog.CatalogInvalid);assert.equal((await h.catalog.readCatalog()).revision,2);assert.equal((await h.catalog.editorState()).history.length,2);h.sql.close();
});
test('a stale draft cannot change its base, while a new draft from the current publication can save',async()=>{
 const h=setup(),old=await reviewed(h,'stale-base',structuredClone(h.seed),0);await publish(h,'other-publication',structuredClone(h.seed),0);await assert.rejects(()=>h.catalog.saveCatalogDraft('owner-a',{...old,baseCatalogRevision:1}),h.catalog.CatalogConflict);const current=await h.catalog.readCatalog(),fresh=await reviewed(h,'fresh-rebase',current,current.revision);assert.equal(fresh.baseCatalogRevision,1);h.sql.close();
});

