import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),ts=require('typescript'),root=fileURLToPath(new URL('../',import.meta.url));
function load(file){const exports={},compiled=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',compiled)(name=>name==='./trip-store'?{getSession:async()=>null}:require(name),{exports},exports);return exports}
const {createTeamClient,TeamApiError,teamError,validAllocation,allocationTotals,invitationUrl,readInvitation}=load('lib/team-client.ts'),{teamWords,teamText}=load('lib/team-copy.ts');
const user={userId:'account-a',displayName:'A'},json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
function fixture(options={}){const requests=[],state={stamp:'epoch-a|account-a',online:true,user},deps={session:async()=>state.user,stamp:()=>state.stamp,online:()=>state.online,fetch:async(...args)=>{requests.push(args);return json({boards:[]})},...options};return {state,requests,client:createTeamClient(deps)}}

test('team quantities retain gap and overassignment independently of packed counts',()=>{const board={allocations:[{itemId:'water',participantId:'a',quantity:4,packed:2},{itemId:'water',participantId:'b',quantity:3,packed:1},{itemId:'other',quantity:20,packed:20}]};assert.deepEqual(allocationTotals(board,'water',5),{assigned:7,packed:3,gap:0,overbooked:2});assert.deepEqual(allocationTotals(board,'water',10),{assigned:7,packed:3,gap:3,overbooked:0});assert.deepEqual(allocationTotals(board,'unknown',2),{assigned:0,packed:0,gap:2,overbooked:0})});
test('allocation validation preserves transient input and respects task/quantity bounds',()=>{for(const pair of [['','0'],['1',''],['-1','0'],['1.5','0'],['NaN','0'],['Infinity','0'],['1e2','1'],['10001','0'],['0','1'],['2','3']])assert.equal(validAllocation(...pair),null,pair.join(','));assert.deepEqual(validAllocation('10000','10000'),{quantity:10000,packed:10000});assert.deepEqual(validAllocation('0','0'),{quantity:0,packed:0});assert.equal(validAllocation('2','0',1),null);assert.deepEqual(validAllocation('1','1',1),{quantity:1,packed:1})});
test('invitation secret is fragment-only and URL values round-trip safely',()=>{const url=new URL(invitationUrl('https://example.test/path','room/a?','secret+&=#'));assert.equal(url.pathname,'/team');assert.equal(url.searchParams.get('room'),'room/a?');assert.equal(url.searchParams.has('invite'),false);assert.equal(url.search.includes('secret'),false);assert.deepEqual(readInvitation(url.search,url.hash),{roomId:'room/a?',token:'secret+&=#'});assert.equal(readInvitation('','#invite=secret').token,'');assert.equal(readInvitation('?room=one','#invite='+'x'.repeat(1025)).token,'')});
test('private GET is no-store, account-scoped and carries no invitation token',async()=>{const {client,requests}=fixture();const result=await client.get('?room=one');assert.equal(result.session.userId,'account-a');assert.equal(requests.length,1);assert.equal(requests[0][0],'/api/team?room=one');assert.deepEqual(requests[0][1].headers,{'X-Daroub-Account':'account-a'});assert.equal(requests[0][1].cache,'no-store');assert.equal(requests[0][1].credentials,'same-origin');assert.equal(requests[0][1].body,undefined)});
test('explicit mutation carries reviewed source and board revision without automatic retry',async()=>{let attempts=0;const body={type:'refresh',roomId:'one',revision:4,expectedSourceRevision:6},f=fixture({fetch:async(url,options)=>{attempts++;assert.equal(url,'/api/team');assert.equal(options.method,'POST');assert.equal(options.headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(options.body),body);return json({error:'conflict'},409)}});await assert.rejects(f.client.mutate(body,'account-a'),e=>e instanceof TeamApiError&&e.code==='conflict'&&e.status===409);assert.equal(attempts,1)});
test('offline and read-only mutations never send group data',async()=>{const f=fixture();f.state.online=false;await assert.rejects(f.client.get(),e=>e.code==='offline');assert.equal(f.requests.length,0);f.state.online=true;f.state.user={...user,readOnly:true};await assert.rejects(f.client.mutate({type:'close',roomId:'one',revision:1},user.userId),e=>e.code==='read_only');assert.equal(f.requests.length,0);await f.client.get();assert.equal(f.requests.length,1)});
test('an expected-owner mismatch fails before fetching a board',async()=>{const f=fixture();await assert.rejects(f.client.get('?room=one','account-b'),e=>e.code==='account_changed');assert.equal(f.requests.length,0)});
test('account transition during session lookup cannot adopt another account for a clicked mutation',async()=>{let stamp='a',sent=0;const client=createTeamClient({session:async()=>{stamp='b';return {...user,userId:'account-b'}},stamp:()=>stamp,online:()=>true,fetch:async()=>{sent++;return json({})}});await assert.rejects(client.mutate({type:'join',roomId:'one',token:'secret',name:'Name'},'account-b'),e=>e.code==='account_changed');assert.equal(sent,0)});
test('initial empty account hydration is allowed but signed-out sessions never fetch',async()=>{let stamp='',sent=0;const client=createTeamClient({session:async()=>{stamp='a';return user},stamp:()=>stamp,online:()=>true,fetch:async()=>{sent++;return json({boards:[]})}});await client.get();assert.equal(sent,1);const f=fixture({session:async()=>null});await assert.rejects(f.client.get(),e=>e.code==='unauthorized');assert.equal(f.requests.length,0)});
test('account switch while the response is pending rejects the old response',async()=>{let release;const pending=new Promise(resolve=>{release=resolve}),f=fixture({fetch:()=>pending});const operation=f.client.get();await Promise.resolve();f.state.stamp='epoch-b|account-b';release(json({board:{title:'private'}}));await assert.rejects(operation,e=>e.code==='account_changed')});
test('account switch during JSON decoding rejects the old private payload',async()=>{let release;const pending=new Promise(resolve=>{release=resolve}),f=fixture({fetch:async()=>({ok:true,status:200,json:()=>pending})});const operation=f.client.get();await Promise.resolve();await Promise.resolve();f.state.stamp='epoch-b|account-b';release({board:{title:'private'}});await assert.rejects(operation,e=>e.code==='account_changed')});
test('network uncertainty is reported without resending a mutation',async()=>{let sent=0;const f=fixture({fetch:async()=>{sent++;throw Error('network details')}});await assert.rejects(f.client.mutate({type:'close',roomId:'one',revision:1},user.userId),e=>e.code==='service_unavailable');assert.equal(sent,1);assert.equal(teamError(Error('private internal data')),'service_unavailable');assert.equal(teamError(new TeamApiError('unknown secret')),'service_unavailable')});
test('known server failures remain actionable without displaying raw server errors',async()=>{for(const code of ['name_taken','invite_invalid','limit','forbidden','not_found','read_only']){const f=fixture({fetch:async()=>json({error:code},400)});await assert.rejects(f.client.get(),e=>teamError(e)===code)}const f=fixture({fetch:async()=>json({error:'SQL private details'},503)});await assert.rejects(f.client.get(),e=>e.code==='service_unavailable')});
test('team copy covers all five languages and literal UI keys',()=>{for(const [key,values] of Object.entries(teamWords)){assert.equal(values.length,5,key);for(const value of values)assert.equal(typeof value==='string'&&value.trim().length>0,true,key)}for(const file of ['components/team-board.tsx','components/team-page.tsx']){const source=fs.readFileSync(path.join(root,file),'utf8');for(const match of source.matchAll(/\bt\('([^']+)'\)/g))assert.ok(teamWords[match[1]],file+':'+match[1])}for(const locale of ['ar','en','fr','zh','hi'])assert.ok(teamText(locale,'missing_key')!== 'missing_key')});
test('embedded board has no nested forms, invite secrets never enter signin returns, and draft controls detach from trip forms',()=>{const source=fs.readFileSync(path.join(root,'components/team-board.tsx'),'utf8');assert.doesNotMatch(source,/<form\b/);assert.match(source,/form=\{id\+'-detached'\}/);assert.doesNotMatch(source,/return_to[^\n]*(?:location\.hash|encodeURIComponent\(token\))/);assert.match(source,/revision:draft\.revision/);assert.match(source,/disabled=\{locked\|\|stale\|\|!selected\}/);assert.match(source,/document\.visibilityState==='visible'&&navigator\.onLine/)});
