'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,BookOpen} from 'lucide-react';
import {useSite} from './site-shell';
import {useCatalog} from '@/lib/catalog-client';
import {activeDestinations,catalogDestination} from '@/lib/catalog-seed';
import {assistantSource,assistantTopics,retrieveGuide,type AssistantRequest,type AssistantTopic} from '@/lib/assistant-guide';
import {retrieveTripGuide,applyAssistantProposal,requestForTrip,checkProposalCatalog,assertProposalCatalog} from '@/lib/assistant-trip';
import {assistantPreparationText as preparation} from '@/lib/assistant-preparation-copy';
import {companionText} from '@/lib/companion-i18n';
import {terrains,type Locale} from '@/lib/terrain';
import {assistantContext,assistantReportHref} from '@/lib/assistant-context';
import {loadTrips,loadGear,saveTrip,getSession} from '@/lib/trip-store';
import type {AssistantAnswer,AssistantProposal,CatalogSnapshot,Coordinates,SessionInfo,Trip} from '@/lib/toolkit-types';
import type {AIProviderId,AIProviderSummary} from '@/lib/ai-providers';
import './companion.css';
import './packing.css';
interface Message{id:string;question:string;answer:AssistantAnswer;catalog:CatalogSnapshot}
export function AssistantView(){
 const {locale,t,tr}=useSite(),{catalog,refresh:refreshCatalog}=useCatalog(),c=(key:string)=>companionText(locale,key),p=(key:string)=>preparation(locale,key);
 const [destinationId,setDestinationId]=useState('liwa'),[genericTerrain,setGenericTerrain]=useState(0),[point,setPoint]=useState<Coordinates|null>(null),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]);
 const [busy,setBusy]=useState(false),[useAI,setUseAI]=useState(false),[shareTrip,setShareTrip]=useState(false),[status,setStatus]=useState(''),[trips,setTrips]=useState<Trip[]>([]),[selectedTrip,setSelectedTrip]=useState(''),[session,setSession]=useState<SessionInfo|null>(null),[saving,setSaving]=useState(false),[applied,setApplied]=useState<string[]>([]),[providers,setProviders]=useState<AIProviderSummary[]>([]),[provider,setProvider]=useState<AIProviderId|''>('');
 const requestRef=useRef<AbortController|null>(null),logRef=useRef<HTMLDivElement>(null),sessionRef=useRef<SessionInfo|null>(null);
 const catalogRef=useRef(catalog);useEffect(()=>{catalogRef.current=catalog;},[catalog]);
 // Which generative providers the operator configured (labels and model names only); the guide answer never depends on this.
 useEffect(()=>{let active=true;fetch('/api/assistant',{credentials:'same-origin'}).then((r):Promise<{providers?:AIProviderSummary[]}>=>r.ok?r.json():Promise.resolve({providers:[]})).then(data=>{if(active)setProviders(Array.isArray(data.providers)?data.providers:[]);}).catch(()=>{if(active)setProviders([]);});return()=>{active=false;};},[]);
 const destination=catalogDestination(catalog,destinationId),terrainIndex=destination?.terrainIndex??genericTerrain,terrain=terrains[terrainIndex],reportHref=assistantReportHref(destinationId||null,terrainIndex,point);
 useEffect(()=>{
  const context=assistantContext(new URLSearchParams(location.search),catalog);
  // Hydrate browser-owned URL selection after SSR; also accept newly published destination identifiers.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setDestinationId(context.destinationId??'');setGenericTerrain(context.terrainIndex);setPoint(context.point);
 },[catalog]);
 useEffect(()=>{let active=true;
  const clear=()=>{requestRef.current?.abort();requestRef.current=null;sessionRef.current=null;setSession(null);setTrips([]);setSelectedTrip('');setShareTrip(false);setMessages([]);setApplied([]);setBusy(false);};
  const load=async()=>{try{const user=await getSession();if(!active)return;if(sessionRef.current&&sessionRef.current.userId!==user?.userId)clear();sessionRef.current=user;setSession(user);if(user){const rows=await loadTrips();if(active&&sessionRef.current?.userId===user.userId)setTrips(rows);}else clear();}catch{if(active)setStatus('tripError');}};
  const storage=(event:StorageEvent)=>{if(event.key==='daroub-offline-account'||event.key==='daroub-account-generation'||event.key===null){clear();void load();}};
  void load();window.addEventListener('storage',storage);window.addEventListener('daroub:trip-sync',load);return()=>{active=false;requestRef.current?.abort();requestRef.current=null;window.removeEventListener('storage',storage);window.removeEventListener('daroub:trip-sync',load);};
 },[]);
 useEffect(()=>{if(logRef.current)logRef.current.scrollTop=logRef.current.scrollHeight;},[messages,busy]);
 function resetContext(){requestRef.current?.abort();requestRef.current=null;setBusy(false);setMessages([]);setStatus('');setShareTrip(false);setApplied([]);}
 function selectDestination(id:string){resetContext();setSelectedTrip('');setDestinationId(id);setPoint(null);const url=new URL(location.href);if(id)url.searchParams.set('destination',id);else url.searchParams.delete('destination');for(const key of ['terrain','terrainId','generic','lat','lon'])url.searchParams.delete(key);history.replaceState(null,'',url);}
 function selectTrip(id:string){resetContext();setSelectedTrip(id);const trip=trips.find(row=>row.id===id);if(trip){setDestinationId(catalogDestination(catalog,trip.destinationId)?.id??'');setGenericTerrain(Math.max(0,terrains.findIndex(row=>row.id===trip.terrainId)));setPoint(trip.destinationId?null:trip.location);}}
 async function answer(text:string,topic?:AssistantTopic){
  if(!text.trim()||busy)return;const controller=new AbortController();requestRef.current=controller;setBusy(true);setStatus('');setQuestion('');
  let input:AssistantRequest={question:text.trim().slice(0,1500),locale,destinationId:destination?.id??null,terrainIndex,topic,useAI,provider:useAI&&provider?provider:undefined,tripId:selectedTrip||undefined,shareTripContext:!!selectedTrip&&shareTrip};
  let result=retrieveGuide(input,catalog),localFallback=false;let owner=sessionRef.current?.userId;
  try{
   if(selectedTrip){const user=await getSession();if(!user||user.userId!==owner)throw Error('account');const current=(await loadTrips()).find(row=>row.id===selectedTrip);if(!current)throw Error('account');input=requestForTrip(input,current,catalog);result=await retrieveTripGuide(input,current,await loadGear(),catalog);}
   const timeout=setTimeout(()=>controller.abort(),15000);
   try{const response=await fetch('/api/assistant',{method:'POST',credentials:'same-origin',signal:controller.signal,headers:{'Content-Type':'application/json',...(owner?{'X-Daroub-Account':owner}:{})},body:JSON.stringify(input)});if([401,404,409].includes(response.status))throw Error('account');if(!response.ok)throw Error('offline');result=await response.json() as AssistantAnswer;}
   catch(error){if(error instanceof Error&&error.message==='account')throw error;localFallback=true;}finally{clearTimeout(timeout);}
  }catch{result=retrieveGuide({...input,tripId:undefined},catalog);setStatus('prep-unavailable');owner=undefined;}
  if(requestRef.current!==controller)return;
  if(owner&&sessionRef.current?.userId!==owner){setBusy(false);requestRef.current=null;return;}
  if(result.catalogRevision!==catalog.revision)void refreshCatalog();
  setMessages(previous=>[...previous.slice(-19),{id:crypto.randomUUID(),question:input.question,answer:result,catalog}]);
  if(localFallback)setStatus(selectedTrip?'prep-offline':'fallback');else if(result.fallbackReason)setStatus('ai-'+result.fallbackReason);setBusy(false);requestRef.current=null;
 }
 async function apply(proposal:AssistantProposal,quantity?:number){
  if(saving||!sessionRef.current)return;setSaving(true);setStatus('');const owner=sessionRef.current.userId;
  try{const user=await getSession();if(!user||user.userId!==owner)throw Error('Account changed');const current=(await loadTrips()).find(trip=>trip.id===proposal.tripId);if(!current)throw Error('Stale proposal');const knownRevision=catalogRef.current.revision,checked=await checkProposalCatalog(proposal,catalogRef.current,navigator.onLine);const updated=await applyAssistantProposal(current,proposal,quantity,checked.revision);if(catalogRef.current.revision!==knownRevision)assertProposalCatalog(proposal,catalogRef.current.revision);const saved=await saveTrip(updated,{expectedTrip:current});if(sessionRef.current?.userId!==owner)return;setTrips(previous=>previous.map(trip=>trip.id===saved.id?saved:trip));setApplied(previous=>[...previous,proposal.id]);setStatus(checked.offline?'prep-appliedOffline':'prep-applied');}
  catch(error){const reason=error instanceof Error?error.message:'';if(reason==='Catalog changed'){setStatus('prep-catalogChanged');void refreshCatalog();}else setStatus(reason==='Catalog unavailable'?'prep-catalogUnavailable':/stale|changed/i.test(reason)?'prep-stale':'prep-applyError');}finally{setSaving(false);}
 }
 return <main id="main" className="page inner-page assistant-page"><div className="view-heading"><div><span className="eyebrow">DAROUB / {c('destination')}</span><h1>{t('assistant')}</h1><p>{t('companionDesc')}</p></div><label className="companion-select">{c('destination')}<select value={destinationId} onChange={e=>selectDestination(e.target.value)}>{!destinationId&&<option value="">{tr(terrain.names)} · {c('generic')}</option>}{(destination?.archived?[destination,...activeDestinations(catalog)]:activeDestinations(catalog)).map(item=><option key={item.id} value={item.id}>{tr(item.names)}</option>)}</select></label></div>
 <div className="chat-layout"><aside className="chat-context"><img src={destination?.image??terrain.image} alt={t('illustration')}/><div><h2>{tr(destination?.names??terrain.names)}</h2><p>{destination?tr(destination.summary):c('generic')}</p><a className="source-link" href={reportHref}>{t('report')} ↗</a><a className="source-link companion-trip-link" href="/trips">{c('trips')} ↗</a></div></aside>
 <section className="chat-panel" aria-label={t('assistant')}><div className="chat-heading"><Sparkles aria-hidden/><div><h2>{t('assistant')}</h2><span className="mode-pill">{c('guideMode')}</span></div></div><p className="subtle">{c('modeNote')}</p>
 <div className="assistant-context-picker">{session?<><label className="companion-select">{p('context')}<select value={selectedTrip} disabled={busy||saving} onChange={e=>selectTrip(e.target.value)}><option value="">{p('public')}</option>{trips.map(trip=><option key={trip.id} value={trip.id}>{trip.title}</option>)}</select></label><p>{p('useTrip')}</p>{!trips.length&&<a href="/trips">{c('createTrip')}</a>}</>:<a className="source-link" href="/login?return_to=%2Fassistant">{c('signIn')}</a>}</div>
 <label className="companion-checkbox"><input type="checkbox" checked={useAI} onChange={e=>{setUseAI(e.target.checked);if(!e.target.checked)setShareTrip(false);}}/>{c('aiOptIn')}</label>{useAI&&<div className="assistant-trip-consent"><p>{p('aiScope')}</p>{providers.length>0?<><label className="companion-select">{c('aiProvider')}<select value={provider} disabled={busy} onChange={e=>setProvider(e.target.value as AIProviderId|'')}>{providers.map(item=><option key={item.id} value={item.id}>{item.label} · {item.model}</option>)}</select></label><p>{c('aiProviderNote')}</p></>:<p>{c('ai-unconfigured')}</p>}{selectedTrip&&<><label className="companion-checkbox"><input type="checkbox" checked={shareTrip} onChange={e=>setShareTrip(e.target.checked)}/>{p('share')}</label><p>{p('scope')}</p></>}</div>}
 <div ref={logRef} className="chat-log" role="log" aria-live="polite" aria-relevant="additions" aria-atomic="false" aria-busy={busy}>{messages.length===0?<div className="chat-empty"><BookOpen size={35} aria-hidden/><h3>{t('companion')}</h3><p>{c('clarify')}</p><p>{p('selectToPropose')}</p></div>:messages.map(message=><article key={message.id} className="chat-pair" lang={message.answer.locale} dir={message.answer.locale==='ar'?'rtl':'ltr'}><p className="question-bubble">{message.question}</p><div className="answer-bubble">{message.answer.tripContext&&<strong>{preparation(message.answer.locale,'context')}: {message.answer.tripContext.title}</strong>}{message.answer.aiText&&<section className="companion-ai-draft"><h3>{companionText(message.answer.locale,'aiMode')}{message.answer.aiProvider?` · ${message.answer.aiProvider.label}`:''}</h3><p className="subtle">{companionText(message.answer.locale,'aiUnverified')}</p><p className="companion-answer">{message.answer.aiText}</p></section>}<span className="mode-pill">{companionText(message.answer.locale,'guideMode')}</span><p className="companion-answer">{message.answer.text}</p><p className="subtle">{preparation(message.answer.locale,'catalogRevision')}: {message.answer.catalogRevision??message.catalog.revision}</p>{message.answer.sourceIds.length>0&&<details className="companion-sources"><summary>{companionText(message.answer.locale,'sources')}</summary><ul>{message.answer.sourceIds.map(id=>{const source=message.answer.sources?.find(source=>source.id===id)??assistantSource(id,message.catalog);return source?<li key={id}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a><small>{companionText(message.answer.locale,'reviewed')}: {source.reviewedAt}</small></li>:null;})}</ul></details>}{message.answer.proposals?.map(proposal=><ProposalPreview key={proposal.id} proposal={proposal} locale={message.answer.locale} disabled={!session||saving||selectedTrip!==proposal.tripId} applied={applied.includes(proposal.id)} staleCatalog={proposal.expectedCatalogRevision!==catalog.revision} onApply={(edited,qty)=>void apply(edited,qty)}/>)}</div></article>)}{busy&&<p role="status">{c('busy')}</p>}</div>
 <div className="suggestions">{assistantTopics.map(topic=><button type="button" disabled={busy} key={topic} onClick={()=>void answer(c(topic),topic)}>{c(topic)}</button>)}</div><form onSubmit={e=>{e.preventDefault();void answer(question);}} className="chat-input"><label htmlFor="question" className="sr-only">{t('question')}</label><input id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t('question')} maxLength={1500} required disabled={busy}/><button disabled={busy||!question.trim()} type="submit" className="primary-btn" aria-label={t('send')}><Send size={21}/></button></form>{status&&<p className="status-message" role="status">{status.startsWith('prep-')?p(status.slice(5)):c(status)}</p>}<a className="source-link" href={reportHref}>{t('report')} ↗</a></section></div></main>;
}
function ProposalPreview({proposal,locale,disabled,applied,staleCatalog,onApply}:{proposal:AssistantProposal;locale:Locale;disabled:boolean;applied:boolean;staleCatalog:boolean;onApply:(proposal:AssistantProposal,quantity?:number)=>void}){
 const c=(key:string)=>preparation(locale,key),[quantity,setQuantity]=useState(String(proposal.items?.[0]?.requiredQuantity??1)),qty=Number(quantity),equipment=proposal.type==='add-equipment',[entryTitle,setEntryTitle]=useState(proposal.entry?.title??''),[duration,setDuration]=useState(String(proposal.entry?.durationMinutes??30)),minutes=Number(duration),validEntry=!!entryTitle.trim()&&entryTitle.length<=160&&Number.isInteger(minutes)&&minutes>=0&&minutes<=10080;
 return <section className="assistant-proposal"><h3>{c('preview')}</h3><p>{proposal.label}</p><p>{c('catalogRevision')}: {proposal.expectedCatalogRevision}</p><p className="subtle">{c('catalogOffline')}</p>{staleCatalog&&<p>{c('catalogChanged')}</p>}{equipment?<><ul>{proposal.items?.map(item=><li key={item.id}>{item.label}</li>)}</ul><label>{c('quantity')} <input type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} disabled={applied}/></label></>:<><p>{c('firstDay')}</p><label>{c('entryTitle')} <input value={entryTitle} maxLength={160} disabled={applied} onChange={e=>setEntryTitle(e.target.value)}/></label><label>{c('duration')} <input type="number" min="0" max="10080" step="1" value={duration} disabled={applied} onChange={e=>setDuration(e.target.value)}/></label><p>{proposal.entry?.notes}</p></>}<button className="outline-btn" type="button" disabled={disabled||applied||staleCatalog||(equipment?(!Number.isInteger(qty)||qty<1||qty>10000):!validEntry)} onClick={()=>onApply(equipment?proposal:{...proposal,entry:proposal.entry?{...proposal.entry,title:entryTitle.trim(),durationMinutes:minutes}:undefined},equipment?qty:undefined)}>{c(applied?'applied':'apply')}</button></section>;
}
