'use client';
import {useState} from 'react';
import {ArrowDown,ArrowUp,CalendarDays,Check,ChevronDown,Clock,Copy,MapPin,Plus,Route,Settings2,Trash2} from 'lucide-react';
import {focusAfterRender} from '@/lib/preparation-focus';
import {validTimeZone} from '@/lib/preparation-schema';
import {prepText} from '@/lib/preparation-copy';
import {releaseText,activityIds} from '@/lib/preparation-release-copy';
import {itineraryText} from '@/lib/itinerary-copy';
import {dayDate,duplicateDay,emptyEntry,itineraryWarnings,moveItem} from '@/lib/itinerary';
import type {Locale} from '@/lib/terrain';
import type {CatalogSnapshot,ItineraryDay,ItineraryEntry,Trip} from '@/lib/toolkit-types';
import {catalogDestination} from '@/lib/catalog-seed';

function invalidEntry(entry:ItineraryEntry){return !entry.title.trim()||!Number.isInteger(entry.durationMinutes)||entry.durationMinutes<0||entry.durationMinutes>10080||!/^(?:|(?:[01]\d|2[0-3]):[0-5]\d)$/.test(entry.startTime)||!!entry.startTime&&!validTimeZone(entry.timeZone);}
function invalidDay(day:ItineraryDay){return !Number.isInteger(day.dayOffset)||day.dayOffset<0||day.dayOffset>3650;}

export function ItineraryEditor({trip,onChange,catalog,locale}:{trip:Trip;onChange:(trip:Trip)=>void;catalog:CatalogSnapshot;locale:Locale}){
 const p=(key:string)=>prepText(locale,key),r=(key:string)=>releaseText(locale,key),c=(key:string)=>itineraryText(locale,key);
 const days=trip.itinerary??[],warnings=itineraryWarnings(trip),total=days.reduce((count,day)=>count+day.entries.length,0);
 const [announcement,setAnnouncement]=useState(''),[editing,setEditing]=useState<string[]>([]),[dayOptions,setDayOptions]=useState<string[]>([]);
 const zone=catalogDestination(catalog,trip.destinationId)?.timezone??'';
 const activities=[...new Set([...activityIds,...catalog.packingRules.flatMap(rule=>rule.activities),...(trip.activities??[]),...days.flatMap(day=>day.entries.map(entry=>entry.activityId))])];
 const nextOffset=Math.max(-1,...days.map(day=>day.dayOffset))+1,canAddDay=days.length<60&&Number.isInteger(nextOffset)&&nextOffset<=3650;
 function updateDays(next:ItineraryDay[]){onChange({...trip,itinerary:next});}
 function updateDay(id:string,patch:Partial<ItineraryDay>){updateDays(days.map(day=>day.id===id?{...day,...patch}:day));}
 function openEntry(id:string){setEditing(ids=>ids.includes(id)?ids:[...ids,id]);}
 function updateEntry(day:ItineraryDay,id:string,patch:Partial<ItineraryEntry>){openEntry(id);updateDay(day.id,{entries:day.entries.map(entry=>entry.id===id?{...entry,...patch}:entry)});}
 function reorderDay(index:number,delta:number){const next=moveItem(days,index,delta),offsets=days.map(day=>day.dayOffset);updateDays(next.map((day,i)=>({...day,dayOffset:offsets[i]})));setAnnouncement(r('dayMoved')+': '+(days[index].dayOffset+1)+' → '+(offsets[index+delta]+1));focusAfterRender('day-heading-'+days[index].id);}
 function removeDay(day:ItineraryDay,index:number){const next=days[index+1]??days[index-1];updateDays(days.filter(item=>item.id!==day.id));setAnnouncement(r('dayRemoved')+': '+(Number.isFinite(day.dayOffset)?day.dayOffset+1:'—'));focusAfterRender(next?'day-heading-'+next.id:'add-itinerary-day','itinerary-section');}
 function removeEntry(day:ItineraryDay,entry:ItineraryEntry,index:number){const next=day.entries[index+1]??day.entries[index-1];updateDay(day.id,{entries:day.entries.filter(item=>item.id!==entry.id)});setAnnouncement(r('entryRemoved')+': '+(entry.title||r('entryTitle')));focusAfterRender(next?'entry-heading-'+next.id:'add-entry-'+day.id,'itinerary-section');}
 function moveEntry(day:ItineraryDay,index:number,delta:number){updateDay(day.id,{entries:moveItem(day.entries,index,delta)});setAnnouncement(r('entryMoved')+': '+(day.entries[index].title||r('entryTitle'))+' · '+r('position')+' '+(index+delta+1)+'/'+day.entries.length);focusAfterRender('entry-heading-'+day.entries[index].id);}
 function addEntry(day:ItineraryDay){if(day.entries.length>=40||total>=600)return;const entry=emptyEntry(zone);openEntry(entry.id);updateDay(day.id,{entries:[...day.entries,entry]});setAnnouncement(r('entryAdded'));focusAfterRender('entry-title-'+entry.id);}
 function copyEntry(day:ItineraryDay,entry:ItineraryEntry){if(day.entries.length>=40||total>=600)return;const copy={...structuredClone(entry),id:crypto.randomUUID()};openEntry(copy.id);updateDay(day.id,{entries:[...day.entries,copy]});setAnnouncement(r('entryCopied')+': '+entry.title);focusAfterRender('entry-title-'+copy.id);}
 function copyDay(day:ItineraryDay){if(!canAddDay||total+day.entries.length>600)return;const copy=duplicateDay(day,nextOffset);updateDays([...days,copy]);setAnnouncement(r('dayCopied')+': '+(day.dayOffset+1)+' → '+(copy.dayOffset+1));focusAfterRender('day-heading-'+copy.id);}
 function addDay(){if(!canAddDay)return;const day={id:crypto.randomUUID(),dayOffset:nextOffset,entries:[]};updateDays([...days,day]);setAnnouncement(r('dayAdded')+': '+(day.dayOffset+1));focusAfterRender('add-entry-'+day.id);}
 return <section id="itinerary-section" className="itinerary" aria-labelledby="itinerary-title" tabIndex={-1}>
  <div className="itinerary-heading"><div><span className="itinerary-eyebrow"><Route size={17} aria-hidden="true"/>{c('yourPlan')}</span><h3 id="itinerary-title">{r('itinerary')}</h3><p>{c('intro')}</p></div>{days.length>0&&<span className="itinerary-count">{c('days')}: <bdi>{days.length}</bdi> · {c('activities')}: <bdi>{total}</bdi></span>}</div>
  <details className="itinerary-preferences"><summary><Settings2 size={17} aria-hidden="true"/><span>{c('tripActivities')}</span><small>{(trip.activities?.length??0)>0?trip.activities?.map(id=>r(id)).join(' · '):c('optional')}</small><ChevronDown size={17} aria-hidden="true"/></summary><p>{c('activitiesHelp')}</p><div className="itinerary-activity-chips">{activities.filter(id=>id!=='other').map(id=><label key={id}><input type="checkbox" checked={trip.activities?.includes(id)??false} disabled={!trip.activities?.includes(id)&&(trip.activities?.length??0)>=30} onChange={event=>onChange({...trip,activities:event.target.checked?[...trip.activities??[],id]:(trip.activities??[]).filter(activity=>activity!==id)})}/><span>{r(id)}</span></label>)}</div></details>
  <p role="status" aria-atomic="true" className="sr-only">{announcement}</p>
  {!days.length&&<div className="itinerary-empty"><CalendarDays size={32} aria-hidden="true"/><h4>{c('emptyTitle')}</h4><p>{r('noDays')}</p></div>}
  <div className="itinerary-days">{days.map((day,index)=>{
   const dayNumber=Number.isFinite(day.dayOffset)?day.dayOffset+1:'—',date=dayDate(trip.startDate,day.dayOffset),badDay=invalidDay(day),optionsOpen=dayOptions.includes(day.id)||badDay;
   return <section className="itinerary-day" key={day.id} aria-labelledby={'day-heading-'+day.id}>
    <div className="itinerary-day-heading"><span className="itinerary-day-number" aria-hidden="true">{dayNumber}</span><div><h4 id={'day-heading-'+day.id} tabIndex={-1}>{r('day')} <bdi>{dayNumber}</bdi>{date&&<time dateTime={date}>{date}</time>}</h4><p>{c('activities')}: {day.entries.length}{!date&&' · '+c('datesLater')}</p></div><button id={'day-toggle-'+day.id} className="itinerary-icon-button" type="button" aria-expanded={optionsOpen} aria-controls={optionsOpen?'day-options-'+day.id:undefined} aria-label={`${c('dayOptions')}: ${r('day')} ${dayNumber}`} onClick={()=>setDayOptions(ids=>optionsOpen?ids.filter(id=>id!==day.id):[...ids,day.id])}><Settings2 size={19} aria-hidden="true"/></button></div>
    {optionsOpen&&<div id={'day-options-'+day.id} className="itinerary-day-options"><label>{r('dayOffset')}<input id={'day-offset-'+day.id} type="number" min={1} max={3651} step={1} required value={Number.isFinite(day.dayOffset)?day.dayOffset+1:''} aria-invalid={badDay||undefined} aria-describedby={badDay?'day-error-'+day.id:undefined} onChange={event=>{setDayOptions(ids=>ids.includes(day.id)?ids:[...ids,day.id]);updateDay(day.id,{dayOffset:event.target.value===''?NaN:Number(event.target.value)-1})}}/></label><div className="itinerary-actions"><button type="button" disabled={index===0||days.some(invalidDay)} onClick={()=>reorderDay(index,-1)}><ArrowUp size={16} aria-hidden="true"/>{r('moveUp')}</button><button type="button" disabled={index===days.length-1||days.some(invalidDay)} onClick={()=>reorderDay(index,1)}><ArrowDown size={16} aria-hidden="true"/>{r('moveDown')}</button><button type="button" disabled={!canAddDay||total+day.entries.length>600} onClick={()=>copyDay(day)}><Copy size={16} aria-hidden="true"/>{r('duplicateDay')}</button><button className="itinerary-remove" type="button" onClick={()=>removeDay(day,index)}><Trash2 size={16} aria-hidden="true"/>{r('removeDay')}</button></div>{badDay&&<p id={'day-error-'+day.id} className="prep-warning">{c('invalidDay')}</p>}</div>}
    {warnings.filter(warning=>warning.dayId===day.id).map(warning=><p className="itinerary-warning" key={warning.key}>{r(warning.key)}</p>)}
    {!day.entries.length&&<p className="itinerary-day-empty">{c('emptyDay')}</p>}
    <ol className="itinerary-entry-list">{day.entries.map((entry,entryIndex)=>{
     const bad=invalidEntry(entry),open=editing.includes(entry.id)||bad,badZone=!!entry.startTime&&!validTimeZone(entry.timeZone),badDuration=!Number.isInteger(entry.durationMinutes)||entry.durationMinutes<0||entry.durationMinutes>10080;
     return <li className={'itinerary-entry'+(open?' is-editing':'')} key={entry.id}>
      <div className="itinerary-entry-heading"><span className="itinerary-time"><Clock size={15} aria-hidden="true"/><bdi>{entry.startTime||c('flexible')}</bdi>{entry.startTime&&entry.timeZone&&<small>{entry.timeZone}</small>}</span><div className="itinerary-entry-summary"><h5 id={'entry-heading-'+entry.id} tabIndex={-1}>{entry.title||c('newActivity')}</h5><p><span>{r(entry.activityId)}</span>{entry.durationMinutes>0&&<span>{entry.durationMinutes} {c('minutes')}</span>}{entry.place&&<span><MapPin size={13} aria-hidden="true"/>{entry.place}</span>}</p>{bad&&<span className="itinerary-needs-detail">{c('completeDetails')}</span>}</div><button className="itinerary-edit" type="button" disabled={bad&&open} aria-label={`${open?c('close'):p('edit')}: ${entry.title||c('newActivity')}`} aria-expanded={open} aria-controls={open?'entry-editor-'+entry.id:undefined} onClick={()=>{setEditing(ids=>open?ids.filter(id=>id!==entry.id):[...ids,entry.id]);if(!open)focusAfterRender('entry-title-'+entry.id)}}>{open?c('close'):p('edit')}<ChevronDown size={16} aria-hidden="true"/></button></div>
      {open&&<div className="itinerary-entry-editor" id={'entry-editor-'+entry.id}><div className="prep-fields">
       <label>{r('entryTitle')}<input id={'entry-title-'+entry.id} required value={entry.title} maxLength={160} aria-invalid={!entry.title.trim()||undefined} ref={node=>{node?.setCustomValidity(entry.title.trim()?'':c('nameRequired'))}} onChange={event=>updateEntry(day,entry.id,{title:event.target.value})}/></label>
       <label>{r('activity')}<select value={entry.activityId} onChange={event=>updateEntry(day,entry.id,{activityId:event.target.value})}>{activities.map(id=><option key={id} value={id}>{r(id)}</option>)}</select></label>
       <label className="prep-wide">{r('place')}<input value={entry.place} maxLength={240} onChange={event=>updateEntry(day,entry.id,{place:event.target.value})}/></label>
       <label>{r('localTime')}<input type="time" value={entry.startTime} onChange={event=>updateEntry(day,entry.id,{startTime:event.target.value})}/></label>
       <label>{r('duration')}<input type="number" min={0} max={10080} step={1} required value={Number.isFinite(entry.durationMinutes)?entry.durationMinutes:''} aria-invalid={badDuration||undefined} aria-describedby={badDuration?'duration-error-'+entry.id:undefined} onChange={event=>updateEntry(day,entry.id,{durationMinutes:event.target.value===''?NaN:Number(event.target.value)})}/>{badDuration&&<small id={'duration-error-'+entry.id}>{c('invalidDuration')}</small>}</label>
       <label className="prep-wide">{r('timeZone')}<input ref={node=>{node?.setCustomValidity(badZone?r('invalidZone'):'')}} aria-invalid={badZone||undefined} aria-describedby={badZone?'zone-'+entry.id:undefined} value={entry.timeZone} placeholder="Asia/Dubai" maxLength={100} required={!!entry.startTime} onChange={event=>updateEntry(day,entry.id,{timeZone:event.target.value})}/>{badZone&&<small id={'zone-'+entry.id} role="status">{r('invalidZone')}</small>}</label>
      </div><details className="itinerary-extra"><summary>{c('extraDetails')}{(entry.transport||entry.notes)&&<span className="itinerary-has-details"><Check size={14} aria-hidden="true"/>{c('added')}</span>}</summary><div className="prep-fields"><label className="prep-wide">{p('transport')}<input maxLength={200} value={entry.transport} onChange={event=>updateEntry(day,entry.id,{transport:event.target.value})}/></label><label className="prep-wide">{p('notes')}<textarea maxLength={2000} value={entry.notes} onChange={event=>updateEntry(day,entry.id,{notes:event.target.value})}/></label></div></details>
      <div className="itinerary-entry-footer"><div className="itinerary-actions"><button type="button" disabled={entryIndex===0} onClick={()=>moveEntry(day,entryIndex,-1)}><ArrowUp size={16} aria-hidden="true"/>{r('moveUp')}</button><button type="button" disabled={entryIndex===day.entries.length-1} onClick={()=>moveEntry(day,entryIndex,1)}><ArrowDown size={16} aria-hidden="true"/>{r('moveDown')}</button><button type="button" disabled={day.entries.length>=40||total>=600} onClick={()=>copyEntry(day,entry)}><Copy size={16} aria-hidden="true"/>{r('duplicateEntry')}</button><button type="button" className="itinerary-remove" onClick={()=>removeEntry(day,entry,entryIndex)}><Trash2 size={16} aria-hidden="true"/>{r('removeEntry')}</button></div><button type="button" className="outline-btn" disabled={bad} onClick={()=>{setEditing(ids=>ids.filter(id=>id!==entry.id));focusAfterRender('entry-heading-'+entry.id)}}><Check size={16} aria-hidden="true"/>{c('done')}</button></div></div>}
     </li>;
    })}</ol>
    <button id={'add-entry-'+day.id} className="itinerary-add-entry" type="button" disabled={day.entries.length>=40||total>=600} onClick={()=>addEntry(day)}><Plus size={18} aria-hidden="true"/>{r('addEntry')}</button>
   </section>;
  })}</div>
  <button id="add-itinerary-day" className="outline-btn itinerary-add-day" type="button" disabled={!canAddDay} onClick={addDay}><Plus size={18} aria-hidden="true"/>{r('addDay')}</button>
  <details className="itinerary-help"><summary>{c('planningNotes')}</summary><p>{r('estimateNote')}</p><p>{r('zoneHelp')}</p><p>{r('scheduleLimit')}</p></details>
 </section>;
}
