"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Download,TriangleAlert} from 'lucide-react';
import {useSite} from './site-shell';
import {assertLegacyRecoveryCurrent,exportLegacyRecovery,readLegacyRecovery,type LegacyRecovery} from '@/lib/legacy-recovery';
import {downloadText} from '@/lib/trip-preparation';
const copy={
 title:['استرجاع بيانات قديمة','Recover older data','Récupérer des données anciennes','恢复旧数据','पुराना डेटा पुनर्प्राप्त करें'],
 warning:['تعذّر تحويل بعض السجلات القديمة تلقائياً. بقيت النسخ الأصلية محفوظة ولم تتأثر الرحلات السليمة. نزّل نسخة الاسترجاع قبل تسجيل الخروج أو مسح البيانات.','Some older records could not be converted automatically. Originals remain untouched, and healthy trips are unaffected. Download a recovery copy before signing out or clearing data.','Certains anciens éléments ne peuvent pas être convertis automatiquement. Les originaux sont conservés et les voyages valides restent inchangés. Téléchargez une copie avant de vous déconnecter ou d’effacer les données.','部分旧记录无法自动转换。原始副本保持不变，正常行程不受影响。退出或清除数据前，请下载恢复副本。','कुछ पुराने रिकॉर्ड अपने आप परिवर्तित नहीं हो सके। मूल प्रतियाँ सुरक्षित हैं और सही यात्राओं पर असर नहीं पड़ा। साइन आउट या डेटा मिटाने से पहले पुनर्प्राप्ति प्रति डाउनलोड करें।'],
 count:['سجلات تحتاج مراجعة','Records needing review','Éléments à examiner','需要检查的记录','समीक्षा की आवश्यकता वाले रिकॉर्ड'],
 download:['تنزيل بيانات الاسترجاع · JSON','Download recovery data · JSON','Télécharger les données à récupérer · JSON','下载恢复数据 · JSON','पुनर्प्राप्ति डेटा डाउनलोड करें · JSON'],
 note:['هذه نسخة خاصة للاسترجاع اليدوي، وليست ملف استيراد للرحلات. قد تحتوي على ملاحظاتك؛ احتفظ بها في مكان آمن.','This private copy is for manual recovery, not normal trip import. It may include your notes; keep it securely.','Cette copie privée sert à la récupération manuelle, pas à l’importation habituelle. Elle peut contenir vos notes ; conservez-la en sécurité.','此私人副本用于手动恢复，并非普通行程导入文件。可能包含您的备注，请妥善保存。','यह निजी प्रति मैन्युअल पुनर्प्राप्ति के लिए है, सामान्य यात्रा आयात के लिए नहीं। इसमें आपकी टिप्पणियाँ हो सकती हैं; सुरक्षित रखें।'],
 failed:['تعذّر قراءة نسخة الاسترجاع أو تنزيلها. لم تتغير البيانات؛ أعد المحاولة.','Recovery data could not be read or downloaded. Nothing was changed; retry.','Lecture ou téléchargement impossible. Aucune donnée n’a changé ; réessayez.','无法读取或下载恢复数据。数据未更改，请重试。','पुनर्प्राप्ति डेटा पढ़ना या डाउनलोड करना विफल। डेटा नहीं बदला; फिर प्रयास करें।'],
 saved:['أُعدّ ملف الاسترجاع للتنزيل. تحقّق من حفظه قبل مسح النسخ الخاصة.','Recovery download prepared. Check that the file was saved before clearing private copies.','Téléchargement préparé. Vérifiez que le fichier est enregistré avant d’effacer les copies privées.','恢复下载已准备就绪。清除私人副本前，请确认文件已保存。','पुनर्प्राप्ति डाउनलोड तैयार है। निजी प्रतियाँ मिटाने से पहले फ़ाइल सहेजी गई है यह जाँचें।'],
 };
export function LegacyRecoveryNotice(){
 const{tr,t}=useSite(),[snapshot,setSnapshot]=useState<LegacyRecovery|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),sequence=useRef(0),loaded=useRef<LegacyRecovery|null>(null);
 const refresh=useCallback(async()=>{const token=++sequence.current;try{const result=await readLegacyRecovery();if(token!==sequence.current)return;if(result)assertLegacyRecoveryCurrent(result);loaded.current=result;setSnapshot(result);setError(false)}catch{if(token===sequence.current){loaded.current=null;setSnapshot(null);setError(true)}}},[]);
 // IndexedDB/session reads are external state; invalidate pending reads when the account changes.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void refresh();const clear=()=>{sequence.current++;loaded.current=null;setSnapshot(null);setError(false);setSaved(false);setBusy(false)},account=(event:StorageEvent)=>{if(event.key===null||event.key==='daroub-account-generation'||event.key==='daroub-offline-account')clear()},update=()=>{try{if(!localStorage.getItem('daroub-offline-account')){clear();return}if(loaded.current)assertLegacyRecoveryCurrent(loaded.current)}catch{clear();return}void refresh()};window.addEventListener('storage',account);window.addEventListener('daroub:trip-sync',update);return()=>{sequence.current++;window.removeEventListener('storage',account);window.removeEventListener('daroub:trip-sync',update)}},[refresh]);
 async function download(){if(!snapshot)return;const token=sequence.current;setBusy(true);setSaved(false);try{const json=await exportLegacyRecovery(snapshot);if(token!==sequence.current)return;assertLegacyRecoveryCurrent(snapshot);downloadText(json,'daroub-legacy-recovery.json','application/json');setSaved(true);setError(false)}catch{if(token===sequence.current)setError(true)}finally{if(token===sequence.current)setBusy(false)}}
 if(!snapshot?.rows.length&&!error)return null;
 return <section className="panel warning-panel" aria-labelledby="legacy-recovery-title"><div className="panel-title"><TriangleAlert size={22}/><h2 id="legacy-recovery-title">{tr(copy.title)}</h2></div>{snapshot?.rows.length?<><p>{tr(copy.warning)}</p><p>{tr(copy.count)}: <strong>{snapshot.rows.length}</strong></p><button className="outline-btn" disabled={busy} onClick={()=>void download()}><Download size={18}/>{busy?t('load'):tr(copy.download)}</button><p className="subtle">{tr(copy.note)}</p></>:null}{error&&<div role="alert"><p>{tr(copy.failed)}</p><button className="outline-btn" onClick={()=>void refresh()}>{t('retry')}</button></div>}{saved&&<p role="status">{tr(copy.saved)}</p>}</section>;
}
