"use client";
import {createContext,useContext,useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';

import {ToolkitRuntime} from './toolkit-runtime';
import {Compass,Globe2,Accessibility,Watch,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Locale,locales,languageNames,translate,words} from '@/lib/terrain';
const Context=createContext({locale:'ar' as Locale,t:(k:string)=>k,tr:(v:string[])=>v[0],reduced:false});
export const useSite=()=>useContext(Context);
export function SiteShell({children}:{children:React.ReactNode}){
 const [locale,setLocale]=useState<Locale>('ar'),[access,setAccess]=useState(false),[contrast,setContrast]=useState(false),[reduced,setReduced]=useState(false),[scale,setScale]=useState('100'),[ready,setReady]=useState(false);
 const pathname=usePathname();const t=(k:string)=>translate(locale,words[k]??[k]);const tr=(v:string[])=>translate(locale,v);
 // Hydrate browser-only preferences after the server's stable initial render.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('daroub-preferences')||'{}');if(locales.includes(p.locale))setLocale(p.locale);setContrast(!!p.contrast);setReduced(p.reduced??matchMedia('(prefers-reduced-motion: reduce)').matches);if(['100','125','150','200'].includes(p.scale))setScale(p.scale)}catch{}setReady(true)},[]);
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.documentElement.style.fontSize=scale+'%';document.documentElement.classList.toggle('high-contrast',contrast);document.documentElement.classList.toggle('reduce-motion',reduced);if(ready)try{localStorage.setItem('daroub-preferences',JSON.stringify({locale,contrast,reduced,scale}))}catch{}},[locale,contrast,reduced,scale,ready]);
 return <Context.Provider value={{locale,t,tr,reduced}}><a className="skip" href="#main">{t('skip')}</a><header className="header"><a className="brand" href="/" aria-label="دروب — Daroub"><span className="brand-icon"><Compass size={29} aria-hidden/></span><span>دروب<small>DAROUB</small></span></a><nav aria-label={t('home')}>{[['/','home'],['/regions','regions'],['/globe','globe']].map(([path,label])=><a key={path} className={pathname===path?'nav-active':''} aria-current={pathname===path?'page':undefined} href={path}>{t(label)}</a>)}</nav><div className="header-tools"><button className="icon-button" aria-label={t('access')} onClick={()=>setAccess(true)}><Accessibility size={21}/></button><Select value={locale} onValueChange={v=>setLocale(v as Locale)}><SelectTrigger aria-label={t('language')} className="language-select"><Globe2 size={17}/><SelectValue/></SelectTrigger><SelectContent>{locales.map((l,i)=><SelectItem key={l} value={l}><span lang={l}>{languageNames[i]}</span></SelectItem>)}</SelectContent></Select><a className="watch-link" href="/health" aria-label={t('health')}><Watch size={19}/><span>{t('health')}</span></a></div></header><ToolkitRuntime/>{children}<footer><a href="/" className="footer-brand">دروب <Compass size={18}/></a><p>{t('footer')}</p><a href="/sources">{t('sources')}</a></footer><Dialog open={access} onOpenChange={setAccess}><DialogContent className="access-dialog" showCloseButton={false} dir={locale==='ar'?'rtl':'ltr'}><DialogTitle>{t('access')}</DialogTitle><DialogDescription>{t('accessNote')}</DialogDescription><DialogClose className="dialog-x" aria-label={t('close')}><X size={20}/></DialogClose><label className="setting"><span>{t('contrast')}</span><Switch checked={contrast} onCheckedChange={setContrast}/></label><label className="setting"><span>{t('motion')}</span><Switch checked={reduced} onCheckedChange={setReduced}/></label><div className="setting"><label id="text-size-label">{t('textSize')}</label><Select value={scale} onValueChange={setScale}><SelectTrigger aria-labelledby="text-size-label"><SelectValue/></SelectTrigger><SelectContent>{['100','125','150','200'].map(v=><SelectItem value={v} key={v}>{v}%</SelectItem>)}</SelectContent></Select></div><button className="outline-btn" onClick={()=>{setContrast(false);setReduced(matchMedia('(prefers-reduced-motion: reduce)').matches);setScale('100')}}>{t('reset')}</button></DialogContent></Dialog></Context.Provider>
}
