'use client';
import {useCallback,useEffect,useId,useRef,useState} from 'react';
import {Users,RefreshCw,Copy,Plus,UserMinus,Link2,Check,AlertTriangle,PackageCheck,ArrowRight} from 'lucide-react';
import type {Locale} from '@/lib/terrain';
import type {SessionInfo} from '@/lib/toolkit-types';
import type {TeamAction,TeamBoard,TeamItem,TeamPreview,TeamResponse} from '@/lib/team-types';
import {allocationTotals,invitationUrl,teamClient,teamError,validAllocation} from '@/lib/team-client';
import {teamText} from '@/lib/team-copy';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {TeamPersonEditor} from './team-person-editor';
import './team-board.css';

type ConfirmState={kind:'create'|'refresh'|'remove-person'|'close'|'leave'|'invite';action:TeamAction;preview?:TeamPreview;person?:string};
type AllocationDraft={participantId:string;quantity:string;packed:string;revision:number};
export type TeamFilter='remaining'|'mine'|'unassigned'|'all';
export function teamItemMatches(board:TeamBoard,item:TeamItem,filter:TeamFilter){
 const totals=allocationTotals(board,item.id,item.required);
 if(filter==='mine')return board.allocations.some(row=>row.itemId===item.id&&row.quantity>0&&board.participants.some(person=>person.id===row.participantId&&person.isYou));
 if(filter==='unassigned')return totals.gap>0;
 return filter==='all'||totals.gap>0||totals.overbooked>0||totals.packed<item.required;
}
/** Count checklist lines, never add together quantities with different units. */
export function teamPreparationSummary(board:TeamBoard){
 const values=board.items.map(item=>({item,...allocationTotals(board,item.id,item.required)}));
 return {total:values.length,packed:values.filter(row=>row.packed>=row.item.required).length,remaining:values.filter(row=>row.packed<row.item.required).length,unassigned:values.filter(row=>row.gap>0).length,overassigned:values.filter(row=>row.overbooked>0).length,mine:board.items.filter(item=>teamItemMatches(board,item,'mine')).length,myRemaining:board.items.filter(item=>board.allocations.some(row=>row.itemId===item.id&&row.packed<row.quantity&&board.participants.some(person=>person.id===row.participantId&&person.isYou))).length,joined:board.participants.filter(person=>person.linked).length,named:board.participants.filter(person=>!person.linked).length};
}
function date(locale:Locale,value:string){try{return new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return ''}}
export function TeamBoardPanel({tripId,locale,dirty=false}:{tripId:string;locale:Locale;dirty?:boolean}){return <TeamBoardView key={tripId} tripId={tripId} locale={locale} dirty={dirty}/>}
export function TeamBoardRoom({roomId,token,locale}:{roomId:string;token:string;locale:Locale}){return <TeamBoardView key={roomId} roomId={roomId} token={token} locale={locale}/>}

function TeamBoardView({tripId,roomId,token='',locale,dirty=false}:{tripId?:string;roomId?:string;token?:string;locale:Locale;dirty?:boolean}){
 const t=(key:string)=>teamText(locale,key),id=useId();
 const [board,setBoard]=useState<TeamBoard|null>(null),[session,setSession]=useState<SessionInfo|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[online,setOnline]=useState(true),[name,setName]=useState(''),[personName,setPersonName]=useState(''),[invite,setInvite]=useState(''),[confirm,setConfirm]=useState<ConfirmState|null>(null),[joinAvailable,setJoinAvailable]=useState(false),[tokenCleared,setTokenCleared]=useState(false),[panel,setPanel]=useState<'people'|'items'|'invite'>('items'),[filter,setFilter]=useState<TeamFilter>('all'),[clock,setClock]=useState(Date.now);
 const activeToken=tokenCleared?'':token;
 const alive=useRef(false),epoch=useRef(0),owner=useRef<string|null>(null),busyRef=useRef(false),returnFocus=useRef<HTMLElement|null>(null),heading=useRef<HTMLHeadingElement>(null),inviteInput=useRef<HTMLInputElement>(null),requestNumber=useRef(0),inviteExpiry=useRef<string|null>(null),listHeading=useRef<HTMLHeadingElement>(null);
 const query=tripId?'?trip='+encodeURIComponent(tripId):'?room='+encodeURIComponent(roomId??'');
 const reset=useCallback(()=>{epoch.current++;owner.current=null;busyRef.current=false;setBusy(false);setLoading(false);setBoard(null);setSession(null);setInvite('');setConfirm(null);setName('');setPersonName('');setJoinAvailable(false);setFilter('all');setPanel('items')},[]);
 const reload=useCallback(async(preserveStatus=false)=>{
  if(busyRef.current)return;setClock(Date.now());const generation=epoch.current,request=++requestNumber.current;
  try{const {data,session:user}=await teamClient.get(query);if(!alive.current||generation!==epoch.current||request!==requestNumber.current)return;
   if(owner.current&&owner.current!==user.userId){reset();setTokenCleared(true);setStatus('account_changed');return}
   owner.current=user.userId;setSession(user);setBoard(data.board??null);if(inviteExpiry.current!==data.board?.inviteExpiresAt||(data.board?.inviteExpiresAt&&Date.parse(data.board.inviteExpiresAt)<=Date.now()))setInvite('');setJoinAvailable(!data.board&&!!roomId&&!!activeToken);if(!preserveStatus)setStatus('');
  }catch(error){if(!alive.current||generation!==epoch.current||request!==requestNumber.current)return;const code=teamError(error);
   if(code==='unauthorized'||code==='account_changed'){reset();if(code==='account_changed')setTokenCleared(true);setStatus(code)}else{if(code==='not_found'||code==='forbidden'){setBoard(null);setInvite('');setJoinAvailable(!!roomId&&!!activeToken)}setStatus(code)}
  }finally{if(alive.current&&generation===epoch.current)setLoading(false)}
 },[query,reset,roomId,activeToken]);
 // Online API hydration, account changes and visibility are external browser state.
 useEffect(()=>{alive.current=true;queueMicrotask(()=>{if(alive.current){setOnline(navigator.onLine);void reload()}});
  const invalidate=()=>{epoch.current++},refresh=()=>{if(document.visibilityState==='visible')setClock(Date.now());if(document.visibilityState==='visible'&&navigator.onLine)void reload(true)},network=()=>{setOnline(navigator.onLine);if(!navigator.onLine){setInvite('');setConfirm(null);setStatus('offline')}else refresh()},account=(event:StorageEvent)=>{if(event.key===null||['daroub-account-generation','daroub-offline-account'].includes(event.key)){reset();setTokenCleared(true);setLoading(true);void reload()}};
  const timer=setInterval(refresh,15000);addEventListener('online',network);addEventListener('offline',network);addEventListener('storage',account);addEventListener('daroub:trip-sync',refresh);document.addEventListener('visibilitychange',refresh);
  return()=>{alive.current=false;invalidate();clearInterval(timer);removeEventListener('online',network);removeEventListener('offline',network);removeEventListener('storage',account);removeEventListener('daroub:trip-sync',refresh);document.removeEventListener('visibilitychange',refresh)};
 },[reload,reset]);
 async function mutate(action:TeamAction){
  if(busyRef.current||!online)return false;const generation=epoch.current,targetOwner=owner.current;
  if(!targetOwner){setStatus('unauthorized');return false}busyRef.current=true;setBusy(true);requestNumber.current++;setStatus('');
  try{const {data}=await teamClient.mutate(action,targetOwner);if(!alive.current||generation!==epoch.current||owner.current!==targetOwner)return false;
   applyResponse(data,action);return true;
  }catch(error){if(!alive.current||generation!==epoch.current)return false;const code=teamError(error);setStatus(code);
   if(code==='account_changed'||code==='unauthorized'){reset();setTokenCleared(true)}
   if(code==='invite_invalid'){setTokenCleared(true);history.replaceState(null,'',location.pathname+location.search)}
   if(code==='conflict'){busyRef.current=false;await reload(true)}return false;
  }finally{if(alive.current&&generation===epoch.current){busyRef.current=false;setBusy(false)}}
 }
 function applyResponse(data:TeamResponse,action:TeamAction){
  if(action.type==='close'||action.type==='leave'){setBoard(null);setInvite('');setJoinAvailable(false);setTokenCleared(true);history.replaceState(null,'',location.pathname+location.search);setStatus(action.type==='close'?'closed':'left');requestAnimationFrame(()=>heading.current?.focus());return}
  if(data.board){setBoard(data.board);setJoinAvailable(false);if(data.inviteToken){setInvite(invitationUrl(location.origin,data.board.id,data.inviteToken));inviteExpiry.current=data.board.inviteExpiresAt;requestAnimationFrame(()=>inviteInput.current?.focus())}if(action.type==='revoke-invite'||action.type==='remove-person')setInvite('')}
  if(action.type==='join'){history.replaceState(null,'',location.pathname+location.search);setTokenCleared(true);setName('')}
  if(action.type==='remove-person')requestAnimationFrame(()=>heading.current?.focus());
  if(action.type==='add-person'){setPersonName('');requestAnimationFrame(()=>document.getElementById(id+'-person')?.focus())}setStatus(action.type==='add-person'?'personAdded':action.type==='rename-person'?'savedName':action.type==='allocate'?'allocationSaved':'saved');
 }
 function ask(value:ConfirmState){returnFocus.current=document.activeElement as HTMLElement;setConfirm(value)}
 async function preview(){
  const source=tripId??board?.tripId;if(!source||dirty||busyRef.current||!online)return;
  if(!board&&(!name.trim()||name.trim().length>80)){setStatus('invalid');document.getElementById(id+'-name')?.focus();return}
  const generation=epoch.current,targetOwner=owner.current;if(!targetOwner)return;busyRef.current=true;setBusy(true);requestNumber.current++;
  try{const {data}=await teamClient.get('?trip='+encodeURIComponent(source)+'&preview=1',targetOwner);if(!alive.current||generation!==epoch.current)return;if(!data.preview)throw Error('Missing preview');
   ask({kind:board?'refresh':'create',preview:data.preview,action:board?{type:'refresh',roomId:board.id,revision:board.revision,expectedSourceRevision:data.preview.sourceRevision}:{type:'create',tripId:source,name:name.trim(),expectedSourceRevision:data.preview.sourceRevision}});
  }catch(error){if(alive.current&&generation===epoch.current){const code=teamError(error);setStatus(code);if(code==='account_changed'||code==='unauthorized')reset()}}finally{if(alive.current&&generation===epoch.current){busyRef.current=false;setBusy(false)}}
 }
 async function join(){if(!/^[a-f0-9]{64}$/.test(activeToken)){setStatus('invite_invalid');setTokenCleared(true);history.replaceState(null,'',location.pathname+location.search);return}if(!roomId||!activeToken||!name.trim()||name.trim().length>80){setStatus('invalid');return}const generation=epoch.current;if(!owner.current){try{const {session:user}=await teamClient.get();if(!alive.current||generation!==epoch.current)return;owner.current=user.userId;setSession(user)}catch(error){if(alive.current&&generation===epoch.current)setStatus(teamError(error));return}}await mutate({type:'join',roomId,token:activeToken,name:name.trim()})}
 const locked=busy||!online||!!session?.readOnly,showSignIn=status==='unauthorized'||status==='account_changed',removed=confirm?.preview&&board?board.items.filter(item=>!confirm.preview!.items.some(next=>next.id===item.id)):[];
 const n=(value:number)=>new Intl.NumberFormat(locale).format(value),stats=board?teamPreparationSummary(board):null,inviteActive=!!board?.inviteExpiresAt&&Date.parse(board.inviteExpiresAt)>clock;
 const focusList=()=>listHeading.current?.focus(),showItems=(next:TeamFilter)=>{setPanel('items');setFilter(next);requestAnimationFrame(focusList)},showInvitation=()=>{setPanel('invite');requestAnimationFrame(()=>document.getElementById(id+'-invitation-heading')?.focus())};
 const sectionButtons=[{key:'people',title:'peopleStep',hint:'peopleStepHint',Icon:Users},{key:'items',title:'assignStep',hint:'assignStepHint',Icon:PackageCheck},...(board?.isOwner?[{key:'invite',title:'inviteStep',hint:'inviteStepHint',Icon:Link2}]:[])] as const;

 return <section className="team-board" dir={locale==='ar'?'rtl':'ltr'} aria-labelledby={id+'-heading'}>
  <div className="team-heading"><div><span className="team-kicker">{t('title')}</span><h2 id={id+'-heading'} ref={heading} tabIndex={-1}><Users size={21} aria-hidden="true"/>{board?.title??t('startTeam')}</h2><p>{board?t(board.isOwner?'organizerHint':'memberHint'):t('intro')}</p></div><button type="button" className="team-button" disabled={busy||!online} onClick={()=>void reload()}><RefreshCw size={16} aria-hidden="true"/>{t('refresh')}</button></div>
  {loading&&<p role="status">{t('loading')}</p>}
  <p className="team-status" role="status" aria-live="polite">{status?t(status):''}</p>
  {!online&&status!=='offline'&&<p className="team-warning">{t('offline')}</p>}
  {session?.readOnly&&<p className="team-warning">{t('read_only')}</p>}
  {showSignIn&&<div className="team-empty"><p>{t('signIn')}</p>{token&&<p>{t('inviteSignIn')}</p>}<a className="team-button team-primary" href={'/login?return_to='+encodeURIComponent(roomId?'/team?room='+encodeURIComponent(roomId):'/trips?trip='+encodeURIComponent(tripId??''))}>{t('signInAction')}</a></div>}
  {!board&&!loading&&!showSignIn&&tripId&&<div className="team-empty"><p>{t('noBoard')}</p><p>{t('privacy')}</p><p className={dirty?'team-warning':''}>{t('savedOnly')}</p><label htmlFor={id+'-name'}>{t('yourName')}<input id={id+'-name'} form={id+'-detached'} autoComplete="nickname" maxLength={80} value={name} onChange={e=>setName(e.target.value)} disabled={locked}/></label><button className="team-button team-primary" type="button" disabled={locked||dirty||!session} onClick={()=>void preview()}>{t('preview')}</button></div>}
  {!board&&!loading&&!showSignIn&&activeToken&&(joinAvailable||!!roomId)&&<div className="team-empty"><h3>{t('join')}</h3><p>{t('joinHint')}</p><p>{t('privacy')}</p><label htmlFor={id+'-name'}>{t('yourName')}<input id={id+'-name'} form={id+'-detached'} autoComplete="nickname" maxLength={80} value={name} disabled={locked} onChange={e=>setName(e.target.value)}/></label><button className="team-button team-primary" type="button" disabled={locked} onClick={()=>void join()}>{t('join')}</button></div>}
  {board&&stats&&<>
   <div className="team-context"><span>{t(board.isOwner?'owner':'member')}</span><span>{t('updated')}: <time dateTime={board.updatedAt}>{date(locale,board.updatedAt)}</time></span>{!tripId&&board.isOwner&&board.tripId&&<a href={'/trips?trip='+encodeURIComponent(board.tripId)}>{t('openTrip')}</a>}{tripId&&!dirty&&<a href={'/team?room='+encodeURIComponent(board.id)}>{t('room')}</a>}</div>
   <div className="team-overview">
    <div className="team-progress"><PackageCheck size={25} aria-hidden="true"/><div><strong><bdi>{n(stats.packed)} / {n(stats.total)}</bdi> {t('itemsPacked')}</strong><progress value={stats.packed} max={Math.max(stats.total,1)} aria-label={t('checklistProgress')}/><p>{t('itemCountHint')}</p></div></div>
    <dl className="team-metrics"><div><dt>{t('needsCarrier')}</dt><dd>{n(stats.unassigned)}</dd></div><div><dt>{t('needsPacking')}</dt><dd>{n(stats.remaining)}</dd></div><div><dt>{t('participants')}</dt><dd>{n(board.participants.length)}</dd></div>{stats.overassigned>0&&<div className="team-warning"><dt>{t('reviewExcess')}</dt><dd>{n(stats.overassigned)}</dd></div>}</dl>
   </div>
   <div className="team-sections" role="group" aria-label={t('teamSections')}>{sectionButtons.map((section,index)=><button key={section.key} type="button" className="team-section-card" aria-pressed={panel===section.key} aria-controls={id+'-panel-'+section.key} onClick={()=>setPanel(section.key as 'people'|'items'|'invite')}><section.Icon size={21} aria-hidden="true"/><span><strong>{n(index+1)}. {t(section.title)}</strong><small>{t(section.hint)}</small></span>{section.key==='people'&&<bdi>{n(board.participants.length)}</bdi>}</button>)}</div>
   <div id={id+'-panel-items'} hidden={panel!=='items'}>
   <div className="team-next"><div><span className="team-kicker">{t('nextAction')}</span><p>{t(!stats.total?'emptyNext':stats.overassigned?'excessNext':board.isOwner&&board.participants.length===1&&!inviteActive?'inviteNext':stats.unassigned?'assignNext':stats.myRemaining?'packMineNext':stats.remaining?'packingNext':'completeNext')}</p></div>{!stats.total?<button className="team-button" type="button" onClick={focusList}>{t('viewChecklist')}</button>:stats.overassigned?<button className="team-button team-primary" type="button" onClick={()=>showItems('remaining')}>{t('reviewAssignments')}<ArrowRight size={17} aria-hidden="true"/></button>:board.isOwner&&board.participants.length===1&&!inviteActive?<button className="team-button team-primary" type="button" onClick={showInvitation}>{t('invitation')}<Link2 size={17} aria-hidden="true"/></button>:<button className="team-button team-primary" type="button" onClick={()=>showItems(stats.unassigned?'unassigned':stats.myRemaining?'mine':stats.remaining?'remaining':'all')}>{t(stats.unassigned?'assignRemaining':stats.myRemaining?'packMine':stats.remaining?'viewRemaining':'viewAll')}<ArrowRight size={17} aria-hidden="true"/></button>}</div>
   <div className="team-list-heading"><div><h3 ref={listHeading} tabIndex={-1}>{t('whoBrings')}</h3><p>{t('allocationHint')}</p></div></div>
   {board.items.length>0&&<div className="team-filters" role="group" aria-label={t('filterItems')}>{(['remaining','mine','unassigned','all'] as TeamFilter[]).map(value=><button type="button" className="team-button" key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{t('filter_'+value)} <bdi>{n(board.items.filter(item=>teamItemMatches(board,item,value)).length)}</bdi></button>)}</div>}
   {!board.items.length?<div className="team-empty team-checklist-empty"><p>{t(board.isOwner?'noItems':'noItemsMember')}</p>{board.isOwner&&<button type="button" className="team-button" disabled={locked||dirty||!board.tripId} onClick={()=>void preview()}>{t('replace')}</button>}</div>:<><p className="team-filter-result" role="status">{t('showingItems')}: {n(board.items.filter(item=>teamItemMatches(board,item,filter)).length)}{filter==='mine'&&!stats.mine?' · '+t('noMine'):''}</p>{!board.items.some(item=>teamItemMatches(board,item,filter))&&<div className="team-empty team-filter-empty"><p>{t(filter==='remaining'?'nothingRemaining':filter==='unassigned'?'everyoneAssigned':filter==='mine'?'claimHint':'noItems')}</p><button type="button" className="team-button" onClick={()=>setFilter('all')}>{t('viewAll')}</button></div>}<ul className="team-items">{board.items.map(item=><AllocationItem key={item.id} board={board} item={item} locale={locale} locked={locked} save={mutate} visible={teamItemMatches(board,item,filter)} focusList={focusList}/>)}</ul></>}
   </div>
   <section className="team-participants" id={id+'-panel-people'} hidden={panel!=='people'} aria-label={t('peopleStep')}><h3>{t('peopleStep')}</h3><p className="team-muted">{t('namesSaved')}</p><p>{n(stats.joined)} {t('joinedAccounts')}{stats.named>0&&<> · {n(stats.named)} {t('managedNames')}</>}</p><ul>{board.participants.map(person=>{const allocations=board.allocations.filter(row=>row.participantId===person.id);return <li key={person.id}><div className="team-person"><div className="team-person-heading"><strong>{person.name}</strong>{person.isYou&&<small>{t('you')}</small>}<small>{t(person.linked?'joined':'managedName')}</small>{person.isOwner&&<small>{t('owner')}</small>}</div><TeamPersonEditor board={board} person={person} locale={locale} locked={locked} save={mutate}/>{allocations.length?<ul className="team-person-items">{allocations.map(row=><li key={row.itemId}><span>{board.items.find(item=>item.id===row.itemId)?.label}</span><span><bdi>{n(row.packed)} / {n(row.quantity)}</bdi> {t('packed')}</span></li>)}</ul>:<p className="team-muted">{t('noResponsibilities')}</p>}</div>{board.isOwner&&!person.isOwner&&<button className="team-button" type="button" disabled={locked} onClick={()=>ask({kind:'remove-person',person:person.name,action:{type:'remove-person',roomId:board.id,revision:board.revision,participantId:person.id}})}><UserMinus size={16} aria-hidden="true"/>{t('remove')}<span className="team-sr"> {person.name}</span></button>}</li>})}</ul>{board.isOwner&&<div className="team-add-person"><h4>{t('addPerson')}</h4><p>{t('managedIntro')}</p><label htmlFor={id+'-person'}>{t('personName')}<input id={id+'-person'} form={id+'-detached'} maxLength={80} value={personName} disabled={locked} onChange={e=>setPersonName(e.target.value)}/></label><button className="team-button" type="button" disabled={locked} onClick={()=>{if(!personName.trim()){setStatus('invalid');document.getElementById(id+'-person')?.focus();return}void mutate({type:'add-person',roomId:board.id,revision:board.revision,name:personName.trim()})}}><Plus size={16} aria-hidden="true"/>{t('addPersonSave')}</button><p>{t('inviteInstead')}</p><button type="button" className="team-button" onClick={showInvitation}>{t('inviteStep')}<Link2 size={16} aria-hidden="true"/></button></div>}</section>
   {board.isOwner&&<section className="team-invitation" id={id+'-panel-invite'} hidden={panel!=='invite'}><h3 id={id+'-invitation-heading'} tabIndex={-1}><Link2 size={17} aria-hidden="true"/>{t('invitation')}<span className={'team-badge'+(inviteActive?' team-badge-good':'')}>{t(inviteActive?'linkActive':board.inviteExpiresAt?'linkExpired':'noInvite')}</span></h3><h4>{t('inviteHow')}</h4><ol className="team-invite-steps">{['inviteOne','inviteTwo','inviteThree','inviteFour'].map(key=><li key={key}><span>{t(key)}{key==='inviteThree'&&<small>{t('inviteSignIn')}</small>}</span></li>)}</ol><p>{t('inviteHint')}</p><p className="team-muted">{t('invitationTracking')}</p>{board.inviteExpiresAt&&<p>{t('expires')}: <time dateTime={board.inviteExpiresAt}>{date(locale,board.inviteExpiresAt)}</time></p>}{inviteActive&&!invite&&<p>{t('inviteActive')}</p>}<div className="team-actions"><button className={'team-button'+(!invite?' team-primary':'')} type="button" disabled={locked} onClick={()=>{const action:TeamAction={type:'invite',roomId:board.id,revision:board.revision};if(inviteActive)ask({kind:'invite',action});else void mutate(action)}}>{t(board.inviteExpiresAt?'renew':'generate')}</button>{board.inviteExpiresAt&&<button className="team-button" type="button" disabled={locked} onClick={()=>void mutate({type:'revoke-invite',roomId:board.id,revision:board.revision})}>{t('revoke')}</button>}</div>{invite&&<div className="team-link"><h4>{t('inviteReady')}</h4><label htmlFor={id+'-invite'}>{t('copy')}<input id={id+'-invite'} ref={inviteInput} readOnly form={id+'-detached'} dir="ltr" value={invite} onFocus={e=>e.target.select()}/></label><button className="team-button team-primary" type="button" disabled={locked} onClick={()=>{void navigator.clipboard?.writeText(invite).then(()=>setStatus('copied')).catch(()=>{setStatus('copyFailed');inviteInput.current?.focus();inviteInput.current?.select()});if(!navigator.clipboard){setStatus('copyFailed');inviteInput.current?.focus();inviteInput.current?.select()}}}><Copy size={16} aria-hidden="true"/>{t('copy')}</button></div>}<p className="team-muted">{t('inviteSeparate')}</p><button type="button" className="team-button" onClick={()=>setPanel('people')}>{t('peopleStep')}</button></section>}
   <details className="team-settings"><summary>{t(board.isOwner?'manageTeam':'aboutTeam')}</summary><p>{t('snapshot')}</p><p>{t('privacy')}</p><p className="team-muted">{t('polling')} · {t('revision')}: {n(board.sourceRevision)}</p>{board.isOwner&&<><p className={dirty?'team-warning':'team-muted'}>{t('savedOnly')}</p><button type="button" className="team-button" disabled={locked||dirty||!board.tripId} onClick={()=>void preview()}>{t('replace')}</button></>}<div className="team-end"><button type="button" className="team-button team-danger" disabled={locked} onClick={()=>ask({kind:board.isOwner?'close':'leave',action:{type:board.isOwner?'close':'leave',roomId:board.id,revision:board.revision}})}>{t(board.isOwner?'close':'leave')}</button></div></details>
  </>}
  <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null)}}><AlertDialogContent dir={locale==='ar'?'rtl':'ltr'} className="team-confirm" onCloseAutoFocus={event=>{event.preventDefault();requestAnimationFrame(()=>{if(returnFocus.current?.isConnected&&!returnFocus.current.matches(':disabled'))returnFocus.current.focus();else heading.current?.focus()})}}><AlertDialogTitle>{confirm?.preview?t('previewTitle'):t(confirm?.kind==='remove-person'?'remove':confirm?.kind==='invite'?'renewConfirm':confirm?.kind??'confirm')}{confirm?.person&&' · '+confirm.person}</AlertDialogTitle><AlertDialogDescription>{t(confirm?.preview?'privacy':confirm?.kind==='remove-person'?'removeHint':confirm?.kind==='leave'?'leaveHint':confirm?.kind==='invite'?'renewWarning':'closeHint')}</AlertDialogDescription>{confirm?.preview&&<div className="team-preview"><h3>{confirm.preview.title}</h3><p>{t('changedItems')}</p><ul>{confirm.preview.items.map(item=><li key={item.id}><span>{item.label}</span><strong>{t('required')}: {new Intl.NumberFormat(locale).format(item.required)}</strong></li>)}</ul>{!confirm.preview.items.length&&<p>{t('noItems')}</p>}{confirm.kind==='refresh'&&<><p className="team-warning">{t('replaceHint')}</p><h4>{t('removed')}</h4>{removed.length?<ul>{removed.map(item=><li key={item.id}><span>{item.label}</span><strong>{t('assigned')}: {allocationTotals(board!,item.id,item.required).assigned} · {t('packed')}: {allocationTotals(board!,item.id,item.required).packed}</strong></li>)}</ul>:<p>{t('noneRemoved')}</p>}</>}</div>}<AlertDialogFooter><AlertDialogCancel>{t('cancel')}</AlertDialogCancel><AlertDialogAction disabled={locked} onClick={()=>{if(confirm)void mutate(confirm.action)}}>{t(confirm?.kind==='create'?'create':confirm?.kind==='refresh'?'replace':'confirm')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>
}

export function AllocationItem({board,item,locale,locked,save,visible=true,focusList=()=>{}}:{board:TeamBoard;item:TeamItem;locale:Locale;locked:boolean;save:(action:TeamAction)=>Promise<boolean>;visible?:boolean;focusList?:()=>void}){
 const t=(key:string)=>teamText(locale,key),id=useId(),[draft,setDraft]=useState<AllocationDraft|null>(null),[error,setError]=useState(''),editButton=useRef<HTMLButtonElement>(null);
 const totals=allocationTotals(board,item.id,item.required),people=board.participants.filter(person=>board.isOwner||person.isYou),rows=board.allocations.filter(row=>row.itemId===item.id),selected=draft&&people.find(person=>person.id===draft.participantId),stale=!!draft&&draft.revision!==board.revision,n=(value:number)=>new Intl.NumberFormat(locale).format(value);
 function choose(participantId:string){const current=rows.find(row=>row.participantId===participantId);setDraft({participantId,quantity:String(current?.quantity??Math.max(1,Math.min(totals.gap,item.kind==='task'?1:10000))),packed:String(current?.packed??0),revision:board.revision});setError('')}
 function edit(participantId:string){choose(participantId);requestAnimationFrame(()=>document.getElementById(id+'-participant')?.focus())}
 async function submit(){if(!draft||!selected||stale)return;const values=validAllocation(draft.quantity,draft.packed,item.kind==='task'?1:10000);if(!values){setError(item.kind==='task'?'taskQuantity':'invalid');document.getElementById(id+'-quantity')?.focus();return}if(await save({type:'allocate',roomId:board.id,revision:draft.revision,itemId:item.id,participantId:draft.participantId,...values})){setDraft(null);setError('');requestAnimationFrame(()=>{if(editButton.current&&!editButton.current.closest('[hidden]'))editButton.current.focus();else focusList()})}}
 return <li className="team-item" hidden={!visible&&!draft}><div className="team-item-heading"><div><h4 id={id+'-label'}>{item.label}{item.kind==='task'&&<small>{t('task')}</small>}</h4><span className={'team-badge'+(totals.packed>=item.required&&!totals.overbooked?' team-badge-good':'')}>{t(totals.overbooked?'overbooked':totals.gap?'needsCarrier':totals.packed>=item.required?(item.kind==='task'?'completed':'itemComplete'):'inProgress')}</span></div><button type="button" ref={editButton} className="team-button" disabled={locked||!people.length} aria-expanded={!!draft} aria-controls={id+'-editor'} onClick={()=>{if(draft){setDraft(null);setError('');if(!visible)requestAnimationFrame(focusList)}else if(people[0])edit(board.isOwner&&people.length>1?'':people.find(person=>person.isYou)?.id??people[0].id)}}>{t(draft?'cancel':rows.length?(board.isOwner?'addAssignment':'editAllocation'):item.kind==='task'?(board.isOwner?'chooseTaskOwner':'claimTask'):board.isOwner?'chooseCarrier':'claimItem')}<span className="team-sr"> · {item.label}</span></button></div><dl className="team-counts"><div><dt>{t('required')}</dt><dd>{n(item.required)}</dd></div><div><dt>{t('assigned')}</dt><dd>{n(totals.assigned)}</dd></div><div><dt>{t(item.kind==='task'?'completed':'packed')}</dt><dd>{n(totals.packed)}</dd></div>{totals.gap>0&&<div className="team-warning"><dt>{t('gap')}</dt><dd>{n(totals.gap)}</dd></div>}{totals.overbooked>0&&<div className="team-warning"><dt><AlertTriangle size={14} aria-hidden="true"/>{t('overbooked')}</dt><dd>{n(totals.overbooked)}</dd></div>}</dl>
  {rows.length?<ul className="team-allocation-rows" aria-label={t('whoBrings')}>{rows.map(row=>{const person=board.participants.find(person=>person.id===row.participantId);return <li key={row.participantId}><span className="team-assignee"><strong>{person?.name??t('missingParticipant')}</strong>{person?.isYou&&<small>{t('you')}</small>}</span><span className="team-packed-count"><bdi>{n(row.packed)} / {n(row.quantity)}</bdi> {t(item.kind==='task'?'completed':'packed')}</span>{(board.isOwner||person?.isYou)&&<div className="team-row-actions">{row.packed<row.quantity&&<button type="button" className="team-button team-compact team-primary" disabled={locked||!!draft} onClick={async()=>{if(await save({type:'allocate',roomId:board.id,revision:board.revision,itemId:item.id,participantId:row.participantId,quantity:row.quantity,packed:row.quantity}))requestAnimationFrame(()=>{if(editButton.current&&!editButton.current.closest('[hidden]'))editButton.current.focus();else focusList()})}}><Check size={15} aria-hidden="true"/>{t(person?.isYou?'fullyPackedAction':'fullyPackedOther')}<span className="team-sr"> · {person?.name} · {item.label}</span></button>}<button className="team-button team-compact" type="button" disabled={locked||!!draft} onClick={()=>edit(row.participantId)}>{t(item.kind==='task'?'updateTask':'updatePacked')}<span className="team-sr"> · {person?.name} · {item.label}</span></button></div>}</li>})}</ul>:<p className="team-muted">{t(item.kind==='task'?'noTaskOwner':'noAllocation')}</p>}
  {draft&&<div id={id+'-editor'} className="team-allocation-editor" role="group" aria-labelledby={id+'-label'}><p>{t('assignmentSteps')}</p><label htmlFor={id+'-participant'}>{t('assignedTo')}<select id={id+'-participant'} form={id+'-detached'} value={selected?draft.participantId:''} disabled={locked||stale} onChange={e=>choose(e.target.value)}>{!selected&&<option value="" disabled>{t(draft.participantId?'missingParticipant':'choosePerson')}</option>}{people.map(person=><option key={person.id} value={person.id}>{person.name}{person.isYou?' · '+t('you'):''}</option>)}</select></label><label htmlFor={id+'-quantity'}>{t('quantity')}<input id={id+'-quantity'} form={id+'-detached'} type="number" inputMode="numeric" min={0} max={item.kind==='task'?1:10000} step={1} value={draft.quantity} disabled={locked} aria-invalid={!!error} aria-describedby={id+'-hint'+(error?' '+id+'-error':'')} onChange={e=>setDraft({...draft,quantity:e.target.value})}/></label><label htmlFor={id+'-packed'}>{t(item.kind==='task'?'completed':'packedQuantity')}<input id={id+'-packed'} form={id+'-detached'} type="number" inputMode="numeric" min={0} max={validAllocation(draft.quantity,'0',item.kind==='task'?1:10000)?.quantity??(item.kind==='task'?1:10000)} step={1} value={draft.packed} disabled={locked} aria-invalid={!!error} aria-describedby={id+'-hint'+(error?' '+id+'-error':'')} onChange={e=>setDraft({...draft,packed:e.target.value})}/></label><p id={id+'-hint'}>{t(item.kind==='task'?'taskQuantity':'zeroHint')}</p>{error&&<p id={id+'-error'} role="alert" className="team-warning">{t(error)}</p>}{!selected&&draft.participantId&&<p role="alert">{t('missingParticipant')}</p>}{stale&&<div className="team-warning" role="status"><p>{t('draftChanged')}</p><button className="team-button" type="button" disabled={locked||!selected} onClick={()=>setDraft({...draft,revision:board.revision})}>{t('keepDraft')}</button></div>}<button className="team-button team-primary" type="button" disabled={locked||stale||!selected} onClick={()=>void submit()}><Check size={16} aria-hidden="true"/>{t('save')}</button>{selected&&rows.some(row=>row.participantId===selected.id)&&<button type="button" className="team-button team-danger" disabled={locked||stale} onClick={async()=>{if(await save({type:'allocate',roomId:board.id,revision:draft.revision,itemId:item.id,participantId:selected.id,quantity:0,packed:0})){setDraft(null);requestAnimationFrame(focusList)}}}>{t('removeAssignment')}</button>}</div>}
 </li>
}
