'use client';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {Backpack,BookOpenCheck,Check,Package,UsersRound} from 'lucide-react';
import {useSite} from './site-shell';
import {getSession,signOut,syncTrips} from '@/lib/trip-store';
import type {SessionInfo,SyncStatus} from '@/lib/toolkit-types';
import {tripSignInHref} from '@/lib/trip-signin';
import {releaseText} from '@/lib/preparation-release-copy';
import './navigation-cards.css';
const copy={checking:['جارٍ التحقق من المزامنة','Checking synchronization','Vérification de la synchronisation','正在检查同步','सिंक्रनाइज़ेशन जाँचा जा रहा है'],trips:['رحلاتي','My trips','Mes voyages','我的旅行','मेरी यात्राएँ'],offline:['أدلتي المحفوظة','Offline guides','Guides hors ligne','离线指南','ऑफ़लाइन गाइड'],sync:['مزامنة','Sync','Synchroniser','同步','सिंक करें'],synced:['محفوظ ومتزامن','Saved and synced','Enregistré et synchronisé','已保存并同步','सहेजा और सिंक किया'],pending:['تغييرات بانتظار الاتصال','Changes waiting to sync','Modifications en attente','更改等待同步','बदलाव सिंक होने की प्रतीक्षा में'],error:['تعذرت المزامنة؛ التغييرات محفوظة على الجهاز','Sync unavailable; changes saved on this device','Synchronisation indisponible ; changements conservés ici','暂时无法同步；更改已保存在设备上','सिंक उपलब्ध नहीं; बदलाव इस उपकरण पर सुरक्षित हैं'],signin:['سجّل الدخول لحفظ الرحلات','Sign in to save trips','Se connecter pour enregistrer','登录以保存旅行','यात्राएँ सहेजने के लिए साइन इन'],out:['تسجيل الخروج ومسح النسخ الخاصة','Sign out and clear private copies','Déconnexion et suppression des copies privées','退出并清除私人副本','साइन आउट करें और निजी प्रतियाँ हटाएँ'],confirm:['ستُمسح النسخ الخاصة والتغييرات غير المتزامنة من هذا الجهاز. صدّرها أولاً إن احتجتها. متابعة؟','Private copies and unsynced changes will be cleared from this device. Export them first if needed. Continue?','Les copies privées et modifications non synchronisées seront effacées. Exportez-les si nécessaire. Continuer ?','此设备上的私人副本和未同步更改将被清除。请先按需导出。继续？','इस उपकरण की निजी प्रतियाँ और असिंक बदलाव मिटेंगे। ज़रूरत हो तो पहले निर्यात करें। जारी रखें?'],conflict:['حُفظت تعديلات متعارضة كنسخ قابلة للاسترجاع','Conflicting edits preserved as recoverable copies','Modifications en conflit conservées en copies récupérables','冲突更改已保留为可恢复副本','विरोधी बदलाव पुनर्प्राप्त प्रतियों में सुरक्षित हैं']};
export function ToolkitRuntime(){const{tr,locale}=useSite(),pathname=usePathname();const[user,setUser]=useState<SessionInfo|null>(null),[status,setStatus]=useState<SyncStatus|null>(null),[busy,setBusy]=useState(false);
 const [signOutError,setSignOutError]=useState(false);
 const [signInHref,setSignInHref]=useState(tripSignInHref(''));
 const refresh=async()=>{setBusy(true);try{setUser(await getSession());setStatus(await syncTrips())}catch{setStatus({state:'error',pending:0,conflicts:0})}finally{setBusy(false)}};
 // The initial refresh synchronizes authenticated state and IndexedDB after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(location.pathname==='/trips')setSignInHref(tripSignInHref(location.search));void refresh();const update=()=>void refresh();const accountChanged=(event:StorageEvent)=>{if(event.key==='daroub-offline-account'){if(['/login','/register'].includes(location.pathname))void refresh();else location.reload()}};window.addEventListener('storage',accountChanged);window.addEventListener('online',update);window.addEventListener('offline',update);const timer=setInterval(update,60000);if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('storage',accountChanged);window.removeEventListener('online',update);window.removeEventListener('offline',update);clearInterval(timer)}},[]);
 const key=status?.state==='synced'?'synced':status?.state==='error'?'error':status?.state==='sign-in'?'signin':'pending';
 const links=[{href:'/trips',label:tr(copy.trips),Icon:Backpack,tone:'trips'},{href:'/team',label:tr(['رفقاء الرحلة','Trip teams','Équipes de voyage','旅行团队','यात्रा समूह']),Icon:UsersRound,tone:'team'},{href:'/inventory',label:releaseText(locale,'inventory'),Icon:Package,tone:'gear'},{href:'/offline',label:tr(copy.offline),Icon:BookOpenCheck,tone:'guides'}];
 return <div className="toolkit-bar toolkit-navigation"><nav className="toolkit-links" aria-label={tr(['أدوات الرحلة','Trip tools','Outils de voyage','旅行工具','यात्रा के साधन'])}>{links.map(({href,label,Icon,tone})=>{const active=pathname===href||pathname?.startsWith(href+'/');return <a key={href} href={href} className={'toolkit-nav-card toolkit-nav-'+tone} aria-current={active?'page':undefined}><span className="toolkit-nav-icon"><Icon size={20} aria-hidden="true"/></span><span className="toolkit-nav-label">{label}</span>{active&&<Check className="toolkit-nav-current" size={16} aria-hidden="true"/>}</a>})}</nav><div className="toolkit-account">{signOutError&&<span role="alert">{tr(['تعذر تسجيل الخروج. تحقق من الاتصال وحاول مجددًا.','Could not sign out. Check your connection and retry.','Déconnexion impossible. Vérifiez la connexion et réessayez.','无法退出登录。请检查连接后重试。','साइन आउट नहीं हुआ। कनेक्शन जाँचकर फिर कोशिश करें।'])}</span>}{user?<><span className="sync-note" role="status" aria-busy={busy}>{busy||!status?tr(copy.checking):user.readOnly?tr(['تحديثات الخادم متوقفة مؤقتاً؛ يمكنك التصدير وحفظ المسودات محلياً.','Server updates paused; exports and local drafts remain available.','Mises à jour du serveur suspendues ; export et brouillons locaux disponibles.','服务器更新已暂停；仍可导出并保存本地草稿。','सर्वर अपडेट रुके हैं; निर्यात और स्थानीय मसौदे उपलब्ध हैं।']):status.state==='upgrade'?releaseText(locale,'upgrade'):tr(copy[key])}{status?.pending?` (${status.pending})`:''}{status?.conflicts?` · ${tr(copy.conflict)}`:''}</span><button onClick={refresh} disabled={busy}>{tr(copy.sync)}</button><details><summary>{user.displayName}</summary><a href="/login">{tr(['الحساب والدخول','Account and sign-in','Compte et connexion','账户与登录','खाता और साइन इन'])}</a><button onClick={()=>{if(window.confirm(tr(copy.confirm))){setSignOutError(false);void signOut().catch(()=>setSignOutError(true))}}}>{tr(copy.out)}</button></details></>:<a href={signInHref} target="_top">{tr(copy.signin)}</a>}</div></div>
}

