'use client';
import {useRef,useState} from 'react';
import {FlaskConical,UsersRound,ArrowUpLeft,X} from 'lucide-react';
import {translate,type Locale} from '@/lib/terrain';
import type {Trip,GearItem,CatalogSnapshot} from '@/lib/toolkit-types';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {TripSimulator} from './trip-simulator';
import {TeamBoardPanel} from './team-board';
import './trip-simulator.css';
import './team-board.css';
import './trip-tools.css';
export function TripTools({trip,gear,catalog,locale,onChange,dirty}:{trip:Trip;gear:GearItem[];catalog:CatalogSnapshot;locale:Locale;onChange:(trip:Trip)=>void;dirty:boolean}){
 const opener=useRef<HTMLButtonElement|null>(null); const [tool,setTool]=useState<'simulation'|'team'|null>(null),[applied,setApplied]=useState(false),tr=(copy:string[])=>translate(locale,copy);
 const simulation=tr(['ماذا لو تغيّرت الخطة؟','What if your plans change?','Et si le plan changeait ?','如果计划变了呢？','अगर योजना बदल जाए तो?']),team=tr(['من يحضر ماذا؟','Who brings what?','Qui apporte quoi ?','谁来带什么？','कौन क्या लाएगा?']);
 return <div className="trip-tools"><div className="trip-tool-buttons"><button type="button" onClick={event=>{opener.current=event.currentTarget;setTool('simulation')}}><FlaskConical size={22} aria-hidden="true"/><span><strong>{simulation}</strong><small>{tr(['قارن المشاركين والتواريخ والتجهيزات','Compare group, dates and equipment','Comparez groupe, dates et équipement','比较人数、日期和装备','समूह, तिथियों और सामान की तुलना करें'])}</small></span><ArrowUpLeft size={16} aria-hidden="true"/></button><button type="button" onClick={event=>{opener.current=event.currentTarget;setTool('team')}}><UsersRound size={22} aria-hidden="true"/><span><strong>{team}</strong><small>{tr(['وزّع المسؤوليات مع مجموعتك','Share responsibilities with your group','Répartissez les responsabilités','与团队分配准备任务','समूह में ज़िम्मेदारियाँ बाँटें'])}</small></span><ArrowUpLeft size={16} aria-hidden="true"/></button></div>{applied&&dirty&&<p className="trip-tools-notice" role="status">{tr(['طُبقت المقارنة على المسودة. اضغط «حفظ الرحلة» للاحتفاظ بها.','Scenario applied to your draft. Choose “Save trip” to keep it.','Scénario appliqué au brouillon. Enregistrez le voyage pour le conserver.','方案已应用到草稿，请保存行程以保留更改。','परिदृश्य मसौदे पर लागू हुआ। रखने के लिए यात्रा सहेजें।'])}</p>}<Dialog open={tool!==null} onOpenChange={open=>{if(!open)setTool(null)}}><DialogContent showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();opener.current?.focus()}} className="trip-tool-dialog" dir={locale==='ar'?'rtl':'ltr'}><button className="trip-tool-close" type="button" aria-label={tr(['إغلاق','Close','Fermer','关闭','बंद करें'])} onClick={()=>setTool(null)}><X size={20} aria-hidden="true"/></button><DialogTitle>{tool==='simulation'?simulation:team}</DialogTitle><DialogDescription>{tool==='simulation'?tr(['جرّب بحرية؛ لن تتغير رحلتك حتى تعتمد المقارنة.','Explore freely; your trip changes only when you apply the preview.','Explorez librement ; le voyage change seulement après validation.','自由尝试，应用预览后才会更改行程。','बेझिझक आज़माएँ; पूर्वावलोकन लागू करने पर ही यात्रा बदलेगी।']):tr(['لوحة مشتركة للتجهيزات التي تختار مشاركتها.','A shared board for the equipment you choose to share.','Un tableau commun pour le matériel que vous partagez.','仅共享您选择的装备清单。','आपके चुने हुए सामान के लिए साझा बोर्ड।'])}</DialogDescription>{tool==='simulation'?<TripSimulator trip={trip} gear={gear} catalog={catalog} locale={locale} onApply={next=>{onChange(next);setApplied(true);setTool(null)}}/>:tool==='team'?<TeamBoardPanel tripId={trip.id} locale={locale} dirty={dirty}/>:null}</DialogContent></Dialog></div>
}
