'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Backpack,Plus,Save,Download,Copy,Trash2,RefreshCw,Upload,ArrowLeft,ArrowRight,MapPin,CalendarDays,Users,Route,Search,Check,ChevronDown,SlidersHorizontal,Pencil} from 'lucide-react';
import {useSite} from './site-shell';
import {terrains} from '@/lib/terrain';
import {useCatalog} from '@/lib/catalog-client';
import {catalogDestination} from '@/lib/catalog-seed';
import {prepText} from '@/lib/preparation-copy';
import {releaseText,activityIds} from '@/lib/preparation-release-copy';
import {workspaceText} from '@/lib/trip-workspace-copy';
import {invalidTripSection,type TripSection} from '@/lib/trip-workspace';
import {newTrip,copyTrip,validTrip,parsePreparationImport,exportPreparation,downloadText} from '@/lib/trip-preparation';
import {normalizeTrip} from '@/lib/preparation-schema';
import {tripItineraryHtml} from '@/lib/fieldbook';
import {packingCounts} from '@/lib/checklist-view';
const checklistProgress=(rows:Trip['checklist'])=>{const counts=packingCounts(rows);return {done:counts.complete,total:counts.items}};
import {getSession,loadTrips,loadGear,saveTrip,savePreparationBatch,deleteTrip,syncTrips} from '@/lib/trip-store';
import type {Trip,TerrainId,SessionInfo,SyncStatus,GearItem} from '@/lib/toolkit-types';
import {QuantityChecklist} from './quantity-checklist';
import {ItineraryEditor} from './itinerary-editor';
import {PackingPanel} from './packing-panel';
import {PackingWorkspace,type PackingView} from './packing-workspace';
import {TripDetails} from './trip-details';
import {TripTools} from './trip-tools';
import {DestinationBrief} from './destination-brief';
import {tripSignInHref} from '@/lib/trip-signin';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import './preparation.css';
import './preparation-release.css';
import './quantity-checklist.css';
import './itinerary-editor.css';
import './trip-workspace.css';

export function TripsView(){
 const {locale,t,tr}=useSite(),{catalog,loading:catalogLoading}=useCatalog(),p=(k:string)=>prepText(locale,k),r=(k:string)=>releaseText(locale,k),w=(k:string)=>workspaceText(locale,k);
 const [trips,setTrips]=useState<Trip[]>([]),[gear,setGear]=useState<GearItem[]>([]),[draft,setDraft]=useState<Trip|null>(null),[session,setSession]=useState<SessionInfo|null>(null),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[sync,setSync]=useState<SyncStatus|null>(null);
 const [packingView,setPackingView]=useState<PackingView>('list');
 const [section,setSection]=useState<TripSection>('overview'),[editing,setEditing]=useState(false),[query,setQuery]=useState(''),[dialog,setDialog]=useState<'discard'|'delete'|null>(null),[invalid,setInvalid]=useState<TripSection|null>(null);
 const dirtyRef=useRef(false),base=useRef<Trip|undefined>(undefined),owner=useRef<string|null>(null),importInput=useRef<HTMLInputElement>(null),pendingAction=useRef<(()=>void)|null>(null),form=useRef<HTMLFormElement>(null),heading=useRef<HTMLHeadingElement>(null),dialogReturn=useRef<HTMLElement|null>(null),dialogConfirmed=useRef(false);
 function markDirty(value:boolean){dirtyRef.current=value;setDirty(value)}
 function change(value:Trip){setDraft(value);markDirty(true);setStatus('');setInvalid(null)}
 const focusHeading=()=>requestAnimationFrame(()=>heading.current?.focus());
 const refresh=useCallback(async()=>{const user=await getSession();setSession(user);if(owner.current!==(user?.userId??null)){owner.current=user?.userId??null;setDraft(null);base.current=undefined;markDirty(false);pendingAction.current=null;setDialog(null);setInvalid(null)}const [rows,items]=user?await Promise.all([loadTrips(),loadGear()]):[[],[]];rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));setTrips(rows);setGear(items);if(!dirtyRef.current)setDraft(current=>{const next=current?rows.find(row=>row.id===current.id)??current:current;if(next&&rows.some(row=>row.id===next.id))base.current=structuredClone(next);return next});return rows},[]);
 const [signInHref,setSignInHref]=useState(tripSignInHref(''));
 const initialized=useRef(false);
 useEffect(()=>{if(catalogLoading||initialized.current)return;let mounted=true;async function initialize(){try{setSignInHref(tripSignInHref(location.search));const rows=await refresh();if(!mounted)return;initialized.current=true;const q=new URLSearchParams(location.search),destination=catalogDestination(catalog,q.get('destination')),terrainId=q.get('terrainId');let next:Trip|null=null;
  if(destination||terrains.some(region=>region.id===terrainId)){next=newTrip(locale,destination?.id,catalog);if(!destination){next.destinationId=null;next.terrainId=terrainId as TerrainId;const lat=Number(q.get('lat')),lon=Number(q.get('lon'));next.location=q.get('lat')?.trim()&&q.get('lon')?.trim()&&Number.isFinite(lat)&&Math.abs(lat)<=90&&Number.isFinite(lon)&&Math.abs(lon)<=180?{lat,lon}:{lat:NaN,lon:NaN};next.title=prepText(locale,'custom')}const party=Number(q.get('group'));if(Number.isInteger(party)&&party>=1&&party<=1000)next.groupSize=party;const activity=q.get('activity');if(activity&&activityIds.includes(activity))next.activities=[activity];markDirty(true)}
  else if(q.has('destination')||q.has('terrainId'))setStatus('invalid');else if(q.get('trip')){next=rows.find(row=>row.id===q.get('trip'))??null;if(!next)setStatus('tripMissing')}
  setDraft(next);if(next&&rows.some(row=>row.id===next.id))base.current=structuredClone(next);const state=await syncTrips();if(mounted)setSync(state);
 }catch{if(mounted)setStatus('failed')}finally{if(mounted)setLoading(false)}}void initialize();return()=>{mounted=false}},[catalogLoading,catalog,locale,refresh]);
 useEffect(()=>{const changed=()=>void refresh().catch(()=>setStatus('failed')),unload=(event:BeforeUnloadEvent)=>{if(dirtyRef.current){event.preventDefault();event.returnValue=''}};addEventListener('daroub:trip-sync',changed);addEventListener('beforeunload',unload);return()=>{removeEventListener('daroub:trip-sync',changed);removeEventListener('beforeunload',unload)}},[refresh]);
 function guard(action:()=>void){if(busy)return;if(dirtyRef.current){pendingAction.current=action;dialogReturn.current=document.activeElement as HTMLElement;dialogConfirmed.current=false;setDialog('discard')}else action()}
 function select(trip:Trip|null,asNew=false){guard(()=>{setDraft(trip?structuredClone(trip):null);base.current=trip&&!asNew&&trips.some(row=>row.id===trip.id)?structuredClone(trip):undefined;markDirty(asNew);setSection('overview');setPackingView('list');setEditing(false);setInvalid(null);setStatus('');history.replaceState(null,'',trip&&!asNew?`?trip=${encodeURIComponent(trip.id)}`:location.pathname);focusHeading()})}
 function goTo(next:TripSection){setSection(next);requestAnimationFrame(()=>document.getElementById('journey-tab-'+next)?.focus())}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft||busy||!session)return;const invalidSection=invalidTripSection(draft);if(invalidSection){setInvalid(invalidSection);setSection(invalidSection);if(invalidSection==='packing')setPackingView('list');if(invalidSection==='overview')setEditing(true);requestAnimationFrame(()=>{const panel=form.current?.querySelector<HTMLElement>('[data-journey-panel]:not([hidden])')??form.current;const input=panel?.querySelector<HTMLInputElement>('input:invalid,select:invalid,textarea:invalid,[aria-invalid="true"]');if(input){input.focus();input.reportValidity?.()}else document.getElementById('journey-validation')?.focus()});return}const operationOwner=owner.current;setBusy(true);try{const record=await saveTrip(normalizeTrip({...draft,title:draft.title.trim(),updatedAt:new Date().toISOString()}),base.current?{expectedTrip:base.current}:undefined);if(owner.current!==operationOwner)return;markDirty(false);base.current=structuredClone(record);setDraft(record);setEditing(false);setInvalid(null);await refresh();if(owner.current!==operationOwner)return;history.replaceState(null,'',`?trip=${encodeURIComponent(record.id)}`);setStatus('saved');setSync(await syncTrips());await refresh()}catch(error){setStatus(error instanceof Error&&/reload before|trip changed|record changed|gear changed/i.test(error.message)?'changedRecord':session?'failed':'signIn')}finally{setBusy(false)}}
 function requestDelete(){if(!draft||busy)return;const target=structuredClone(base.current??draft),targetOwner=owner.current;pendingAction.current=()=>{if(owner.current===targetOwner)void remove(target)};dialogReturn.current=document.activeElement as HTMLElement;dialogConfirmed.current=false;setDialog('delete')}
 async function remove(target:Trip){const operationOwner=owner.current;setBusy(true);try{await deleteTrip(target.id,{expectedTrip:target});if(owner.current!==operationOwner)return;markDirty(false);setDraft(null);base.current=undefined;await refresh();history.replaceState(null,'',location.pathname);setSync(await syncTrips());focusHeading()}catch{setStatus('failed')}finally{setBusy(false)}}
 async function importFile(file:File){const operationOwner=owner.current;setBusy(true);let parsed=false;try{if(file.size>4*1024*1024)throw Error('size');const imported=parsePreparationImport(await file.text());parsed=true;await savePreparationBatch(imported.trips,imported.gear);if(owner.current!==operationOwner)return;markDirty(false);const rows=await refresh(),next=rows.find(row=>row.id===imported.trips[0]?.id)??null;if(owner.current!==operationOwner)return;setDraft(next);base.current=next?structuredClone(next):undefined;setSection('overview');setPackingView('list');setEditing(false);setInvalid(null);history.replaceState(null,'',next?`?trip=${encodeURIComponent(next.id)}`:location.pathname);setStatus('imported');setSync(await syncTrips());await refresh();focusHeading()}catch{setStatus(parsed?'failed':'importError')}finally{setBusy(false)}}
 async function synchronize(){setBusy(true);try{setSync(await syncTrips());await refresh()}catch{setStatus('failed')}finally{setBusy(false)}}
 function exportDraft(withGear:boolean){if(!draft)return;try{const linked=withGear?gear.filter(g=>draft.checklist.some(i=>i.gearId===g.id)):[];downloadText(exportPreparation([draft],linked),'daroub-preparation.json','application/json')}catch{setStatus('bundleLimit')}}
 const existing=!!draft&&trips.some(row=>row.id===draft.id),destination=catalogDestination(catalog,draft?.destinationId),region=terrains.find(t=>t.id===draft?.terrainId),progress=checklistProgress(draft?.checklist??[]),days=draft?.itinerary??[],activities=days.reduce((sum,d)=>sum+d.entries.length,0),Back=locale==='ar'?ArrowRight:ArrowLeft,Forward=locale==='ar'?ArrowLeft:ArrowRight;
 const date=(value:string)=>{try{return new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'))}catch{return value}};
 const dates=(trip:Trip)=>trip.startDate||trip.endDate?[trip.startDate&&date(trip.startDate),trip.endDate&&date(trip.endDate)].filter(Boolean).join(' – '):w('datesLater');
 const filtered=trips.filter(trip=>(trip.title+' '+tr(catalogDestination(catalog,trip.destinationId)?.names??[])).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const syncLabel=sync?(sync.state==='upgrade'?r('upgrade'):p(sync.state==='sign-in'?'signIn':sync.state))+(sync.pending>0?` · ${sync.pending} ${p('pending')}`:'')+(sync.conflicts>0?` · ${p('conflict')}: ${sync.conflicts}`:''):'';
 return <main id="main" className="page inner-page journey-page">
  <div className="journey-heading"><div>{draft?<button className="journey-text-button journey-back" type="button" disabled={busy} onClick={()=>select(null)}><Back size={17} aria-hidden="true"/>{w('all')}</button>:<span className="eyebrow">DAROUB · {p('trips')}</span>}<h1 ref={heading} tabIndex={-1}>{draft?(existing?(draft.title.trim()||p('title')):p('new')):p('trips')}</h1><p>{draft?(!existing?w('createHint'):destination?tr(destination.names):p('custom')):w('intro')}</p></div>{!draft&&<button className="primary-btn" disabled={busy||loading} onClick={()=>select(newTrip(locale,undefined,catalog),true)}><Plus size={18} aria-hidden="true"/>{p('new')}</button>}</div>
  <div className="journey-utility"><span className="journey-sync" role="status">{syncLabel||(!loading&&!session?p('signIn'):'')}</span><details className="journey-menu"><summary><SlidersHorizontal size={16} aria-hidden="true"/>{w('tools')}<ChevronDown size={14} aria-hidden="true"/></summary><div className="journey-menu-items"><a href="/inventory"><Backpack size={17} aria-hidden="true"/>{r('inventory')}</a>{session&&<><button type="button" disabled={busy} onClick={synchronize}><RefreshCw size={17} aria-hidden="true"/>{p('sync')}</button><button type="button" disabled={busy} onClick={()=>importInput.current?.click()}><Upload size={17} aria-hidden="true"/>{p('import')}</button></>}</div></details><input ref={importInput} type="file" accept="application/json,.json" hidden aria-label={p('import')} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)guard(()=>void importFile(file))}}/></div>
  {!session&&!loading&&<div className="journey-signin"><p>{p('localNote')}</p><a className="primary-btn" href={signInHref}>{p('signInAction')}</a></div>}
  {status&&<p className="prep-status" role="status">{status==='tripMissing'?w(status):['importError','bundleLimit','imported','invalidPreparation','changedRecord'].includes(status)?r(status):p(status)}</p>}
  {loading?<p role="status">{t('load')}</p>:draft?<form ref={form} className="journey-form" noValidate onSubmit={save}>
   <fieldset className="journey-lock" disabled={busy}>
   {!existing?<section className="panel journey-create"><TripDetails key={draft.id} trip={draft} onChange={change} catalog={catalog} locale={locale} creating/></section>:<>
    <div className="journey-banner"><img src={region?.image} alt=""/><div className="journey-banner-body"><span className="journey-place"><MapPin size={16} aria-hidden="true"/>{destination?tr(destination.names):p('custom')}</span><div className="journey-facts"><span><CalendarDays size={18} aria-hidden="true"/>{dates(draft)}</span><span><Users size={18} aria-hidden="true"/>{draft.groupSize} {w('participants')}</span></div>{draft.conflictOf&&<span className="prep-tag">{p('conflict')}</span>}</div><details className="journey-menu journey-trip-menu"><summary>{w('more')}<ChevronDown size={15} aria-hidden="true"/></summary><div className="journey-menu-items"><button type="button" disabled={!validTrip(draft)} onClick={()=>select(copyTrip(draft),true)}><Copy size={17} aria-hidden="true"/>{p('duplicate')}</button><button type="button" disabled={!validTrip(draft)} onClick={()=>downloadText(tripItineraryHtml(normalizeTrip(draft),locale,catalog),`daroub-trip-${locale}.html`)}><Download size={17} aria-hidden="true"/>{p('itinerary')}</button><button type="button" disabled={!validTrip(draft)} onClick={()=>exportDraft(false)}>{p('export')}</button><button type="button" disabled={!validTrip(draft)} onClick={()=>exportDraft(true)}>{r('bundle')}</button><button className="journey-delete" type="button" onClick={requestDelete}><Trash2 size={17} aria-hidden="true"/>{p('delete')}</button></div></details></div>
    <Tabs value={section} onValueChange={value=>setSection(value as TripSection)} dir={locale==='ar'?'rtl':'ltr'}>
     <TabsList className="journey-tabs" aria-label={w('details')}><TabsTrigger id="journey-tab-overview" value="overview"><MapPin aria-hidden="true"/>{w('overview')}</TabsTrigger><TabsTrigger id="journey-tab-packing" value="packing"><Backpack aria-hidden="true"/>{w('packing')}</TabsTrigger><TabsTrigger id="journey-tab-itinerary" value="itinerary"><Route aria-hidden="true"/>{w('itinerary')}</TabsTrigger></TabsList>
     <TabsContent aria-labelledby="journey-tab-overview" value="overview" forceMount hidden={section!=='overview'} data-journey-panel className="journey-overview">
      <section className="panel journey-summary"><div className="journey-section-heading"><h2>{w('details')}</h2><button className="journey-text-button" type="button" aria-expanded={editing} onClick={()=>setEditing(!editing)}><Pencil size={16} aria-hidden="true"/>{editing?t('close'):w('editDetails')}</button></div>{editing?<TripDetails key={draft.id} trip={draft} onChange={change} catalog={catalog} locale={locale}/>:<><dl className="journey-detail-list"><div><dt>{p('destination')}</dt><dd>{destination?tr(destination.names):`${p('custom')} (${draft.location.lat}, ${draft.location.lon})`}</dd></div><div><dt>{p('start')} / {p('end')}</dt><dd>{dates(draft)}</dd></div><div><dt>{p('group')}</dt><dd>{draft.groupSize}</dd></div><div><dt>{p('transport')}</dt><dd>{draft.transport||w('notAdded')}</dd></div></dl>{draft.notes&&<div className="journey-notes"><h3>{p('notes')}</h3><p>{draft.notes}</p></div>}</>}</section>
      <section className="journey-next"><h2>{w('next')}</h2><p>{w('nextHint')}</p><button className="journey-step" type="button" onClick={()=>goTo('packing')}><span className="journey-step-icon"><Backpack size={24} aria-hidden="true"/></span><span><strong>{w('packAction')}</strong><small><bdi>{progress.done} / {progress.total}</bdi> {w('completed')}</small><span className="journey-meter"><span style={{width:`${progress.total?progress.done/progress.total*100:0}%`}}/></span></span><Forward size={18} aria-hidden="true"/></button><button className="journey-step" type="button" onClick={()=>goTo('itinerary')}><span className="journey-step-icon"><Route size={24} aria-hidden="true"/></span><span><strong>{w('dayAction')}</strong><small>{days.length} {w('days')} · {activities} {w('activities')}</small></span><Forward size={18} aria-hidden="true"/></button><TripTools key={draft.id} trip={draft} gear={gear} catalog={catalog} locale={locale} onChange={change} dirty={dirty}/><p className="journey-footnote">{w('packNote')}</p></section>
     </TabsContent>
     <TabsContent aria-labelledby="journey-tab-packing" value="packing" forceMount hidden={section!=='packing'} data-journey-panel className="panel journey-panel"><PackingWorkspace key={draft.id} view={packingView} onViewChange={setPackingView} locale={locale} count={draft.checklist.length} checklist={<QuantityChecklist trip={draft} onChange={change} gear={gear} trips={trips} locale={locale} showSave={false}/>} suggestions={<PackingPanel trip={draft} onChange={change} gear={gear} catalog={catalog} locale={locale}/>} guide={draft.destinationId?<DestinationBrief catalog={catalog} destinationId={draft.destinationId} locale={locale} compact/>:undefined}/></TabsContent>
     <TabsContent aria-labelledby="journey-tab-itinerary" value="itinerary" forceMount hidden={section!=='itinerary'} data-journey-panel className="panel journey-panel"><ItineraryEditor key={draft.id} trip={draft} onChange={change} catalog={catalog} locale={locale}/></TabsContent>
    </Tabs>
   </>}
   {invalid&&<p id="journey-validation" className="prep-status" role="alert" tabIndex={-1}>{w(invalid==='overview'?'checkOverview':invalid==='packing'?'checkPacking':'checkItinerary')}</p>}
   <div className="journey-savebar"><span><Check size={17} aria-hidden="true"/>{w(dirty?'saveHint':'savedHint')}</span><button type="submit" className="primary-btn" disabled={busy||!session||!dirty}><Save size={18} aria-hidden="true"/>{busy?w('saving'):existing?p('save'):w('create')}</button></div>
   </fieldset>
  </form>:<section className="journey-collection" aria-label={p('trips')}>
   {trips.length>0?<><div className="journey-collection-heading"><span>{p('trips')} · <bdi>{trips.length}</bdi></span><label className="journey-search"><Search size={18} aria-hidden="true"/><span className="sr-only">{w('search')}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={w('search')}/></label></div><div className="journey-cards">{filtered.map(trip=>{const packed=checklistProgress(trip.checklist),d=catalogDestination(catalog,trip.destinationId),terrain=terrains.find(t=>t.id===trip.terrainId);return <button type="button" disabled={busy} className="journey-card" key={trip.id} onClick={()=>select(trip)}><div className="journey-card-photo"><img src={terrain?.image} alt=""/><span>{d?tr(d.names):p('custom')}</span></div><div className="journey-card-body"><h2>{trip.title}</h2><p><CalendarDays size={16} aria-hidden="true"/>{dates(trip)}</p><p><Users size={16} aria-hidden="true"/>{trip.groupSize} {w('participants')}</p><div className="journey-card-progress"><span><bdi>{packed.done} / {packed.total}</bdi> {w('completed')}</span><Backpack size={16} aria-hidden="true"/></div><span className="journey-meter"><span style={{width:`${packed.total?packed.done/packed.total*100:0}%`}}/></span>{trip.conflictOf&&<small className="prep-tag">{p('conflict')}</small>}<span className="journey-card-open">{w('open')}<Forward size={17} aria-hidden="true"/></span></div></button>})}</div>{!filtered.length&&<div className="prep-empty"><p>{w('noResults')}</p><button className="outline-btn" onClick={()=>setQuery('')}>{w('clear')}</button></div>}</>:<div className="journey-empty"><img src="/images/mountain.jpg" alt=""/><div><span className="eyebrow">DAROUB</span><h2>{w('emptyTitle')}</h2><p>{w('emptyHint')}</p><button className="primary-btn" disabled={busy} onClick={()=>select(newTrip(locale,undefined,catalog),true)}><Plus size={18} aria-hidden="true"/>{w('start')}</button></div></div>}
  </section>}
  <AlertDialog open={dialog!==null} onOpenChange={open=>{if(!open){setDialog(null);pendingAction.current=null}}}><AlertDialogContent dir={locale==='ar'?'rtl':'ltr'} className="journey-confirm" onCloseAutoFocus={event=>{event.preventDefault();requestAnimationFrame(()=>{if(!dialogConfirmed.current&&dialogReturn.current?.isConnected)dialogReturn.current.focus();else heading.current?.focus()})}}><AlertDialogTitle>{dialog==='delete'?p('confirmDelete'):p('discard')}</AlertDialogTitle><AlertDialogDescription>{w(dialog==='delete'?'deleteHint':'discardHint')}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>{dialog==='delete'?p('cancel'):w('stay')}</AlertDialogCancel><AlertDialogAction onClick={()=>{const action=pendingAction.current;dialogConfirmed.current=true;pendingAction.current=null;action?.()}}>{dialog==='delete'?p('delete'):w('discard')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
