import {translate,type Locale} from './terrain';

// Arabic, English, French, Simplified Chinese, Hindi.
export const authWords:Record<string,string[]>={
 login:['تسجيل الدخول','Sign in','Se connecter','登录','साइन इन करें'],
 register:['إنشاء حساب','Create account','Créer un compte','创建账户','खाता बनाएँ'],
 loginTitle:['أهلاً بعودتك إلى دروب','Welcome back to Daroub','Heureux de vous revoir sur Daroub','欢迎回到 Daroub','दरोब में फिर स्वागत है'],
 registerTitle:['رحلتك القادمة تبدأ هنا','Your next journey starts here','Votre prochain voyage commence ici','下一段旅程从这里开始','आपकी अगली यात्रा यहीं से शुरू होती है'],
 loginIntro:['تابع تجهيز رحلاتك ومعداتك والأماكن المحفوظة.','Continue preparing your trips, gear and saved places.','Retrouvez vos voyages, votre matériel et vos lieux enregistrés.','继续准备行程、装备和已保存地点。','अपनी यात्राओं, सामान और सहेजी गई जगहों की तैयारी जारी रखें।'],
 registerIntro:['أنشئ حساب دروب ببريدك وكلمة مرور لحفظ رحلاتك وتجهيزاتك.','Create a Daroub account with your email and a password to save your trips and gear.','Créez un compte Daroub avec votre adresse e-mail et un mot de passe pour conserver vos voyages et votre matériel.','使用邮箱和密码创建 Daroub 账户，保存行程与装备。','ईमेल और पासवर्ड से दरोब खाता बनाएँ और अपनी यात्राएँ व सामान सहेजें।'],
 provider:['يمكنك أيضاً استخدام حساب ChatGPT.','You can also use a ChatGPT account.','Vous pouvez aussi utiliser un compte ChatGPT.','也可以使用 ChatGPT 账户。','आप ChatGPT खाते का भी उपयोग कर सकते हैं।'],
 continueProvider:['المتابعة مع ChatGPT','Continue with ChatGPT','Continuer avec ChatGPT','使用 ChatGPT 继续','ChatGPT के साथ जारी रखें'],
 methods:['خيارات إضافية عبر ChatGPT','More options through ChatGPT','Autres options via ChatGPT','通过 ChatGPT 使用其他方式','ChatGPT के ज़रिए अन्य विकल्प'],
 google:['استخدام Google','Use Google','Utiliser Google','使用 Google','Google का उपयोग करें'],
 googleHelp:['اختر المتابعة مع Google في صفحة ChatGPT إذا كان هذا الخيار متاحاً لحسابك.','Choose Continue with Google on the ChatGPT page if available for your account.','Choisissez Continuer avec Google sur la page ChatGPT si cette option est disponible pour votre compte.','如果您的账户支持，请在 ChatGPT 页面选择使用 Google 继续。','यदि आपके खाते में उपलब्ध हो, तो ChatGPT पेज पर Google से जारी रखने का विकल्प चुनें।'],
 phone:['الدخول بمفتاح مرور على الهاتف','Sign in with a phone passkey','Se connecter avec une clé d’accès sur téléphone','使用手机通行密钥登录','फ़ोन की पासकी से साइन इन करें'],
 phone1:['في ChatGPT: الإعدادات ← الأمان ← مفاتيح المرور ← إضافة مفتاح مرور.','ChatGPT: Settings → Security → Passkeys → Add passkey.','ChatGPT : Paramètres → Sécurité → Clés d’accès → Ajouter une clé.','ChatGPT：设置 → 安全 → 通行密钥 → 添加通行密钥。','ChatGPT: सेटिंग्स → सुरक्षा → पासकी → पासकी जोड़ें।'],
 phone2:['عند تسجيل الدخول، اختر جهازاً آخر إذا ظهر هذا الخيار.','When signing in, choose another device, if offered.','À la connexion, choisissez un autre appareil, si proposé.','登录时，如有此选项，请选择使用其他设备。','साइन इन करते समय, विकल्प मिलने पर दूसरा डिवाइस चुनें।'],
 phone3:['امسح رمز QR الذي يعرضه المتصفح وأكّد على هاتفك.','Scan the browser’s QR code; confirm on your phone.','Scannez le code QR du navigateur et confirmez sur votre téléphone.','扫描浏览器显示的二维码，并在手机上确认。','ब्राउज़र का QR कोड स्कैन करें और फ़ोन पर पुष्टि करें।'],
 phoneNote:['توفر الميزة وطريقة فتح الهاتف يعتمدان على حسابك ومتصفحك وجهازك.','Availability and phone unlock methods depend on your account, browser and device.','La disponibilité et le déverrouillage dépendent du compte, du navigateur et de l’appareil.','功能是否可用及手机解锁方式取决于账户、浏览器和设备。','उपलब्धता और फ़ोन अनलॉक का तरीका आपके खाते, ब्राउज़र और डिवाइस पर निर्भर हैं।'],
 phoneGuide:['دليل مفاتيح المرور من OpenAI','OpenAI passkey guide','Guide OpenAI des clés d’accès','OpenAI 通行密钥指南','OpenAI पासकी गाइड'],
 checking:['جارٍ تجهيز تسجيل الدخول…','Preparing sign-in…','Préparation de la connexion…','正在准备登录…','साइन इन की तैयारी हो रही है…'],
 unavailable:['تسجيل الدخول غير متاح حالياً. أعد المحاولة لاحقاً.','Sign-in is temporarily unavailable. Please try again later.','La connexion est temporairement indisponible. Réessayez plus tard.','登录暂时不可用，请稍后重试。','साइन इन अभी उपलब्ध नहीं है। कृपया बाद में फिर कोशिश करें।'],
 retry:['إعادة المحاولة','Try again','Réessayer','重试','फिर कोशिश करें'],
 existing:['أنت مسجل الدخول بالفعل','You’re already signed in','Vous êtes déjà connecté','您已登录','आप पहले से साइन इन हैं'],
 continueJourney:['متابعة رحلتك','Continue your journey','Poursuivre votre voyage','继续您的旅程','अपनी यात्रा जारी रखें'],
 back:['استكشف دروب','Explore Daroub','Explorer Daroub','探索 Daroub','दरोब खोजें'],
 benefitTitle:['اختر المكان. جهّز الرحلة.','Choose a place. Prepare your trip.','Choisissez un lieu. Préparez votre voyage.','选择目的地，准备旅程。','जगह चुनें। यात्रा तैयार करें।'],
 benefitPlaces:['وجهات وأدلة مرتبطة بالمصادر','Destinations and source-linked guides','Destinations et guides sourcés','目的地与附有来源的指南','गंतव्य और स्रोत वाले गाइड'],
 benefitPacking:['قوائم تجهيز يمكنك تعديلها','Packing lists you can adjust','Listes de matériel modifiables','可调整的装备清单','बदलने योग्य सामान की सूचियाँ'],
 benefitTrips:['رحلاتك وأماكنك المحفوظة في حسابك','Your trips and saved places in your account','Vos voyages et lieux enregistrés dans votre compte','账户中的行程和已保存地点','आपके खाते में यात्राएँ और सहेजी गई जगहें'],
 noScript:['يلزم تفعيل JavaScript للتحقق من توفر تسجيل الدخول.','Enable JavaScript to check sign-in availability.','Activez JavaScript pour vérifier la disponibilité de la connexion.','请启用 JavaScript 以检查登录是否可用。','साइन इन की उपलब्धता जाँचने के लिए JavaScript चालू करें।'],
 accountPages:['خيارات الحساب','Account options','Options du compte','账户选项','खाते के विकल्प'],
 name:['الاسم','Name','Nom','姓名','नाम'],
 email:['البريد الإلكتروني','Email','Adresse e-mail','电子邮箱','ईमेल'],
 password:['كلمة المرور','Password','Mot de passe','密码','पासवर्ड'],
 newPassword:['كلمة المرور الجديدة','New password','Nouveau mot de passe','新密码','नया पासवर्ड'],
 confirmPassword:['تأكيد كلمة المرور','Confirm password','Confirmer le mot de passe','确认密码','पासवर्ड की पुष्टि करें'],
 showPasswords:['إظهار','Show','Afficher','显示','दिखाएँ'],
 hidePasswords:['إخفاء','Hide','Masquer','隐藏','छिपाएँ'],
 passwordHelp:['استخدم من 15 إلى 128 حرفاً. يمكنك استخدام المسافات والحروف بأي لغة.','Use 15–128 characters. Spaces and characters from any language are welcome.','Utilisez 15 à 128 caractères. Les espaces et les caractères de toutes les langues sont acceptés.','请使用15至128个字符，可包含空格及各种语言的字符。','15–128 अक्षर रखें। खाली जगह और किसी भी भाषा के अक्षर इस्तेमाल कर सकते हैं।'],
 nameError:['أدخل اسماً من حرف إلى 80 حرفاً.','Enter a name of 1–80 characters.','Saisissez un nom de 1 à 80 caractères.','请输入1至80个字符的姓名。','1–80 अक्षरों का नाम लिखें।'],
 emailError:['أدخل بريداً إلكترونياً صالحاً.','Enter a valid email address.','Saisissez une adresse e-mail valide.','请输入有效的邮箱地址。','सही ईमेल पता लिखें।'],
 confirmError:['كلمتا المرور غير متطابقتين.','The passwords do not match.','Les mots de passe ne correspondent pas.','两次输入的密码不一致。','दोनों पासवर्ड मेल नहीं खाते।'],
 invalidInput:['راجع البيانات المدخلة وأعد المحاولة.','Check your details and try again.','Vérifiez les informations et réessayez.','请检查输入信息并重试。','जानकारी जाँचकर फिर कोशिश करें।'],
 invalidCredentials:['تعذّر تسجيل الدخول بهذه البيانات. تحقق من البريد وكلمة المرور أو رمز الاسترداد.','These details could not be verified. Check your email and password or recovery code.','Ces informations n’ont pas pu être confirmées. Vérifiez l’adresse, le mot de passe ou le code de récupération.','无法验证这些信息。请检查邮箱、密码或恢复码。','इन जानकारियों की पुष्टि नहीं हुई। ईमेल और पासवर्ड या रिकवरी कोड जाँचें।'],
 accountUnavailable:['تعذّر إنشاء الحساب بهذه البيانات. جرّب تسجيل الدخول أو استخدام بريد آخر.','An account could not be created with these details. Try signing in or using another email.','Impossible de créer un compte avec ces informations. Essayez de vous connecter ou utilisez une autre adresse.','无法使用这些信息创建账户。请尝试登录或使用其他邮箱。','इन जानकारियों से खाता नहीं बन सका। साइन इन करें या दूसरा ईमेल आज़माएँ।'],
 rateLimited:['محاولات كثيرة خلال وقت قصير. انتظر قليلاً ثم أعد المحاولة.','Too many attempts. Wait a little before trying again.','Trop de tentatives. Patientez avant de réessayer.','尝试次数过多，请稍后重试。','बहुत ज़्यादा कोशिशें हुईं। थोड़ा रुककर फिर कोशिश करें।'],
 alreadySignedIn:['تغيّرت جلسة الحساب. تحقق من الحساب الحالي قبل المتابعة.','Your account session changed. Check the current account before continuing.','La session a changé. Vérifiez le compte actuel avant de continuer.','账户会话已变更，请先检查当前账户。','खाते का सत्र बदल गया है। आगे बढ़ने से पहले मौजूदा खाता जाँचें।'],
 checkAccount:['التحقق من الحساب','Check account','Vérifier le compte','检查账户','खाता जाँचें'],
 requestFailed:['تعذّر إكمال الطلب. تحقق من اتصالك وأعد المحاولة.','The request could not be completed. Check your connection and try again.','La demande n’a pas abouti. Vérifiez votre connexion et réessayez.','无法完成请求，请检查网络并重试。','अनुरोध पूरा नहीं हुआ। इंटरनेट जाँचकर फिर कोशिश करें।'],
 submitting:['جارٍ المتابعة…','Please wait…','Veuillez patienter…','请稍候…','कृपया प्रतीक्षा करें…'],
 otherMethod:['أو استخدم حساباً آخر','Or use another sign-in method','Ou utilisez une autre méthode','或使用其他登录方式','या दूसरा साइन इन तरीका चुनें'],
 sameMethod:['استخدم طريقة الدخول التي بدأت بها للعثور على رحلاتك السابقة. حساب البريد وحساب ChatGPT منفصلان، حتى عند استخدام البريد نفسه.','Use your original sign-in method to find existing trips. Email and ChatGPT accounts stay separate, even with the same email.','Utilisez votre méthode habituelle pour retrouver vos voyages. Les comptes e-mail et ChatGPT restent séparés, même avec la même adresse.','要查找已有行程，请使用最初的登录方式。邮箱账户和 ChatGPT 账户彼此独立，即使邮箱相同。','पुरानी यात्राएँ पाने के लिए वही तरीका चुनें जिससे पहले साइन इन किया था। एक ही ईमेल होने पर भी ईमेल और ChatGPT खाते अलग रहते हैं।'],
 noEmail:['لا نرسل رسالة تحقق أو استرداد بالبريد. بعد إنشاء الحساب، احفظ رمز الاسترداد الذي سيظهر لك.','We do not send verification or recovery emails. Save the recovery code shown after creating your account.','Aucun e-mail de vérification ou de récupération n’est envoyé. Conservez le code affiché après la création du compte.','我们不会发送验证或恢复邮件。创建账户后，请保存显示的恢复码。','हम सत्यापन या रिकवरी ईमेल नहीं भेजते। खाता बनने के बाद दिखाया गया रिकवरी कोड सहेजें।'],
 recoverLink:['نسيت كلمة المرور؟ استخدم رمز الاسترداد','Forgot your password? Use your recovery code','Mot de passe oublié ? Utilisez votre code','忘记密码？使用恢复码','पासवर्ड भूल गए? रिकवरी कोड इस्तेमाल करें'],
 backToLogin:['العودة إلى تسجيل الدخول','Back to sign in','Retour à la connexion','返回登录','साइन इन पर लौटें'],
 recoverTitle:['استعادة حساب البريد','Recover your email account','Récupérer votre compte e-mail','恢复邮箱账户','ईमेल खाता वापस पाएँ'],
 recoverHelp:['أدخل بريد حساب دروب ورمز الاسترداد الذي حفظته، ثم اختر كلمة مرور جديدة. لا تُرسل رسالة بريد.','Enter your Daroub account email and the recovery code you saved, then choose a new password. No email is sent.','Saisissez l’adresse de votre compte Daroub et le code conservé, puis choisissez un nouveau mot de passe. Aucun e-mail n’est envoyé.','输入 Daroub 账户邮箱及已保存的恢复码，然后设置新密码。不会发送邮件。','दरोब खाते का ईमेल और सहेजा हुआ रिकवरी कोड लिखें, फिर नया पासवर्ड चुनें। कोई ईमेल नहीं भेजा जाएगा।'],
 savedCode:['رمز الاسترداد المحفوظ','Saved recovery code','Code de récupération conservé','已保存的恢复码','सहेजा हुआ रिकवरी कोड'],
 codeHelp:['استخدم الرمز الكامل؛ يمكن إبقاء المسافات والشرطات.','Use the full code; spaces and hyphens are accepted.','Utilisez le code complet ; les espaces et tirets sont acceptés.','请输入完整恢复码，可包含空格和连字符。','पूरा कोड इस्तेमाल करें; खाली जगह और हाइफ़न स्वीकार हैं।'],
 codeError:['أدخل رمز الاسترداد الكامل المكوّن من 64 حرفاً ورقماً، دون احتساب المسافات والشرطات.','Enter the full 64-character recovery code, excluding spaces and hyphens.','Saisissez les 64 caractères du code, sans compter espaces et tirets.','请输入完整的64位恢复码，不计空格和连字符。','पूरा 64-अक्षर वाला रिकवरी कोड लिखें; खाली जगह और हाइफ़न गिनती में नहीं आते।'],
 resetPassword:['تغيير كلمة المرور','Change password','Changer le mot de passe','更改密码','पासवर्ड बदलें'],
 saveCodeTitle:['احفظ رمز استرداد حسابك','Save your account recovery code','Conservez votre code de récupération','保存账户恢复码','अपना रिकवरी कोड सहेजें'],
 saveCodeHelp:['تمت العملية. احفظ هذا الرمز في مكان آمن الآن؛ لن تتمكن من عرضه مجدداً بعد مغادرة الصفحة. إذا نسيت كلمة المرور، ستحتاجه لاستعادة الحساب.','You’re all set. Save this code somewhere safe now; it cannot be shown again after you leave this page. You will need it if you forget your password.','L’opération a réussi. Conservez ce code en lieu sûr ; il ne pourra plus être affiché après avoir quitté cette page. Il vous servira si vous oubliez le mot de passe.','操作成功。请立即妥善保存此码，离开本页后将无法再次显示。忘记密码时需要使用此码。','काम पूरा हुआ। कोड अभी सुरक्षित जगह रखें; यह पेज छोड़ने के बाद दोबारा नहीं दिखाया जा सकेगा। पासवर्ड भूलने पर इसकी ज़रूरत पड़ेगी।'],
 recoveryCode:['رمز الاسترداد الجديد','New recovery code','Nouveau code de récupération','新恢复码','नया रिकवरी कोड'],
 copyCode:['نسخ الرمز','Copy code','Copier le code','复制恢复码','कोड कॉपी करें'],
 downloadCode:['تنزيل الرمز','Download code','Télécharger le code','下载恢复码','कोड डाउनलोड करें'],
 copied:['تم نسخ الرمز. احفظه في مكان آمن قبل المتابعة.','Code copied. Store it safely before continuing.','Code copié. Conservez-le en lieu sûr avant de continuer.','已复制，请在继续前将其妥善保存。','कोड कॉपी हुआ। आगे बढ़ने से पहले सुरक्षित जगह सहेजें।'],
 copyFailed:['تعذّر النسخ التلقائي. حدّد الرمز وانسخه يدوياً أو نزّل الملف.','Copying failed. Select and copy the code manually, or download the file.','La copie a échoué. Sélectionnez et copiez le code, ou téléchargez le fichier.','复制失败。请手动选中并复制恢复码，或下载文件。','कॉपी नहीं हुआ। कोड चुनकर खुद कॉपी करें या फ़ाइल डाउनलोड करें।'],
 codePrivate:['لا تشارك هذا الرمز. أي رمز سابق يصبح غير صالح بعد الاسترداد. احتفظ بالرمز الجديد مع بريد حسابك.','Keep this code private. Recovery replaces any previous code. Keep the new code with your account email.','Gardez ce code secret. Une récupération remplace tout ancien code. Conservez le nouveau avec l’adresse du compte.','请勿分享此码。恢复账户后旧码将失效，请将新码与账户邮箱一同妥善保存。','यह कोड निजी रखें। रिकवरी से पुराना कोड बदल जाता है। नया कोड खाते के ईमेल के साथ रखें।'],
 savedCodeAck:['حفظت الرمز في مكان آمن','I saved the code somewhere safe','J’ai conservé le code en lieu sûr','我已妥善保存恢复码','मैंने कोड सुरक्षित जगह सहेज लिया है'],
 codeFileTitle:['دروب — رمز استرداد الحساب','Daroub — account recovery code','Daroub — code de récupération','Daroub — 账户恢复码','दरोब — खाते का रिकवरी कोड'],
 codeFileNote:['احفظ هذا الملف بشكل خاص مع بريد حسابك. استخدم الرمز في صفحة تسجيل الدخول عند نسيان كلمة المرور. لا تشاركه.','Keep this file private with your account email. Use the code on the sign-in page if you forget your password. Do not share it.','Conservez ce fichier confidentiel avec l’adresse du compte. Utilisez le code sur la page de connexion en cas d’oubli du mot de passe. Ne le partagez pas.','请将本文件与账户邮箱一同保密保存。忘记密码时，在登录页使用此码。请勿分享。','यह फ़ाइल खाते के ईमेल के साथ निजी रखें। पासवर्ड भूलने पर साइन इन पेज पर इस कोड का उपयोग करें। इसे साझा न करें।'],
};
export function authText(locale:Locale,key:string){return translate(locale,authWords[key]??authWords.unavailable)}
