import {translate,type Locale} from './terrain';
export const checklistWords:Record<string,string[]>={
 completeCount:['العناصر المكتملة: {done} من {total}','{done} of {total} items complete','{done} articles terminés sur {total}','已完成 {done} 项，共 {total} 项','{total} में से {done} आइटम पूरे'],
 packedCount:['جُهّز {packed} من {required}','Packed {packed} of {required}','{packed} préparés sur {required}','已打包 {packed} 件，共 {required} 件','{required} में से {packed} पैक'],
 help:['مساعدة القائمة','Checklist help','Aide pour la liste','清单帮助','सूची की मदद'],
 itemType:['نوع العنصر','Item type','Type d’article','项目类型','आइटम का प्रकार'],
 progressHelp:['يحسب شريط التقدم العناصر المكتملة، وليس مجموع كميات الأغراض المختلفة.','Progress counts completed list items, not the combined quantities of different supplies.','La progression compte les articles terminés, pas les quantités cumulées de fournitures différentes.','进度统计已完成的清单项目，不把不同物资的数量相加。','प्रगति पूरे हुए सूची आइटम गिनती है, अलग-अलग सामान की कुल मात्रा नहीं।'],
 subtitle:['حدّد ما تريد أخذه، ثم سجّل ما وضعته فعلياً في حقيبتك.','Set what you plan to bring, then record what is actually in your bag.','Définissez ce que vous emportez, puis indiquez ce qui est réellement dans votre sac.','先确定准备携带的物品，再记录实际装入行囊的数量。','पहले तय करें क्या ले जाना है, फिर दर्ज करें वास्तव में बैग में क्या रखा है।'],
 all:['الكل','All','Tout','全部','सभी'],remaining:['غير مكتمل','Remaining','À préparer','未完成','बाकी'],packed:['مكتمل','Packed / done','Terminé','已完成','पूरा'],
 search:['ابحث في قائمتك','Search your checklist','Rechercher dans la liste','搜索清单','अपनी सूची में खोजें'],
 equipment:['المجهّز من الكمية التي خططت لها','Packed out of your planned quantity','Préparé sur la quantité prévue','已打包／计划数量','तय मात्रा में से पैक किया'],tasks:['مهام منجزة','Tasks done','Tâches terminées','已完成任务','पूरे कार्य'],
 items:['عناصر مكتملة','Items complete','Articles terminés','已完成项目','पूरे आइटम'],
 ready:['القائمة مكتملة','Checklist complete','Liste terminée','清单已完成','सूची पूरी है'],
 empty:['ابدأ بأول قطعة','Add your first item','Ajoutez un premier article','添加第一件装备','पहला सामान जोड़ें'],
 emptyHelp:['اكتب اسم الغرض أو المهمة في خانة الإضافة أعلاه.','Enter an item or task in the quick-add field above.','Saisissez un article ou une tâche dans le champ d’ajout ci-dessus.','在上方快速添加栏输入物品或任务。','ऊपर जोड़ने वाले खाने में सामान या कार्य लिखें।'],
 noMatch:['لا توجد عناصر بهذا الاختيار.','No items match this view.','Aucun article ne correspond.','没有匹配的项目。','इस चयन से कोई आइटम नहीं मिलता।'],
 reset:['عرض القائمة كاملة','Show the full list','Afficher toute la liste','显示全部清单','पूरी सूची दिखाएँ'],
 detail:['التفاصيل والتعديل','Details & edit','Détails et modification','详情与编辑','विवरण और बदलाव'],
 mark:['تحديد كمجهّز','Mark packed','Marquer préparé','标记为已装包','पैक किया चिह्नित करें'],
 unmark:['إلغاء التجهيز','Unpack','Défaire','取消装包','पैक हटाएँ'],
 markTask:['إنجاز المهمة','Complete task','Terminer la tâche','完成任务','कार्य पूरा करें'],
 unmarkTask:['إعادة فتح المهمة','Reopen task','Rouvrir la tâche','重新打开任务','कार्य फिर खोलें'],
 decrease:['تقليل المجهّز','Decrease packed','Réduire la quantité préparée','减少已装包数量','पैक मात्रा घटाएँ'],
 increase:['زيادة المجهّز','Increase packed','Augmenter la quantité préparée','增加已装包数量','पैक मात्रा बढ़ाएँ'],
 count:['المجهّز من المطلوب','Packed of required','Préparé sur nécessaire','已装包／所需','पैक / आवश्यक'],
 planned:['الكمية التي سأخذها','Quantity I plan to bring','Quantité que je prévois d’emporter','计划携带数量','साथ ले जाने की तय मात्रा'],
 plannedHelp:['هذه الكمية تحدد هدف قائمتك. عدّلها حسب نوع الغرض ومدة الرحلة واحتياجات مجموعتك.','This is your checklist target. Adjust it for the item, trip length and your group’s needs.','C’est votre objectif de préparation. Adaptez-le à l’article, à la durée et aux besoins du groupe.','这是你的清单目标，请根据物品、行程时长和团队需要调整。','यह आपकी सूची का लक्ष्य है। सामान, यात्रा की अवधि और समूह की ज़रूरत के अनुसार बदलें।'],
 packedLabel:['الموجود فعلياً في الحقيبة','Actually packed','Réellement dans le sac','实际已装包','वास्तव में पैक किया'],
 packedHelp:['استخدم + و− أو أدخل العدد. علامة الصح تعني أنك جهّزت الكمية كلها.','Use + and − or enter a number. Checking the box marks the full quantity as packed.','Utilisez + et − ou saisissez un nombre. Cocher la case indique que toute la quantité est préparée.','用加减按钮或输入数字。勾选表示已打包全部计划数量。','+ और − दबाएँ या संख्या भरें। टिक करने का अर्थ पूरी तय मात्रा पैक हो गई है।'],
 quantityGuide:['كيف أقرأ الأرقام؟','How do these numbers work?','Comment lire ces nombres ?','这些数字是什么意思？','इन संख्याओं का मतलब क्या है?'],
 countExample:['مثال: المجهّز 2 من 3 يعني أن قطعة واحدة ما زالت تحتاج تجهيزاً.','Example: 2 packed out of 3 means one unit still needs packing.','Exemple : 2 préparés sur 3 signifie qu’il reste une unité à préparer.','例如：计划3件，已打包2件，表示还差1件。','उदाहरण: 3 में से 2 पैक का मतलब एक इकाई अभी पैक करनी है।'],
 plannedCount:['الهدف: {count}','Planned: {count}','Prévu : {count}','计划：{count}','तय: {count}'],
 unitsNote:['الأرقام تعدّ الأغراض التي حددتها؛ ليست لترات ماء أو وجبات أو ضماناً لكفاية المؤن. اكتب الوحدة في اسم الغرض عند الحاجة.','Counts refer to the items you define, not litres of water, meals or proof of enough supplies. Include the unit in the item name when needed.','Les nombres comptent les articles que vous définissez, pas des litres, des repas ou une garantie de réserves suffisantes. Précisez l’unité dans le nom si nécessaire.','数字表示你定义的物品数量，并非水的升数、餐数或补给充足的保证。需要时请在名称中注明单位。','गिनती आपके बताए सामान की है, पानी के लीटर, भोजन की संख्या या पर्याप्त आपूर्ति का प्रमाण नहीं। ज़रूरत हो तो नाम में इकाई लिखें।'],
 inventoryOptional:['الربط بمخزوني — اختياري','Use my inventory — optional','Utiliser mon inventaire — facultatif','使用我的库存（可选）','मेरी सामान-सूची से जोड़ें — वैकल्पिक'],
 inventoryHelp:['المخزون يسجّل ما تملكه. حجز قطعة منه لهذه الرحلة لا يعني أنها في الحقيبة، ويمكنك تجهيز قائمتك دون ربط أي مخزون.','Inventory records what you own. Reserving it for this trip does not mean it is packed. You can use this checklist without linking inventory.','L’inventaire indique ce que vous possédez. Le réserver ne signifie pas l’avoir préparé. Vous pouvez utiliser cette liste sans inventaire lié.','库存记录你拥有的物品。为行程预留不表示已打包，无需关联库存也能使用清单。','सामान-सूची बताती है आपके पास क्या है। यात्रा के लिए आरक्षित करना पैक करना नहीं है। बिना जोड़ें भी सूची इस्तेमाल कर सकते हैं।'],
 reserved:['من مخزوني لهذه الرحلة','From my inventory for this trip','De mon inventaire pour ce voyage','本次行程从库存预留','इस यात्रा के लिए मेरी सामान-सूची से'],
 clearReservation:['إلغاء الحجز من المخزون','Clear inventory reservation','Effacer la réservation de stock','清除库存预留','सामान-सूची का आरक्षण हटाएँ'],
 availableCount:['المسجّل في مخزوني: {count}','Recorded in my inventory: {count}','Dans mon inventaire : {count}','库存记录：{count}','मेरी सामान-सूची में दर्ज: {count}'],
 edit:['تعديل','Edit','Modifier','编辑','बदलें'],
 unavailableEquipment:['المعدة المرتبطة غير متاحة','Linked equipment unavailable','Matériel lié indisponible','关联装备不可用','जुड़ा उपकरण उपलब्ध नहीं'],
 linked:['مرتبط بمخزونك','Linked to your inventory','Lié à votre inventaire','已关联库存','आपकी सामान-सूची से जुड़ा'],
 noLink:['دون ربط بالمخزون','No inventory link','Sans lien à l’inventaire','未关联库存','सामान-सूची से नहीं जुड़ा'],
 keepLink:['الإبقاء على الربط الحالي','Keep current assignment','Conserver l’affectation actuelle','保留当前关联','मौजूदा आवंटन रखें'],
 note:['ضع علامة التجهيز فقط على ما جهّزته فعلياً. الربط بالمخزون لا يجهّز القطعة تلقائياً.','Mark only what you have actually packed. Linking inventory does not pack it.','Cochez uniquement ce que vous avez préparé. Un lien à l’inventaire ne prépare rien.','仅标记实际装包的物品。关联库存不会自动完成装包。','केवल सच में पैक किया सामान चिह्नित करें। सूची से जोड़ने पर सामान पैक नहीं होता।'],
 newItem:['إضافة قطعة أو مهمة','Add an item or task','Ajouter un article ou une tâche','添加物品或任务','सामान या कार्य जोड़ें'],
 example:['مثال: قارورة ماء سعة لتر، مصباح…','e.g. 1-litre water bottle, headlamp…','Ex. : gourde d’un litre, lampe…','例如：1升水瓶、头灯…','जैसे: 1 लीटर की पानी बोतल, टॉर्च…'],
 undo:['تراجع','Undo','Annuler','撤销','वापस लाएँ'],
 restored:['أُعيد العنصر إلى مكانه.','Item restored to its position.','Article remis à sa place.','项目已恢复至原位置。','आइटम अपनी जगह वापस आ गया।'],
 saveHint:['تعديلاتك غير محفوظة بعد.','Your changes are not saved yet.','Vos modifications ne sont pas encore enregistrées.','您的更改尚未保存。','आपके बदलाव अभी सहेजे नहीं गए हैं।'],
 save:['حفظ التجهيزات','Save packing changes','Enregistrer la préparation','保存装备更改','पैकिंग बदलाव सहेजें'],
 saved:['لا توجد تعديلات غير محفوظة','No unsaved changes','Aucune modification non enregistrée','没有未保存的更改','कोई बिना सहेजे बदलाव नहीं'],
 tripDetails:['تفاصيل الرحلة','Trip details','Détails du voyage','行程详情','यात्रा विवरण'],
 suggestions:['اقتراحات لرحلتك','Suggestions for your trip','Suggestions pour votre voyage','行程装备建议','आपकी यात्रा के सुझाव'],
 suggestionsHelp:['اختر ما يناسبك، وعدّل الكميات قبل الإضافة.','Choose what fits your trip; adjust quantities before adding.','Choisissez vos besoins et ajustez les quantités avant d’ajouter.','选择适合行程的物品，添加前可调整数量。','अपनी ज़रूरत चुनें और जोड़ने से पहले मात्रा बदलें।'],
 review:['للمراجعة','To review','À vérifier','待查看','समीक्षा के लिए'],
 suggestionDetails:['الكمية والمصدر','Quantity & source','Quantité et source','数量与来源','मात्रा और स्रोत'],
 addSuggestion:['أضف إلى قائمتي','Add to my list','Ajouter à ma liste','添加到我的清单','मेरी सूची में जोड़ें'],
 updateSuggestion:['تحديث العنصر','Update item','Mettre à jour','更新项目','आइटम बदलें'],
 showHandled:['عرض الاقتراحات السابقة','Show handled suggestions','Afficher les suggestions traitées','显示已处理建议','पहले देखे सुझाव दिखाएँ'],
 reviewed:['راجعت كل الاقتراحات الحالية.','You have reviewed the current suggestions.','Vous avez examiné toutes les suggestions actuelles.','已查看所有当前建议。','आपने सभी मौजूदा सुझाव देख लिए हैं।'],
 task:['مهمة','Task','Tâche','任务','कार्य'],unit:['قطعة','units','unités','件','इकाइयाँ'],
 warning:['يحتاج مراجعة','Needs review','À vérifier','需检查','जाँच आवश्यक'],
 removeHint:['يمكنك التراجع عن آخر حذف قبل مغادرة الرحلة.','You can undo the last removal before leaving this trip.','Vous pouvez annuler la dernière suppression avant de quitter ce voyage.','离开此行程前可撤销最后一次删除。','इस यात्रा से जाने से पहले अंतिम हटाना वापस ले सकते हैं।'],
 limit:['وصلت إلى الحد: 200 عنصر.','Limit reached: 200 items.','Limite atteinte : 200 articles.','已达到200项上限。','200 आइटम की सीमा पूरी हो गई।'],
 invalid:['راجع الكميات في تفاصيل العنصر.','Check quantities in item details.','Vérifiez les quantités dans les détails.','请检查详情中的数量。','आइटम विवरण में मात्राएँ जाँचें।'],
 suggestionsChanged:['أُضيف إلى قائمتك. احفظ التجهيزات للاحتفاظ بالتغيير.','Added to your list. Save packing changes to keep it.','Ajouté à votre liste. Enregistrez la préparation pour le conserver.','已加入清单，请保存装备更改。','सूची में जोड़ा गया। इसे रखने के लिए पैकिंग बदलाव सहेजें।']
};
export const checklistText=(locale:Locale,key:string,values:Record<string,string|number>={})=>translate(locale,checklistWords[key]??checklistWords.invalid).replace(/\{(\w+)\}/g,(match,name)=>values[name]===undefined?match:String(values[name]));
