import type {Destination, GuideSection, Localized, PackingRule, SourceReference, TerrainId} from './toolkit-types';

// Editorial review date, not a promise that closures, bookings or alerts are current.
const reviewedAt = '2026-09-17';
const l = (...values: Localized): Localized => values;
const source = (id: string, title: string, url: string): SourceReference => ({id, title, url, reviewedAt});

export const worldSources: SourceReference[] = [
  source('world-plitvice-place', 'Plitvice Lakes National Park · General information', 'https://np-plitvicka-jezera.hr/en/about-the-park/general-information/'),
  source('world-plitvice-activities', 'Plitvice Lakes National Park · Activities and trail conditions', 'https://np-plitvicka-jezera.hr/en/plan-your-visit/istrazite-jezera/activities/'),
  source('world-plitvice-hiking', 'Plitvice Lakes National Park · Hiking', 'https://np-plitvicka-jezera.hr/en/plan-your-visit/istrazite-jezera/activities/hiking/'),
  source('world-plitvice-faq', 'Plitvice Lakes National Park · FAQ and tickets', 'https://np-plitvicka-jezera.hr/en/faq/'),
  source('world-plitvice-alerts', 'Plitvice Lakes National Park · Current conditions and alerts', 'https://np-plitvicka-jezera.hr/en/plan-your-visit/current-conditions-alerts/'),
  source('world-ever-safety', 'National Park Service · Everglades safety', 'https://www.nps.gov/ever/planyourvisit/safety.htm'),
  source('world-ever-weather', 'National Park Service · Everglades weather and seasons', 'https://www.nps.gov/ever/planyourvisit/weather.htm'),
  source('world-ever-anhinga', 'National Park Service · Anhinga Trail', 'https://www.nps.gov/ever/planyourvisit/anhinga-trail.htm'),
  source('world-ever-directions', 'National Park Service · Everglades entrances and directions', 'https://www.nps.gov/ever/planyourvisit/directions.htm'),
  source('world-ever-paddling', 'National Park Service · Everglades canoe and kayak trails', 'https://www.nps.gov/ever/planyourvisit/canoe-and-kayak-trails.htm'),
  source('world-ever-alligator', 'National Park Service · American alligator species profile', 'https://www.nps.gov/ever/learn/nature/alligator.htm'),
  source('world-yellow-safety', 'National Park Service · Yellowstone safety', 'https://www.nps.gov/yell/planyourvisit/safety.htm'),
  source('world-yellow-weather', 'National Park Service · Yellowstone weather', 'https://www.nps.gov/yell/planyourvisit/weather.htm'),
  source('world-yellow-roads', 'National Park Service · Yellowstone park roads', 'https://www.nps.gov/yell/planyourvisit/parkroads.htm'),
  source('world-yellow-oldfaithful', 'National Park Service · Explore the Old Faithful area', 'https://www.nps.gov/yell/planyourvisit/exploreoldfaithful.htm'),
  source('world-yellow-bison', 'National Park Service · Yellowstone bison ecology', 'https://www.nps.gov/yell/learn/nature/bison.htm'),
  source('world-skaftafell-place', 'Vatnajökull National Park · Skaftafell', 'https://www.vatnajokulsthjodgardur.is/en/areas/skaftafell'),
  source('world-skaftafell-advice', 'Vatnajökull National Park · Travel advice', 'https://www.vatnajokulsthjodgardur.is/en/advice--safety/ferdarad'),
  source('world-skaftafell-seasons', 'Vatnajökull National Park · Seasons', 'https://www.vatnajokulsthjodgardur.is/en/visit/arstidir'),
  source('world-skaftafell-glacier', 'Vatnajökull National Park · Falljökull and guided glacier walks', 'https://www.vatnajokulsthjodgardur.is/en/areas/skaftafell/destination-falljokull'),
  source('world-iceland-clothing', 'ICE-SAR SafeTravel · Appropriate clothing in Iceland', 'https://safetravel.is/outdoors/clothing/'),
  source('world-iceland-glacier', 'ICE-SAR SafeTravel · Glacier safety and crevasse maps', 'https://safetravel.is/outdoors/crevasse-maps/'),
  source('world-bromo-visit', 'Indonesia Ministry of Tourism · Activities and preparation for Bromo Tengger Semeru', 'https://www.indonesia.travel/id/id/travel-ideas/adventure/ide-aktivitas-bromo-tengger-semeru'),
  source('world-bromo-access', 'Indonesia Ministry of Tourism · Mount Bromo: viewpoints, seasons and access', 'https://www.indonesia.travel/uk/en/travel-ideas/adventure/gunung-bromo'),
  source('world-bromo-hazard', 'PVMBG / Geological Agency · Bromo volcanic hazards (23 October 2023; historical notice)', 'https://geologi.esdm.go.id/media-center/press-release-aktivitas-vulkanik-gunung-api-bromo-23-oktober-2023'),
];

const headings = {
  place: l('المكان والتضاريس', 'Place and terrain', 'Lieu et relief', '位置与地形', 'स्थान और भूभाग'),
  equipment: l('تجهيزات الزيارة', 'Visit equipment', 'Équipement de visite', '游览装备', 'यात्रा का सामान'),
  clothing: l('الملابس والأحذية', 'Clothing and footwear', 'Vêtements et chaussures', '衣物与鞋具', 'कपड़े और जूते'),
  transport: l('الوصول والتنقل', 'Access and transport', 'Accès et déplacements', '交通与通行', 'पहुँच और परिवहन'),
  season: l('المواسم والظروف', 'Seasons and conditions', 'Saisons et conditions', '季节与环境', 'ऋतुएँ और परिस्थितियाँ'),
  nature: l('الطبيعة وحدود التعرف', 'Nature and identification limits', 'Nature et limites d’identification', '自然与识别局限', 'प्रकृति और पहचान की सीमाएँ'),
  hazard: l('احتياطات مهمة', 'Important precautions', 'Précautions importantes', '重要注意事项', 'ज़रूरी सावधानियाँ'),
  visit: l('أنشطة وخطة بديلة', 'Activities and an easier option', 'Activités et option plus facile', '活动与较轻松的选择', 'गतिविधियाँ और आसान विकल्प'),
} satisfies Record<string, Localized>;
function section(id: keyof typeof headings, body: Localized, sourceIds: string[]): GuideSection {
  return {id, title: headings[id], body, sourceIds};
}

export const worldDestinations: Destination[] = [
  {
    id: 'plitvice-lakes', terrainId: 'forest', terrainIndex: 2, lat: 44.88, lon: 15.62, timezone: 'Europe/Zagreb',
    image: '/images/forest.jpg', imageIsIllustrative: true,
    names: l('بحيرات بليتفيتسه · كرواتيا', 'Plitvice Lakes · Croatia', 'Lacs de Plitvice · Croatie', '普利特维采湖群 · 克罗地亚', 'प्लिटवित्से झीलें · क्रोएशिया'),
    summary: l('بحيرات كارستية وشلالات وسط الغابات؛ تتطلب الممرات الخشبية والصخرية انتباهاً للبلل والإغلاق الموسمي.', 'Karst lakes and waterfalls within forest; wooden and rocky paths require attention to wet footing and seasonal closures.', 'Lacs karstiques et cascades en forêt ; passerelles et chemins rocheux demandent attention au sol humide et aux fermetures saisonnières.', '森林中的喀斯特湖群与瀑布；木栈道和石径湿滑，部分路线季节性关闭。', 'वनों के बीच कार्स्ट झीलें और झरने; लकड़ी व पत्थर के रास्तों पर गीली सतह और मौसमी बंदी का ध्यान रखें।'),
    sourceIds: ['world-plitvice-place', 'world-plitvice-activities', 'world-plitvice-faq', 'world-plitvice-alerts'],
    sections: [
      section('place', l('تقع البحيرات في كرواتيا ضمن نظام كارستي تحيط به الغابات. النقطة على الخريطة تمثل المنطقة تقريبياً؛ استخدم مدخل التذكرة ومسار المنتزه للوصول.', 'These Croatian lakes lie in a forested karst landscape. The map pin represents the area approximately; navigate using your ticketed entrance and park route.', 'Ces lacs croates occupent un paysage karstique boisé. Le repère situe approximativement la région ; utilisez l’entrée du billet et le parcours du parc.', '这些克罗地亚湖泊位于森林喀斯特地貌中。地图点仅表示大致区域；请按门票入口和公园路线通行。', 'क्रोएशिया की ये झीलें वनाच्छादित कार्स्ट भूभाग में हैं। मानचित्र बिंदु अनुमानित क्षेत्र दिखाता है; टिकट वाले प्रवेश और पार्क मार्ग का उपयोग करें।'), ['world-plitvice-place', 'world-plitvice-faq']),
      section('equipment', l('احتفظ بتذكرة الدخول وخريطة المسار معك، وخذ واقياً من المطر والشمس. للمسارات الغابية اطّلع على طول الطريق وعلاماته قبل الانطلاق.', 'Carry your entry ticket, route map, and rain and sun protection. Before a forest hike, check the route length and trail markings.', 'Gardez billet, carte du parcours et protections contre pluie et soleil. Avant une randonnée forestière, vérifiez longueur et balisage.', '随身带门票、路线图及防雨防晒用品。走森林步道前，确认距离和标记。', 'प्रवेश टिकट, मार्ग नक्शा और बारिश व धूप से बचाव साथ रखें। वन-पथ पर निकलने से पहले दूरी और संकेत जाँचें।'), ['world-plitvice-activities', 'world-plitvice-hiking']),
      section('clothing', l('اختر أحذية مشي ثابتة وملابس تناسب توقعات الطقس. المسارات غير مستوية وقد تكون الصخور زلقة؛ حذاء المدينة الأملس ليس خياراً مناسباً.', 'Choose supportive walking footwear and clothing for the forecast. Paths are uneven and rocks can be slippery; smooth city shoes are a poor choice.', 'Choisissez des chaussures de marche stables et des vêtements adaptés aux prévisions. Sol irrégulier et rochers glissants rendent les semelles lisses peu adaptées.', '穿稳固的步行鞋，并按预报着装。路面不平、岩石可能湿滑，光滑鞋底不适合。', 'मज़बूत पकड़ वाले चलने के जूते और पूर्वानुमान के अनुसार कपड़े चुनें। रास्ते असमतल और चट्टानें फिसलनभरी हो सकती हैं; चिकने तलवे ठीक नहीं।'), ['world-plitvice-activities']),
      section('transport', l('تحقق من تشغيل القوارب الكهربائية والمركبات البانورامية عند اختيار جولتك. لا تفترض أن اختصار العودة متاح؛ قد يوقف الطقس الخدمة أو يغلق جزءاً من المسار.', 'Check electric-boat and panoramic-vehicle services when choosing a circuit. Do not assume a return shortcut is operating; weather can interrupt services or close paths.', 'Vérifiez bateaux électriques et véhicules panoramiques avant de choisir un circuit. Un retour raccourci peut devenir indisponible si météo ou fermetures interrompent le service.', '选环线前核对电船和观光车班次。不要默认返程捷径可用；天气可能中断服务或关闭道路。', 'परिक्रमा चुनते समय विद्युत नाव और दर्शनीय वाहन सेवा जाँचें। वापसी का छोटा रास्ता चालू मानकर न चलें; मौसम से सेवा या पथ बंद हो सकते हैं।'), ['world-plitvice-alerts', 'world-plitvice-activities']),
      section('season', l('تؤثر ظروف الشتاء في فتح البحيرات العليا والمسارات. الصيف قد يشهد ازدحاماً؛ احجز الموعد المناسب وراجع التنبيهات قبل الزيارة في كل موسم.', 'Winter conditions affect Upper Lakes and trail access. Summer can be busy; choose an entry slot and check alerts before visiting in any season.', 'Les conditions hivernales limitent l’accès aux lacs supérieurs et sentiers. L’été peut être fréquenté ; choisissez un créneau et consultez les alertes en toute saison.', '冬季情况影响上湖区和步道开放。夏季可能拥挤；选择入园时段，无论季节都应提前查看公告。', 'सर्दियों की स्थिति ऊपरी झीलों और पथों की पहुँच बदलती है। गर्मियों में भीड़ हो सकती है; प्रवेश समय चुनें और हर ऋतु में सूचना जाँचें।'), ['world-plitvice-faq', 'world-plitvice-alerts']),
      section('nature', l('الغابة والمياه موائل مترابطة؛ احترم الحيوانات واترك النباتات في مكانها. هذا الدليل ليس قائمة أنواع محلية كاملة ولا وسيلة لتحديد نبات صالح للاستخدام.', 'Forest and water form connected habitats; leave animals undisturbed and plants in place. This guide is not a complete local species list or a plant-use identifier.', 'Forêt et eau forment des habitats liés ; ne dérangez pas la faune et laissez les plantes. Ce guide ne constitue ni inventaire complet ni identification pour utilisation.', '森林与水域构成相连的栖息地；不惊扰动物，不采植物。本指南不是完整物种清单，也不能据此判断植物用途。', 'वन और जल जुड़े हुए आवास हैं; जीवों को न छेड़ें, पौधे न तोड़ें। यह पूर्ण स्थानीय प्रजाति सूची या पौधों के उपयोग की पहचान नहीं है।'), ['world-plitvice-place', 'world-plitvice-hiking']),
      section('hazard', l('ابقَ على الممرات المحددة ولا تسبح في البحيرات أو تطعم الحيوانات. اسأل المركز عن ملاءمة المسار للحركة المحدودة؛ الممرات الضيقة والسلالم ليست متاحة للجميع.', 'Stay on marked paths; swimming and wildlife feeding are prohibited. Ask staff about mobility access: narrow paths and steps are not suitable for everyone.', 'Restez sur les chemins balisés ; baignade et nourrissage sont interdits. Demandez conseil pour l’accessibilité : passages étroits et marches ne conviennent pas à tous.', '留在标记路径上；禁止游泳和喂食野生动物。行动不便者请询问工作人员：狭窄步道和台阶并非人人适用。', 'चिह्नित रास्तों पर रहें; तैरना और वन्यजीवों को खिलाना मना है। सीमित गतिशीलता हो तो कर्मचारियों से पूछें; सँकरे रास्ते और सीढ़ियाँ सबके अनुकूल नहीं।'), ['world-plitvice-place', 'world-plitvice-activities']),
      section('visit', l('اختر جولة البحيرات المفتوحة حسب قدرتك. للمبتدئ: اطلب أقصر برنامج مناسب من مركز المعلومات بدلاً من مسار غابي طويل؛ ثبّت المدخل وموعد التذكرة على الموقع الرسمي.', 'Choose an open lake circuit within your ability. Beginners can ask the information centre for a shorter suitable circuit instead of a long forest hike; confirm the official entrance and ticket slot.', 'Choisissez un circuit lacustre ouvert adapté à votre niveau. Débutants : demandez un parcours plus court au centre, plutôt qu’une longue randonnée ; confirmez entrée et créneau officiels.', '按能力选择开放的湖区环线。初学者可向咨询中心询问较短路线，不必选择长途森林徒步；确认官方入口和门票时段。', 'अपनी क्षमता के अनुसार खुला झील-मार्ग चुनें। शुरुआती यात्री लंबी वन-पदयात्रा के बजाय सूचना केंद्र से छोटा उपयुक्त मार्ग पूछें; आधिकारिक प्रवेश और टिकट समय सुनिश्चित करें।'), ['world-plitvice-activities', 'world-plitvice-faq']),
    ],
    species: [],
  },
  {
    id: 'everglades', terrainId: 'coast', terrainIndex: 3, lat: 25.32, lon: -80.93, timezone: 'America/New_York',
    image: '/images/coast.jpg', imageIsIllustrative: true,
    names: l('إيفرغليدز · الولايات المتحدة', 'Everglades · United States', 'Everglades · États-Unis', '大沼泽地 · 美国', 'एवरग्लेड्स · संयुक्त राज्य अमेरिका'),
    summary: l('أراضٍ رطبة شبه استوائية تتصل بالساحل؛ استكشاف الممرات المرفوعة والمجاري المائية يتأثر بالحر والرطوبة والعواصف.', 'Subtropical wetlands meeting the coast; boardwalk and waterway visits depend on heat, humidity and storm conditions.', 'Zones humides subtropicales jusqu’au littoral ; passerelles et voies d’eau demandent de tenir compte de chaleur, humidité et orages.', '与海岸相连的亚热带湿地；栈道与水路游览受高温、湿度和风暴影响。', 'तट से जुड़ी उपोष्णकटिबंधीय आर्द्रभूमि; ऊँचे पथों और जलमार्गों की यात्रा गर्मी, उमस और तूफ़ानों पर निर्भर है।'),
    sourceIds: ['world-ever-safety', 'world-ever-weather', 'world-ever-anhinga', 'world-ever-directions'],
    sections: [
      section('place', l('تقع إيفرغليدز في جنوب فلوريدا، وتجمع مستنقعات وممرات مائية ومناطق ساحلية. النقطة تقريبية للمنطقة وليست نقطة إنزال قارب أو بداية مسار.', 'Everglades lies in southern Florida, combining marshes, waterways and coastal areas. The pin is an approximate area marker, not a launch site or trailhead.', 'Au sud de la Floride, les Everglades associent marais, voies d’eau et littoral. Le repère est approximatif, pas une mise à l’eau ni un départ de sentier.', '大沼泽地位于佛罗里达南部，包括沼泽、水道和海岸区域。地图点只是区域标记，不是下水点或步道起点。', 'दक्षिण फ़्लोरिडा के एवरग्लेड्स में दलदल, जलमार्ग और तटीय क्षेत्र हैं। बिंदु अनुमानित क्षेत्र है, नाव उतारने या पथ शुरू करने की जगह नहीं।'), ['world-ever-directions', 'world-ever-anhinga']),
      section('equipment', l('خذ ماءً للشرب وواقي شمس وطارد حشرات. قبل التجديف اختر مساراً يناسب الخبرة وتحقق من تجهيز القارب والإرشاد المحلي؛ الممر البري خيار مختلف عن رحلة المياه.', 'Carry drinking water, sun protection and insect repellent. For paddling, match the route and boat equipment to your experience with local advice; a land trail is a different outing.', 'Emportez eau potable, protection solaire et répulsif. Pour pagayer, adaptez parcours et équipement à votre expérience avec un conseil local ; un sentier terrestre est une autre sortie.', '携带饮用水、防晒用品和驱虫剂。划船需按经验并听取当地建议选择路线和装备；陆地步道与水上行程不能等同。', 'पीने का पानी, धूप से बचाव और कीटरोधी साथ रखें। पैडलिंग का मार्ग व नाव-सामान अनुभव और स्थानीय सलाह के अनुसार चुनें; भूमि-पथ अलग तरह की यात्रा है।'), ['world-ever-safety', 'world-ever-paddling']),
      section('clothing', l('الأكمام والسراويل الطويلة تساعد على تقليل التعرض للبعوض. اختر ملابس مناسبة للنشاط والحر الرطب، وراجع احتمال الهواء البارد في الموسم الجاف.', 'Long sleeves and trousers help reduce mosquito exposure. Choose clothing for your activity and humid heat, while allowing for cool fronts in the dry season.', 'Manches longues et pantalon réduisent l’exposition aux moustiques. Adaptez la tenue à l’activité et à la chaleur humide, avec une couche pour les fronts frais en saison sèche.', '长袖长裤有助减少蚊虫叮咬。按活动和湿热环境着装，旱季也要考虑冷空气到来。', 'लंबी आस्तीन और पैंट मच्छरों से बचाव में मदद करती हैं। गतिविधि और उमस के अनुसार कपड़े पहनें; शुष्क ऋतु में ठंडी हवा की संभावना भी देखें।'), ['world-ever-safety', 'world-ever-weather']),
      section('transport', l('المداخل الرئيسية غير متصلة داخل المنتزه؛ اختر مدخل يومك مسبقاً ورتب العودة. خدمة ترولي هومستيد موسمية وتتغير مواعيدها؛ لا تعتمد على طلب سيارة عودة فورياً.', 'The main entrances are not connected inside the park; choose your entrance and arrange return transport. Homestead trolley service is seasonal; do not rely on an on-demand return ride.', 'Les entrées principales ne sont pas reliées dans le parc ; choisissez l’accès et organisez le retour. Le trolley de Homestead est saisonnier ; ne comptez pas sur une voiture à la demande.', '主要入口在园内不相通；提前选择入口并安排返程。霍姆斯特德电车服务有季节性，不要依赖临时叫车返回。', 'मुख्य प्रवेश पार्क के भीतर आपस में नहीं जुड़े हैं; प्रवेश और वापसी तय करें। होमस्टेड ट्रॉली मौसमी है; तुरंत वापसी की टैक्सी मिलने पर निर्भर न रहें।'), ['world-ever-directions']),
      section('season', l('الموسم الرطب أكثر حرارة ورطوبة وتكثر فيه العواصف والبعوض. الموسم الجاف ألطف عادة لكنه قد يشهد جبهات باردة؛ راجع التنبيهات والإغلاق بعد الطقس الشديد.', 'The wet season brings humid heat, storms and more mosquitoes. The dry season is usually milder but can have cold fronts; check alerts and post-storm closures.', 'La saison humide apporte chaleur moite, orages et davantage de moustiques. La saison sèche est généralement plus douce, avec parfois des fronts froids ; vérifiez alertes et fermetures.', '雨季湿热、雷暴和蚊虫较多。旱季通常较温和，也可能有冷锋；查看警报及风暴后的关闭信息。', 'वर्षा ऋतु में उमस, गर्मी, तूफ़ान और मच्छर बढ़ते हैं। शुष्क ऋतु अक्सर सुहानी है, पर शीतलहर आ सकती है; तूफ़ान बाद की बंदी जाँचें।'), ['world-ever-weather', 'world-ever-safety']),
      section('nature', l('يمكن مشاهدة الأليغيتور وطيور المياه من مسار أنهينغا؛ الرؤية ليست مضمونة. النباتات قد تسبب تهيجاً باللمس؛ لا تستخدم هذا الملخص للتعرف على نبات أو الاقتراب من حيوان.', 'Anhinga Trail offers possible alligator and waterbird sightings, never guaranteed. Some plants irritate on contact; this summary cannot identify plants or justify approaching wildlife.', 'Le sentier Anhinga permet parfois d’observer alligators et oiseaux d’eau, sans garantie. Certaines plantes sont irritantes ; ce résumé ne permet ni identification ni approche des animaux.', 'Anhinga 步道可能看到短吻鳄与水鸟，但不保证遇见。部分植物接触后会刺激皮肤；不能凭本摘要识别植物或接近动物。', 'अनहिंगा पथ से एलिगेटर और जलपक्षी दिख सकते हैं, गारंटी नहीं। कुछ पौधे छूने से जलन करते हैं; यह सार पौधों की पहचान या जीवों के पास जाने का आधार नहीं।'), ['world-ever-anhinga', 'world-ever-safety']),
      section('hazard', l('لا تطعم الحيوانات أو تلمسها، وأبقِ الأطفال تحت المراقبة وبعيداً عن حافة الماء. ابتعد إذا تغير سلوك الحيوان؛ أخبر شخصاً بمسارك وعدّل النشاط عند الحر الشديد أو تحذير العواصف.', 'Do not feed or touch wildlife; supervise children near water. Give animals more room if their behaviour changes; share your route and change plans for extreme heat or storm warnings.', 'Ne nourrissez ni ne touchez les animaux ; surveillez les enfants près de l’eau. Éloignez-vous si leur comportement change ; communiquez l’itinéraire et adaptez-le aux alertes météo.', '不要喂食或触碰野生动物，水边照看儿童。动物行为改变时应进一步远离；告知他人路线，遇高温或风暴预警时调整计划。', 'जीवों को न खिलाएँ, न छुएँ; पानी के पास बच्चों की निगरानी रखें। व्यवहार बदले तो और दूरी बनाएँ; मार्ग किसी को बताएँ और तेज़ गर्मी या तूफ़ान में योजना बदलें।'), ['world-ever-safety', 'world-ever-weather']),
      section('visit', l('ابدأ بالممشى الذاتي في أنهينغا عند رويال بالم؛ يصفه المنتزه بأنه متاح للكراسي المتحركة، مع ضرورة التحقق من حالته. للتجديف تحقق من المسار ومنسوب الماء وتوافر المرشد وتصريح المبيت إن لزم.', 'Begin with the self-guided Anhinga Trail at Royal Palm; the park lists wheelchair access, subject to current conditions. For paddling, confirm the route, water levels, guide availability and any overnight permit.', 'Commencez par le sentier autonome Anhinga à Royal Palm, annoncé accessible aux fauteuils sous réserve de son état. Pour pagayer, confirmez parcours, niveaux d’eau, disponibilité du guide et permis de nuit éventuel.', '初访可选择皇家棕榈的自助Anhinga 步道，官方列为轮椅可通行，仍需确认现况。划船前确认路线、水位、向导名额及可能需要的过夜许可。', 'शुरुआत रॉयल पाम के स्व-निर्देशित अनहिंगा पथ से करें; पार्क इसे व्हीलचेयर के अनुकूल बताता है, वर्तमान स्थिति जाँचें। पैडलिंग के लिए मार्ग, जलस्तर, गाइड की उपलब्धता और आवश्यक रात्रि-परमिट की पुष्टि करें।'), ['world-ever-anhinga', 'world-ever-paddling']),
    ],
    species: [{
      id: 'everglades-alligator', coverage: 'local', sourceIds: ['world-ever-alligator', 'world-ever-safety'],
      name: l('الأليغيتور الأمريكي', 'American alligator', 'Alligator d’Amérique', '美洲短吻鳄', 'अमेरिकी एलिगेटर'),
      description: l('يحفر هذا الزاحف الأصيل تجاويف تحتفظ بالماء وتؤوي كائنات أخرى في الجفاف. الملخص ليس مفتاح تمييز بين الأليغيتور والتماسيح الأخرى؛ راقبه من الممر.', 'This native reptile excavates water-holding holes that shelter other wildlife during dry periods. This is not an identification key separating alligators from crocodiles; observe from the trail.', 'Ce reptile indigène creuse des trous retenant l’eau et abritant d’autres animaux en période sèche. Ce résumé ne distingue pas formellement alligator et crocodile ; observez depuis le sentier.', '这种本土爬行动物挖出的水坑在干旱时为其他动物提供庇护。本摘要不能用于区分短吻鳄与其他鳄类；请从步道观察。', 'यह स्थानीय सरीसृप पानी वाले गड्ढे खोदता है जो सूखे में दूसरे जीवों को आश्रय देते हैं। यह एलिगेटर और अन्य मगरमच्छों में अंतर करने की कुंजी नहीं; पथ से देखें।'),
      precaution: l('لا تقترب أو تطعم أو تلمس. التزم بتعليمات المسافة المحلية وابتعد أكثر عند الفحيح أو تغير السلوك؛ وجود حاجز أو رقم للمسافة لا يضمن السلامة.', 'Never approach, feed or touch. Follow posted distance guidance and move farther away if it hisses or changes behaviour; a barrier or distance figure does not guarantee safety.', 'Ne l’approchez, nourrissez ni touchez. Respectez les distances affichées et éloignez-vous davantage s’il siffle ou change de comportement ; aucune distance ne garantit la sécurité.', '不要靠近、喂食或触碰。遵守现场距离规定，发出嘶声或行为改变时更远离；护栏或距离数字并非安全保证。', 'पास न जाएँ, न खिलाएँ, न छुएँ। स्थानीय दूरी-निर्देश मानें और फुफकार या बदले व्यवहार पर और दूर जाएँ; कोई दूरी सुरक्षा की गारंटी नहीं।'),
    }],
  },
  {
    id: 'yellowstone', terrainId: 'mountain', terrainIndex: 1, lat: 44.60, lon: -110.50, timezone: 'America/Denver',
    image: '/images/mountain.jpg', imageIsIllustrative: true,
    names: l('يلوستون · الولايات المتحدة', 'Yellowstone · United States', 'Yellowstone · États-Unis', '黄石 · 美国', 'येलोस्टोन · संयुक्त राज्य अमेरिका'),
    summary: l('هضبة مرتفعة تضم أحواضاً حرارية أرضية وغابات وحياة برية؛ المشاهدة من الممرات لا تعني إمكان السير على القشرة المحيطة.', 'A high plateau of hydrothermal basins, forest and wildlife; viewing from boardwalks does not make the surrounding ground walkable.', 'Haut plateau de bassins hydrothermaux, forêts et faune ; les passerelles n’autorisent pas à marcher sur le sol environnant.', '高原上的地热盆地、森林与野生动物；从栈道观赏并不表示周围地表可以行走。', 'ऊँचा पठार, जलतापीय कुंड, वन और वन्यजीव; बोर्डवॉक से दृश्य दिखने का अर्थ आसपास की धरती पर चलना नहीं है।'),
    sourceIds: ['world-yellow-safety', 'world-yellow-weather', 'world-yellow-roads', 'world-yellow-oldfaithful'],
    sections: [
      section('place', l('يلوستون هضبة بركانية مرتفعة في شمال غرب الولايات المتحدة. تختلف الأحواض الحرارية عن مسارات الغابة؛ النقطة تقريبية للمنتزه وليست مدخلاً أو مكاناً آمناً للتوقف.', 'Yellowstone is a high volcanic plateau in the northwestern United States. Hydrothermal basins differ from forest trails; the pin marks the park approximately, not an entrance or stopping place.', 'Yellowstone est un haut plateau volcanique du nord-ouest américain. Bassins hydrothermaux et sentiers forestiers diffèrent ; le repère est approximatif, pas une entrée ni un arrêt.', '黄石是美国西北部的高海拔火山高原。地热盆地不同于森林步道；地图点仅示意公园区域，不是入口或停车点。', 'येलोस्टोन उत्तर-पश्चिम अमेरिका का ऊँचा ज्वालामुखीय पठार है। जलतापीय क्षेत्र वन-पथ से अलग हैं; बिंदु पार्क का अनुमान है, प्रवेश या रुकने की जगह नहीं।'), ['world-yellow-oldfaithful', 'world-yellow-weather']),
      section('equipment', l('خذ طبقات دافئة وواقياً من المطر؛ في زيارات يلوستون راجع إرشادات حمل رذاذ الدببة وتعلم استخدامه، حتى قرب مناطق المشاهدة. خزّن الطعام والمواد ذات الرائحة حسب قواعد الموقع.', 'Bring warm layers and rain protection. For Yellowstone outings, including near viewing areas, consult bear-spray guidance and learn its use; store food and scented items under site-specific rules.', 'Prenez couches chaudes et protection pluie. Pour vos sorties à Yellowstone, y compris près des belvédères, consultez les conseils sur le spray anti-ours et son usage ; rangez aliments et produits odorants selon les règles.', '带保暖层和雨具。在黄石公园活动时，包括观景区附近，请查阅防熊喷雾说明并学习使用；按所在地规定存放食物和有气味物品。', 'गरम परतें और बारिश से बचाव लाएँ। येलोस्टोन की सैर में, दर्शनीय क्षेत्रों के पास भी, बेयर स्प्रे के निर्देश और उपयोग सीखें; भोजन और गंध वाली चीज़ें स्थानीय नियम से रखें।'), ['world-yellow-safety']),
      section('clothing', l('توقع برداً أو ثلجاً حتى في أشهر الصيف. جهز طبقة عازلة وطبقة مقاومة للمطر وقبعة وقفازات؛ عدّل الجولة إذا تعذر البقاء دافئاً وجافاً.', 'Cold or snow can occur even in summer. Pack insulating and rain layers, a hat and gloves; change the outing if you cannot remain warm and dry.', 'Froid et neige sont possibles même en été. Prévoyez isolation, protection pluie, bonnet et gants ; modifiez la sortie si vous ne pouvez rester au chaud et au sec.', '夏季也可能寒冷或降雪。准备保暖层、雨具、帽子和手套；无法保持温暖干燥时应调整行程。', 'गर्मियों में भी ठंड या बर्फ़ संभव है। गरम परत, वर्षारोधी कपड़े, टोपी और दस्ताने रखें; गरम व सूखा रहना कठिन हो तो यात्रा बदलें।'), ['world-yellow-weather', 'world-yellow-safety']),
      section('transport', l('خطط حسب الطرق المفتوحة فعلياً؛ معظم طرق المركبات تغلق موسمياً ولا تصلح خريطة الصيف لخطة الشتاء. استخدم أماكن التوقف المحددة ولا تعطل الطريق لمشاهدة الحيوانات.', 'Plan around roads actually open; most vehicle roads close seasonally, so a summer map is not a winter itinerary. Use designated pullouts without blocking traffic to watch wildlife.', 'Planifiez selon les routes ouvertes ; les fermetures saisonnières rendent un itinéraire estival inadapté à l’hiver. Observez la faune depuis les emplacements prévus, sans bloquer la circulation.', '按实际开放道路规划；多数车道季节性关闭，夏季地图不能直接作为冬季行程。观看动物时使用停车湾，不堵道路。', 'खुली सड़कों के अनुसार योजना बनाएँ; अधिकतर वाहन मार्ग मौसमी रूप से बंद होते हैं, इसलिए गर्मी का मार्ग सर्दियों में न मानें। जीव देखने को निर्धारित जगह रुकें।'), ['world-yellow-roads', 'world-yellow-safety']),
      section('season', l('الصيف له ليالٍ باردة وعواصف بعد الظهر؛ الربيع والخريف قد يشهدان ثلوجاً. الشتاء يحتاج خطة نقل وخدمات مختلفة؛ راجع مواعيد الطرق والخدمات قبل الحجز.', 'Summer has cool nights and afternoon storms; spring and autumn can bring snow. Winter requires different transport and service planning; verify road and facility schedules before booking.', 'Nuits fraîches et orages l’après-midi en été ; neige possible au printemps et en automne. L’hiver impose d’autres transports et services : vérifiez les calendriers avant réservation.', '夏夜凉爽，午后可能有雷暴；春秋可能降雪。冬季交通和服务安排不同，预订前核对道路及设施开放时间。', 'गर्मियों की रातें ठंडी और दोपहर तूफ़ानी हो सकती हैं; वसंत व पतझड़ में बर्फ़ संभव है। सर्दियों में परिवहन व सेवाएँ अलग होती हैं; बुकिंग से पहले जाँचें।'), ['world-yellow-weather', 'world-yellow-roads']),
      section('nature', l('تعيش البيسون وغيرها حول الهضبة، وتوجد كائنات دقيقة محبة للحرارة في الأحواض. راقب دون الاقتراب أو لمس الماء؛ هذه أمثلة وليست قائمة أنواع أو دليلاً لتحديدها.', 'Bison and other wildlife inhabit the plateau; heat-loving microbes live in thermal basins. Observe without approaching animals or touching water; these are examples, not a species-identification guide.', 'Bisons et autres animaux habitent le plateau ; des microbes thermophiles vivent dans les bassins. Observez sans approche ni contact avec l’eau ; ce ne sont que des exemples.', '高原生活着野牛等动物，地热盆地中有嗜热微生物。勿靠近动物或触水；这些只是例子，并非物种识别指南。', 'पठार पर बाइसन व अन्य जीव और गर्म कुंडों में ऊष्माप्रिय सूक्ष्मजीव रहते हैं। जीवों के पास या पानी को छुए बिना देखें; ये उदाहरण हैं, पहचान मार्गदर्शिका नहीं।'), ['world-yellow-oldfaithful', 'world-yellow-bison']),
      section('hazard', l('ابقَ على الممرات والجسور المحددة في الأحواض الحرارية؛ القشرة رقيقة والماء قد يحرق بشدة. لا تسترجع شيئاً سقط خارج الممر؛ أخبر موظف المنتزه واحترم الإغلاق.', 'Remain on designated thermal-area trails and boardwalks; thin crust and scalding water can cause severe injury. Do not retrieve dropped objects off-path; tell park staff and obey closures.', 'Restez sur sentiers et passerelles des zones thermales : croûte mince et eau brûlante sont dangereuses. Ne récupérez pas un objet hors parcours ; prévenez le personnel et respectez les fermetures.', '地热区只走指定步道和栈道；薄地壳与滚烫水会造成重伤。物品掉到道外不要取回，通知工作人员并遵守关闭规定。', 'तापीय क्षेत्रों के निर्धारित पथ और बोर्डवॉक पर रहें; पतली पपड़ी व खौलता पानी गंभीर चोट दे सकते हैं। बाहर गिरी चीज़ न उठाएँ; कर्मचारी को बताएँ और बंदी मानें।'), ['world-yellow-safety']),
      section('visit', l('للبداية اختر منطقة مشاهدة أولد فيثفول ومركز الزوار عندما يكونان مفتوحين، ثم ممرات الحوض المناسبة لقدرتك. لا تحول الزيارة إلى مسار حراري ناءٍ؛ تحقق من الإغلاق وحجز المبيت مسبقاً.', 'Start at the Old Faithful viewing area and visitor centre when open, then choose suitable basin boardwalks. Do not extend casually into remote thermal terrain; check closures and lodging bookings beforehand.', 'Commencez par Old Faithful et son centre d’accueil ouverts, puis des passerelles adaptées. N’improvisez pas une extension vers un bassin isolé ; vérifiez fermetures et hébergement.', '初访可先去开放的老忠实泉观景区和游客中心，再选合适栈道。不要随意延伸至偏远地热区；提前确认关闭信息和住宿。', 'शुरुआत खुले ओल्ड फ़ेथफ़ुल दर्शनीय क्षेत्र और आगंतुक केंद्र से करें, फिर अनुकूल बोर्डवॉक चुनें। दूर के तापीय क्षेत्र तक अचानक न बढ़ें; बंदी व ठहरने की बुकिंग जाँचें।'), ['world-yellow-oldfaithful', 'world-yellow-roads', 'world-yellow-safety']),
    ],
    species: [{
      id: 'yellowstone-bison', coverage: 'local', sourceIds: ['world-yellow-bison', 'world-yellow-safety'],
      name: l('البيسون الأمريكي', 'American bison', 'Bison d’Amérique', '美洲野牛', 'अमेरिकी बाइसन'),
      description: l('قطيع بري يتنقل بين المراعي ومناطق أخرى من المنتزه، وهو جزء مهم من تاريخ الحفظ. المظهر الهادئ لا يدل على الأمان؛ الوصف للتعلم لا للتعرف من قرب.', 'A wild herd ranges across grasslands and other park habitats, with an important conservation history. A calm appearance does not mean safety; learn from a distance.', 'Ce troupeau sauvage parcourt prairies et autres habitats du parc, avec une histoire majeure de conservation. Une apparence calme ne signifie pas absence de danger ; observez de loin.', '野生牛群往来于草地和其他公园栖息地，有重要的保护历史。看似平静并不代表安全；应从远处了解。', 'यह जंगली झुंड घासभूमि व दूसरे आवासों में घूमता है और संरक्षण इतिहास का महत्त्वपूर्ण हिस्सा है। शांत दिखना सुरक्षित होने का संकेत नहीं; दूर से सीखें।'),
      precaution: l('لا تقترب للصورة أو تعترض طريقه. التزم بتعليمات المسافة وانسحب لإفساح الطريق؛ من السيارة انتظر بهدوء ولا تدفع القطيع بالبوق أو القيادة العدوانية.', 'Do not approach for photos or block its route. Follow distance guidance and give way; from a vehicle, wait patiently without honking or driving animals onward.', 'Ne l’approchez pas pour une photo et ne bloquez pas son passage. Respectez les distances et cédez la place ; en voiture, attendez sans klaxonner ni pousser les animaux.', '勿为拍照靠近或挡路。遵守距离规定并让路；在车内耐心等待，不鸣笛或驱赶牛群。', 'फ़ोटो के लिए पास न जाएँ और रास्ता न रोकें। दूरी-निर्देश मानें व रास्ता दें; वाहन में धैर्य से रुकें, हॉर्न या आक्रामक ड्राइविंग से झुंड न हाँकें।'),
    }],
  },
  {
    id: 'skaftafell', terrainId: 'mountain', terrainIndex: 1, lat: 64.03, lon: -16.97, timezone: 'Atlantic/Reykjavik',
    image: '/images/mountain.jpg', imageIsIllustrative: true,
    names: l('سكافتافيل · آيسلندا', 'Skaftafell · Iceland', 'Skaftafell · Islande', '斯卡夫塔山 · 冰岛', 'स्काफ्टाफेल · आइसलैंड'),
    summary: l('منحدرات وممرات عند حواف الأنهار الجليدية في فاتنايوكوتل؛ المشي إلى نقطة مشاهدة يختلف عن دخول الجليد.', 'Slopes and trails beside Vatnajökull outlet glaciers; a walk to a viewpoint is different from travelling on ice.', 'Pentes et sentiers près des langues glaciaires du Vatnajökull ; rejoindre un point de vue diffère d’une marche sur glace.', '瓦特纳冰川出口冰川旁的山坡与步道；走到观景点与进入冰川是两回事。', 'वत्नायोकुत्ल की हिमनदी शाखाओं के पास ढलानें और पथ; दृश्य-बिंदु तक चलना बर्फ़ पर यात्रा से अलग है।'),
    sourceIds: ['world-skaftafell-place', 'world-skaftafell-advice', 'world-skaftafell-glacier', 'world-iceland-glacier'],
    sections: [
      section('place', l('سكافتافيل جنوب شرقي آيسلندا ضمن منتزه فاتنايوكوتل؛ شكّل الجليد والماء منحدراتها وأوديتها. الإحداثيات تقريبية للمنطقة وليست تصريحاً أو مساراً للوصول إلى الجليد.', 'Skaftafell in southeast Iceland belongs to Vatnajökull National Park; ice and water shaped its slopes and valleys. Coordinates indicate the area, not an approved route onto ice.', 'Skaftafell, au sud-est de l’Islande, appartient au parc du Vatnajökull ; glace et eau ont façonné pentes et vallées. Les coordonnées ne définissent aucun accès autorisé au glacier.', '斯卡夫塔山位于冰岛东南部的瓦特纳冰川国家公园，冰与水塑造了山坡和谷地。坐标仅示意区域，并非进入冰川的许可路线。', 'दक्षिण-पूर्व आइसलैंड का स्काफ्टाफेल वत्नायोकुत्ल राष्ट्रीय उद्यान में है; बर्फ़ व जल ने ढलान और घाटियाँ बनाई हैं। निर्देशांक हिमनदी पर स्वीकृत मार्ग नहीं हैं।'), ['world-skaftafell-place']),
      section('equipment', l('للممرات البرية جهّز حقيبة تحمي الملابس الاحتياطية من المطر وخريطة المسار. تجهيزات الجليد يحددها مرشد متخصص؛ حقيبة المشي المعتادة لا تؤهل لعبور نهر جليدي.', 'For land trails, protect spare clothing in a waterproof pack and carry a route map. A specialist guide determines glacier equipment; an ordinary hiking pack does not qualify you for ice travel.', 'Sur les sentiers terrestres, protégez les vêtements de rechange dans un sac étanche et emportez une carte. Le guide spécialisé définit le matériel glaciaire ; un sac de randonnée ne suffit pas.', '陆地徒步要用防水背包保护备用衣物并带路线图。冰川装备由专业向导确定，普通徒步背包不足以支持冰川穿越。', 'भूमि-पथ पर अतिरिक्त कपड़े जलरोधी बैग में रखें और नक्शा लें। हिमनदी उपकरण विशेषज्ञ गाइड तय करे; सामान्य पैदल-यात्रा बैग बर्फ़ पार करने की योग्यता नहीं देता।'), ['world-iceland-clothing', 'world-skaftafell-advice', 'world-skaftafell-glacier']),
      section('clothing', l('إرشاد آيسلندي عام: طبقات صوف أو ألياف صناعية، وغطاء خارجي ضد الرياح والمطر، وقبعة وقفازات وأحذية دافئة مقاومة للماء. البرد ممكن حتى صيفاً.', 'General Iceland guidance: wool or synthetic layers, a wind- and waterproof shell, hat, gloves and warm waterproof footwear. Cold conditions remain possible in summer.', 'Conseil général pour l’Islande : couches en laine ou synthétiques, veste coupe-vent imperméable, bonnet, gants et chaussures chaudes étanches. Le froid reste possible en été.', '冰岛通用户外建议：羊毛或合成纤维分层衣物、防风防水外层、帽子、手套和保暖防水鞋；夏季仍可能寒冷。', 'आइसलैंड की सामान्य सलाह: ऊनी या सिंथेटिक परतें, हवा व पानी रोकने वाला बाहरी कपड़ा, टोपी, दस्ताने और गरम जलरोधी जूते। गर्मियों में भी ठंड संभव है।'), ['world-iceland-clothing']),
      section('transport', l('الوصول من الطريق 1 يتوقف على حالة الطريق والطقس. تحقق من النشرات الرسمية قبل القيادة ومن رسوم المنطقة والخدمات؛ لا تتبع اختصاراً غير معتمد يقترحه جهاز الملاحة.', 'Access from Route 1 depends on road and weather conditions. Check official road updates, area fees and services before driving; do not follow unapproved navigation shortcuts.', 'L’accès par la route 1 dépend de la météo et de la chaussée. Consultez informations routières, frais et services ; évitez les raccourcis non autorisés du GPS.', '从1号公路前往需考虑路况和天气。驾车前查官方路况、区域收费和服务，不走导航推荐的未经许可捷径。', 'रूट 1 से पहुँच सड़क व मौसम पर निर्भर है। वाहन चलाने से पहले आधिकारिक स्थिति, शुल्क और सेवाएँ देखें; नेविगेशन के अस्वीकृत शॉर्टकट न लें।'), ['world-skaftafell-place', 'world-skaftafell-advice']),
      section('season', l('الصيف قصير والطقس سريع التغير؛ خارج الصيف تتغير ظروف الوصول والخدمات أكثر. اسأل المركز عن الجليد والثلج وحالة المسار يوم الزيارة، ولا تعتمد على وصف صيفي قديم.', 'Summer is short and weather changes quickly; access and services vary more outside summer. Ask the visitor centre about ice, snow and that day’s trail conditions, not an old summer description.', 'L’été est court et le temps change vite ; accès et services varient davantage hors été. Demandez au centre l’état du jour, neige et glace, plutôt que suivre un ancien descriptif estival.', '夏季短且天气多变，其他季节的通行和服务变化更大。当天向游客中心询问冰雪及步道情况，不依赖旧的夏季说明。', 'गर्मी छोटी और मौसम तेज़ी से बदलता है; अन्य ऋतुओं में पहुँच व सेवाएँ अधिक बदलती हैं। केंद्र से उस दिन की बर्फ़ और पथ की स्थिति पूछें, पुरानी गर्मी की जानकारी न मानें।'), ['world-skaftafell-seasons', 'world-skaftafell-place']),
      section('nature', l('تضم المنطقة غطاءً نباتياً متنوعاً إلى جوار تضاريس جليدية. لا تترك المسار للاقتراب من نبات أو تبنِ رجوماً حجرية؛ لا يقدم هذا التقرير قائمة أنواع ميدانية كاملة.', 'Vegetation borders a landscape shaped by glaciers. Stay on paths rather than approaching plants, and do not build stone cairns; this report is not a complete field species inventory.', 'La végétation côtoie un paysage glaciaire. Restez sur les sentiers au lieu d’approcher les plantes et ne construisez pas de cairns ; cet inventaire n’est pas exhaustif.', '植被分布在冰川塑造的地形旁。不要离开步道接近植物，不堆石塔；本报告并非完整的实地物种清单。', 'हिमनदियों से बने भूभाग के पास विविध वनस्पति है। पौधों के लिए पथ न छोड़ें और पत्थर न जमाएँ; यह पूरी क्षेत्रीय प्रजाति सूची नहीं है।'), ['world-skaftafell-place', 'world-skaftafell-advice']),
      section('hazard', l('لا تدخل الجليد أو تجاويفه اعتماداً على أثر أقدام؛ الشقوق وحافة الجليد تتغير. اختر مرشداً مؤهلاً وتجهيزاً مناسباً لأي نشاط جليدي، واتبع إغلاق المسارات وتعليمات الحراس.', 'Do not enter ice or its cavities by following footprints; crevasses and glacier edges change. Use a qualified guide and appropriate equipment for glacier activities, and obey trail closures and ranger instructions.', 'Ne suivez pas des traces sur la glace ou dans ses cavités ; crevasses et marges changent. Choisissez guide qualifié et équipement adapté, puis respectez fermetures et consignes des gardes.', '不要循脚印进入冰面或冰洞，裂隙与冰缘不断变化。冰川活动需合格向导和合适装备，并遵守步道关闭与护林员指示。', 'पदचिह्न देखकर बर्फ़ या उसकी गुफाओं में न जाएँ; दरारें और किनारे बदलते हैं। हिमनदी गतिविधि में योग्य गाइड व उचित उपकरण लें और बंदी व रेंजर निर्देश मानें।'), ['world-iceland-glacier', 'world-skaftafell-glacier']),
      section('visit', l('اختر ممشى الزوار السهل الذي يرشحه المركز، مثل غوملوتون إذا كان مفتوحاً. مسارات المرتفعات أطول وأصعب؛ المشي الموجّه على الجليد نشاط مستقل يتطلب تأكيد الحجز والظروف.', 'Ask the centre for an easy visitor trail, such as Gömlutún when open. Higher routes are longer and harder; guided glacier walking is a separate activity requiring confirmed arrangements and conditions.', 'Demandez un sentier facile, comme Gömlutún s’il est ouvert. Les itinéraires élevés sont plus longs et difficiles ; la marche glaciaire guidée nécessite une organisation et des conditions confirmées.', '初访可向中心询问较轻松的游客步道，例如开放时的Gömlutún。高处路线更长更难；向导带领的冰川行走是需另行确认安排和条件的活动。', 'केंद्र से आसान आगंतुक पथ पूछें, जैसे खुला होने पर Gömlutún। ऊँचे मार्ग लंबे व कठिन हैं; निर्देशित हिमनदी पदयात्रा अलग गतिविधि है जिसकी व्यवस्था और स्थिति पुष्टि करनी होगी।'), ['world-skaftafell-place', 'world-skaftafell-glacier']),
    ],
    species: [],
  },
  {
    id: 'bromo', terrainId: 'mountain', terrainIndex: 1, lat: -7.94, lon: 112.95, timezone: 'Asia/Jakarta',
    image: '/images/mountain.jpg', imageIsIllustrative: true,
    names: l('برومو · إندونيسيا', 'Bromo · Indonesia', 'Bromo · Indonésie', '布罗莫 · 印度尼西亚', 'ब्रोमो · इंडोनेशिया'),
    summary: l('بركان نشط وسط كالديرا ورمال بركانية في جاوة الشرقية؛ خطط لنقاط المشاهدة المسموحة واحترم القيود المتغيرة.', 'An active volcano within a caldera and volcanic sand plain in East Java; plan around permitted viewpoints and changing restrictions.', 'Volcan actif dans une caldeira et une plaine de sable volcanique de Java oriental ; privilégiez les belvédères autorisés et les restrictions en vigueur.', '东爪哇火山口盆地与火山沙原中的活火山；按获准观景点和变化中的限制规划。', 'पूर्वी जावा की कैल्डेरा और ज्वालामुखीय रेत के बीच सक्रिय ज्वालामुखी; अनुमत दृश्य-बिंदुओं और बदलते प्रतिबंधों के अनुसार योजना बनाएँ।'),
    sourceIds: ['world-bromo-visit', 'world-bromo-access', 'world-bromo-hazard'],
    sections: [
      section('place', l('يقع برومو في منتزه برومو تنغر سيميرو في جاوة الشرقية، داخل كالديرا ورمال بركانية. النقطة تمثل المنطقة تقريبياً؛ لا تستخدمها للوصول إلى الفوهة أو منطقة محظورة.', 'Bromo lies in East Java’s Bromo Tengger Semeru National Park, within a caldera and volcanic sand plain. The approximate pin is not a route to the crater or restricted ground.', 'Bromo se situe dans le parc Bromo Tengger Semeru, à Java oriental, au sein d’une caldeira sableuse. Le repère approximatif n’indique aucun accès au cratère ou aux zones interdites.', '布罗莫位于东爪哇的布罗莫腾格尔塞梅鲁国家公园，周围是火山口盆地与沙原。大致地图点不是前往火山口或禁区的路线。', 'ब्रोमो पूर्वी जावा के ब्रोमो टेंगर सेमेरू पार्क की कैल्डेरा और रेत में है। अनुमानित बिंदु क्रेटर या प्रतिबंधित क्षेत्र तक मार्ग नहीं है।'), ['world-bromo-visit', 'world-bromo-hazard']),
      section('equipment', l('للرمال المغبرة توصي وزارة السياحة بكمامة ونظارات واقية، مع ملابس دافئة. لا تجعل معدات الغبار سبباً لتجاوز منع الدخول أو الاقتراب من انبعاثات البركان.', 'For dusty sand areas, the tourism ministry recommends a mask and eye protection, alongside warm clothing. Dust equipment is not a reason to cross closures or approach volcanic emissions.', 'Pour les zones sableuses poussiéreuses, le ministère conseille masque, lunettes et vêtements chauds. Ces protections ne justifient ni franchissement d’une fermeture ni approche d’émissions volcaniques.', '旅游部建议在扬尘沙地带口罩、护目镜和保暖衣物。防尘装备不构成越过关闭区域或接近火山排放物的理由。', 'धूलभरी रेत के लिए पर्यटन मंत्रालय मास्क, आँखों की सुरक्षा और गरम कपड़े सुझाता है। धूल का सामान बंद क्षेत्र पार करने या ज्वालामुखी उत्सर्जन के पास जाने का आधार नहीं।'), ['world-bromo-visit', 'world-bromo-hazard']),
      section('clothing', l('قد يكون الانتظار ليلاً أو فجراً بارداً؛ جهّز سترة دافئة وقفازات وغطاء رأس. راجع الطقس الفعلي والملابس المطلوبة مع المشغّل قبل الانطلاق.', 'Night and dawn waits can be cold; bring a warm jacket, gloves and headwear. Confirm actual weather and clothing requirements with the operator before departure.', 'L’attente de nuit ou à l’aube peut être froide ; prévoyez veste chaude, gants et bonnet. Confirmez météo et tenue avec l’organisateur avant le départ.', '夜间和黎明等待可能寒冷，带保暖外套、手套和帽子。出发前向运营方确认实际天气及衣物要求。', 'रात और भोर की प्रतीक्षा ठंडी हो सकती है; गरम जैकेट, दस्ताने और टोपी रखें। रवाना होने से पहले संचालक से वास्तविक मौसम और कपड़ों की ज़रूरत जाँचें।'), ['world-bromo-visit']),
      section('transport', l('اختر مدخلاً رسمياً مثل سيمورو لاوانغ ورتب النقل المحلي ومسار الجيب المسموح. للمرة الأولى استعن بمشغّل موثوق؛ وجود مركبة دفع رباعي لا يلغي قيود البركان.', 'Choose an official approach such as Cemoro Lawang and arrange local transport on permitted jeep routes. First-time visitors should use a reputable operator; four-wheel drive does not override volcanic restrictions.', 'Choisissez un accès officiel, comme Cemoro Lawang, et un trajet en jeep autorisé. Pour une première visite, recourez à un opérateur fiable ; un 4×4 n’annule aucune restriction volcanique.', '选择Cemoro Lawang等官方入口并安排获准吉普路线的当地交通。初访者宜用可靠运营方；四驱车不能豁免火山限制。', 'Cemoro Lawang जैसे आधिकारिक प्रवेश और अनुमत जीप मार्ग चुनें। पहली यात्रा में भरोसेमंद संचालक लें; चार-पहिया ड्राइव ज्वालामुखी प्रतिबंध नहीं हटाती।'), ['world-bromo-access', 'world-bromo-visit']),
      section('season', l('يُفضّل الطقس الأجف عادة للمشاهد البعيدة، لكن الضباب والمطر قد يغيران الخطة. برودة الفجر لا تتنبأ ببقية ظروف اليوم؛ حالة البركان تتقدم على اختيار الموسم.', 'Drier weather is generally favoured for distant views, but fog and rain can change plans. Cold dawn does not predict the later conditions; volcanic status takes priority over seasonal preferences.', 'Le temps plus sec favorise généralement les panoramas, mais brouillard et pluie peuvent changer le programme. Une aube froide ne prédit pas la suite ; l’état du volcan prime sur la saison.', '较干燥天气通常有利于远眺，但雾雨可能改变计划。清晨寒冷不能代表之后情况；火山状态优先于季节偏好。', 'दूर के दृश्यों के लिए शुष्क मौसम अक्सर बेहतर है, पर कोहरा और बारिश योजना बदल सकते हैं। ठंडी भोर आगे के मौसम का संकेत नहीं; ज्वालामुखी स्थिति ऋतु से पहले है।'), ['world-bromo-access', 'world-bromo-visit']),
      section('nature', l('تحيط بالكالديرا رمال بركانية وسافانا، والمنطقة ذات قيمة ثقافية لشعب تنغر. احترم المناطق المقدسة؛ لم تُثبت هنا قائمة أنواع محلية فلا تستخدم نباتاً اعتماداً على الصورة.', 'Volcanic sand and savanna surround the caldera, with cultural importance to Tengger communities. Respect sacred areas; no local species inventory is established here, so do not infer plant uses from images.', 'Sable volcanique et savane entourent la caldeira, importante pour les communautés Tengger. Respectez les lieux sacrés ; aucun inventaire local ici ne permet de déduire l’usage d’une plante.', '火山沙地与稀树草地围绕盆地，对腾格尔社区有文化意义。尊重神圣区域；此处未建立当地物种清单，不能凭照片判断植物用途。', 'कैल्डेरा के आसपास ज्वालामुखीय रेत और सवाना हैं, जो टेंगर समुदायों के लिए सांस्कृतिक महत्त्व रखते हैं। पवित्र स्थलों का सम्मान करें; यहाँ स्थानीय प्रजाति सूची नहीं, चित्र से पौधे का उपयोग न मानें।'), ['world-bromo-visit']),
      section('hazard', l('برومو بركان نشط قد يطلق غازات ورماداً أو يقذف مواد فجأة. مرجع PVMBG هنا تاريخي لشرح الخطر، وليس تنبيهاً حالياً؛ راجع MAGMA والمنتزه واتبع المنع القائم يوم الزيارة.', 'Bromo can release gas, ash or sudden ejecta. The linked PVMBG notice is historical hazard evidence, not today’s alert; check MAGMA and park updates and obey the current exclusion area.', 'Bromo peut émettre gaz, cendres ou projections soudaines. L’avis PVMBG cité est historique, pas l’alerte du jour ; vérifiez MAGMA et le parc, puis respectez les exclusions actuelles.', '布罗莫可能排出气体、火山灰或突发喷出物。所引PVMBG通报仅是历史风险依据，不是当天预警；核对MAGMA和公园公告，遵守现行禁区。', 'ब्रोमो से गैस, राख या अचानक पदार्थ निकल सकते हैं। जुड़ा PVMBG नोटिस ऐतिहासिक जोखिम-साक्ष्य है, आज की चेतावनी नहीं; MAGMA व पार्क सूचना देखकर वर्तमान निषेध क्षेत्र मानें।'), ['world-bromo-hazard', 'world-bromo-visit']),
      section('visit', l('اختر نقطة مشاهدة مسموحة مثل منطقة بنانجاكان بعد تأكيد فتحها. للمبتدئ جولة مشاهدة مع نقل محلي بديل عن صعود الفوهة؛ تحقق من التذكرة الإلكترونية والحجز والإغلاقات الرسمية.', 'Choose a permitted viewpoint such as the Penanjakan area after confirming access. Beginners can take a viewpoint outing with local transport instead of a crater ascent; verify official online tickets, bookings and closures.', 'Choisissez un belvédère autorisé, comme Penanjakan après confirmation. Débutants : sortie panoramique avec transport local plutôt qu’ascension du cratère ; vérifiez billets officiels, réservations et fermetures.', '确认开放后选择Penanjakan等获准观景区。初访者可乘当地交通观景，替代攀登火山口；核对官方电子票、预约及关闭信息。', 'पहुँच की पुष्टि के बाद Penanjakan जैसा अनुमत दृश्य-बिंदु चुनें। शुरुआती यात्री क्रेटर चढ़ने के बजाय स्थानीय परिवहन से दृश्य-दौरा करें; आधिकारिक ऑनलाइन टिकट, बुकिंग और बंदी जाँचें।'), ['world-bromo-visit', 'world-bromo-access']),
    ],
    species: [],
  },
];

// Each unit is an editable checklist starting point, not a capacity or safety guarantee.
function packing(destinationId: string, terrainId: TerrainId, equipmentId: string, label: Localized, reason: Localized, sourceIds: string[], coverage: PackingRule['coverage'] = 'local'): PackingRule {
  return {id: `world-${destinationId}-${equipmentId}`, version: 1, equipmentId, label, category: 'essentials', terrainIds: [terrainId], activities: [], months: [], minDays: 0, transport: [], baseQuantity: 1, perPerson: true, reason, sourceIds, coverage, destinationIds: [destinationId]};
}

const rain = l('طبقة واقية من المطر', 'Rain shell', 'Veste imperméable', '防雨外层', 'वर्षारोधी बाहरी परत');
const warm = l('طبقة ملابس دافئة', 'Warm clothing layer', 'Couche chaude', '保暖层', 'गरम कपड़ों की परत');
const sun = l('حماية شخصية من الشمس', 'Personal sun protection', 'Protection solaire personnelle', '个人防晒用品', 'व्यक्तिगत धूप से बचाव');

export const worldRules: PackingRule[] = [
  packing('plitvice-lakes', 'forest', 'rain-shell', rain, l('يوصي المنتزه بحماية من المطر للممرات المتغيرة الظروف؛ عدّل التجهيز حسب التوقعات.', 'The park recommends rain protection for changeable trail conditions; adapt it to the forecast.', 'Le parc conseille une protection pluie ; adaptez-la aux prévisions.', '公园建议准备雨具，应按天气预报调整。', 'पार्क वर्षा से बचाव सुझाता है; पूर्वानुमान के अनुसार बदलें।'), ['world-plitvice-activities']),
  packing('plitvice-lakes', 'forest', 'walking-shoes', l('أحذية مشي ثابتة', 'Supportive walking footwear', 'Chaussures de marche stables', '稳固步行鞋', 'मज़बूत पकड़ वाले जूते'), l('ممرات خشبية وصخرية غير مستوية؛ الأحذية المناسبة مهمة حتى في جولة البحيرات.', 'Uneven wooden and rocky paths make suitable footwear important even on a lake circuit.', 'Passerelles et rochers irréguliers exigent des chaussures adaptées, même autour des lacs.', '湖区环线也有不平木道和石径，需要合适鞋具。', 'झील की परिक्रमा में भी असमतल लकड़ी व पत्थर के रास्तों के लिए उचित जूते ज़रूरी हैं।'), ['world-plitvice-activities']),
  packing('plitvice-lakes', 'forest', 'sun-protection', sun, l('يوصي المنتزه بواقيات الشمس عند ملاءمتها للموسم والطقس؛ اختر ما يناسب زيارتك.', 'The park recommends sun protection as appropriate to season and weather; choose what suits your visit.', 'Le parc conseille une protection solaire selon saison et météo ; adaptez votre choix.', '公园建议按季节天气准备防晒用品，按行程选择。', 'पार्क ऋतु और मौसम के अनुसार धूप से बचाव सुझाता है; यात्रा के अनुकूल चुनें।'), ['world-plitvice-place']),
  packing('everglades', 'coast', 'insect-repellent', l('طارد حشرات مناسب', 'Suitable insect repellent', 'Répulsif adapté', '合适的驱虫剂', 'उपयुक्त कीटरोधी'), l('البعوض شائع، خصوصاً في الموسم الرطب وحول النباتات؛ اتبع تعليمات المنتج.', 'Mosquitoes are common, especially in the wet season and vegetation; follow product directions.', 'Moustiques fréquents, surtout en saison humide et près de la végétation ; suivez la notice.', '雨季及植被附近蚊虫较多，按产品说明使用。', 'वर्षा ऋतु और वनस्पति के पास मच्छर अधिक होते हैं; उत्पाद निर्देश मानें।'), ['world-ever-safety']),
  packing('everglades', 'coast', 'sun-protection', sun, l('توصي إرشادات إيفرغليدز بواقي الشمس للأنشطة الخارجية؛ عدّل النشاط أيضاً حسب الحرارة.', 'Everglades guidance recommends sun protection outdoors; also adjust activity to the heat.', 'Les Everglades recommandent une protection solaire ; adaptez aussi l’activité à la chaleur.', '大沼泽地建议户外防晒，也应按高温调整活动。', 'एवरग्लेड्स बाहरी गतिविधियों में धूप से बचाव सुझाता है; गर्मी के अनुसार गतिविधि भी बदलें।'), ['world-ever-safety']),
  packing('everglades', 'coast', 'long-clothing', l('قميص طويل الأكمام وسروال', 'Long sleeves and trousers', 'Manches longues et pantalon', '长袖衣与长裤', 'लंबी आस्तीन और पैंट'), l('تساعد التغطية على تقليل التعرض للبعوض؛ اختر ملابس تناسب الحر الرطب.', 'Covering skin helps reduce mosquito exposure; choose clothing suited to humid heat.', 'Couvrir la peau réduit l’exposition aux moustiques ; adaptez la tenue à la chaleur humide.', '遮盖皮肤有助减少蚊虫叮咬，选择适合湿热的衣物。', 'त्वचा ढकने से मच्छरों का संपर्क घटता है; उमस के अनुकूल कपड़े चुनें।'), ['world-ever-safety']),
  packing('yellowstone', 'mountain', 'rain-shell', rain, l('المطر والرياح والبرد ممكنة طوال العام؛ توصي إرشادات المنتزه بحماية من المطر.', 'Rain, wind and cold are possible year-round; park guidance recommends rain protection.', 'Pluie, vent et froid restent possibles toute l’année ; le parc conseille une protection pluie.', '全年都可能有风雨和寒冷，公园建议带雨具。', 'साल भर वर्षा, हवा और ठंड संभव हैं; पार्क वर्षा से बचाव सुझाता है।'), ['world-yellow-weather']),
  packing('yellowstone', 'mountain', 'warm-layers', warm, l('حتى الصيف قد يشهد برداً أو ثلجاً؛ كمية البداية لا تحدد سماكة الطبقات المناسبة.', 'Even summer can bring cold or snow; this starting quantity does not specify suitable insulation.', 'Même l’été peut apporter froid et neige ; la quantité initiale ne définit pas l’isolation nécessaire.', '夏季也可能寒冷降雪，起始数量不代表所需保暖程度。', 'गर्मियों में भी ठंड या बर्फ़ संभव है; शुरुआती मात्रा आवश्यक गरमाहट तय नहीं करती।'), ['world-yellow-weather']),
  packing('yellowstone', 'mountain', 'warm-gloves', l('قفازات دافئة', 'Warm gloves', 'Gants chauds', '保暖手套', 'गरम दस्ताने'), l('توصي إرشادات يلوستون بالقفازات لحفظ الدفء في الطقس المتغير.', 'Yellowstone guidance recommends gloves for warmth in changing weather.', 'Yellowstone conseille des gants pour conserver la chaleur lorsque le temps change.', '黄石建议在多变天气中使用手套保暖。', 'येलोस्टोन बदलते मौसम में गरम रहने के लिए दस्ताने सुझाता है।'), ['world-yellow-safety']),
  packing('skaftafell', 'mountain', 'rain-shell', rain, l('إرشاد آيسلندي عام للرياح والمطر، مطبق هنا على سكافتافيل؛ راجع توقعات المسار.', 'General Iceland wind and rain guidance, scoped here to Skaftafell; check the route forecast.', 'Conseil général islandais contre vent et pluie, limité ici à Skaftafell ; vérifiez les prévisions.', '冰岛通用防风雨建议，此处仅用于斯卡夫塔山；核对路线预报。', 'आइसलैंड की सामान्य हवा-वर्षा सलाह यहाँ स्काफ्टाफेल तक सीमित है; मार्ग का पूर्वानुमान देखें।'), ['world-iceland-clothing'], 'terrain-example'),
  packing('skaftafell', 'mountain', 'warm-layers', warm, l('إرشاد آيسلندي عام: طبقات عازلة حتى صيفاً؛ لا يغني هذا عن تجهيزات مرشد الجليد.', 'General Iceland guidance: insulating layers even in summer; this does not replace glacier-guide equipment.', 'Conseil général islandais : couches isolantes même en été, sans remplacer le matériel du guide glaciaire.', '冰岛通用建议：夏季也需保暖层，不能替代冰川向导要求的装备。', 'आइसलैंड की सामान्य सलाह: गर्मियों में भी गरम परतें; यह हिमनदी गाइड के उपकरणों का विकल्प नहीं।'), ['world-iceland-clothing'], 'terrain-example'),
  packing('skaftafell', 'mountain', 'waterproof-pack', l('حقيبة أو غطاء يحمي الملابس من الماء', 'Waterproof pack or clothing protection', 'Sac ou protection étanche pour vêtements', '防水背包或衣物防水保护', 'जलरोधी बैग या कपड़ों का बचाव'), l('إرشاد SafeTravel العام يحث على إبقاء الملابس الاحتياطية جافة؛ اختر الحماية المناسبة لحقيبتك.', 'General SafeTravel guidance keeps spare clothing dry; select protection suitable for your pack.', 'SafeTravel conseille de garder les vêtements de rechange secs ; choisissez une protection adaptée.', 'SafeTravel通用建议保持备用衣物干燥；选择适合背包的防水保护。', 'SafeTravel की सामान्य सलाह अतिरिक्त कपड़े सूखे रखने की है; बैग के अनुसार सुरक्षा चुनें।'), ['world-iceland-clothing'], 'terrain-example'),
  packing('bromo', 'mountain', 'warm-layers', warm, l('توصي وزارة السياحة بملابس دافئة لليل والفجر في برومو؛ راجع توقعات يومك.', 'The tourism ministry recommends warm clothing for Bromo nights and dawn; check your day’s forecast.', 'Le ministère conseille une tenue chaude pour nuit et aube à Bromo ; vérifiez la météo du jour.', '旅游部建议布罗莫夜间和黎明保暖，核对当天预报。', 'पर्यटन मंत्रालय ब्रोमो की रात और भोर के लिए गरम कपड़े सुझाता है; उस दिन का पूर्वानुमान देखें।'), ['world-bromo-visit']),
  packing('bromo', 'mountain', 'dust-eye-protection', l('نظارات لحماية العين من الغبار', 'Dust eye protection', 'Lunettes contre la poussière', '防尘护目镜', 'धूल से आँखों की सुरक्षा'), l('توصية سياحية لمناطق الرمال المغبرة؛ ليست حماية تبيح دخول منطقة غازات أو رماد محظورة.', 'Tourism advice for dusty sand areas; this never permits entering an excluded gas or ash area.', 'Conseil pour le sable poussiéreux ; cela n’autorise jamais l’entrée dans une zone exclue de gaz ou cendres.', '用于扬尘沙地的旅游建议，不代表能进入气体或火山灰禁区。', 'धूलभरी रेत के लिए सलाह; इससे गैस या राख वाले निषिद्ध क्षेत्र में प्रवेश की अनुमति नहीं मिलती।'), ['world-bromo-visit']),
  packing('bromo', 'mountain', 'warm-gloves', l('قفازات دافئة', 'Warm gloves', 'Gants chauds', '保暖手套', 'गरम दस्ताने'), l('توصي الوزارة بالقفازات مع الملابس الدافئة لزيارات برومو الباردة قبل الشروق.', 'The ministry recommends gloves with warm clothing for cold pre-sunrise visits to Bromo.', 'Le ministère conseille des gants avec la tenue chaude avant le lever du soleil à Bromo.', '旅游部建议布罗莫日出前寒冷时段穿保暖衣物并戴手套。', 'मंत्रालय ब्रोमो में सूर्योदय से पहले ठंडी यात्रा के लिए गरम कपड़ों के साथ दस्ताने सुझाता है।'), ['world-bromo-visit']),
];
