import type {Localized,PackingRule,TerrainId} from './toolkit-types';
// Practical adaptations of the cited guidance, not locally mandated equipment lists.
function scoped(destinationId:string,terrainId:TerrainId,equipmentId:string,label:Localized,reason:Localized,sourceIds:string[],perPerson=true,activities:string[]=[]):PackingRule{return{id:`${destinationId}-${equipmentId}`,version:1,equipmentId,label,category:'equipment',terrainIds:[terrainId],activities,months:[],minDays:0,transport:[],baseQuantity:1,perPerson,reason,sourceIds,coverage:'terrain-example',destinationIds:[destinationId]}}
const sun:Localized=['قبعة ونظارة وحماية من الشمس','Hat, sunglasses and sun protection','Chapeau, lunettes et protection solaire','帽子、太阳镜与防晒用品','टोपी, धूप का चश्मा और धूप से सुरक्षा'];
const shoes:Localized=['حذاء مشي ثابت جيد التماسك','Supportive walking shoes with grip','Chaussures de marche stables et adhérentes','稳固防滑的步行鞋','अच्छी पकड़ वाले सहायक पैदल जूते'];
export const originalRules:PackingRule[]=[
scoped('liwa','desert','sun-protection',sun,['المساحات المكشوفة في ليوا تجعل حماية كل مشارك من الشمس أولوية؛ اختر ملابس تغطي الجلد أيضاً.','Open terrain in Liwa makes sun protection a priority for every participant; also choose clothing that covers skin.','Les espaces ouverts de Liwa rendent la protection solaire prioritaire pour chaque participant ; portez aussi des vêtements couvrants.','利瓦地形开阔，每位参与者都应优先准备防晒用品，并穿着遮盖皮肤的衣物。','लीवा का खुला भूभाग हर यात्री के लिए धूप से सुरक्षा जरूरी बनाता है; त्वचा ढकने वाले कपड़े भी चुनें।'],['liwa-desert-season','essentials']),
scoped('liwa','desert','power-bank',['بطارية متنقلة مشحونة','Charged power bank','Batterie externe chargée','充好电的移动电源','चार्ज किया हुआ पावर बैंक'],['للخرائط والاتصال خلال الانتقال بين الواحة والكثبان؛ لا تعتمد على الهاتف وحده خارج الطرق.','For maps and communication between the oasis and dunes; do not rely on a phone alone off-road.','Pour les cartes et les communications entre oasis et dunes ; hors route, ne comptez pas uniquement sur le téléphone.','往返绿洲与沙丘时用于地图和通信；越野时不要仅依赖手机。','नखलिस्तान और टीलों के बीच नक्शे व संपर्क के लिए; सड़क से बाहर केवल फोन पर निर्भर न रहें।'],['liwa-desert-visit','essentials'],false),
scoped('jebel-shams','mountain','grippy-footwear',shoes,['للمسارات الصخرية في جبل شمس؛ الحذاء لا يجعل الاقتراب من الحواف أو مسار مغلق آمناً.','For rocky paths at Jebel Shams; footwear does not make cliff edges or closed trails safe.','Pour les sentiers rocheux du Jebel Shams ; les chaussures ne sécurisent ni les falaises ni les sentiers fermés.','适用于沙姆山岩石步道；鞋子不能使悬崖边缘或封闭步道变得安全。','जेबेल शम्स के पथरीले रास्तों के लिए; जूते चट्टान के किनारे या बंद रास्ते सुरक्षित नहीं बनाते।'],['oman-mountains','essentials']),
scoped('jebel-shams','mountain','warm-layer',['طبقة دافئة وواقية من الرياح','Warm layer and wind protection','Couche chaude et protection contre le vent','保暖层与防风衣物','गर्म परत और हवा से सुरक्षा'],['الارتفاع والرياح قد يغيران إحساسك بالحرارة؛ راجع طقس الجبل قبل اختيار الطبقات.','Altitude and wind can change how cold it feels; check mountain weather before choosing layers.','Altitude et vent modifient le ressenti ; consultez la météo de montagne avant de choisir vos couches.','海拔和风会改变体感温度；选择衣物前请查看山区天气。','ऊँचाई और हवा ठंड का एहसास बदल सकते हैं; परतें चुनने से पहले पहाड़ का मौसम जाँचें।'],['oman-mountains','essentials']),
scoped('black-forest','forest','rain-shell',['طبقة خارجية واقية من المطر','Waterproof outer layer','Veste imperméable','防雨外套','बारिश से बचाने वाली बाहरी परत'],['للمشي في الغابة السوداء مع تغير الطقس؛ أضف طبقة دافئة حسب التوقعات.','For changing weather while walking in the Black Forest; add a warm layer according to the forecast.','Pour la météo changeante en Forêt-Noire ; ajoutez une couche chaude selon les prévisions.','应对黑森林步行时多变的天气；请按预报添加保暖层。','ब्लैक फॉरेस्ट में पैदल चलते समय बदलते मौसम के लिए; पूर्वानुमान के अनुसार गर्म परत जोड़ें।'],['forest-visitor-tips','essentials']),
scoped('black-forest','forest','waste-bag',['كيس لإعادة نفايات المجموعة','Bag for the group’s waste','Sac pour les déchets du groupe','团队垃圾回收袋','समूह का कचरा वापस ले जाने का बैग'],['أعد النفايات معك واحمِ النباتات والحيوانات؛ عدّل عدد الأكياس بحسب مدة الرحلة وحجم المجموعة.','Carry waste out to protect plants and wildlife; adjust bag count to trip length and group size.','Rapportez vos déchets pour protéger la faune et la flore ; adaptez le nombre de sacs à la durée et au groupe.','带走垃圾以保护动植物；按行程长短与人数调整袋数。','पौधों और वन्यजीवों की रक्षा के लिए कचरा वापस लाएँ; अवधि और समूह के अनुसार थैलों की संख्या बदलें।'],['forest-rules','forest-visitor-tips'],false),
scoped('hurghada','coast','sun-protection',sun,['للشاطئ ورحلات القارب في الغردقة؛ اختر حماية وملابس تناسب التعرض للشمس.','For Hurghada beaches and boat trips; choose protection and clothing suited to sun exposure.','Pour les plages et sorties en bateau à Hurghada ; choisissez une protection et des vêtements adaptés au soleil.','适用于赫尔格达海滩和乘船活动；选择适合日晒的防护用品与衣物。','हर्गहाडा के समुद्र तट और नाव यात्राओं के लिए; धूप के अनुसार सुरक्षा और कपड़े चुनें।'],['egypt-sea','essentials']),
scoped('hurghada','coast','dry-bag',['حقيبة مقاومة للماء للمتعلقات','Dry bag for belongings','Sac étanche pour les effets personnels','个人物品防水袋','सामान के लिए वाटरप्रूफ बैग'],['للقارب والرذاذ: احفظ الهاتف والمستندات بعيداً عن الماء، وتحقق من مستوى عزل الحقيبة.','For boats and spray: keep phones and documents dry, and check the bag’s water resistance.','Sur le bateau et contre les éclaboussures : protégez téléphone et papiers, et vérifiez l’étanchéité du sac.','乘船时防范水花：保护手机和证件，并核对袋子的防水等级。','नाव और पानी के छींटों में फोन व दस्तावेज सूखे रखें और बैग की जलरोधक क्षमता जाँचें।'],['egypt-snorkel','essentials'],true,['boating']),
];
