import type { Destination, GuideSection, Localized, PackingRule, SourceReference } from './toolkit-types';

// Reviewed against the linked official sources on 2026-09-17. Map coordinates are
// approximate place markers, never route instructions or verified trailheads.
export const eastSources: SourceReference[] = [
  { id: 'east-rum-unesco', title: 'UNESCO · Wadi Rum Protected Area', url: 'https://whc.unesco.org/en/list/1377/', reviewedAt: '2026-09-17' },
  { id: 'east-rum-visit', title: 'Jordan Tourism Board · Wadi Rum', url: 'https://international.visitjordan.com/wheretogo/wadi-rum/', reviewedAt: '2026-09-17' },
  { id: 'east-alula-hegra', title: 'Experience AlUla · Hegra Day Tour', url: 'https://www.experiencealula.com/en/things-to-do/experiences/hegra-day-tour', reviewedAt: '2026-09-17' },
  { id: 'east-alula-oasis', title: 'Experience AlUla · AlUla Oasis', url: 'https://www.experiencealula.com/en/places-to-go/alula-oasis', reviewedAt: '2026-09-17' },
  { id: 'east-alula-practical', title: 'Experience AlUla · Practical information', url: 'https://www.experiencealula.com/en/plan-your-trip/practical-information', reviewedAt: '2026-09-17' },
  { id: 'east-alula-plan', title: 'Experience AlUla · Plan your trip', url: 'https://www.experiencealula.com/en/plan-your-trip', reviewedAt: '2026-09-17' },
  { id: 'east-jais-hiking', title: 'Visit Jebel Jais · Hiking', url: 'https://visitjebeljais.com/jais-hiking', reviewedAt: '2026-09-17' },
  { id: 'east-jais-visit', title: 'Visit Jebel Jais · Day trip and travel tips', url: 'https://visitjebeljais.com/blog/jebel-jais-itinerary-guide-top-activities-day-trip-travel-tips', reviewedAt: '2026-09-17' },
  { id: 'east-jais-nature', title: 'Visit Jebel Jais · Flora and fauna', url: 'https://visitjebeljais.com/flora-fauna', reviewedAt: '2026-09-17' },
  { id: 'east-jais-transport', title: 'Visit Jebel Jais · Transport', url: 'https://visitjebeljais.com/transport', reviewedAt: '2026-09-17' },
  { id: 'east-shab-visit', title: 'Experience Oman · Wadi Shab', url: 'https://experienceoman.om/destinations/al-sharqiyah-south/wadi-shab', reviewedAt: '2026-09-17' },
  { id: 'east-oman-outdoors', title: 'Experience Oman · Activities booklet: outdoor precautions', url: 'https://experienceoman.om/wp-content/uploads/2024/02/Activities-booklet_English_30_aug.pdf', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-visit', title: 'Visit Abu Dhabi · Jubail Mangrove Park', url: 'https://visitabudhabi.ae/en/things-to-do/nature-and-wildlife/parks/jubail-mangrove-park', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-island', title: 'Visit Abu Dhabi · Jubail Island', url: 'https://visitabudhabi.ae/en/where-to-go/islands/jubail-island', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-rules', title: 'Jubail Island · Mangrove Park visitor rules', url: 'https://jubailisland.ae/terms-conditions/', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-activities', title: 'Jubail Mangrove Park · Activities and booking', url: 'https://www.jubailmangrovepark.ae/en/activities', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-kayak', title: 'Jubail Mangrove Park · Kayaking conditions', url: 'https://www.jubailmangrovepark.ae/en/activities/single-kayaking-experience', reviewedAt: '2026-09-17' },
  { id: 'east-jubail-boardwalk', title: 'Jubail Mangrove Park · Boardwalk experience', url: 'https://www.jubailmangrovepark.ae/en/activities/boardwalk-experience', reviewedAt: '2026-09-17' },
  { id: 'east-outdoor-essentials', title: 'National Park Service · Ten Essentials (general outdoor guidance)', url: 'https://www.nps.gov/articles/10essentials.htm', reviewedAt: '2026-09-17' },
];

const sectionTitles: Record<string, Localized> = {
  place: ['المكان وطبيعة التضاريس', 'Place and terrain', 'Lieu et relief', '地点与地形', 'स्थान और भूभाग'],
  equipment: ['المعدات والاستعداد', 'Equipment and preparation', 'Matériel et préparation', '装备与准备', 'सामान और तैयारी'],
  clothing: ['الملابس والأحذية', 'Clothing and footwear', 'Vêtements et chaussures', '衣物与鞋履', 'कपड़े और जूते'],
  transport: ['الوصول والتنقل', 'Access and transport', 'Accès et déplacements', '交通与抵达', 'पहुँच और परिवहन'],
  season: ['الموسم والظروف', 'Season and conditions', 'Saison et conditions', '季节与条件', 'मौसम और परिस्थितियाँ'],
  nature: ['الطبيعة وحدود التعرف', 'Nature and identification limits', 'Nature et limites d’identification', '自然与识别局限', 'प्रकृति और पहचान की सीमाएँ'],
  hazard: ['احتياطات الزيارة', 'Visit precautions', 'Précautions de visite', '游览注意事项', 'यात्रा की सावधानियाँ'],
  visit: ['اختيار النشاط والحجز', 'Activity choice and booking', 'Activités et réservation', '活动选择与预约', 'गतिविधि और बुकिंग'],
};
const section = (id: string, body: Localized, sourceIds: string[]): GuideSection => ({ id, title: sectionTitles[id], body, sourceIds });

export const eastDestinations: Destination[] = [
  {
    id: 'wadi-rum', terrainId: 'desert', terrainIndex: 0, lat: 29.6397, lon: 35.4339, timezone: 'Asia/Amman',
    names: ['وادي رم', 'Wadi Rum', 'Wadi Rum', '瓦迪拉姆', 'वाडी रम'],
    summary: ['صحراء أردنية بجبال من الحجر الرملي؛ تناسب الجولات المحلية ومشاهدة النجوم مع تحضير للانكشاف.', 'Jordanian sandstone desert for local tours and stargazing, with preparation for exposed terrain.', 'Désert jordanien de grès, pour les visites locales et l’observation des étoiles en terrain exposé.', '约旦砂岩沙漠，可参加当地游览与观星，需为无遮蔽地形做好准备。', 'जॉर्डन का बलुआ-पत्थर वाला रेगिस्तान; स्थानीय भ्रमण और तारों को देखने के लिए खुले भूभाग की तैयारी करें।'],
    image: '/images/desert.jpg', imageIsIllustrative: true, sourceIds: ['east-rum-unesco', 'east-rum-visit'], species: [],
    sections: [
      section('place', ['تؤكد اليونسكو تضاريس الحجر الرملي والأقواس الطبيعية. المؤشر تقريبي للمنطقة، وليس بداية مسار؛ الصورة توضيحية.', 'UNESCO documents sandstone landforms and natural arches. This is an approximate area marker, not a trailhead; the image is illustrative.', 'L’UNESCO décrit des reliefs de grès et des arches naturelles. Repère approximatif, pas un départ de sentier ; image illustrative.', '联合国教科文组织记录了砂岩地貌与天然拱门。标记仅示大致区域，并非步道起点；图片为示意。', 'यूनेस्को बलुआ-पत्थर की आकृतियों और प्राकृतिक मेहराबों का वर्णन करता है। यह क्षेत्र का अनुमानित चिह्न है, पगडंडी का प्रवेश नहीं; चित्र उदाहरणात्मक है।'], ['east-rum-unesco']),
      section('equipment', ['استنتاج عملي للصحراء: جهّز الملاحة والماء واحتياطياً يناسب خطتك. اتفق مع المشغّل على ما يوفره؛ لا تفترض أن المخيم يوفّر معدات المشي.', 'Practical desert inference: prepare navigation, water and a reserve suited to your plan. Confirm operator supplies; a camp booking need not include walking equipment.', 'Conseil déduit du terrain : prévoyez navigation, eau et réserve adaptées. Vérifiez le matériel fourni ; réserver un camp ne garantit pas l’équipement de marche.', '沙漠准备建议：备好导航、饮水及适合计划的备用物资。确认运营方提供的物品；营地预订不一定含徒步装备。', 'रेगिस्तानी तैयारी का व्यावहारिक सुझाव: रास्ते की जानकारी, पानी और योजना के अनुसार भंडार रखें। संचालक से सामान की पुष्टि करें; शिविर बुकिंग में पैदल यात्रा का सामान जरूरी नहीं शामिल हो।'], ['east-outdoor-essentials']),
      section('clothing', ['نصيحة عامة وليست قاعدة محلية: غطاء للرأس وملابس تحمي من الشمس، وطبقة إضافية حسب التوقعات. جرّب الأحذية قبل الخروج.', 'General advice, not a local requirement: sun hat, covering clothing and an extra layer matched to the forecast. Try footwear before departure.', 'Conseil général, sans obligation locale : chapeau, vêtements couvrants et couche adaptée aux prévisions. Essayez vos chaussures avant le départ.', '一般建议，并非当地规定：遮阳帽、遮蔽衣物及按预报准备的备用衣层。出发前试穿鞋履。', 'सामान्य सलाह, स्थानीय अनिवार्यता नहीं: टोपी, धूप से ढकने वाले कपड़े और पूर्वानुमान के अनुसार अतिरिक्त परत। निकलने से पहले जूते आजमाएँ।'], ['east-outdoor-essentials']),
      section('transport', ['تذكر هيئة السياحة جولات الدفع الرباعي عبر المخيم أو مركز الزوار. اقتراح عملي: رتّب نقطة اللقاء والعودة، ولا تعامل مؤشر الخريطة كمسار قيادة صحراوي.', 'The tourism board lists 4×4 tours through camps or the visitor centre. Practical suggestion: arrange pickup and return; the map marker is not an off-road driving route.', 'L’office du tourisme propose des excursions en 4×4 via les camps ou le centre d’accueil. Convenez du retour ; le repère ne constitue pas un itinéraire tout-terrain.', '旅游局介绍可通过营地或游客中心安排四驱游览。实用建议：确认接送与返回安排；地图标记不是越野路线。', 'पर्यटन बोर्ड शिविरों या आगंतुक केंद्र से 4×4 भ्रमण बताता है। व्यावहारिक सुझाव: मिलने और लौटने की व्यवस्था करें; नक्शे का चिह्न रेगिस्तानी ड्राइविंग मार्ग नहीं है।'], ['east-rum-visit']),
      section('season', ['قرار تخطيطي: قارن توقعات النهار والليل قبل الحجز، وأعد جدولة المشي عند الحرارة أو ضعف الرؤية. لا تمثل المتوسطات الشهرية حالة اليوم.', 'Planning choice: compare day and night forecasts before booking, and reschedule walking for excessive heat or poor visibility. Monthly averages do not describe today.', 'Choix de préparation : comparez les prévisions de jour et de nuit ; reportez la marche en cas de chaleur excessive ou de mauvaise visibilité. Les moyennes ne décrivent pas le jour prévu.', '规划建议：预订前比较昼夜预报；高温或能见度差时调整徒步安排。月均值不代表当天条件。', 'योजना संबंधी सुझाव: बुकिंग से पहले दिन और रात का पूर्वानुमान देखें; अत्यधिक गर्मी या कम दृश्यता में पैदल कार्यक्रम बदलें। मासिक औसत आज की स्थिति नहीं बताते।'], ['east-outdoor-essentials']),
      section('nature', ['لم نتحقق من دليل محلي كافٍ لتحديد الأنواع هنا؛ خلو القائمة لا يعني غياب الحياة البرية. اقتراح: راقب من بعيد ولا تجمع نباتات أو حطباً.', 'No sufficiently specific local species guide was verified here; an empty list does not mean no wildlife. Suggested practice: observe at a distance and leave plants and wood.', 'Aucun guide local assez précis n’a été vérifié ici ; une liste vide ne signifie pas absence de faune. Observez à distance, sans prélever plantes ni bois.', '此处尚未核实足够具体的当地物种资料；列表为空不代表没有野生生物。建议远观，不采集植物或木材。', 'यहाँ प्रजातियों की पहचान के लिए पर्याप्त स्थानीय जानकारी सत्यापित नहीं हुई; खाली सूची का मतलब वन्यजीवों का अभाव नहीं है। दूर से देखें और पौधे या लकड़ी न लें।'], ['east-rum-unesco']),
      section('hazard', ['استنتاج من تضاريس الأقواس والجروف: لا تتسلق تكويناً لمجرد ظهوره في الصور. اختر مساراً يناسب قدرتك مع مرشد، واترك النقوش والصخور كما هي.', 'Terrain-based inference: a photographed arch or cliff is not a climbing invitation. Choose a route within your ability with a guide; leave inscriptions and rocks undisturbed.', 'Déduction liée au relief : une arche photographiée n’est pas une invitation à grimper. Choisissez un parcours adapté avec un guide ; préservez inscriptions et roches.', '地形推断：照片中的拱门或崖壁不表示适合攀爬。与向导选择符合能力的路线，不扰动岩画和岩石。', 'भूभाग से निकली सावधानी: फोटो में दिखने वाली मेहराब या चट्टान चढ़ने की अनुमति नहीं है। गाइड के साथ अपनी क्षमता का मार्ग चुनें; शिलालेख और पत्थर न छेड़ें।'], ['east-rum-unesco']),
      section('visit', ['الأنشطة المعلنة تشمل جولات محلية ومشاهدة النجوم. للمبتدئ نقترح جولة قصيرة مع مشغّل بدل المشي النائي؛ أكّد الحجز والمدة وشروط الطقس مسبقاً.', 'Advertised activities include local tours and stargazing. For beginners, we suggest a short operated tour instead of a remote walk; confirm booking, duration and weather conditions.', 'Les activités annoncées incluent excursions et observation des étoiles. Débutants : privilégiez une sortie courte organisée ; confirmez réservation, durée et conditions météo.', '公布的活动包括当地游览和观星。初学者可选择运营方安排的短途游览；提前确认预约、时长与天气限制。', 'बताई गई गतिविधियों में स्थानीय भ्रमण और तारों का अवलोकन है। शुरुआती यात्रियों के लिए दूर की पैदल यात्रा की बजाय छोटी संचालित यात्रा सुझाते हैं; बुकिंग, अवधि और मौसम की शर्तें पूछें।'], ['east-rum-visit']),
    ],
  },
  {
    id: 'alula', terrainId: 'desert', terrainIndex: 0, lat: 26.6084, lon: 37.9229, timezone: 'Asia/Riyadh',
    names: ['العُلا', 'AlUla', 'AlUla', '欧拉', 'अलऊला'],
    summary: ['واحة سعودية وسط الحجر الرملي؛ تجمع المشي الزراعي وزيارات التراث المحجوزة.', 'A Saudi oasis amid sandstone, combining cultivated walks with booked heritage visits.', 'Oasis saoudienne parmi les grès, entre promenades agricoles et visites patrimoniales réservées.', '砂岩间的沙特绿洲，结合农耕步道与需预约的文化遗址游览。', 'बलुआ-पत्थर के बीच सऊदी नखलिस्तान; खेती वाले रास्तों पर सैर और बुक किए हुए विरासत भ्रमण।'],
    image: '/images/desert.jpg', imageIsIllustrative: true, sourceIds: ['east-alula-hegra', 'east-alula-oasis'],
    sections: [
      section('place', ['الحِجر يضم واجهات منحوتة في الحجر الرملي، والواحة بيئة زراعية. المؤشر للعُلا تقريباً وليس نقطة تجمع جولة؛ الصورة توضيحية.', 'Hegra has carved sandstone facades; the oasis is cultivated land. The marker approximates AlUla, not a tour meeting point; the image is illustrative.', 'Hégra présente des façades sculptées dans le grès ; l’oasis est cultivée. Repère approximatif d’AlUla, pas un lieu de rendez-vous ; image illustrative.', '黑格拉有砂岩雕刻立面，绿洲为耕作区。标记仅示欧拉大致位置，不是集合点；图片为示意。', 'हेग्रा में बलुआ-पत्थर पर तराशे मुखभाग हैं; नखलिस्तान कृषि क्षेत्र है। चिह्न अलऊला का अनुमानित स्थान है, भ्रमण का मिलन-बिंदु नहीं; चित्र उदाहरणात्मक है।'], ['east-alula-hegra', 'east-alula-oasis']),
      section('equipment', ['استنتاج عملي: احفظ التذاكر ونقطة اللقاء دون إنترنت، وخطط للماء والاستراحة. المصدر الرسمي ينبه إلى ضعف الاتصال في المناطق النائية.', 'Practical inference: keep tickets and meeting details offline, and plan water and breaks. Official guidance notes limited connectivity in remote areas.', 'Conseil pratique : conservez billets et rendez-vous hors ligne, prévoyez eau et pauses. Le guide officiel signale une connexion limitée dans les zones isolées.', '实用推断：离线保存票据和集合信息，安排饮水与休息。官方资料提示偏远地区通信有限。', 'व्यावहारिक सुझाव: टिकट और मिलने की जानकारी ऑफलाइन रखें, पानी और विश्राम की योजना बनाएँ। आधिकारिक मार्गदर्शन दूरस्थ क्षेत्रों में सीमित नेटवर्क बताता है।'], ['east-alula-practical']),
      section('clothing', ['توصي جولة الحِجر بأحذية مشي مغلقة وحماية من الشمس. أضف، كتكييف عملي، طبقة تناسب توقعات وقت زيارتك.', 'The Hegra tour recommends closed walking shoes and sun protection. As a practical adaptation, add a layer suited to your visit’s forecast.', 'La visite d’Hégra recommande chaussures fermées et protection solaire. Ajoutez, selon vos besoins, une couche adaptée aux prévisions.', '黑格拉游览建议穿包头步行鞋并防晒。实用调整：按游览时段预报增加合适衣层。', 'हेग्रा भ्रमण में बंद पैदल चलने वाले जूते और धूप से सुरक्षा सुझाई जाती है। व्यावहारिक तौर पर यात्रा के पूर्वानुमान के अनुसार एक परत जोड़ें।'], ['east-alula-hegra']),
      section('transport', ['تتضمن جولة الحِجر المعلنة نقلاً منظماً. اتبع نقطة اللقاء في تأكيد حجزك؛ استنتاج عملي: لا تستخدم إحداثيات العُلا بديلاً عنها.', 'The advertised Hegra tour includes organised transport. Follow the meeting point on your booking; practical advice: AlUla’s coordinates cannot replace it.', 'La visite annoncée d’Hégra comprend un transport organisé. Suivez le rendez-vous de votre réservation ; les coordonnées d’AlUla ne le remplacent pas.', '公布的黑格拉游览包含组织交通。请按预订确认中的集合点抵达；欧拉坐标不能代替该地址。', 'बताए गए हेग्रा भ्रमण में व्यवस्थित परिवहन शामिल है। बुकिंग पर दिया मिलन-बिंदु मानें; अलऊला के निर्देशांक उसका विकल्प नहीं हैं।'], ['east-alula-hegra']),
      section('season', ['صفحة التخطيط الرسمية تعرض توقعات الطقس. اقتراحنا: اختر توقيت المشي من التوقعات القريبة، وأبقِ بديل زيارة قصيرة عند الحر؛ لا نثبت هنا درجات موسمية.', 'The official planning page offers a forecast. Our suggestion: time walks using near-term conditions and keep a shorter visit option for heat; no seasonal temperatures are asserted here.', 'La page officielle propose des prévisions. Adaptez l’horaire de marche et gardez une visite courte en cas de chaleur ; aucune température saisonnière n’est affirmée ici.', '官方规划页提供天气预报。建议依据临近天气安排步行时间，高温时保留短途替代；此处不声称固定季节温度。', 'आधिकारिक योजना पृष्ठ मौसम का पूर्वानुमान देता है। निकट अवधि की स्थिति से सैर का समय चुनें और गर्मी में छोटी यात्रा का विकल्प रखें; यहाँ ऋतु के निश्चित तापमान नहीं बताए गए हैं।'], ['east-alula-plan']),
      section('nature', ['تصف المصادر بساتين نخيل مثمرة. الزيارة ليست إذناً بالحصاد: استنتاج عملي هو البقاء في المسارات العامة وطلب الإذن قبل دخول المزارع.', 'Sources describe productive date groves. A visit is not harvest permission: our practical advice is to stay on public paths and ask before entering farms.', 'Les sources décrivent des palmeraies productives. La visite n’autorise pas la récolte : restez sur les chemins publics et demandez avant d’entrer dans une exploitation.', '资料描述了产枣的棕榈林。参观不代表允许采收：建议留在公共路径，进入农田前征得同意。', 'स्रोत फल देने वाले खजूर के बाग बताते हैं। घूमना फसल तोड़ने की अनुमति नहीं है: सार्वजनिक रास्ते पर रहें और खेत में जाने से पहले अनुमति लें।'], ['east-alula-oasis']),
      section('hazard', ['اقتراح وقائي: لا تصعد واجهات المقابر أو تدخل مساراً مغلقاً. اسأل المشغّل عن السطح وإمكانية الوصول قبل الدفع؛ ملاءمة كل تجربة تختلف.', 'Precautionary suggestion: do not climb tomb facades or enter closed routes. Ask the operator about surfaces and access before payment; suitability varies by experience.', 'Précaution proposée : ne grimpez pas sur les façades et n’empruntez pas de parcours fermé. Demandez l’état du sol et les conditions d’accès avant de payer.', '防范建议：不要攀爬墓葬立面或进入封闭路线。付款前询问运营方路面和无障碍条件；不同体验的适用性不同。', 'सावधानी का सुझाव: कब्रों के मुखभाग पर न चढ़ें और बंद रास्तों पर न जाएँ। भुगतान से पहले सतह और पहुँच की स्थिति पूछें; हर अनुभव की उपयुक्तता अलग है।'], ['east-alula-hegra']),
      section('visit', ['للمبتدئ نقترح جزءاً قصيراً من مسارات الواحة العامة. احجز الزيارات المنظمة من القناة الرسمية، وأكّد المرشد وشروط الدخول بدلاً من افتراض دخول كل موقع بحرية.', 'For beginners, we suggest a short section of the oasis public paths. Book organised visits officially and confirm guide and entry arrangements rather than assuming unrestricted access.', 'Débutants : choisissez une courte portion des chemins publics de l’oasis. Réservez officiellement les visites organisées et confirmez guide et accès, sans présumer une entrée libre partout.', '初学者可选绿洲公共步道的一小段。通过官方渠道预订组织游览并确认导游和入场安排，不要默认各处可自由进入。', 'शुरुआती यात्रियों के लिए नखलिस्तान के सार्वजनिक रास्ते का छोटा भाग सुझाते हैं। आयोजित भ्रमण आधिकारिक माध्यम से बुक करें और गाइड व प्रवेश की पुष्टि करें; हर स्थान पर खुला प्रवेश न मानें।'], ['east-alula-oasis', 'east-alula-plan']),
    ],
    species: [{ id: 'alula-date-palm', coverage: 'local', name: ['نخيل التمر', 'Date palms', 'Palmiers dattiers', '海枣树', 'खजूर के पेड़'], description: ['يوثق المصدر نخيل الواحة ودوره في تظليل الزراعة تحته؛ هذا وصف عام وليس مفتاحاً لتحديد الصنف.', 'The source documents oasis palms shading crops below; this overview does not identify cultivars.', 'La source décrit des palmiers ombrageant les cultures ; ce résumé ne permet pas d’identifier les cultivars.', '资料记录绿洲棕榈为下层作物遮阴；此概述不能鉴定栽培品种。', 'स्रोत नखलिस्तान के खजूरों द्वारा नीचे की फसल को छाया देने का वर्णन करता है; यह किस्मों की पहचान नहीं है।'], precaution: ['لا تتسلق أو تجمع الثمار دون إذن؛ اشترِ المنتجات من جهة معروفة.', 'Do not climb or collect fruit without permission; buy produce from a known seller.', 'Ne grimpez pas et ne récoltez pas sans autorisation ; achetez auprès d’un vendeur identifié.', '未经许可不要攀爬或采果；从可靠商家购买农产品。', 'बिना अनुमति न चढ़ें, न फल तोड़ें; परिचित विक्रेता से उपज खरीदें।'], sourceIds: ['east-alula-oasis'] }],
  },
  {
    id: 'jebel-jais', terrainId: 'mountain', terrainIndex: 1, lat: 25.954, lon: 56.151, timezone: 'Asia/Dubai',
    names: ['جبل جيس', 'Jebel Jais', 'Jebel Jais', '杰贝勒贾伊斯山', 'जेबेल जैस'],
    summary: ['جبال صخرية في رأس الخيمة؛ اختر بين منصة مشاهدة ومسار مشي مفتوح يناسب خبرتك.', 'Rocky mountains in Ras Al Khaimah: choose a viewing deck or an open walking route suited to your experience.', 'Montagnes rocheuses de Ras Al Khaimah : belvédère ou sentier ouvert adapté à votre expérience.', '哈伊马角的岩石山地；可选择观景平台或符合自身经验的开放步道。', 'रास अल खैमाह के पथरीले पहाड़; अपनी क्षमता के अनुसार व्यूइंग डेक या खुला पैदल मार्ग चुनें।'],
    image: '/images/mountain.jpg', imageIsIllustrative: true, sourceIds: ['east-jais-visit', 'east-jais-hiking', 'east-jais-nature'],
    sections: [
      section('place', ['منطقة جبلية من سلسلة الحجر، وليست صحراء رملية. المؤشر تقريبي وليس بداية مسار أو تصريح وصول للقمة؛ الصورة توضيحية.', 'A Hajar mountain area, not a sand desert. The approximate marker is neither a trailhead nor permission to access a summit; the image is illustrative.', 'Secteur montagneux du Hajar, pas un désert de sable. Le repère n’est ni départ de sentier ni autorisation d’accès au sommet ; image illustrative.', '这里属于哈杰尔山地，并非沙漠沙丘。近似标记既不是步道起点，也不表示可进入山顶；图片为示意。', 'यह हजर का पर्वतीय क्षेत्र है, रेत का रेगिस्तान नहीं। अनुमानित चिह्न न पगडंडी का प्रवेश है, न शिखर पर जाने की अनुमति; चित्र उदाहरणात्मक है।'], ['east-jais-visit']),
      section('equipment', ['المصدر يوصي بالاستعداد للمشي. استنتاج عملي: احفظ المسار المعتمد وخطة العودة دون إنترنت؛ الهاتف وحده لا يثبت أن المسار مفتوح.', 'The operator advises walking preparation. Practical inference: save the approved route and return plan offline; a phone map alone does not establish that a route is open.', 'L’opérateur conseille de préparer la marche. Conservez parcours autorisé et retour hors ligne ; une carte sur téléphone ne prouve pas qu’un sentier est ouvert.', '运营方建议做好步行准备。实用推断：离线保存认可路线和返回计划；手机地图不能证明路线开放。', 'संचालक पैदल यात्रा की तैयारी की सलाह देता है। स्वीकृत रास्ता और वापसी की योजना ऑफलाइन रखें; फोन का नक्शा रास्ता खुला होने का प्रमाण नहीं है।'], ['east-jais-hiking']),
      section('clothing', ['أحذية ثابتة للمشي موصى بها محلياً. استنتاج عملي: أضف طبقة للرياح والبرد حسب الارتفاع والتوقعات، حتى إن كان الطقس دافئاً في المدينة.', 'Stable walking footwear is locally recommended. Practical inference: add a wind/cold layer for altitude and forecast, even when the city is warm.', 'Des chaussures stables sont recommandées localement. Prévoyez une couche contre vent et froid selon altitude et météo, même si la ville est chaude.', '当地建议穿稳定的步行鞋。实用推断：根据海拔和预报准备防风保暖层，即使城区温暖也应核对。', 'स्थानीय सलाह स्थिर पकड़ वाले जूते है। ऊँचाई और पूर्वानुमान के अनुसार हवा व ठंड से बचने की परत रखें, भले शहर गर्म हो।'], ['east-jais-visit']),
      section('transport', ['تذكر الصفحة الرسمية السيارة والأجرة والنقل الخاص. اقتراح: رتّب رحلة العودة قبل الصعود وتأكد من الوقود؛ لا تفترض توفر سيارة أجرة عند كل نقطة.', 'Official options include car, taxi and private transfers. Suggestion: arrange the return before ascending and check fuel; do not assume taxis wait at every stop.', 'Les options officielles comprennent voiture, taxi et transfert privé. Prévoyez le retour et vérifiez le carburant ; ne supposez pas un taxi disponible à chaque arrêt.', '官方交通选项包括汽车、出租车和私人接送。建议上山前安排返程并核对油量，不要默认各站点都有出租车。', 'आधिकारिक विकल्पों में कार, टैक्सी और निजी ट्रांसफर हैं। चढ़ने से पहले वापसी और ईंधन तय करें; हर पड़ाव पर टैक्सी मिलने की उम्मीद न करें।'], ['east-jais-transport', 'east-jais-visit']),
      section('season', ['يُذكر أكتوبر إلى أبريل لموسم المشي. هذه نافذة تخطيط وليست ضماناً: راجع الطقس والإغلاق يوم الزيارة، وتجنب مشياً مكشوفاً في حرارة غير مناسبة.', 'October–April is listed for hiking. This is a planning window, not a guarantee: check weather and closures on the day and avoid exposed walks in unsuitable heat.', 'Octobre à avril est indiqué pour la randonnée. Ce créneau ne garantit rien : vérifiez météo et fermetures le jour même et évitez une chaleur inadaptée.', '资料列出10月至4月为徒步季。这只是规划时段，不是保证；当天核对天气与封闭信息，避免不适宜高温下的无遮蔽徒步。', 'पैदल यात्रा का मौसम अक्टूबर–अप्रैल बताया गया है। यह योजना की अवधि है, गारंटी नहीं; उसी दिन मौसम और बंद मार्ग जाँचें तथा अनुपयुक्त गर्मी में खुली चढ़ाई से बचें।'], ['east-jais-hiking']),
      section('nature', ['القائمة أدناه أمثلة موثقة وليست حصراً للأنواع أو وسيلة تعرف ميدانية. اقتراح: استخدم منظاراً إن توفر، وابتعد عن الأعشاش ولا تطعم الحيوانات.', 'Entries below are documented examples, not a complete inventory or field identification key. Suggested practice: use binoculars if available, avoid nests and do not feed wildlife.', 'Les exemples documentés ci-dessous ne forment ni inventaire complet ni clé d’identification. Utilisez des jumelles si disponibles, évitez les nids et ne nourrissez pas la faune.', '以下是有记录的示例，并非完整名录或野外鉴定工具。建议有条件时用望远镜观察，远离巢穴，不投喂野生动物。', 'नीचे के उदाहरण दर्ज हैं, पूरी सूची या मैदानी पहचान की कुंजी नहीं। उपलब्ध हो तो दूरबीन लें, घोंसलों से दूर रहें और वन्यजीवों को न खिलाएँ।'], ['east-jais-nature']),
      section('hazard', ['بعض المسارات المعلنة ما زالت قيد التطوير؛ لا تختَرها كمسارات مفتوحة. استنتاج وقائي: لا تعبر الحواجز ولا تقترب من الحواف لالتقاط صورة.', 'Some promoted routes remain in development; do not treat them as open trails. Precautionary inference: do not cross barriers or approach cliff edges for photographs.', 'Certains itinéraires annoncés sont encore en développement : ne les considérez pas ouverts. Ne franchissez pas les barrières et ne vous approchez pas du vide pour une photo.', '部分公布路线仍在建设中，不应视为开放步道。防范建议：不要跨越障碍，也不要为拍照靠近崖边。', 'कुछ प्रचारित मार्ग अभी विकासाधीन हैं; उन्हें खुला न मानें। सावधानी: अवरोध पार न करें और फोटो के लिए चट्टान के किनारे न जाएँ।'], ['east-jais-hiking']),
      section('visit', ['للمبتدئ نقترح منصة المشاهدة أو مشياً قصيراً مع مرشد. تحقق من المسار المفتوح، واحجز الأنشطة المنظمة وافحص شروط المشاركة؛ المرشد ليس مطلوباً لكل مسار عام.', 'For beginners, we suggest the viewing deck or a short guided walk. Confirm open routes and book operated activities with eligibility checks; not every public trail requires a guide.', 'Débutants : belvédère ou courte marche guidée. Vérifiez les sentiers ouverts et réservez les activités encadrées selon leurs critères ; tous les sentiers publics n’exigent pas de guide.', '初学者可选观景台或短程向导徒步。确认开放路线，预约运营活动并核对参加条件；并非每条公共步道都强制向导。', 'शुरुआती यात्रियों के लिए व्यूइंग डेक या गाइड के साथ छोटी सैर सुझाते हैं। खुला मार्ग और गतिविधि की पात्रता जाँचकर बुक करें; हर सार्वजनिक पगडंडी पर गाइड अनिवार्य नहीं है।'], ['east-jais-visit', 'east-jais-hiking']),
    ],
    species: [
      { id: 'jais-sidr', coverage: 'local', name: ['السدر', 'Sidr tree', 'Jujubier épine-du-Christ', '基督刺枣', 'सिद्र वृक्ष'], description: ['يذكر المصدر Ziziphus spina-christi ودعمه للنحل. الاسم لا يكفي للتعرف على شجرة بعينها.', 'The source lists Ziziphus spina-christi and its support for bees. A name alone cannot identify an individual tree.', 'La source cite Ziziphus spina-christi et son rôle pour les abeilles. Le nom ne suffit pas à identifier un arbre.', '资料列出Ziziphus spina-christi及其对蜜蜂的作用。仅凭名称不能鉴定一棵树。', 'स्रोत Ziziphus spina-christi और मधुमक्खियों के लिए इसकी उपयोगिता बताता है। केवल नाम से किसी पेड़ की पहचान नहीं होती।'], precaution: ['راقب دون قطف؛ لا تستخدمه علاجاً اعتماداً على هذا الملخص.', 'Observe without harvesting; do not use it medicinally based on this overview.', 'Observez sans récolter ; n’en faites pas un remède sur la base de ce résumé.', '只观察不采集，不要依据此概述将其用于治疗。', 'बिना तोड़े देखें; इस संक्षिप्त विवरण के आधार पर औषधीय उपयोग न करें।'], sourceIds: ['east-jais-nature'] },
      { id: 'jais-chukar', coverage: 'local', name: ['حجل الشوكار', 'Chukar partridge', 'Perdrix choukar', '石鸡', 'चुकोर तीतर'], description: ['يوثق المصدر Alectoris chukar قرب الحواف الصخرية؛ وجوده غير مضمون وهذه ليست أداة للتعرف.', 'The source records Alectoris chukar on rocky ridges; sightings are not guaranteed and this is not an identification tool.', 'La source mentionne Alectoris chukar sur les crêtes rocheuses ; observation non garantie, sans outil d’identification.', '资料记录Alectoris chukar出现在岩脊；不保证目击，此处也不是鉴定工具。', 'स्रोत चट्टानी धारों पर Alectoris chukar बताता है; दिखना निश्चित नहीं और यह पहचान उपकरण नहीं है।'], precaution: ['اترك له مسافة ولا تتبعه خارج المسار أو قرب الأعشاش.', 'Keep your distance; do not follow it off trail or toward nests.', 'Gardez vos distances ; ne le suivez pas hors sentier ni vers les nids.', '保持距离，不要离开步道追随或接近巢穴。', 'दूरी रखें; रास्ते से हटकर या घोंसले तक उसका पीछा न करें।'], sourceIds: ['east-jais-nature'] },
    ],
  },
  {
    id: 'wadi-shab', terrainId: 'mountain', terrainIndex: 1, lat: 22.833, lon: 59.245, timezone: 'Asia/Muscat',
    names: ['وادي شاب', 'Wadi Shab', 'Wadi Shab', '沙布溪谷', 'वाडी शाब'],
    summary: ['وادي عُماني بين جروف جيرية وبرك؛ المشي والعبور والسباحة أنشطة مختلفة تحتاج اختياراً واعياً.', 'An Omani wadi with limestone cliffs and pools: walking, crossing and swimming require separate decisions.', 'Wadi omanais aux falaises calcaires et bassins : marche, traversée et nage demandent des choix distincts.', '阿曼的石灰岩峭壁与水潭溪谷；步行、渡水和游泳需要分别评估。', 'चूना-पत्थर की चट्टानों और कुंडों वाला ओमानी वाडी; पैदल चलने, पार करने और तैरने के फैसले अलग हैं।'],
    image: '/images/mountain.jpg', imageIsIllustrative: true, sourceIds: ['east-shab-visit', 'east-oman-outdoors'], species: [],
    sections: [
      section('place', ['يقع في جنوب الشرقية؛ هو وادٍ صخري مائي وليس شاطئاً. المؤشر تقريبي وليس مدخلاً معتمداً أو مساراً؛ الصورة توضيحية.', 'In South Al Sharqiyah, this is a rocky watercourse, not a beach. The approximate marker is not a verified entrance or route; the image is illustrative.', 'Dans le gouvernorat d’Ach-Charqiya du Sud, c’est un cours d’eau rocheux, pas une plage. Repère approximatif, sans entrée ni parcours vérifiés ; image illustrative.', '位于南沙尔基亚省，是岩石水道而非海滩。近似标记不是已核实入口或路线；图片为示意。', 'दक्षिण अश शरकियाह में यह पथरीला जलमार्ग है, समुद्र तट नहीं। अनुमानित चिह्न प्रमाणित प्रवेश या रास्ता नहीं है; चित्र उदाहरणात्मक है।'], ['east-shab-visit']),
      section('equipment', ['استنتاج عملي: خطط للماء والطعام والعودة، واحمِ الهاتف والتذاكر من البلل. سترة النجاة لا تحول مسار السباحة إلى نشاط يناسب الجميع.', 'Practical inference: plan water, food and return, and protect your phone and tickets from water. A life jacket does not make a swimming route suitable for everyone.', 'Conseil pratique : prévoyez eau, nourriture et retour, protégez téléphone et billets de l’eau. Un gilet ne rend pas un parcours de nage adapté à tous.', '实用推断：规划饮水、食物与返程，保护手机和票据防水。救生衣并不使游泳路线适合所有人。', 'व्यावहारिक सुझाव: पानी, भोजन और वापसी तय करें; फोन और टिकट पानी से बचाएँ। जीवन जैकेट होने से तैराकी का रास्ता सबके लिए उपयुक्त नहीं हो जाता।'], ['east-oman-outdoors', 'east-shab-visit']),
      section('clothing', ['توصي الصفحة المحلية بأحذية للمشي أو صنادل مناسبة للماء، لا شباشب رخوة. اقتراحنا: جرّب الثبات والملاءمة واحمل ملابس جافة إذا اخترت السباحة.', 'Local guidance recommends walking shoes or water-suitable sandals, not loose flip-flops. Our suggestion: check grip and fit, with dry clothes if you choose swimming.', 'Le guide local conseille chaussures de marche ou sandales adaptées à l’eau, pas de tongs. Vérifiez adhérence et maintien, et prévoyez du sec si vous nagez.', '当地建议穿步行鞋或适合涉水的凉鞋，不穿松脱的人字拖。建议检查抓地与贴合度，若游泳则备干衣。', 'स्थानीय मार्गदर्शन पैदल चलने के जूते या पानी के अनुकूल सैंडल सुझाता है, ढीली चप्पल नहीं। पकड़ और फिट जाँचें; तैरना चुनें तो सूखे कपड़े रखें।'], ['east-shab-visit']),
      section('transport', ['الدخول المعتاد يتضمن عبوراً قصيراً بالقارب. اقتراح عملي: أكّد تشغيل القارب وموعد العودة والتكلفة محلياً قبل مواصلة المشي.', 'Usual access includes a short boat crossing. Practical suggestion: confirm operation, return time and cost locally before continuing on foot.', 'L’accès habituel comprend une courte traversée en bateau. Confirmez sur place fonctionnement, retour et tarif avant de poursuivre à pied.', '通常需短程乘船渡过入口水道。建议开始步行前在当地确认开航、返程时间和费用。', 'सामान्य प्रवेश में छोटी नाव-पार यात्रा है। पैदल आगे बढ़ने से पहले संचालन, वापसी के समय और शुल्क की स्थानीय पुष्टि करें।'], ['east-shab-visit']),
      section('season', ['تعرض السياحة العُمانية سبتمبر إلى مايو للزيارة. استنتاجنا: لا يكفي الشهر؛ راجع المطر وحالة الوادي يومها، بما في ذلك الأمطار أعلى المجرى.', 'Oman tourism lists September–May for visits. Our inference: the month is insufficient; check rain and wadi conditions that day, including upstream rainfall.', 'Le tourisme omanais indique septembre à mai. Le mois ne suffit pas : vérifiez pluies et état du wadi le jour même, y compris en amont.', '阿曼旅游资料列出9月至5月适合到访。我们的判断：月份不足以决定，当天还须核对溪谷及上游降雨条件。', 'ओमान पर्यटन सितंबर–मई की अवधि बताता है। हमारा निष्कर्ष: केवल महीना पर्याप्त नहीं; उस दिन वाडी और ऊपरी जलग्रहण में बारिश की स्थिति जाँचें।'], ['east-shab-visit', 'east-oman-outdoors']),
      section('nature', ['لا تقدم المصادر المختارة تعريفاً دقيقاً لأنواع يمكن تمييزها هنا، لذلك لم نضف قائمة تخمينية. لا تشرب ماء البرك أو تجمع النباتات اعتماداً على مظهرها.', 'The selected sources do not identify species precisely enough for this guide, so no speculative list is added. Do not drink pool water or gather plants based on appearance.', 'Les sources retenues ne permettent pas une identification précise : aucune liste supposée n’est ajoutée. Ne buvez pas l’eau des bassins et ne cueillez pas à partir de l’apparence.', '所选资料不足以精确识别本地物种，因此不添加推测名单。不要凭外观判断水潭可饮用或植物可采食。', 'चुने स्रोत यहाँ प्रजातियों की पर्याप्त सटीक पहचान नहीं देते, इसलिए अनुमानित सूची नहीं है। दिखावट के आधार पर कुंड का पानी न पिएँ या पौधे न चुनें।'], ['east-shab-visit']),
      section('hazard', ['يحذر الدليل العُماني من التخييم في مجاري الأودية بسبب السيول. تطبيق عملي: لا تدخل عند تحذير أو تغير الماء؛ ألغِ الزيارة بدل عبور تيار مجهول.', 'Oman’s guide warns against camping in wadi beds because of flash floods. Practical application: do not enter during warnings or changing water; cancel rather than cross an unknown current.', 'Le guide omanais déconseille le camping dans les lits de wadis à cause des crues soudaines. En cas d’alerte ou de changement de l’eau, renoncez au lieu de traverser un courant inconnu.', '阿曼指南警告山洪风险，勿在溪谷河床露营。实际应用：有警报或水情变化时不要进入；宁可取消，也不要穿越不明水流。', 'ओमान का गाइड अचानक बाढ़ के कारण वाडी तल में शिविर से मना करता है। चेतावनी या पानी बदलने पर प्रवेश न करें; अनजान बहाव पार करने के बजाय यात्रा रद्द करें।'], ['east-oman-outdoors']),
      section('visit', ['الكهف يتطلب سباحة وليس جزءاً إلزامياً من الزيارة. للمبتدئ نقترح مشياً قصيراً مع مرشد ونقطة رجوع محددة؛ أكّد الظروف والحجز، ولا تواصل للماء إن لم تناسبك السباحة.', 'The cave requires swimming and is optional. For beginners, we suggest a short guided walk with an agreed turnaround; confirm conditions and booking, and skip the water if swimming is unsuitable.', 'La grotte nécessite de nager et reste facultative. Débutants : courte marche guidée avec demi-tour convenu ; confirmez conditions et réservation, sans entrer dans l’eau si la nage ne vous convient pas.', '洞穴需游泳进入，属于可选活动。初学者可选约定折返点的短程向导步行；确认条件与预约，不适合游泳就不要继续进入水域。', 'गुफा के लिए तैरना जरूरी है और जाना वैकल्पिक है। शुरुआती यात्रियों के लिए गाइड संग छोटी सैर और तय वापसी-बिंदु सुझाते हैं; स्थिति और बुकिंग पूछें, तैरना उपयुक्त न हो तो पानी में न जाएँ।'], ['east-shab-visit']),
    ],
  },
  {
    id: 'jubail-mangrove', terrainId: 'coast', terrainIndex: 3, lat: 24.543, lon: 54.485, timezone: 'Asia/Dubai',
    names: ['منتزه قرم الجبيل', 'Jubail Mangrove Park', 'Parc des mangroves de Jubail', '朱拜勒红树林公园', 'जुबैल मैंग्रोव पार्क'],
    summary: ['غابة قرم مدّية في أبوظبي؛ زيارة على الممر الخشبي أو تجديف محجوز، وليست منطقة سباحة.', 'Abu Dhabi’s tidal mangroves: boardwalk visits or booked kayaking, not a swimming destination.', 'Mangrove soumise aux marées à Abou Dhabi : promenade ou kayak réservé, sans baignade.', '阿布扎比的潮汐红树林：可走栈道或预约皮划艇，不是游泳地点。', 'अबू धाबी का ज्वारीय मैंग्रोव: बोर्डवॉक या बुक किया कयाक भ्रमण, तैराकी का स्थान नहीं।'],
    image: '/images/coast.jpg', imageIsIllustrative: true, sourceIds: ['east-jubail-visit', 'east-jubail-island', 'east-jubail-rules'],
    sections: [
      section('place', ['هذا موطن ساحلي يتأثر بالمد، وليس غابة برية للمشي الحر. المؤشر تقريبي للمنتزه وليس رصيف انطلاق؛ الصورة توضيحية وليست صورة الجبيل.', 'This is tidal coastal habitat, not woodland for unrestricted walking. The marker approximates the park, not a launch point; the image illustrates terrain, not Jubail itself.', 'Habitat côtier soumis aux marées, pas une forêt en accès libre. Repère approximatif du parc, pas un embarcadère ; l’image illustre le terrain, pas Jubail.', '这是受潮汐影响的沿海生境，并非可随意穿行的林地。标记仅示公园大致位置，不是下水点；图片仅示地形，并非朱拜勒实景。', 'यह ज्वारीय तटीय आवास है, खुला घूमने वाला जंगल नहीं। चिह्न पार्क का अनुमानित स्थान है, नाव उतारने का बिंदु नहीं; चित्र भूभाग का उदाहरण है, जुबैल का नहीं।'], ['east-jubail-island']),
      section('equipment', ['تذكر جولة الكاياك الرسمية توفير سترات نجاة ووجوب ارتدائها. استنتاج عملي: أكّد المقاس والمعدات المشمولة قبل شراء بدائل، ولا تفترض أنها تكفي لكل نشاط.', 'The official kayak tour supplies life jackets and requires wearing them. Practical inference: confirm fit and included equipment before buying alternatives; do not assume suitability for every activity.', 'La sortie officielle fournit un gilet et impose son port. Vérifiez taille et matériel inclus avant d’acheter une alternative ; ne présumez pas sa convenance pour toute activité.', '官方皮划艇行程提供救生衣并要求穿戴。实用建议：购买替代装备前确认尺码与所含用品，不要默认适合所有活动。', 'आधिकारिक कयाक भ्रमण जीवन जैकेट देता है और पहनना अनिवार्य करता है। विकल्प खरीदने से पहले फिट और शामिल सामान पूछें; हर गतिविधि के लिए उपयुक्तता न मानें।'], ['east-jubail-kayak']),
      section('clothing', ['المشغّل يطلب ملابس إضافية للتجديف. اقتراح عملي: ملابس للحركة وحماية من الشمس وحذاء ثابت للممر؛ احترم تعليمات المكان عند تغيير الملابس.', 'The kayak operator asks for spare clothes. Practical suggestion: movement-friendly clothing, sun protection and stable boardwalk footwear; follow site rules when changing.', 'L’opérateur demande des vêtements de rechange pour le kayak. Prévoyez tenue mobile, protection solaire et chaussures stables ; respectez les consignes pour vous changer.', '皮划艇运营方要求带备用衣物。实用建议：便于活动的衣物、防晒及稳固栈道鞋履；更衣时遵守场地规定。', 'कयाक संचालक अतिरिक्त कपड़े लाने को कहता है। आराम से चलने वाले कपड़े, धूप से सुरक्षा और बोर्डवॉक पर स्थिर जूते रखें; कपड़े बदलने के स्थानीय नियम मानें।'], ['east-jubail-kayak']),
      section('transport', ['تذكر جهة السياحة الوصول بالسيارة أو الأجرة إلى الجزيرة. اقتراح: رتّب العودة من المنتزه وتحقق من مدخل الحجز؛ لا تستخدم الممرات المائية كطرق عبور مستقلة.', 'Tourism guidance describes car or taxi access to the island. Suggestion: arrange the return and check the booked entrance; waterways are not independent crossing routes.', 'Le guide touristique indique l’accès à l’île en voiture ou taxi. Prévoyez le retour et vérifiez l’entrée réservée ; les chenaux ne sont pas des passages autonomes.', '旅游资料说明可驾车或乘出租车到岛。建议安排返程并核对预订入口，不把水道当作自行穿越的路线。', 'पर्यटन मार्गदर्शन कार या टैक्सी से द्वीप पहुँच बताता है। वापसी और बुक किए प्रवेश की पुष्टि करें; जलमार्ग को स्वयं पार करने का रास्ता न समझें।'], ['east-jubail-island']),
      section('season', ['يغيّر المد المشهد ومستوى الماء. استنتاج تخطيطي: أكّد موعد التجديف مع المشغّل وفق المد والطقس، واختر وقتاً يناسب قدرتك على تحمل الحر.', 'Tides change the landscape and water level. Planning inference: confirm kayaking time with the operator for tide and weather, and choose conditions within your heat tolerance.', 'La marée modifie paysage et niveau d’eau. Confirmez l’horaire de kayak selon marée et météo ; choisissez des conditions de chaleur que vous supportez.', '潮汐会改变景观和水位。规划建议：与运营方按潮汐和天气确认划艇时间，并选择自己能够承受的气温条件。', 'ज्वार से दृश्य और पानी का स्तर बदलता है। ज्वार व मौसम के अनुसार संचालक से कयाक का समय पक्का करें; गर्मी की सहनशीलता के अनुसार समय चुनें।'], ['east-jubail-island']),
      section('nature', ['تؤكد جهة السياحة دور القرم في حماية الساحل وإيواء الكائنات. ملخصنا لا يحدد كل الأنواع؛ الأفضل مراقبتها من الممر دون لمس أو إطعام.', 'Tourism sources describe mangroves supporting habitat and coastal protection. This overview does not identify every species; observe from the walkway without touching or feeding.', 'Les sources décrivent l’habitat et la protection côtière assurés par les mangroves. Ce résumé n’identifie pas toutes les espèces ; observez sans toucher ni nourrir.', '旅游资料说明红树林提供生境并保护海岸。本概述不鉴定所有物种；请从栈道观察，不触碰、不投喂。', 'पर्यटन स्रोत मैंग्रोव को जीवों का आवास और तट की सुरक्षा बताते हैं। यह सभी प्रजातियों की पहचान नहीं है; रास्ते से देखें, न छुएँ न खिलाएँ।'], ['east-jubail-visit']),
      section('hazard', ['تمنع قواعد المنتزه السباحة والطعام والمشروبات على الممر الخشبي. خطط للشرب في الأماكن المسموحة واسأل الموظفين؛ لا تتجاوز الدرابزين أو تنزل للطين.', 'Park rules prohibit swimming, food and beverages on the boardwalk. Plan drinking in permitted areas and ask staff; do not cross railings or step into mud.', 'Le règlement interdit baignade, nourriture et boissons sur la passerelle. Prévoyez de boire dans les zones autorisées ; ne franchissez pas les garde-corps et restez hors de la vase.', '公园规定禁止游泳及在栈道上饮食。请询问员工并在许可区域补水，不翻栏杆或进入淤泥。', 'पार्क के नियम तैरने तथा बोर्डवॉक पर भोजन और पेय को रोकते हैं। अनुमत जगह पर पानी पीने की योजना बनाएँ और कर्मचारियों से पूछें; रेलिंग पार या कीचड़ में न जाएँ।'], ['east-jubail-rules']),
      section('visit', ['للمبتدئ نقترح الممر الخشبي أو جولة مع مرشد. احجز التجديف مسبقاً وتحقق من شروط المشاركة الحالية؛ صلاحية الحجز لا تضمن ملاءمة الحالة الجوية.', 'For beginners, we suggest the boardwalk or a ranger walk. Book kayaking ahead and check current participation conditions; a booking does not guarantee suitable weather.', 'Débutants : passerelle ou promenade avec un guide du parc. Réservez le kayak et vérifiez les conditions de participation ; une réservation ne garantit pas la météo.', '初学者可选栈道或护林员导览。提前预约皮划艇并核对当前参加条件；有预订不保证天气适宜。', 'शुरुआती यात्रियों के लिए बोर्डवॉक या रेंजर संग सैर सुझाते हैं। कयाक पहले बुक करें और वर्तमान भागीदारी शर्तें जाँचें; बुकिंग मौसम की उपयुक्तता की गारंटी नहीं है।'], ['east-jubail-boardwalk', 'east-jubail-activities', 'east-jubail-island']),
    ],
    species: [{ id: 'jubail-mangrove-trees', coverage: 'local', name: ['أشجار القرم — تعريف عام', 'Mangrove trees — broad identification', 'Mangroves — identification générale', '红树林树木——概括识别', 'मैंग्रोव वृक्ष — सामान्य पहचान'], description: ['القرم موثق في المنتزه؛ المصدر المختار لا يثبت النوع العلمي، فلا ننسب إليه اسماً تخمينياً.', 'Mangroves are documented in the park; the selected source does not establish the scientific species, so none is guessed.', 'Les mangroves sont documentées dans le parc ; la source retenue ne précise pas l’espèce scientifique, sans supposition ici.', '公园有红树林记录，但所选资料未确定科学物种名，因此不作猜测。', 'पार्क में मैंग्रोव दर्ज हैं; चुना स्रोत वैज्ञानिक प्रजाति तय नहीं करता, इसलिए कोई अनुमानित नाम नहीं दिया गया।'], precaution: ['اترك الجذور والنباتات كما هي؛ استخدم الممر ولا تجمع أجزاءً منها.', 'Leave roots and plants undisturbed; stay on the walkway and do not collect parts.', 'Préservez racines et plantes ; restez sur la passerelle sans prélèvement.', '不扰动根部和植株，留在栈道上，不采集其部分。', 'जड़ों और पौधों को न छेड़ें; बोर्डवॉक पर रहें और कोई भाग न तोड़ें।'], sourceIds: ['east-jubail-visit', 'east-jubail-rules'] }],
  },
];

// Counts are editable planning defaults, not safety standards or water dosages.
// Shared equipment IDs let the packing engine deduplicate across catalog rules.
const sunHat: Localized = ['قبعة للحماية من الشمس', 'Sun hat', 'Chapeau de soleil', '遮阳帽', 'धूप की टोपी'];
const warmLayer: Localized = ['طبقة إضافية تناسب التوقعات', 'Extra layer suited to the forecast', 'Couche adaptée aux prévisions', '适合预报的备用衣层', 'पूर्वानुमान के अनुसार अतिरिक्त परत'];
const walkingShoes: Localized = ['حذاء مشي ثابت', 'Stable walking footwear', 'Chaussures de marche stables', '稳固的步行鞋', 'स्थिर पकड़ वाले पैदल जूते'];
const lifeJacket: Localized = ['سترة نجاة مناسبة ومضبوطة', 'Suitable, fitted life jacket', 'Gilet adapté et ajusté', '适用且合身的救生衣', 'उपयुक्त और सही फिट की जीवन जैकेट'];
const adjustable: Localized = [' الكمية نقطة بداية قابلة للتعديل وليست معيار سلامة.', ' The quantity is an editable starting point, not a safety standard.', ' La quantité est un point de départ modifiable, pas une norme de sécurité.', '数量是可调整的起点，并非安全标准。', ' मात्रा बदलने योग्य शुरुआती सुझाव है, सुरक्षा मानक नहीं।'];
function packingRule(id: string, destinationId: string, terrainId: Destination['terrainId'], equipmentId: string, label: Localized, reason: Localized, sourceIds: string[], coverage: PackingRule['coverage'], activities: string[] = []): PackingRule {
  return { id, version: 1, equipmentId, label, category: 'equipment', terrainIds: [terrainId], activities, months: [], minDays: 0, transport: [], baseQuantity: 1, perPerson: true, reason: reason.map((text, index) => text + adjustable[index]) as Localized, sourceIds, coverage, destinationIds: [destinationId] };
}
export const eastRules: PackingRule[] = [
  packingRule('east-rum-sun', 'wadi-rum', 'desert', 'sun-hat', sunHat,
    ['تطبيق عام للحماية من الشمس في الصحراء، وليس اشتراطاً محلياً.', 'General sun-protection advice applied to the desert, not a local requirement.', 'Conseil général de protection solaire appliqué au désert, sans obligation locale.', '将一般防晒建议用于沙漠，并非当地规定。', 'रेगिस्तान के लिए सामान्य धूप-सुरक्षा सलाह है, स्थानीय अनिवार्यता नहीं।'], ['east-outdoor-essentials'], 'terrain-example'),
  packingRule('east-rum-layer', 'wadi-rum', 'desert', 'extra-layer', warmLayer,
    ['اقتراح عام لتغير الطقس؛ اختر الطبقة وفق توقعات وقت الخروج.', 'General preparation for weather changes; choose the layer for your outing’s forecast.', 'Préparation générale aux changements météo ; choisissez la couche selon les prévisions.', '为天气变化作一般准备；按出行预报选择衣层。', 'मौसम बदलने की सामान्य तैयारी; यात्रा के पूर्वानुमान से परत चुनें।'], ['east-outdoor-essentials'], 'terrain-example'),
  packingRule('east-alula-shoes', 'alula', 'desert', 'walking-shoes', walkingShoes,
    ['توصية جولة الحِجر بحذاء مغلق؛ اختر ملاءمة وثباتاً يناسبانك.', 'Hegra tour guidance recommends closed footwear; choose suitable fit and grip.', 'La visite d’Hégra conseille des chaussures fermées ; choisissez maintien et adhérence.', '黑格拉游览建议包头鞋；请选择合适尺码与抓地性能。', 'हेग्रा भ्रमण बंद जूते सुझाता है; सही फिट और पकड़ चुनें।'], ['east-alula-hegra'], 'local'),
  packingRule('east-alula-sun', 'alula', 'desert', 'sun-hat', sunHat,
    ['الحماية من الشمس ضمن توصيات جولة الحِجر.', 'Sun protection is included in Hegra tour recommendations.', 'La protection solaire figure dans les conseils de la visite d’Hégra.', '黑格拉游览建议包含防晒。', 'हेग्रा भ्रमण की सलाह में धूप से सुरक्षा शामिल है।'], ['east-alula-hegra'], 'local'),
  packingRule('east-jais-shoes', 'jebel-jais', 'mountain', 'walking-shoes', walkingShoes,
    ['المصدر المحلي يوصي بأحذية ثابتة؛ راجع ملاءمتها لمسارك المختار.', 'Local guidance recommends stable footwear; check suitability for your chosen route.', 'Le guide local conseille des chaussures stables ; vérifiez leur adaptation au parcours.', '当地建议稳固鞋履；请核对是否适合所选路线。', 'स्थानीय सलाह स्थिर जूते है; चुने मार्ग के लिए उपयुक्तता जाँचें।'], ['east-jais-visit'], 'local'),
  packingRule('east-jais-layer', 'jebel-jais', 'mountain', 'extra-layer', warmLayer,
    ['استنتاج عملي للجبال المكشوفة: راجع حماية الرياح والبرد حسب التوقعات.', 'Practical inference for exposed mountains: review wind and cold protection against the forecast.', 'Déduction pratique en montagne exposée : adaptez la protection contre vent et froid aux prévisions.', '对无遮蔽山地的实用推断：按预报核对防风保暖需求。', 'खुले पहाड़ों के लिए व्यावहारिक अनुमान: पूर्वानुमान से हवा और ठंड की सुरक्षा तय करें।'], ['east-jais-visit'], 'terrain-example'),
  packingRule('east-shab-shoes', 'wadi-shab', 'mountain', 'water-walking-shoes', ['حذاء مشي مناسب للبلل', 'Wet-terrain walking footwear', 'Chaussures de marche adaptées à l’eau', '适合湿地形的步行鞋', 'गीले भूभाग के अनुकूल पैदल जूते'],
    ['الصفحة المحلية توصي بحذاء مناسب للمشي والماء؛ تحقّق من الثبات.', 'Local guidance recommends footwear suited to walking and water; check grip.', 'Le guide local recommande des chaussures adaptées à la marche et à l’eau ; vérifiez l’adhérence.', '当地建议适合步行与涉水的鞋履；请检查抓地性能。', 'स्थानीय सलाह पैदल और पानी के अनुकूल जूते है; पकड़ जाँचें।'], ['east-shab-visit'], 'local'),
  packingRule('east-shab-vest', 'wadi-shab', 'mountain', 'life-jacket', lifeJacket,
    ['عند اختيار السباحة، تنصح الصفحة المحلية بسترة نجاة؛ لا تغني عن القدرة والظروف المناسبة.', 'When swimming is selected, local guidance advises a life jacket; it does not replace ability or suitable conditions.', 'Si vous choisissez de nager, le guide local conseille un gilet ; il ne remplace ni aptitude ni conditions adaptées.', '选择游泳时，当地建议救生衣；它不能代替游泳能力或合适条件。', 'तैराकी चुनने पर स्थानीय सलाह जीवन जैकेट है; यह क्षमता या उचित परिस्थितियों का विकल्प नहीं।'], ['east-shab-visit'], 'local', ['swimming']),
  packingRule('east-jubail-vest', 'jubail-mangrove', 'coast', 'life-jacket', lifeJacket,
    ['للتجديف: المشغّل يوفر السترة ويشترط ارتداءها؛ أكّد المقاس قبل توفير واحدة بنفسك.', 'For kayaking: the operator supplies a mandatory vest; confirm fit before sourcing your own.', 'Pour le kayak : l’opérateur fournit le gilet obligatoire ; confirmez la taille avant d’en prévoir un autre.', '皮划艇：运营方提供且要求穿救生衣；自行准备前先确认尺码。', 'कयाक के लिए संचालक अनिवार्य जैकेट देता है; खुद लेने से पहले फिट की पुष्टि करें।'], ['east-jubail-kayak'], 'local', ['boating']),
  packingRule('east-jubail-change', 'jubail-mangrove', 'coast', 'spare-clothes', ['ملابس جافة إضافية', 'Dry spare clothes', 'Vêtements secs de rechange', '备用干衣', 'अतिरिक्त सूखे कपड़े'],
    ['طلب إحضار ملابس إضافية وارد في شروط التجديف المحلية.', 'Spare clothing is requested in the local kayaking conditions.', 'Les conditions locales de kayak demandent des vêtements de rechange.', '当地皮划艇条件要求携带备用衣物。', 'स्थानीय कयाक शर्तों में अतिरिक्त कपड़े लाने को कहा गया है।'], ['east-jubail-kayak'], 'local', ['boating']),
];

