import { terrains, translate, words, type Locale } from './terrain';
import { catalogDestination,catalogGuidance,catalogSources,seedCatalog } from './catalog-seed';
import { escapeHtml } from './trip-preparation';
import { prepText } from './preparation-copy';
import { releaseText } from './preparation-release-copy';
import { dayDate,itineraryWarnings } from './itinerary';
import type { CatalogSnapshot,Coordinates,Trip } from './toolkit-types';

const style='body{font:18px/1.9 system-ui;max-width:860px;margin:24px auto;padding:24px;color:#183a43;overflow-wrap:anywhere}h1{font-size:2rem}h2{color:#983b1f}img{width:100%;max-height:320px;object-fit:cover;border-radius:12px}a{color:#843719}section,article{break-inside:avoid;margin:28px 0}footer{border-top:1px solid #bbb;margin-top:30px}li{margin:8px 0}small{display:block}p{white-space:pre-wrap}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbc9cd;padding:8px;text-align:start}dl{display:grid;grid-template-columns:1fr 2fr;gap:8px}dd{margin:0}.warning{border-inline-start:3px solid #ad5022;padding-inline-start:12px}@media print{body{margin:0;font-size:12pt}a{color:inherit}img{max-height:200px}}';
function documentHtml(locale:Locale,title:string,body:string){return '<!doctype html><html lang="'+escapeHtml(locale)+'" dir="'+(locale==='ar'?'rtl':'ltr')+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+escapeHtml(title)+' · Daroub</title><style>'+style+'</style></head><body>'+body+'</body></html>'}
function citations(catalog:CatalogSnapshot,ids:string[]){return catalogSources(catalog,ids).map(s=>'<small><a href="'+escapeHtml(s.url)+'">'+escapeHtml(s.title)+'</a> · '+escapeHtml(s.reviewedAt)+'</small>').join('')}
function revision(catalog:CatalogSnapshot,locale:Locale){return '<small>'+escapeHtml(releaseText(locale,'catalogRevision'))+': '+catalog.revision+' · '+escapeHtml(catalog.publishedAt)+'</small>'}
export async function buildGuideHtml({locale,index,point,destinationId,catalog=seedCatalog}:{locale:Locale;index:number;point?:Coordinates;destinationId?:string;catalog?:CatalogSnapshot}){
 const d=catalogDestination(catalog,destinationId),region=terrains[d?.terrainIndex??index]??terrains[0],guidance=catalogGuidance(catalog,(d?.terrainId??region.id) as Trip['terrainId']);const t=(key:string)=>translate(locale,words[key]??[key]),e=escapeHtml,title=d?translate(locale,d.names):point?t('selectedPoint'):translate(locale,region.names),lat=point?.lat??d?.lat??region.lat,lon=point?.lon??d?.lon??region.lon;let image='';
 try{const response=await fetch(d?.image??region.image);if(response.ok){const blob=await response.blob();image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)})}}catch{/* Text chapters remain available when image fetching is unavailable. */}
 const chapters=(d?.sections??guidance.sections).map(section=>'<section><h2>'+e(translate(locale,section.title))+'</h2><p>'+e(translate(locale,section.body))+'</p>'+citations(catalog,section.sourceIds)+'</section>').join('');
 const wildlife=d?'<section><h2>'+e(t('nature'))+'</h2>'+d.species.map(s=>'<article><h3>'+e(translate(locale,s.name))+'</h3><small>'+e(prepText(locale,s.coverage==='local'?'localCoverage':'exampleCoverage'))+'</small><p>'+e(translate(locale,s.description))+'</p><p>'+e(translate(locale,s.precaution))+'</p>'+citations(catalog,s.sourceIds)+'</article>').join('')+'</section>':'';
 const group='<section><h2>'+e(t('group'))+'</h2><p>'+e(translate(locale,guidance.group))+'</p></section>';
 return documentHtml(locale,title,'<h1>'+e(t('book'))+'</h1><h2>'+e(title)+'</h2>'+revision(catalog,locale)+'<p dir="ltr">'+lat.toFixed(3)+', '+lon.toFixed(3)+'</p>'+(image?'<img src="'+e(image)+'" alt="'+e(t('illustration'))+'"><small>'+e(t('illustration'))+'</small>':'')+'<p>'+e(prepText(locale,d?'coverage':'general'))+'</p>'+chapters+wildlife+group+'<footer><p>'+e(t('safety'))+'</p><p>'+e(prepText(locale,'offlineIntro'))+'</p><p>Daroub · '+new Date().toISOString().slice(0,10)+'</p></footer>');
}
export function tripItineraryHtml(trip:Trip,locale:Locale,catalog:CatalogSnapshot=seedCatalog){
 const p=(k:string)=>prepText(locale,k),r=(k:string)=>releaseText(locale,k),e=escapeHtml,d=catalogDestination(catalog,trip.destinationId),warning=itineraryWarnings(trip),sourceIds=d?.sourceIds??catalogGuidance(catalog,trip.terrainId).sections.flatMap(section=>section.sourceIds);
 const detail=(values:string[][])=>'<dl>'+values.map(([label,value])=>'<dt><b>'+e(label)+'</b></dt><dd>'+e(value)+'</dd>').join('')+'</dl>';
 const packing='<section><h2>'+e(p('checklist'))+'</h2><ul>'+trip.checklist.map(row=>'<li>'+e(row.label)+(row.kind==='task'?' · '+(row.done?'☑':'☐'):' · '+e(r('required'))+': '+(row.requiredQuantity??1)+' · '+e(r('assigned'))+': '+(row.assignedQuantity??0)+' · '+e(r('packed'))+': '+(row.packedQuantity??Number(row.done)))+(row.gearSnapshot?'<small>'+e(row.gearSnapshot.name)+' · '+e(r('quantity'))+': '+row.gearSnapshot.quantity+' · '+e(r(row.gearSnapshot.condition))+'</small>':'')+'</li>').join('')+'</ul><p>'+e(r('packingNote'))+'</p></section>';
 const days='<section><h2>'+e(r('itinerary'))+'</h2>'+(trip.itinerary??[]).map(day=>'<article><h3>'+e(r('day'))+' '+(day.dayOffset+1)+' · '+e(dayDate(trip.startDate,day.dayOffset)||r('dateUnknown'))+'</h3>'+warning.filter(w=>w.dayId===day.id).map(w=>'<p class="warning">'+e(r(w.key))+'</p>').join('')+day.entries.map(entry=>'<section><h4>'+e(entry.title)+'</h4>'+detail([[r('activity'),r(entry.activityId)],[r('place'),entry.place],[r('localTime'),entry.startTime],[r('timeZone'),entry.timeZone],[r('duration'),String(entry.durationMinutes)],[p('transport'),entry.transport]])+(entry.coordinates?'<p dir="ltr">'+entry.coordinates.lat+', '+entry.coordinates.lon+'</p>':'')+'<p>'+e(entry.notes)+'</p></section>').join('')+'</article>').join('')+'<p>'+e(r('estimateNote'))+'</p></section>';
 return documentHtml(locale,trip.title,'<h1>'+e(trip.title)+'</h1>'+revision(catalog,locale)+detail([[p('start'),trip.startDate],[p('end'),trip.endDate],[p('group'),String(trip.groupSize)],[p('transport'),trip.transport],[p('destination'),d?translate(locale,d.names):trip.destinationId??p('custom')]])+'<p dir="ltr">'+trip.location.lat+', '+trip.location.lon+'</p><section><h2>'+e(p('notes'))+'</h2><p>'+e(trip.notes)+'</p></section>'+packing+days+'<section><h2>'+e(r('destinationReferences'))+'</h2>'+citations(catalog,sourceIds)+'</section><footer><p>'+e(p('suggestionNote'))+'</p><p>'+e(translate(locale,catalogGuidance(catalog,trip.terrainId).group))+'</p></footer>');
}
