import {translate, type Locale} from './terrain';

// Locale order: Arabic, English, French, Simplified Chinese, Hindi.
export const globeDashboardWords: Record<string, string[]> = {
  explorer: ['مستكشف الأرض', 'Earth explorer', 'Explorer la Terre', '地球探索', 'धरती की खोज'],
  areaView: ['عرض المنطقة', 'Area view', 'Vue de la zone', '区域视图', 'क्षेत्र दृश्य'],
  layerRelief: ['التضاريس', 'Relief', 'Relief', '地形', 'भूभाग'],
  layerImagery: ['صور الأقمار الصناعية', 'Satellite imagery', 'Images satellite', '卫星影像', 'उपग्रह चित्र'],
  layerTopo: ['خريطة المسارات', 'Trail map', 'Carte des sentiers', '路径地图', 'ट्रेल मानचित्र'],
  layerSky: ['السماء أمس', 'Sky yesterday', 'Ciel d’hier', '昨日天空', 'कल का आसमान'],
  layerGoogle: ['Google · قمر صناعي', 'Google satellite', 'Satellite Google', 'Google 卫星', 'Google उपग्रह'],
  layerMapbox: ['Mapbox · قمر صناعي', 'Mapbox satellite', 'Satellite Mapbox', 'Mapbox 卫星', 'Mapbox उपग्रह'],
  openEarth: ['افتح في Google Earth', 'Open in Google Earth', 'Ouvrir dans Google Earth', '在 Google Earth 中打开', 'Google Earth में खोलें'],
  sceneToggle: ['عرض مائل ثلاثي الأبعاد', '3D angled view', 'Vue 3D inclinée', '3D 倾斜视图', '3D तिरछा दृश्य'],
  sceneNote: ['أمثلة تعليمية عن الحياة والأساسيات في هذه التضاريس؛ ليست توثيقاً لوجودها هنا.', 'Educational examples of life and essentials in this terrain, not a record of what is present here.', 'Exemples pédagogiques de la vie et des essentiels de ce milieu, sans preuve de présence ici.', '此类地形中生物与要点的教学示例，并非此处实际存在的记录。', 'इस भूभाग के जीवन और ज़रूरी बातों के शैक्षिक उदाहरण; यहाँ मौजूदगी का प्रमाण नहीं।'],
  openStreetView: ['افتح Street View هنا', 'Open Street View here', 'Ouvrir Street View ici', '在此打开街景', 'यहाँ Street View खोलें'],
  dragHint: ['اسحب لتحريك المنطقة، وانقر لنقل نقطة التركيز', 'Drag to move the area, click to move the focus point', 'Glissez pour déplacer la zone, cliquez pour déplacer le point', '拖动移动区域，点击移动焦点', 'क्षेत्र हिलाने के लिए खींचें, फ़ोकस बदलने के लिए क्लिक करें'],
  areaLayers: ['طبقات المنطقة', 'Area layers', 'Couches de la zone', '区域图层', 'क्षेत्र परतें'],
  areaUnavailable: ['صور المنطقة غير متاحة الآن.', 'Area imagery is unavailable right now.', 'Les images de la zone sont indisponibles pour le moment.', '目前无法获取该区域影像。', 'क्षेत्र की तस्वीरें अभी उपलब्ध नहीं हैं।'],
  areaHint: ['انقر على الخريطة لنقل نقطة التركيز', 'Click the map to move the focus point', 'Cliquez sur la carte pour déplacer le point', '点击地图移动焦点', 'फ़ोकस बिंदु बदलने के लिए नक्शे पर क्लिक करें'],
  viewWidth: ['عرض المشهد', 'View width', 'Largeur de la vue', '视野宽度', 'दृश्य की चौड़ाई'],
  terrain: ['نوع التضاريس', 'Terrain type', 'Type de terrain', '地形类型', 'भूभाग का प्रकार'],
  changeTerrain: ['غيّر نوع التضاريس', 'Change terrain type', 'Changer le type de terrain', '更改地形类型', 'भूभाग का प्रकार बदलें'],
  askTerrain: ['اسأل الدليل عن هذه التضاريس', 'Ask the guide about this terrain', 'Interroger le guide sur ce terrain', '向指南询问此地形', 'इस भूभाग के बारे में गाइड से पूछें'],
  groupSuggested: ['العدد المقترح للمجموعة', 'Suggested group size', 'Taille de groupe conseillée', '建议同行人数', 'सुझाई गई समूह संख्या'],
  selected: ['الوجهة المختارة', 'Selected destination', 'Destination choisie', '已选目的地', 'चुना गया गंतव्य'],
  destinations: ['اختر وجهتك', 'Choose your destination', 'Choisissez votre destination', '选择目的地', 'अपना गंतव्य चुनें'],
  discover: ['استكشف مكاناً', 'Explore a place', 'Explorez un lieu', '探索一处地方', 'कोई जगह खोजें'],
  briefing: ['دليل رحلتك', 'Your trip guide', 'Votre guide de voyage', '您的行程指南', 'आपकी यात्रा का गाइड'],
  overview: ['نظرة عامة', 'Overview', 'Vue d’ensemble', '概览', 'एक नज़र में'],
  visit: ['الأنشطة', 'Activities', 'Activités', '活动', 'गतिविधियाँ'],
  equipment: ['التجهيزات', 'Equipment', 'Équipement', '装备', 'यात्रा का सामान'],
  nature: ['الطبيعة', 'Nature', 'Nature', '自然', 'प्रकृति'],
  safety: ['الاحتياطات', 'Precautions', 'Précautions', '注意事项', 'सावधानियाँ'],
  season: ['الموسم', 'Season', 'Saison', '季节', 'ऋतु'],
  report: ['التقرير الكامل', 'Full report', 'Rapport complet', '完整报告', 'पूरी रिपोर्ट'],
  weather: ['تفاصيل الطقس', 'Weather details', 'Détails météo', '天气详情', 'मौसम का विवरण'],
  plan: ['خطط لرحلتك', 'Plan your trip', 'Préparez votre voyage', '规划行程', 'यात्रा की योजना बनाएँ'],
  guide: ['الكتاب الرقمي', 'Digital guidebook', 'Guide numérique', '数字手册', 'डिजिटल पुस्तिका'],
  sources: ['المصادر', 'Sources', 'Sources', '来源', 'स्रोत'],
  marker: ['موقع تقريبي للمنطقة', 'Approximate area location', 'Emplacement approximatif de la zone', '区域的大致位置', 'क्षेत्र का अनुमानित स्थान'],
  generic: ['نقطة تختارها أنت؛ حدّد تضاريسها لعرض إرشادات عامة.', 'A point you choose; select its terrain to see general guidance.', 'Un point de votre choix ; choisissez son type de terrain pour consulter des conseils généraux.', '这是您自行选择的地点；请选择其地形以查看一般指南。', 'आपका चुना हुआ बिंदु; सामान्य मार्गदर्शन के लिए उसका भूभाग चुनें।'],
  controls: ['أدوات الاستكشاف', 'Exploration tools', 'Outils d’exploration', '探索工具', 'खोज के साधन'],
  liveWeather: ['طقس الموقع', 'Location weather', 'Météo du lieu', '当地天气', 'इस स्थान का मौसम'],
  summary: ['عن المكان', 'About this place', 'À propos du lieu', '关于此地', 'इस जगह के बारे में'],
  selectionHint: ['اختر علامة على الكرة أو وجهة من القائمة', 'Select a marker on the globe or a destination from the list', 'Choisissez un repère sur le globe ou une destination dans la liste', '选择地球上的标记或列表中的目的地', 'ग्लोब पर निशान या सूची से गंतव्य चुनें'],
  handHint: ['تحكم بحركة يدك', 'Control with hand movements', 'Contrôlez avec les mouvements de la main', '用手势控制', 'हाथ की हरकतों से नियंत्रित करें'],
  close: ['إغلاق', 'Close', 'Fermer', '关闭', 'बंद करें'],
  satellite: ['عرض الأرض', 'Earth view', 'Vue de la Terre', '地球视图', 'पृथ्वी का दृश्य'],
  chooseHint: ['ابحث عن اسم أو نوع تضاريس', 'Search by name or terrain type', 'Recherchez un nom ou un type de terrain', '按名称或地形类型搜索', 'नाम या भूभाग के प्रकार से खोजें'],
  openDestinations: ['تغيير الوجهة', 'Change destination', 'Changer de destination', '更改目的地', 'गंतव्य बदलें'],
  fullGuide: ['اقرأ التفاصيل والمصادر', 'Read the details and sources', 'Consultez les détails et les sources', '阅读详情与来源', 'विवरण और स्रोत पढ़ें'],
  emptyNature: ['راجع وصف الطبيعة؛ لا تتوفر قائمة أنواع موثقة لهذا الموقع.', 'See the nature description; no verified species list is available for this location.', 'Consultez la description de la nature ; aucune liste d’espèces vérifiée n’est disponible pour ce lieu.', '请查看自然环境描述；此地暂无经过核实的物种清单。', 'प्रकृति का विवरण देखें; इस स्थान के लिए प्रजातियों की सत्यापित सूची उपलब्ध नहीं है।'],
  lat: ['خط العرض', 'Latitude', 'Latitude', '纬度', 'अक्षांश'],
  lon: ['خط الطول', 'Longitude', 'Longitude', '经度', 'देशांतर'],
  noLocal: ['إرشادات عامة للتضاريس؛ لا تؤكد وجود أنواع أو مسارات عند هذه النقطة.', 'General terrain guidance; it does not verify species or trails at this point.', 'Conseils généraux sur le terrain ; ils ne confirment ni espèces ni sentiers à cet endroit.', '这些是通用地形建议，不能确认此点存在特定物种或步道。', 'भूभाग का सामान्य मार्गदर्शन; इससे इस बिंदु पर प्रजातियों या पथों की मौजूदगी की पुष्टि नहीं होती।'],
  catalog: ['الدليل', 'Guide', 'Guide', '指南', 'गाइड'],
  fullWeather: ['التوقعات والمواسم', 'Forecast and seasons', 'Prévisions et saisons', '预报与季节', 'पूर्वानुमान और ऋतुएँ'],
  details: ['التفاصيل', 'Details', 'Détails', '详情', 'विवरण'],
  fieldGuide: ['دليل المنطقة', 'Area guide', 'Guide de la région', '地区指南', 'क्षेत्र का गाइड'],
  journey: ['خطوات الاستكشاف', 'Explore in three steps', 'Explorez en trois étapes', '三步探索', 'तीन चरणों में खोजें'],
  stepChoose: ['اختر', 'Choose', 'Choisir', '选择', 'चुनें'],
  stepChooseHint: ['ابحث عن وجهة', 'Find a destination', 'Trouvez une destination', '查找目的地', 'गंतव्य खोजें'],
  stepExplore: ['استكشف', 'Explore', 'Explorer', '探索', 'जानें'],
  stepExploreHint: ['تعرّف على المكان', 'Get to know the place', 'Découvrez le lieu', '了解当地情况', 'जगह के बारे में जानें'],
  stepPrepare: ['جهّز رحلتك', 'Prepare', 'Préparer', '准备', 'तैयारी करें'],
  stepPrepareHint: ['افتح مخطط الرحلة', 'Open your trip planner', 'Ouvrez le planificateur', '打开行程规划', 'यात्रा योजनाकार खोलें'],
  moreDetails: ['المزيد: الطبيعة والاحتياطات والموسم', 'More: nature, precautions & season', 'Plus : nature, précautions et saison', '更多：自然、注意事项与季节', 'और जानकारी: प्रकृति, सावधानियाँ और ऋतु'],
  saveShare: ['حفظ ومشاركة والمواقع المحفوظة', 'Save, share & saved places', 'Enregistrer, partager et lieux enregistrés', '保存、分享与已保存地点', 'सहेजें, साझा करें और सहेजी गई जगहें'],
  coordinatesTerrain: ['الإحداثيات ونوع التضاريس', 'Coordinates & terrain', 'Coordonnées et terrain', '坐标与地形', 'निर्देशांक और भूभाग'],
  controlHint: ['اسحب أو استخدم مفاتيح الأسهم للتدوير، واختر علامة لاستكشافها.', 'Drag or use arrow keys to rotate. Select a marker to explore.', 'Faites glisser ou utilisez les flèches pour tourner. Choisissez un repère à explorer.', '拖动或使用方向键旋转，选择标记探索。', 'घुमाने के लिए खींचें या तीर कुंजियाँ दबाएँ। किसी निशान को चुनकर जानें।'],
};

export const globeText = (locale: Locale, key: string): string =>
  translate(locale, globeDashboardWords[key] ?? globeDashboardWords.details);
