import type { ChecklistItem, GearItem, ItineraryDay, ItineraryEntry, Trip } from './toolkit-types';

export function dayDate(start:string,offset:number){if(!start)return '';const date=new Date(start+'T00:00:00Z');if(!Number.isFinite(date.getTime())||!Number.isInteger(offset))return '';date.setUTCDate(date.getUTCDate()+offset);return date.toISOString().slice(0,10)}
export function moveItem<T>(items:T[],index:number,delta:number){const result=[...items],target=index+delta;if(index<0||index>=items.length||target<0||target>=items.length)return result;[result[index],result[target]]=[result[target],result[index]];return result}
export function emptyEntry(timeZone=''):ItineraryEntry{return{id:crypto.randomUUID(),title:'',activityId:'walking',place:'',startTime:'',timeZone,durationMinutes:0,transport:'',notes:''}}
export function duplicateDay(day:ItineraryDay,offset:number):ItineraryDay{return{...structuredClone(day),id:crypto.randomUUID(),dayOffset:offset,entries:day.entries.map(e=>({...structuredClone(e),id:crypto.randomUUID()}))}}
export function itineraryWarnings(trip:Trip):{dayId:string;key:string}[]{const result:{dayId:string;key:string}[]=[],timed=(trip.itinerary??[]).flatMap(day=>day.entries.filter(e=>e.startTime&&e.timeZone&&e.durationMinutes>0).map(entry=>({dayId:day.id,zone:entry.timeZone,start:day.dayOffset*1440+Number(entry.startTime.slice(0,2))*60+Number(entry.startTime.slice(3)),duration:entry.durationMinutes})));for(const day of trip.itinerary??[]){const date=dayDate(trip.startDate,day.dayOffset);if(!date||!trip.endDate)result.push({dayId:day.id,key:'dateUnknown'});else if(date>trip.endDate)result.push({dayId:day.id,key:'dayOutside'});if(timed.some((a,i)=>a.dayId===day.id&&timed.some((b,j)=>i!==j&&a.zone===b.zone&&a.start<b.start+b.duration&&b.start<a.start+a.duration)))result.push({dayId:day.id,key:'timeOverlap'})}return result}
export function checklistProgress(rows:ChecklistItem[]){return rows.reduce((a,r)=>r.kind==='equipment'?{done:a.done+(Number.isFinite(r.packedQuantity)?r.packedQuantity!:0),total:a.total+(Number.isFinite(r.requiredQuantity)?r.requiredQuantity!:1)}:{done:a.done+Number(r.done),total:a.total+1},{done:0,total:0})}
export function allocationWarnings(trip:Trip,row:ChecklistItem,gear:GearItem[],trips:Trip[],today=new Date().toISOString().slice(0,10)):string[]{
 if(!row.gearId)return [];const g=gear.find(x=>x.id===row.gearId);if(!g)return ['gearUnavailable'];const warnings:string[]=[];
 if(g.archived||g.condition!=='ready')warnings.push('gearUnavailable');if(g.expiryDate&&g.expiryDate<(trip.endDate||trip.startDate||today))warnings.push('expired');if(g.maintenanceDate&&g.maintenanceDate<=(trip.endDate||trip.startDate||today))warnings.push('maintenanceDue');
 if(row.gearSnapshot&&(row.gearSnapshot.name!==g.name||row.gearSnapshot.quantity!==g.quantity||row.gearSnapshot.condition!==g.condition))warnings.push('snapshotChanged');
 const assigned=(t:Trip)=>t.checklist.filter(i=>i.gearId===g.id).reduce((sum,i)=>sum+(i.assignedQuantity??0),0),own=assigned(trip);let total=own,unknown=false;const overlapping:Trip[]=[];
 for(const other of trips){if(other.id===trip.id||!assigned(other))continue;if(!trip.startDate||!trip.endDate||!other.startDate||!other.endDate){unknown=true;continue}if(trip.startDate<=other.endDate&&other.startDate<=trip.endDate)overlapping.push(other)}
 // Only simultaneous reservations count; separate trips within a long trip must not be summed.
 for(const date of [trip.startDate,...overlapping.map(t=>t.startDate)]){if(date<trip.startDate||date>trip.endDate)continue;total=Math.max(total,own+overlapping.filter(t=>t.startDate<=date&&date<=t.endDate).reduce((sum,t)=>sum+assigned(t),0))}
 if(total>g.quantity)warnings.push('overAllocated');if(unknown&&own>0)warnings.push('unknownOverlap');return warnings;
}
