import type {Locale} from './terrain';
import type {Localized} from './toolkit-types';

export const teamWords:Record<string,Localized>={
 peopleStep:['المشاركون وأسماؤهم','People and names','Participants et noms','成员和姓名','लोग और नाम'],
 assignStep:['توزيع التجهيزات','Assign the packing','Répartir les équipements','分配装备','पैकिंग बाँटें'],
 inviteStep:['دعوة رفاقك','Invite companions','Inviter vos compagnons','邀请同行者','साथियों को बुलाएँ'],
 peopleStepHint:['أضف الأسماء واحفظها','Add and save names','Ajouter et enregistrer les noms','添加并保存姓名','नाम जोड़ें और सहेजें'],
 assignStepHint:['حدّد من يُحضر كل غرض','Choose who brings each item','Choisir qui apporte chaque article','选择物品携带者','तय करें कौन क्या लाएगा'],
 inviteStepHint:['أنشئ رابطاً وشاركه بنفسك','Create a link and share it','Créer un lien puis le partager','创建并分享链接','लिंक बनाएँ और साझा करें'],
 teamSections:['أقسام تجهيز الفريق','Team preparation sections','Rubriques de préparation','团队准备栏目','दल की तैयारी के भाग'],
 saveName:['حفظ الاسم','Save name','Enregistrer le nom','保存姓名','नाम सहेजें'],
 editMyName:['تعديل اسمي','Edit my name','Modifier mon nom','修改我的姓名','अपना नाम बदलें'],
 editName:['تعديل الاسم','Edit name','Modifier le nom','修改姓名','नाम बदलें'],
 nameChanged:['تحدّث الفريق أثناء التعديل. راجع الاسم المحفوظ قبل المتابعة:','The team changed while editing. Review the saved name before continuing:','L’équipe a été modifiée. Vérifiez le nom enregistré avant de continuer :','编辑期间团队已更新。请先检查已保存的姓名：','संपादन के दौरान दल बदला है। आगे बढ़ने से पहले सहेजा नाम जाँचें:'],
 savedName:['تم حفظ الاسم في المجموعة.','Name saved in the team.','Nom enregistré dans l’équipe.','团队姓名已保存。','दल में नाम सहेजा गया।'],
 personAdded:['تم حفظ المشارك. يمكنك الآن إسناد التجهيزات إليه.','Participant saved. You can now assign items to them.','Participant enregistré. Vous pouvez lui attribuer des articles.','参与者已保存，现在可以为其分配物品。','प्रतिभागी सहेजा गया। अब उन्हें सामान सौंप सकते हैं।'],
 addPersonSave:['إضافة المشارك وحفظه','Add and save participant','Ajouter et enregistrer','添加并保存参与者','प्रतिभागी जोड़ें और सहेजें'],
 managedIntro:['أضف اسماً إذا كنت ستدير تجهيز هذا الشخص بنفسك. هذه الخطوة لا ترسل دعوة ولا تمنحه دخولاً للموقع.','Add a name if you will manage this person’s packing. This does not send an invitation or give them access.','Ajoutez un nom si vous gérez sa préparation. Cela n’envoie pas d’invitation et ne donne aucun accès.','如需代为管理打包，请添加姓名。此操作不会发送邀请或授予访问权限。','यदि आप उनकी पैकिंग सँभालेंगे तो नाम जोड़ें। इससे आमंत्रण नहीं जाता और उन्हें पहुँच नहीं मिलती।'],
 inviteInstead:['ليتابع الشخص تجهيزاته بنفسه، أرسل له رابطاً من قسم «دعوة رفاقك».','To let someone update their own packing, send them a link from Invite companions.','Pour qu’une personne gère sa préparation, envoyez-lui un lien depuis Inviter vos compagnons.','如需对方自行更新打包，请从“邀请同行者”发送链接。','किसी को अपनी पैकिंग अपडेट करने देने के लिए “साथियों को बुलाएँ” से लिंक भेजें।'],
 namesSaved:['الأسماء الظاهرة أدناه محفوظة. تُحفظ الإضافات وتعديلات المسؤوليات فور الضغط على زر الحفظ الخاص بها.','Names below are saved. Additions and assignments are saved when you press their Save button.','Les noms ci-dessous sont enregistrés. Les ajouts et attributions sont enregistrés avec leur bouton de sauvegarde.','下方姓名均已保存。添加或分配后，点击对应保存按钮即可保存。','नीचे के नाम सहेजे गए हैं। नए नाम और जिम्मेदारियाँ उनके सहेजें बटन से सहेजी जाती हैं।'],
 inviteHow:['كيف أدعو شخصاً؟','How do I invite someone?','Comment inviter quelqu’un ?','如何邀请他人？','किसी को कैसे बुलाऊँ?'],
 inviteOne:['أنشئ رابط الدعوة من الزر أدناه.','Create an invitation link below.','Créez un lien ci-dessous.','在下方创建邀请链接。','नीचे आमंत्रण लिंक बनाएँ।'],
 inviteTwo:['انسخ الرابط وأرسله لرفاقك عبر واتساب أو أي تطبيق تختاره.','Copy the link and send it in WhatsApp or your preferred app.','Copiez le lien et envoyez-le via WhatsApp ou votre application préférée.','复制链接，通过微信或其他应用发送给同行者。','लिंक कॉपी करके WhatsApp या पसंदीदा ऐप से भेजें।'],
 inviteThree:['يفتح صديقك الرابط، ويسجّل الدخول، ثم يختار اسمه ويضغط «الانضمام إلى المجموعة».','Your companion opens the link, signs in, chooses a name and presses Join group.','Votre compagnon ouvre le lien, se connecte, choisit un nom et rejoint le groupe.','同行者打开链接，登录，填写姓名并点击加入团队。','साथी लिंक खोलकर साइन इन करें, नाम चुनें और समूह से जुड़ें दबाएँ।'],
 inviteFour:['بعد الانضمام سيظهر هنا بحسابه، ويستطيع تحديث مسؤولياته.','After joining, their account appears here and they can update their assignments.','Après avoir rejoint, son compte apparaît ici et il peut actualiser ses attributions.','加入后，其账号将显示在此，并可更新自己的分配。','जुड़ने के बाद उनका खाता यहाँ दिखेगा और वे अपनी जिम्मेदारियाँ अपडेट कर सकेंगे।'],
 inviteReady:['الرابط جاهز — انسخه وأرسله الآن','Link ready — copy and send it','Lien prêt — copiez-le et envoyez-le','链接已就绪，请复制并发送','लिंक तैयार है — कॉपी करके भेजें'],
 inviteSeparate:['إذا أضفت اسماً يدوياً ثم انضم صاحبه بحسابه، يبقيان مشاركين منفصلين. انقل المسؤوليات للحساب ثم احذف الاسم اليدوي عند الحاجة.','A manually added name and a joined account remain separate. Reassign items to the account, then remove the manual name if needed.','Un nom ajouté et un compte invité restent distincts. Réattribuez les articles au compte puis retirez le nom manuel si nécessaire.','手动姓名与加入的账号彼此独立。请将物品重新分配给账号，再按需移除手动姓名。','हाथ से जोड़ा नाम और जुड़ा खाता अलग रहते हैं। सामान खाते को फिर सौंपें, फिर जरूरत हो तो हाथ से जोड़ा नाम हटाएँ।'],
 renewConfirm:['إنشاء رابط بديل؟','Create a replacement link?','Créer un lien de remplacement ?','创建替代链接？','नया लिंक बनाएँ?'],
 renewWarning:['سيتوقف الرابط السابق فوراً. المشاركون الحاليون يبقون في الفريق. أرسل الرابط الجديد لمن لم ينضم بعد.','The previous link will stop working immediately. Current participants remain. Send the new link to anyone who has not joined yet.','L’ancien lien cessera de fonctionner immédiatement. Les membres actuels restent. Envoyez le nouveau lien aux personnes non encore inscrites.','旧链接将立即失效。现有成员不受影响。请向尚未加入的人发送新链接。','पुराना लिंक तुरंत बंद होगा। मौजूदा सदस्य रहेंगे। जो अभी नहीं जुड़े उन्हें नया लिंक भेजें।'],
 choosePerson:['اختر المشارك…','Choose a participant…','Choisir un participant…','选择参与者…','प्रतिभागी चुनें…'],
 addAssignment:['إسناد كمية لشخص','Assign a quantity to someone','Attribuer une quantité','分配数量给成员','किसी को मात्रा सौंपें'],
 assignmentSteps:['اختر الشخص، وحدّد ما سيُحضره، ثم احفظ. المجهّز يعني ما وضعه فعلياً في الأمتعة.','Choose a person, enter what they will bring, then save. Packed means what is actually in their bags.','Choisissez une personne, indiquez ce qu’elle apporte puis enregistrez. Préparé signifie déjà dans les bagages.','选择成员，输入其携带数量，然后保存。“已打包”指实际装入行李的数量。','व्यक्ति चुनें, उनकी लाने की मात्रा लिखें और सहेजें। पैक का अर्थ सचमुच बैग में रखा सामान है।'],
 fullyPackedAction:['تأكيد تجهيز حصتي كاملة','Mark my allocation packed','Confirmer ma part préparée','确认我的分配已打包','अपनी पूरी मात्रा पैक की पुष्टि करें'],
 fullyPackedOther:['تأكيد تجهيز هذه الكمية','Mark this allocation packed','Confirmer cette part préparée','确认该分配已打包','इस मात्रा के पैक होने की पुष्टि करें'],
 removeAssignment:['إلغاء هذه المسؤولية','Remove this assignment','Retirer cette attribution','移除此分配','यह जिम्मेदारी हटाएँ'],
 allocationSaved:['تم حفظ المسؤولية. تظهر للجميع، ولا تغيّر قائمة رحلتك الخاصة.','Assignment saved. The team can see it; your private checklist is unchanged.','Attribution enregistrée et visible par l’équipe. Votre liste privée reste inchangée.','分配已保存，团队可见。你的私人清单保持不变。','जिम्मेदारी सहेजी गई और दल को दिखेगी। आपकी निजी सूची नहीं बदली।'],
 title:['تجهيز فريق الرحلة','Trip team preparation','Préparation de l’équipe','行程团队准备','यात्रा दल की तैयारी'],
 intro:['اتفقوا على من يحمل كل غرض، وتابعوا الكميات المجهزة معاً.','Agree who brings each item and track packed quantities together.','Décidez qui apporte chaque article et suivez ensemble les quantités préparées.','协商每件物品由谁携带，共同跟进打包数量。','तय करें कि कौन क्या लाएगा और साथ मिलकर पैक की गई मात्रा देखें।'],
 privacy:['تُشارك نسخة من عنوان الرحلة وأسماء عناصر القائمة والكميات فقط. لا تُشارك الملاحظات الخاصة أو مخزون المعدات أو الكميات المجهزة في رحلتك الخاصة.','Only a copy of the trip title, checklist labels and required quantities is shared. Private notes, equipment inventory and your private packed counts are not shared.','Seule une copie du titre, des libellés et des quantités requises est partagée. Les notes, le stock personnel et les quantités préparées privées restent privés.','仅共享行程标题、清单名称和所需数量的副本。私人笔记、装备库存和私人打包数量不会共享。','केवल यात्रा का शीर्षक, सूची के नाम और आवश्यक मात्रा की प्रति साझा होती है। निजी नोट्स, उपकरण भंडार और निजी पैक की गई मात्रा साझा नहीं होती।'],
 snapshot:['هذه لوحة مستقلة. لا تتغير رحلتك الخاصة عند تحديثها.','This is a separate board. Updates do not change your private trip.','Ce tableau est indépendant. Ses mises à jour ne modifient pas votre voyage privé.','这是独立的看板，更新不会改变你的私人行程。','यह अलग बोर्ड है। इसके अपडेट आपकी निजी यात्रा नहीं बदलते।'],
 boards:['فرق رحلاتي','Trip teams','Équipes de voyage','行程团队','यात्रा दल'],
 trips:['رحلاتي','My trips','Mes voyages','我的行程','मेरी यात्राएँ'],
 noBoards:['لا توجد لوحات بعد. أنشئ لوحة من رحلة محفوظة ومتزامنة.','No boards yet. Create one from a saved, synced trip.','Aucun tableau. Créez-en un depuis un voyage enregistré et synchronisé.','还没有看板，请从已保存并同步的行程创建。','अभी कोई बोर्ड नहीं। सहेजी और सिंक की गई यात्रा से बनाएँ।'],
 noBoard:['شارك قائمة التجهيز مع رفاق رحلتك.','Share a packing checklist with your travel companions.','Partagez votre liste avec vos compagnons de voyage.','与同行伙伴共享打包清单。','यात्रा के साथियों के साथ पैकिंग सूची साझा करें।'],
 signIn:['سجّل الدخول للوصول إلى لوحات المجموعة.','Sign in to access group boards.','Connectez-vous pour accéder aux tableaux de groupe.','登录以访问团队看板。','समूह बोर्ड खोलने के लिए साइन इन करें।'],
 signInAction:['تسجيل الدخول','Sign in','Se connecter','登录','साइन इन करें'],
 inviteSignIn:['بعد تسجيل الدخول، افتح رابط الدعوة الأصلي مجدداً للانضمام.','After signing in, reopen the original invitation link to join.','Après connexion, rouvrez le lien d’invitation original pour rejoindre le groupe.','登录后，请重新打开原邀请链接加入。','साइन इन करने के बाद जुड़ने के लिए मूल आमंत्रण लिंक फिर खोलें।'],
 loading:['جارٍ تحميل اللوحة…','Loading board…','Chargement du tableau…','正在加载看板…','बोर्ड लोड हो रहा है…'],
 refresh:['تحديث العرض','Refresh view','Actualiser','刷新显示','दृश्य ताज़ा करें'],
 updated:['آخر تحديث','Last updated','Dernière mise à jour','上次更新','आखिरी अपडेट'],
 polling:['يتحدث العرض كل 15 ثانية عندما تكون الصفحة ظاهرة ومتصلة بالإنترنت.','Refreshes every 15 seconds while this page is visible and online.','Actualisation toutes les 15 secondes quand la page est visible et connectée.','页面可见且在线时，每15秒刷新一次。','पृष्ठ खुला और ऑनलाइन होने पर हर 15 सेकंड में अपडेट होता है।'],
 offline:['لوحات المجموعة تحتاج اتصالاً بالإنترنت ولا تُحفظ للاستخدام دون اتصال. أعد الاتصال ثم حدّث العرض.','Group boards require internet and are not stored offline. Reconnect, then refresh.','Les tableaux nécessitent Internet et ne sont pas stockés hors ligne. Reconnectez-vous puis actualisez.','团队看板需要联网，不会离线保存。请重新连接后刷新。','समूह बोर्ड को इंटरनेट चाहिए; वे ऑफलाइन सहेजे नहीं जाते। जुड़ने के बाद ताज़ा करें।'],
 savedOnly:['احفظ الرحلة وزامنها أولاً؛ تُنشر النسخة المحفوظة على الخادم فقط.','Save and sync the trip first; only the server-saved copy can be shared.','Enregistrez et synchronisez d’abord le voyage ; seule la copie sur le serveur peut être partagée.','请先保存并同步行程；只能共享服务器已保存的副本。','पहले यात्रा सहेजें और सिंक करें; केवल सर्वर पर सहेजी प्रति साझा हो सकती है।'],
 yourName:['اسمك في المجموعة','Your name in the group','Votre nom dans le groupe','你的团队昵称','समूह में आपका नाम'],
 personName:['اسم المشارك','Participant name','Nom du participant','参与者姓名','प्रतिभागी का नाम'],
 preview:['معاينة المشاركة','Preview sharing','Aperçu du partage','预览共享内容','साझा करने का पूर्वावलोकन'],
 create:['إنشاء لوحة مشتركة','Create shared board','Créer le tableau partagé','创建共享看板','साझा बोर्ड बनाएँ'],
 previewTitle:['راجع ما ستشاركه','Review what you will share','Vérifiez le contenu partagé','检查将共享的内容','साझा की जाने वाली जानकारी जाँचें'],
 replace:['استبدال القائمة بأحدث نسخة','Replace with latest checklist','Remplacer par la dernière liste','替换为最新清单','नवीनतम सूची से बदलें'],
 replaceHint:['ستُحذف العناصر التي أُزيلت ومسؤولياتها من هذه اللوحة فقط. تبقى كميات العناصر الأخرى كما هي، حتى إن تجاوزت المطلوب.','Removed items and their allocations will be deleted from this board only. Other allocations stay unchanged, even if they exceed the new requirement.','Les articles retirés et leurs attributions seront supprimés de ce tableau uniquement. Les autres quantités restent inchangées, même en cas de dépassement.','删除的物品及其分配将仅从此看板移除。其他分配保持不变，即使超过新的需求。','हटाए गए सामान और उनके आवंटन केवल इस बोर्ड से हटेंगे। बाकी मात्रा नहीं बदलेगी, भले ही नई आवश्यकता से अधिक हो।'],
 removed:['عناصر ستُحذف مع مسؤولياتها','Items and allocations to remove','Articles et attributions à retirer','将移除的物品及分配','हटने वाला सामान और आवंटन'],
 noneRemoved:['لا توجد عناصر محذوفة.','No items removed.','Aucun article retiré.','没有物品被移除。','कोई सामान नहीं हटेगा।'],
 noItems:['القائمة فارغة. أضف عناصر إلى الرحلة واحفظها وزامنها قبل تحديث اللوحة.','The checklist is empty. Add items to your trip, save and sync before updating the board.','La liste est vide. Ajoutez des articles au voyage, enregistrez et synchronisez avant de mettre à jour le tableau.','清单为空。请在行程中添加物品，保存并同步后再更新看板。','सूची खाली है। यात्रा में सामान जोड़ें, सहेजें और सिंक करें, फिर बोर्ड अपडेट करें।'],
 cancel:['إلغاء','Cancel','Annuler','取消','रद्द करें'],
 confirm:['تأكيد','Confirm','Confirmer','确认','पुष्टि करें'],
 join:['الانضمام إلى المجموعة','Join group','Rejoindre le groupe','加入团队','समूह से जुड़ें'],
 joinHint:['أنت مدعو للانضمام إلى لوحة تجهيز. سيظهر الاسم الذي تختاره للمشاركين بعد تأكيد الانضمام.','You are invited to a packing board. Other participants will see your chosen name after you confirm joining.','Vous êtes invité à un tableau. Votre nom choisi sera visible aux participants après confirmation.','你收到打包看板邀请。确认加入后，其他参与者将看到你选择的昵称。','आपको पैकिंग बोर्ड में आमंत्रित किया गया है। जुड़ने की पुष्टि के बाद अन्य लोगों को आपका चुना हुआ नाम दिखेगा।'],
 participants:['المشاركون','Participants','Participants','参与者','प्रतिभागी'],
 owner:['المنظّم','Organizer','Organisateur','组织者','आयोजक'],
 member:['مشارك','Member','Membre','成员','सदस्य'],
 you:['أنت','You','Vous','你','आप'],
 placeholder:['اسم محلي؛ يديره المنظّم','Local name; managed by organizer','Nom local, géré par l’organisateur','本地姓名，由组织者管理','स्थानीय नाम; आयोजक प्रबंधित करता है'],
 addPerson:['إضافة مشارك بالاسم','Add named participant','Ajouter un participant nommé','添加具名参与者','नाम से प्रतिभागी जोड़ें'],
 placeholderHint:['المشارك المضاف بالاسم لا يرتبط بحساب. من ينضم بالدعوة يحصل على مشاركة مستقلة.','A named participant is not linked to an account. Joining by invitation creates a separate participant.','Un participant nommé n’est lié à aucun compte. Une invitation crée un participant distinct.','具名参与者不关联账号，通过邀请加入会创建独立参与者。','नाम से जोड़ा गया प्रतिभागी खाते से नहीं जुड़ा होता। आमंत्रण से जुड़ने पर अलग प्रतिभागी बनता है।'],
 remove:['إزالة','Remove','Retirer','移除','हटाएँ'],
 removeHint:['ستُزال مشاركة هذا الشخص وجميع مسؤولياته من اللوحة، ويُلغى رابط الدعوة الحالي. أنشئ رابطاً جديداً لدعوات لاحقة.','This person and all their allocations will be removed. The current invitation link will be revoked; create a new link for future invitations.','Cette personne et ses attributions seront retirées. Le lien actuel sera révoqué ; créez-en un nouveau pour les prochaines invitations.','此人及其分配将被移除，当前邀请链接将被撤销。后续邀请请创建新链接。','यह व्यक्ति और उनके आवंटन हटेंगे। मौजूदा आमंत्रण लिंक रद्द होगा; अगले आमंत्रणों के लिए नया लिंक बनाएँ।'],
 invitation:['دعوة المشاركين','Invite participants','Inviter des participants','邀请参与者','प्रतिभागियों को आमंत्रित करें'],
 generate:['إنشاء رابط دعوة','Create invitation link','Créer un lien d’invitation','创建邀请链接','आमंत्रण लिंक बनाएँ'],
 renew:['تجديد رابط الدعوة','Renew invitation link','Renouveler le lien','更新邀请链接','आमंत्रण लिंक नवीनीकृत करें'],
 inviteHint:['الرابط صالح 7 أيام. تجديده يلغي الرابط السابق؛ يمكن لأي شخص مسجّل الدخول ويملك الرابط الانضمام. شاركه مع رفاقك المقصودين فقط.','The link lasts 7 days. Renewing invalidates the old link; anyone signed in with this link can join. Share it only with intended companions.','Le lien dure 7 jours. Le renouveler invalide l’ancien ; toute personne connectée ayant le lien peut rejoindre. Partagez-le uniquement avec vos compagnons prévus.','链接有效期为7天。更新后旧链接失效；任何已登录且持有链接的人都可加入。请仅与预期同行者分享。','लिंक 7 दिन तक मान्य है। नया बनाने से पुराना निष्क्रिय होगा; लिंक वाला कोई भी साइन इन व्यक्ति जुड़ सकता है। इसे केवल इच्छित साथियों से साझा करें।'],
 expires:['تنتهي الدعوة في','Invitation expires','Expiration de l’invitation','邀请到期时间','आमंत्रण की समाप्ति'],
 revoke:['إلغاء رابط الدعوة','Revoke invitation link','Révoquer le lien','撤销邀请链接','आमंत्रण लिंक रद्द करें'],
 copy:['نسخ رابط الدعوة','Copy invitation link','Copier le lien d’invitation','复制邀请链接','आमंत्रण लिंक कॉपी करें'],
 copied:['تم نسخ رابط الدعوة.','Invitation link copied.','Lien d’invitation copié.','邀请链接已复制。','आमंत्रण लिंक कॉपी हो गया।'],
 copyFailed:['تعذّر النسخ تلقائياً. حدّد الرابط وانسخه يدوياً.','Copy failed. Select the link and copy it manually.','Copie impossible. Sélectionnez le lien et copiez-le manuellement.','复制失败，请选中链接手动复制。','कॉपी नहीं हो सका। लिंक चुनकर हाथ से कॉपी करें।'],
 checklist:['القائمة المشتركة','Shared checklist','Liste partagée','共享清单','साझा सूची'],
 required:['المطلوب','Required','Requis','所需','आवश्यक'],
 assigned:['الموزّع','Assigned','Attribué','已分配','आवंटित'],
 packed:['المجهّز','Packed','Préparé','已打包','पैक किया'],
 gap:['كمية لم تُوزّع','Unassigned quantity','Quantité non attribuée','未分配数量','बिना आवंटन की मात्रा'],
 overbooked:['زيادة في التوزيع','Overassigned','Surattribué','超额分配','अधिक आवंटन'],
 task:['مهمة','Task','Tâche','任务','कार्य'],
 taskQuantity:['للمهمة، اختر 0 أو 1 لكل مشارك، ولا يتجاوز المجهّز المسند.','For a task, use 0 or 1 per participant, with packed no greater than assigned.','Pour une tâche, utilisez 0 ou 1 par participant, avec préparé inférieur ou égal à attribué.','每项任务给每位参与者分配0或1，完成数量不能超过分配数量。','कार्य के लिए प्रति प्रतिभागी 0 या 1 चुनें; पूरा किया गया आवंटित से अधिक न हो।'],
 editAllocation:['تعديل المسؤولية','Edit allocation','Modifier l’attribution','编辑分配','आवंटन बदलें'],
 assignedTo:['المسؤول','Assigned to','Attribué à','分配给','जिम्मेदार व्यक्ति'],
 quantity:['الكمية المسندة','Assigned quantity','Quantité attribuée','分配数量','आवंटित मात्रा'],
 packedQuantity:['الكمية المجهزة','Packed quantity','Quantité préparée','打包数量','पैक की गई मात्रा'],
 zeroHint:['ضع الكمية المسندة صفراً لإزالة المسؤولية. لا يمكن أن تتجاوز الكمية المجهزة الكمية المسندة.','Set assigned quantity to zero to remove the allocation. Packed quantity cannot exceed assigned quantity.','Attribuez zéro pour supprimer l’attribution. La quantité préparée ne peut dépasser la quantité attribuée.','将分配数量设为零可移除分配。打包数量不得超过分配数量。','आवंटन हटाने के लिए मात्रा शून्य करें। पैक की गई मात्रा आवंटित मात्रा से अधिक नहीं हो सकती।'],
 save:['حفظ المسؤولية','Save allocation','Enregistrer l’attribution','保存分配','आवंटन सहेजें'],
 draftChanged:['تغيرت اللوحة منذ بدء التعديل. راجع الكميات الحالية ثم أكّد الاحتفاظ بتعديلك قبل حفظه.','The board changed since you started editing. Review current quantities, then confirm keeping your draft before saving.','Le tableau a changé. Vérifiez les quantités actuelles puis confirmez votre brouillon avant de l’enregistrer.','编辑期间看板发生变化。请检查当前数量，再确认保留草稿后保存。','संपादन शुरू करने के बाद बोर्ड बदला है। मौजूदा मात्रा जाँचें, फिर सहेजने से पहले अपना मसौदा रखने की पुष्टि करें।'],
 keepDraft:['راجعت التحديث؛ أبقِ تعديلي','Reviewed; keep my draft','Vérifié ; garder mon brouillon','已检查，保留我的草稿','जाँच लिया; मेरा मसौदा रखें'],
 saved:['تم تحديث اللوحة.','Board updated.','Tableau mis à jour.','看板已更新。','बोर्ड अपडेट हो गया।'],
 close:['إغلاق اللوحة','Close board','Fermer le tableau','关闭看板','बोर्ड बंद करें'],
 closeHint:['ستُحذف اللوحة ومسؤولياتها ولن يعود بإمكان المشاركين الوصول إليها. تبقى الرحلة الخاصة كما هي.','The board and its allocations will be removed and participants will lose access. Your private trip stays unchanged.','Le tableau et ses attributions seront supprimés ; les participants perdront l’accès. Le voyage privé reste inchangé.','看板及其分配将被删除，参与者将失去访问权限。私人行程保持不变。','बोर्ड और उसके आवंटन हटेंगे; प्रतिभागियों की पहुँच समाप्त होगी। निजी यात्रा नहीं बदलेगी।'],
 leave:['مغادرة المجموعة','Leave group','Quitter le groupe','退出团队','समूह छोड़ें'],
 leaveHint:['ستُحذف مسؤولياتك وتفقد الوصول إلى هذه اللوحة. تحتاج دعوة سارية للعودة.','Your allocations will be removed and you will lose access. A valid invitation is needed to rejoin.','Vos attributions seront retirées et vous perdrez l’accès. Une invitation valide sera nécessaire pour revenir.','你的分配将被移除，你将失去访问权限。重新加入需要有效邀请。','आपके आवंटन हटेंगे और पहुँच समाप्त होगी। दोबारा जुड़ने के लिए मान्य आमंत्रण चाहिए।'],
 closed:['أُغلقت اللوحة.','Board closed.','Tableau fermé.','看板已关闭。','बोर्ड बंद हो गया।'],
 left:['غادرت المجموعة.','You left the group.','Vous avez quitté le groupe.','你已退出团队。','आपने समूह छोड़ दिया।'],
 unauthorized:['سجّل الدخول ثم أعد المحاولة.','Sign in and try again.','Connectez-vous puis réessayez.','请登录后重试。','साइन इन करके फिर प्रयास करें।'],
 account_changed:['تغيّر الحساب. حدّث العرض قبل المتابعة.','The account changed. Refresh before continuing.','Le compte a changé. Actualisez avant de continuer.','账号已更改，请刷新后继续。','खाता बदल गया। जारी रखने से पहले ताज़ा करें।'],
 invalid:['تحقق من الاسم والكميات: أعداد صحيحة من 0 إلى 10000، والمجهّز لا يتجاوز المسند.','Check the name and quantities: whole numbers from 0 to 10000, with packed no greater than assigned.','Vérifiez le nom et les quantités : entiers de 0 à 10000, préparé inférieur ou égal à attribué.','请检查名称和数量：0至10000的整数，打包数量不能超过分配数量。','नाम और मात्रा जाँचें: 0 से 10000 तक पूर्णांक; पैक की गई मात्रा आवंटित से अधिक न हो।'],
 not_found:['لم تُعثر على اللوحة أو الرحلة المحفوظة، أو لم يعد الوصول متاحاً.','The board or saved trip was not found, or access is no longer available.','Tableau ou voyage enregistré introuvable, ou accès retiré.','找不到看板或已保存行程，或你已无权访问。','बोर्ड या सहेजी यात्रा नहीं मिली, या पहुँच अब उपलब्ध नहीं है।'],
 forbidden:['لا يسمح حسابك بهذا الإجراء.','Your account cannot perform this action.','Votre compte ne peut pas effectuer cette action.','你的账号无权执行此操作。','आपका खाता यह कार्य नहीं कर सकता।'],
 conflict:['تغيّرت اللوحة أو الرحلة. تم طلب أحدث نسخة؛ بقي تعديلك للمراجعة. أعد المعاينة أو راجع التعديل قبل الإرسال مجدداً.','The board or trip changed. The latest copy was requested; your draft is kept for review. Preview again or review your draft before resubmitting.','Le tableau ou voyage a changé. La dernière copie a été demandée ; votre brouillon est conservé. Revérifiez-le avant de renvoyer.','看板或行程已变化。已请求最新副本，草稿保留供检查。请重新预览或检查草稿后再提交。','बोर्ड या यात्रा बदली है। नवीनतम प्रति माँगी गई; मसौदा जाँच के लिए रखा है। फिर भेजने से पहले पूर्वावलोकन या मसौदा जाँचें।'],
 read_only:['الحفظ متوقف مؤقتاً. يمكنك قراءة اللوحة.','Saving is temporarily disabled. You can still read the board.','L’enregistrement est temporairement désactivé. Le tableau reste consultable.','保存暂时停用，仍可阅读看板。','सहेजना अस्थायी रूप से बंद है। बोर्ड पढ़ सकते हैं।'],
 service_unavailable:['تعذّر الوصول إلى الخدمة. لم يُعَد إرسال التعديل تلقائياً؛ حدّث العرض للتحقق من النتيجة قبل المحاولة مجدداً.','Service unavailable. Your change was not retried automatically; refresh to check the result before trying again.','Service indisponible. Aucun renvoi automatique ; actualisez pour vérifier le résultat avant de réessayer.','服务不可用。修改未自动重试；请刷新检查结果后再试。','सेवा उपलब्ध नहीं। बदलाव अपने आप फिर नहीं भेजा गया; दोबारा प्रयास से पहले ताज़ा करके परिणाम जाँचें।'],
 limit:['تم بلوغ الحد المسموح للوحات أو المشاركين.','The board or participant limit has been reached.','Limite de tableaux ou participants atteinte.','已达到看板或参与者数量上限。','बोर्ड या प्रतिभागियों की सीमा पूरी हो गई।'],
 name_taken:['هذا الاسم مستخدم في المجموعة. اختر اسماً آخر.','This name is already used in the group. Choose another.','Ce nom est déjà utilisé. Choisissez-en un autre.','团队中已有人使用该名称，请换一个。','समूह में यह नाम पहले से है। दूसरा चुनें।'],
 invite_invalid:['رابط الدعوة غير صالح أو انتهت صلاحيته. اطلب رابطاً جديداً من المنظّم.','This invitation is invalid or expired. Ask the organizer for a new link.','Invitation invalide ou expirée. Demandez un nouveau lien à l’organisateur.','邀请无效或已过期，请向组织者索取新链接。','आमंत्रण अमान्य है या समाप्त हो चुका। आयोजक से नया लिंक माँगें।'],
 unavailable:['هذا الإجراء غير متاح الآن. حدّث العرض وأعد المحاولة.','This action is unavailable. Refresh and try again.','Cette action est indisponible. Actualisez et réessayez.','暂时无法执行，请刷新后重试。','यह कार्य अभी उपलब्ध नहीं। ताज़ा करके फिर प्रयास करें।'],
 room:['فتح تجهيز الفريق','Open team preparation','Ouvrir la préparation','打开团队准备','दल की तैयारी खोलें'],
 revision:['نسخة القائمة المشتركة','Shared checklist revision','Version de la liste partagée','共享清单版本','साझा सूची का संस्करण'],
 readLatest:['عرض أحدث مسؤوليات المشاركين','View current participant allocations','Voir les attributions actuelles','查看当前参与者分配','मौजूदा प्रतिभागी आवंटन देखें'],
 changedItems:['العناصر الجديدة والمعدلة ستأخذ الكميات الظاهرة في هذه المعاينة.','New and changed items will use the required quantities in this preview.','Les articles nouveaux ou modifiés utiliseront les quantités requises de cet aperçu.','新增和更改物品将使用本预览中的所需数量。','नए और बदले सामान की आवश्यक मात्रा इस पूर्वावलोकन के अनुसार होगी।'],
 missingParticipant:['لم يعد هذا المشارك في اللوحة. اختر مشاركاً متاحاً.','This participant is no longer on the board. Choose an available participant.','Ce participant a quitté le tableau. Choisissez-en un autre.','此参与者已不在看板中，请选择其他参与者。','यह प्रतिभागी अब बोर्ड में नहीं है। उपलब्ध प्रतिभागी चुनें।'],
 inviteActive:['أُنشئ رابط دعوة سابقاً. لإنشاء رابط يمكنك نسخه، جدّده؛ سيتوقف الرابط القديم.','An invitation was created earlier. Renew it to get a link you can copy; the old link will stop working.','Une invitation a déjà été créée. Renouvelez-la pour obtenir un lien à copier ; l’ancien sera invalidé.','此前已创建邀请。更新后可获取可复制链接，旧链接将失效。','पहले एक आमंत्रण बनाया गया था। कॉपी करने योग्य लिंक पाने के लिए नवीनीकृत करें; पुराना लिंक बंद होगा।'],
 noAllocation:['لم يتولَّ أحد إحضار هذا الغرض بعد.','No one is bringing this yet.','Personne ne s’en charge encore.','还没有人负责携带。','अभी कोई इसे लाने की जिम्मेदारी नहीं ले रहा।'],
 startTeam:['جهّزوا الرحلة معاً','Prepare the trip together','Préparez le voyage ensemble','一起准备行程','मिलकर यात्रा की तैयारी करें'],
 organizerHint:['وزّعوا ما ستأخذونه، ثم سجّلوا ما أصبح مجهّزاً بالفعل.','Choose who brings what, then record what is actually packed.','Répartissez ce que chacun apporte, puis notez ce qui est vraiment préparé.','分配携带责任，再记录实际已打包的物品。','तय करें कि कौन क्या लाएगा, फिर वास्तव में पैक सामान दर्ज करें।'],
 memberHint:['تولَّ إحضار بعض الأغراض وحدّث كمياتك المجهّزة. يرى الجميع توزيع الفريق.','Claim items to bring and update your packed quantities. Everyone can see the team’s assignments.','Prenez des articles en charge et actualisez vos quantités préparées. Toute l’équipe voit la répartition.','认领要携带的物品并更新已打包数量。所有人都能查看团队分配。','सामान लाने की जिम्मेदारी लें और अपनी पैक मात्रा अपडेट करें। सभी दल का बँटवारा देख सकते हैं।'],
 openTrip:['فتح رحلتي الخاصة','Open my private trip','Ouvrir mon voyage privé','打开我的私人行程','मेरी निजी यात्रा खोलें'],
 itemsPacked:['عناصر قائمة مكتملة','checklist items completed','éléments de liste terminés','项清单已完成','सूची मद पूरे हुए'],
 checklistProgress:['اكتمال تجهيز القائمة','Checklist completion','Avancement de la préparation','清单完成进度','सूची पूरी होने की प्रगति'],
 itemCountHint:['نعدّ عناصر القائمة المكتملة، ولا نجمع كميات الأغراض المختلفة.','Counts completed checklist items, without adding different kinds of quantities.','Compte les articles terminés, sans additionner des quantités de nature différente.','按完成的清单项计数，不混加不同物品的数量。','पूरे हुए सूची मद गिने जाते हैं; अलग तरह की मात्राएँ नहीं जोड़ी जातीं।'],
 needsCarrier:['تحتاج مسؤولاً','Need a carrier','À attribuer','待认领','जिम्मेदार व्यक्ति चाहिए'],
 needsPacking:['لم يكتمل تجهيزها','Still to pack','À préparer','尚未打包完成','अभी पैक करना है'],
 reviewExcess:['تحتاج مراجعة التوزيع','Assignments to review','Attributions à vérifier','待检查的分配','बँटवारे की जाँच चाहिए'],
 nextAction:['الخطوة التالية','Next action','Prochaine action','下一步','अगला कदम'],
 emptyNext:['ابدؤوا بإضافة الأغراض إلى الرحلة، ثم شاركوا أحدث قائمة.','Start by adding items to the trip, then share the latest checklist.','Ajoutez d’abord des articles au voyage, puis partagez la liste actualisée.','先在行程中添加物品，再共享最新清单。','पहले यात्रा में सामान जोड़ें, फिर नवीनतम सूची साझा करें।'],
 excessNext:['هناك كميات موزّعة أكثر من المطلوب. راجعوها لتجنب حمل الأغراض مرتين.','Some quantities exceed what is needed. Review them to avoid bringing duplicates.','Certaines quantités attribuées dépassent le besoin. Vérifiez-les pour éviter les doublons.','部分分配数量超过需求，请检查以免重复携带。','कुछ आवंटन जरूरत से अधिक हैं। दोहरा सामान लाने से बचने के लिए जाँचें।'],
 inviteNext:['أنت وحدك في الفريق حالياً. ادعُ رفاقك، أو أضف أسماء من ستدير تجهيزهم.','You are the only participant so far. Invite companions, or add names you will manage.','Vous êtes seul pour le moment. Invitez vos compagnons ou ajoutez des noms à gérer.','目前只有你一人。邀请同行者，或添加由你管理的姓名。','अभी केवल आप जुड़े हैं। साथियों को बुलाएँ या जिनकी तैयारी आप सँभालेंगे उनके नाम जोड़ें।'],
 assignNext:['بعض الأغراض بلا مسؤول. حدّدوا من سيحضر الكميات المتبقية.','Some items have no carrier for the full quantity. Choose who brings the rest.','Certains articles ne sont pas entièrement attribués. Décidez qui apporte le reste.','部分物品尚未全部分配，请确定由谁携带剩余数量。','कुछ सामान की पूरी मात्रा की जिम्मेदारी तय नहीं है। तय करें कि बाकी कौन लाएगा।'],
 packMineNext:['لديك أغراض لم يكتمل تجهيزها. حدّث كمياتك بعد وضعها في الأمتعة.','You still have items to pack. Update your quantities after packing them.','Il vous reste des articles à préparer. Actualisez vos quantités après les avoir rangés.','你还有物品未打包。装入行李后更新数量。','आपका कुछ सामान अभी पैक होना है। पैक करने के बाद मात्रा अपडेट करें।'],
 packingNext:['توزيع الأغراض مكتمل؛ بقي أن يؤكّد أصحابها ما جهّزوه.','Everything is assigned; the team still needs to confirm what is packed.','Tout est attribué ; il reste à confirmer ce qui est préparé.','分配已完成，团队仍需确认实际已打包的物品。','सभी सामान बाँट दिए गए हैं; अब दल को पैक मात्रा की पुष्टि करनी है।'],
 completeNext:['أكّد الفريق تجهيز جميع عناصر هذه القائمة. راجعوا ظروف الرحلة قبل الانطلاق.','The team has marked this checklist packed. Check trip conditions before departure.','L’équipe a terminé cette liste. Vérifiez les conditions du voyage avant le départ.','团队已确认清单全部打包完成。出发前请检查行程条件。','दल ने यह सूची पैक होने की पुष्टि की है। निकलने से पहले यात्रा की स्थितियाँ जाँचें।'],
 viewChecklist:['عرض قائمة التجهيز','View checklist','Voir la liste','查看清单','सूची देखें'],
 reviewAssignments:['مراجعة التوزيع','Review assignments','Vérifier les attributions','检查分配','बँटवारा जाँचें'],
 assignRemaining:['توزيع المتبقي','Assign the rest','Attribuer le reste','分配剩余物品','बाकी की जिम्मेदारी तय करें'],
 packMine:['تحديث أمتعتي','Update my packing','Actualiser ma préparation','更新我的打包','अपनी पैकिंग अपडेट करें'],
 viewRemaining:['عرض المتبقي','View remaining items','Voir le reste','查看剩余物品','बाकी सामान देखें'],
 viewAll:['عرض جميع الأغراض','View all items','Voir tous les articles','查看全部物品','सारा सामान देखें'],
 whoBrings:['من يُحضر ماذا؟','Who brings what','Qui apporte quoi','谁携带什么','कौन क्या लाएगा'],
 allocationHint:['المسند هو ما وافق الشخص على إحضاره؛ المجهّز هو ما وضعه في أمتعته. استخدموا الوحدة المذكورة في اسم الغرض.','Assigned is what someone agrees to bring; packed is what is already in their bags. Use the unit in the item’s name.','Attribué indique ce que la personne apporte ; préparé, ce qui est déjà dans ses bagages. Utilisez l’unité du nom de l’article.','分配数量是承诺携带的数量，已打包数量是实际装入行李的数量。请使用物品名称中的单位。','आवंटित मात्रा वह है जिसे व्यक्ति लाने को तैयार है; पैक मात्रा वह है जो बैग में रखी जा चुकी है। सामान के नाम में दी इकाई इस्तेमाल करें।'],
 filterItems:['تصفية الأغراض','Filter items','Filtrer les articles','筛选物品','सामान छाँटें'],
 filter_remaining:['تحتاج متابعة','Needs attention','À suivre','待处理','ध्यान देना है'],
 filter_mine:['مسؤولياتي','My items','Mes articles','我的物品','मेरी जिम्मेदारियाँ'],
 filter_unassigned:['بلا مسؤول','Unassigned','Non attribués','未分配','बिना जिम्मेदार व्यक्ति'],
 filter_all:['الكل','All','Tous','全部','सभी'],
 showingItems:['العناصر المطابقة','Matching items','Articles correspondants','符合条件的物品','मेल खाने वाला सामान'],
 noMine:['لم تتولَّ إحضار أي غرض بعد.','You have not claimed any items yet.','Vous n’avez encore pris aucun article en charge.','你尚未认领物品。','आपने अभी किसी सामान की जिम्मेदारी नहीं ली।'],
 noResponsibilities:['لم تُسند إليه أغراض بعد.','No items assigned yet.','Aucun article attribué pour le moment.','尚未分配物品。','अभी कोई सामान नहीं सौंपा गया।'],
 claimHint:['افتح جميع الأغراض واختر ما ستحضره، أو اطلب من المنظّم توزيع المسؤوليات.','Open all items and choose what to bring, or ask the organizer to assign responsibilities.','Affichez tous les articles et choisissez ce que vous apportez, ou demandez à l’organisateur.','查看全部物品并认领，或请组织者分配责任。','सारा सामान खोलकर चुनें कि क्या लाएँगे, या आयोजक से जिम्मेदारी बाँटने को कहें।'],
 nothingRemaining:['لا توجد عناصر تحتاج متابعة في هذه القائمة.','No items need attention in this checklist.','Aucun article à suivre dans cette liste.','此清单没有待处理的物品。','इस सूची में कोई सामान ध्यान देने के लिए बाकी नहीं है।'],
 everyoneAssigned:['لكل كمية مطلوبة مسؤول الآن.','Every required quantity has a carrier.','Chaque quantité requise est attribuée.','所有所需数量均已分配。','हर आवश्यक मात्रा के लिए जिम्मेदार व्यक्ति तय है।'],
 noItemsMember:['لم يشارك المنظّم أي عناصر بعد. اطلب منه تحديث قائمة الفريق.','The organizer has not shared any items yet. Ask them to update the team checklist.','L’organisateur n’a pas encore partagé d’articles. Demandez-lui d’actualiser la liste.','组织者尚未共享物品，请让其更新团队清单。','आयोजक ने अभी कोई सामान साझा नहीं किया। उनसे दल की सूची अपडेट करने को कहें।'],
 teamResponsibilities:['الأشخاص ومسؤولياتهم','People and responsibilities','Personnes et responsabilités','成员及其责任','लोग और जिम्मेदारियाँ'],
 joinedAccounts:['حسابات انضمت','joined accounts','comptes ayant rejoint','个已加入账号','जुड़े खाते'],
 managedNames:['أسماء يديرها المنظّم','organizer-managed names','noms gérés par l’organisateur','个由组织者管理的姓名','आयोजक द्वारा सँभाले नाम'],
 joined:['انضم بحسابه','Joined with an account','Compte connecté au groupe','已用账号加入','खाते से जुड़े'],
 managedName:['يديره المنظّم','Managed by organizer','Géré par l’organisateur','由组织者管理','आयोजक सँभालता है'],
 linkActive:['رابط صالح','Active link','Lien actif','链接有效','सक्रिय लिंक'],
 linkExpired:['الرابط منتهي','Link expired','Lien expiré','链接已过期','लिंक समाप्त'],
 noInvite:['لا يوجد رابط صالح','No active link','Aucun lien actif','无有效链接','कोई सक्रिय लिंक नहीं'],
 invitationTracking:['حالة الرابط لا تعني أنه أُرسل أو قُرئ. تظهر الحسابات المنضمة في قائمة الأشخاص.','Link status does not show delivery or views. Joined accounts appear under People and responsibilities.','L’état du lien ne confirme ni envoi ni lecture. Les comptes ayant rejoint figurent dans Personnes et responsabilités.','链接状态不表示已发送或已查看。已加入账号会显示在成员及其责任中。','लिंक की स्थिति भेजे या देखे जाने की पुष्टि नहीं करती। जुड़े खाते लोगों और जिम्मेदारियों में दिखते हैं।'],
 manageTeam:['إدارة الفريق والقائمة','Manage team and checklist','Gérer l’équipe et la liste','管理团队和清单','दल और सूची प्रबंधित करें'],
 aboutTeam:['عن هذا الفريق','About this team','À propos de l’équipe','关于此团队','इस दल के बारे में'],
 itemComplete:['مجهّز بالكامل','Fully packed','Entièrement préparé','全部已打包','पूरी तरह पैक'],
 inProgress:['بانتظار التجهيز','Awaiting packing','À préparer','等待打包','पैक होना बाकी'],
 chooseCarrier:['تحديد المسؤول','Choose who brings it','Choisir qui l’apporte','选择携带者','लाने वाला चुनें'],
 claimItem:['سأتولّى إحضاره','I’ll bring this','Je m’en charge','我来携带','मैं इसे लाऊँगा'],
 chooseTaskOwner:['تحديد مسؤول المهمة','Assign the task','Attribuer la tâche','分配任务','कार्य सौंपें'],
 claimTask:['سأتولّى هذه المهمة','I’ll do this task','Je prends cette tâche','我来完成此任务','मैं यह कार्य करूँगा'],
 noTaskOwner:['لم يتولَّ أحد هذه المهمة بعد.','No one has taken this task yet.','Personne n’a encore pris cette tâche.','尚无人认领此任务。','अभी किसी ने यह कार्य नहीं लिया।'],
 updateTask:['تحديث المهمة','Update task','Actualiser la tâche','更新任务','कार्य अपडेट करें'],
 updatePacked:['تحديث التجهيز','Update packing','Actualiser la préparation','更新打包','पैकिंग अपडेट करें'],
 completed:['مكتمل','Completed','Terminé','已完成','पूरा हुआ'],
 startFromTrip:['اختيار رحلة لتجهيزها معاً','Choose a trip to prepare together','Choisir un voyage à préparer ensemble','选择要一起准备的行程','साथ तैयारी के लिए यात्रा चुनें'],
 allTeams:['جميع الفرق','All teams','Toutes les équipes','全部团队','सभी दल'],
 yourTeams:['فرقك الحالية','Your teams','Vos équipes','你的团队','आपके दल'],
 chooseTeam:['افتح رحلة لتعرف ما بقي ومن سيحضر كل غرض.','Open a trip to see what remains and who is bringing each item.','Ouvrez un voyage pour voir ce qui reste et qui apporte chaque article.','打开行程，查看剩余准备事项及物品携带者。','यात्रा खोलकर देखें कि क्या बाकी है और कौन क्या लाएगा।'],
 startStepTrip:['اختر رحلة، ثم احفظ قائمة تجهيزها وزامنها.','Choose a trip, then save and sync its packing checklist.','Choisissez un voyage, puis enregistrez et synchronisez sa liste.','选择行程，保存并同步打包清单。','यात्रा चुनें, फिर उसकी पैकिंग सूची सहेजें और सिंक करें।'],
 startStepShare:['افتح تجهيز المجموعة من أدوات الرحلة، وراجع ما ستشاركه.','Open Group packing in the trip tools and review what you will share.','Ouvrez Préparation du groupe dans les outils du voyage et vérifiez le partage.','在行程工具中打开团队打包，检查将共享的内容。','यात्रा टूल में समूह की पैकिंग खोलें और साझा जानकारी जाँचें।'],
 startStepPack:['ادعُ رفاقك، ووزّع الأغراض، ثم تابعوا التجهيز.','Invite companions, assign items, then track packing together.','Invitez vos compagnons, attribuez les articles et suivez la préparation.','邀请同行者、分配物品，然后共同跟进打包。','साथियों को बुलाएँ, सामान बाँटें और मिलकर पैकिंग देखें।'],
 joinExisting:['للانضمام إلى فريق موجود، افتح رابط الدعوة الذي أرسله المنظّم.','To join an existing team, open the organizer’s invitation link.','Pour rejoindre une équipe, ouvrez le lien envoyé par l’organisateur.','要加入现有团队，请打开组织者的邀请链接。','मौजूदा दल में जुड़ने के लिए आयोजक का आमंत्रण लिंक खोलें।'],
 searchTeams:['البحث باسم الرحلة','Search by trip name','Rechercher un voyage','按行程名称搜索','यात्रा के नाम से खोजें'],
 filterTeams:['تصفية الفرق حسب دورك','Filter teams by your role','Filtrer par votre rôle','按你的角色筛选团队','अपनी भूमिका से दल छाँटें'],
 ownedTeams:['أنظّمها','I organize','J’organise','我组织的','मैं आयोजन करता हूँ'],
 joinedTeams:['انضممت إليها','I joined','J’ai rejoint','我加入的','मैं जुड़ा हूँ'],
 teamsFound:['فرق مطابقة','matching teams','équipes correspondantes','个匹配团队','मेल खाते दल'],
 openPreparation:['متابعة تجهيز الرحلة','Continue trip preparation','Continuer la préparation','继续行程准备','यात्रा की तैयारी जारी रखें'],
 noMatchingTeams:['لا توجد فرق تطابق البحث.','No teams match your search.','Aucune équipe ne correspond.','没有匹配的团队。','खोज से कोई दल नहीं मिला।'],
 clearFilters:['مسح البحث والتصفية','Clear search and filters','Effacer la recherche et les filtres','清除搜索和筛选','खोज और फ़िल्टर हटाएँ']
};
export function teamText(locale:Locale,key:string){return teamWords[key]?.[(['ar','en','fr','zh','hi'] as Locale[]).indexOf(locale)]??teamWords.unavailable[1]}
