import {translate,type Locale} from './terrain';
const copy:Record<string,string[]>={
 intro:['كل رحلة تبدأ بخطوة. اختر وجهتك، جهّز حقيبتك، ورتّب أيامك.','Choose a destination, pack your bag, and make room for adventure.','Choisissez une destination, préparez votre sac et organisez vos journées.','选好目的地，备好行囊，安排每一天。','गंतव्य चुनें, सामान तैयार करें और अपने दिन व्यवस्थित करें।'],
 all:['كل الرحلات','All trips','Tous les voyages','所有行程','सभी यात्राएँ'],
 overview:['نظرة عامة','Overview','Vue d’ensemble','概览','एक नज़र में'],
 packing:['التجهيزات','Packing','Équipement','装备','तैयारी'],
 itinerary:['برنامج الأيام','Day by day','Programme','每日安排','दिन का कार्यक्रम'],
 more:['خيارات الرحلة','Trip options','Options du voyage','行程选项','यात्रा विकल्प'],
 tools:['إدارة الرحلات','Manage trips','Gérer les voyages','管理行程','यात्राएँ प्रबंधित करें'],
 search:['ابحث عن رحلة أو وجهة','Search trips or destinations','Rechercher un voyage ou une destination','搜索行程或目的地','यात्रा या गंतव्य खोजें'],
 noResults:['لم نجد رحلة بهذا الاسم. جرّب كلمة أخرى.','No matching trips. Try another search.','Aucun voyage trouvé. Essayez un autre mot.','未找到匹配行程，请尝试其他关键词。','कोई यात्रा नहीं मिली। दूसरा शब्द आज़माएँ।'],
 clear:['مسح البحث','Clear search','Effacer la recherche','清除搜索','खोज हटाएँ'],
 datesLater:['التواريخ لاحقاً','Dates to be decided','Dates à définir','日期待定','तिथियाँ बाद में'],
 participants:['مشارك','travelers','participants','位同行者','यात्री'],
 emptyTitle:['إلى أين ستكون رحلتك القادمة؟','Where will you go next?','Quelle sera votre prochaine destination ?','下一站，去哪里？','अगली यात्रा कहाँ होगी?'],
 emptyHint:['ابدأ بوجهة واحدة. يمكنك إضافة التجهيزات والأنشطة بعد إنشاء الرحلة.','Start with a destination. Add equipment and activities after creating your trip.','Commencez par une destination. Ajoutez ensuite votre matériel et vos activités.','先选目的地，创建行程后再添加装备和活动。','गंतव्य से शुरू करें। यात्रा बनाने के बाद सामान और गतिविधियाँ जोड़ें।'],
 start:['ابدأ رحلة','Start a trip','Créer un voyage','开始规划','यात्रा शुरू करें'],
 create:['إنشاء الرحلة','Create trip','Créer le voyage','创建行程','यात्रा बनाएँ'],
 createHint:['الوجهة واسم الرحلة أولاً؛ يمكنك تحديد التواريخ وتعديل التفاصيل لاحقاً.','Start with a destination and a name. Dates and details can be updated later.','Choisissez une destination et un nom. Les dates et détails peuvent attendre.','先选目的地并命名，日期和详情可稍后修改。','पहले गंतव्य और नाम चुनें। तिथियाँ और विवरण बाद में बदल सकते हैं।'],
 choose:['اختر وجهتك','Choose your destination','Choisissez votre destination','选择目的地','गंतव्य चुनें'],
 custom:['أو حدد موقعاً آخر','Or choose another location','Ou choisissez un autre lieu','或选择其他地点','या दूसरी जगह चुनें'],
 details:['تفاصيل الرحلة','Trip details','Détails du voyage','行程详情','यात्रा विवरण'],
 editDetails:['تعديل التفاصيل','Edit details','Modifier les détails','编辑详情','विवरण बदलें'],
 optional:['خيارات إضافية','More details','Détails supplémentaires','更多详情','अन्य विवरण'],
 next:['خطوتك التالية','Your next step','Votre prochaine étape','下一步','अगला कदम'],
 nextHint:['ابدأ بالتجهيزات، ثم أضف الأنشطة التي تود القيام بها.','Start with your packing list, then add the activities you have in mind.','Préparez votre matériel, puis ajoutez les activités qui vous intéressent.','先准备装备清单，再添加想体验的活动。','पहले सामान की सूची तैयार करें, फिर अपनी गतिविधियाँ जोड़ें।'],
 packAction:['جهّز حقيبتك','Pack your bag','Préparez votre sac','准备行囊','सामान तैयार करें'],
 packHint:['قائمة واضحة، كميات قابلة للتعديل، واقتراحات حسب الرحلة.','A clear checklist, adjustable quantities, and suggestions for your trip.','Une liste claire, des quantités ajustables et des suggestions adaptées.','清晰的清单、可调数量与适合行程的建议。','स्पष्ट सूची, बदलने योग्य मात्रा और यात्रा के लिए सुझाव।'],
 dayAction:['رتّب أيام رحلتك','Plan your days','Organisez vos journées','安排每一天','अपने दिन व्यवस्थित करें'],
 dayHint:['أضف نشاطاً لكل يوم، مع الوقت والمكان عند الحاجة.','Add activities to each day, with a time and place when needed.','Ajoutez des activités à chaque jour, avec une heure et un lieu si nécessaire.','为每天添加活动，需要时填写时间和地点。','हर दिन की गतिविधियाँ जोड़ें और ज़रूरत पर समय व जगह भरें।'],
 completed:['عناصر مكتملة','items complete','éléments prêts','项已完成','वस्तुएँ पूरी'],
 activities:['أنشطة مخططة','planned activities','activités prévues','项计划活动','नियोजित गतिविधियाँ'],
 days:['أيام مخططة','days planned','journées prévues','天已安排','दिनों की योजना'],
 notAdded:['لم تُضف بعد','Not added yet','Pas encore ajouté','尚未添加','अभी नहीं जोड़ा गया'],
 savedHint:['التغييرات محفوظة على هذا الجهاز؛ تظهر حالة المزامنة أعلاه.','Changes saved on this device; see the sync status above.','Modifications enregistrées sur cet appareil ; voir la synchronisation ci-dessus.','更改已保存在此设备，同步状态见上方。','बदलाव इस डिवाइस पर सहेजे गए; सिंक स्थिति ऊपर देखें।'],
 saveHint:['احفظ تعديلاتك قبل مغادرة الرحلة.','Save your changes before leaving this trip.','Enregistrez vos modifications avant de quitter ce voyage.','离开行程前请保存更改。','यात्रा छोड़ने से पहले बदलाव सहेजें।'],
 saving:['جارٍ الحفظ…','Saving…','Enregistrement…','正在保存…','सहेजा जा रहा है…'],
 stay:['متابعة التعديل','Keep editing','Continuer à modifier','继续编辑','बदलाव जारी रखें'],
 discard:['تجاهل التعديلات','Discard changes','Abandonner les modifications','放弃更改','बदलाव छोड़ें'],
 discardHint:['لم تُحفظ آخر تعديلاتك. يمكنك العودة لإكمالها وحفظها، أو تجاهلها والانتقال.','Your latest changes are not saved. Keep editing to save them, or discard them and continue.','Vos dernières modifications ne sont pas enregistrées. Continuez pour les conserver, ou abandonnez-les.','最新更改尚未保存。可返回编辑并保存，或放弃更改后继续。','नए बदलाव सहेजे नहीं गए हैं। वापस जाकर सहेजें या उन्हें छोड़कर आगे बढ़ें।'],
 deleteHint:['سيُحذف سجل الرحلة وتجهيزاتها وبرنامجها. لن تُحذف معداتك من المخزون.','This removes the trip, its checklist and itinerary. Your inventory items are kept.','Le voyage, sa liste et son programme seront supprimés. Votre inventaire est conservé.','将删除行程及其清单和日程，装备库存将保留。','यात्रा, सामान सूची और कार्यक्रम हटेंगे। आपकी उपकरण सूची बनी रहेगी।'],
 checkOverview:['راجع بيانات الرحلة: الاسم، التواريخ، عدد المشاركين، وإحداثيات الموقع المخصص.','Check the trip name, dates, group size and any custom coordinates.','Vérifiez le nom, les dates, le nombre de participants et les coordonnées personnalisées.','请检查名称、日期、人数和自定义坐标。','नाम, तिथियाँ, यात्रियों की संख्या और कस्टम निर्देशांक जाँचें।'],
 checkPacking:['راجع أسماء التجهيزات وكمياتها قبل الحفظ.','Check equipment names and quantities before saving.','Vérifiez les noms et les quantités du matériel avant d’enregistrer.','保存前请检查装备名称和数量。','सहेजने से पहले सामान के नाम और मात्रा जाँचें।'],
 checkItinerary:['راجع الأنشطة المفتوحة: الاسم، رقم اليوم، والوقت والمنطقة الزمنية.','Check the open activities: title, day number, time and time zone.','Vérifiez les activités ouvertes : titre, numéro du jour, heure et fuseau horaire.','请检查展开的活动：名称、天数、时间和时区。','खुली गतिविधियों के नाम, दिन, समय और समय क्षेत्र जाँचें।'],
 tripMissing:['هذه الرحلة غير موجودة في حسابك الحالي. اختر رحلة من القائمة.','This trip is not in your current account. Choose a trip below.','Ce voyage ne figure pas dans votre compte actuel. Choisissez un voyage ci-dessous.','当前账户中未找到此行程，请选择下方行程。','इस खाते में यह यात्रा नहीं मिली। नीचे कोई यात्रा चुनें।'],
 packNote:['اكتمال القائمة يساعدك على التنظيم، ولا يضمن السلامة أو جاهزية المسار.','Checklist completion helps you organize; it does not guarantee safety or route readiness.','Compléter la liste aide à s’organiser, sans garantir la sécurité ni la préparation du parcours.','清单完成有助于整理，但不保证安全或路线准备充分。','सूची पूरी होना व्यवस्था में मदद करता है; यह सुरक्षा या मार्ग की तैयारी की गारंटी नहीं है।'],
 open:['فتح الرحلة','Open trip','Ouvrir le voyage','打开行程','यात्रा खोलें']
};
export const workspaceText=(locale:Locale,key:string)=>translate(locale,copy[key]??[key,key,key,key,key]);
