import type { Destination, PackingRule, SourceReference, SpeciesEntry } from '../toolkit-types';
import { UAE, UAE_TZ, reviewedAt, section, sectionOrder } from './shared';

export const sources: SourceReference[] = [
  { id: 'uae-al-marmoom-visit-reserve', title: 'Visit Dubai · Al Marmoom Desert Conservation Reserve', url: 'https://www.visitdubai.com/en/places-to-visit/marmoom-reserve', reviewedAt },
  { id: 'uae-al-marmoom-qudra-lakes', title: 'Visit Dubai · Al Qudra Lakes', url: 'https://www.visitdubai.com/en/places-to-visit/al-qudra-lakes', reviewedAt },
  { id: 'uae-al-marmoom-qudra-cycling', title: 'Visit Dubai · Al Qudra Cycle Track', url: 'https://www.visitdubai.com/en/places-to-visit/al-qudra-cycling-track', reviewedAt },
  { id: 'uae-al-marmoom-dm-protected-areas', title: 'Dubai Municipality · Digital platform for Dubai natural reserves network', url: 'https://www.dm.gov.ae/digital-platform-for-dubais-natural-reserves-network-to-raise-community-awareness/', reviewedAt },
  { id: 'uae-al-marmoom-dm-wildlife', title: 'Dubai Municipality · Dubai Protected Area wildlife', url: 'https://www.dm.gov.ae/dubai-protected-areas/wildlife/', reviewedAt },
  { id: 'uae-al-marmoom-event-environment', title: 'Al Marmoom Ultramarathon · Our environment', url: 'https://ultramarathon.ae/our-environment.php', reviewedAt },
  { id: 'uae-al-marmoom-ncm-weather', title: 'National Center of Meteorology · UAE weather and forecasts', url: 'https://www.ncm.gov.ae/?lang=en', reviewedAt },
  { id: 'uae-al-marmoom-dcaa-drones', title: 'Dubai Civil Aviation Authority · Drone registration', url: 'https://www.dcaa.gov.ae/services/aviation-safety-operations/drone-registration/', reviewedAt },
];

const species: SpeciesEntry[] = [
  {
    id: 'uae-al-marmoom-arabian-oryx',
    name: ['المها العربي', 'Arabian oryx', 'Oryx d’Arabie', '阿拉伯大羚羊', 'अरबी ओरिक्स'],
    description: ['تذكر صفحة بحيرات القدرة احتمال رؤية المها في موئله الطبيعي حول البحيرات داخل نطاق المحمية. اعتبر الرؤية ممكنة لا مضمونة، وراقب من مسافة.', 'Visit Dubai notes that oryx may be seen in natural habitat around the lakes in the reserve area. Treat sightings as possible, not promised, and watch from a distance.', 'Visit Dubai indique que l’oryx peut être observé dans son habitat autour des lacs. La rencontre reste possible, non garantie ; observez à distance.', '迪拜旅游局说明湖区周边可能看到大羚羊在自然栖息地活动。请把观察视为可能而非保证，并保持距离。', 'दुबई पर्यटन बताता है कि झीलों के पास प्राकृतिक आवास में ओरिक्स दिख सकता है। इसे संभावना समझें, गारंटी नहीं; दूरी से देखें।'],
    precaution: ['لا تطارده ولا تطعمه؛ ابتعد إذا غيّر الحيوان سلوكه أو اقترب من الطريق.', 'Do not chase or feed it; move back if the animal changes behaviour or approaches a road.', 'Ne le poursuivez pas et ne le nourrissez pas ; reculez si son comportement change ou s’il approche d’une route.', '不要追逐或投喂；若动物行为改变或靠近道路，请后退。', 'पीछा या भोजन न दें; व्यवहार बदले या सड़क के पास आए तो पीछे हटें।'],
    sourceIds: ['uae-al-marmoom-qudra-lakes'],
    coverage: 'local',
  },
  {
    id: 'uae-al-marmoom-desert-fox',
    name: ['ثعلب الصحراء', 'Desert fox', 'Renard du désert', '沙漠狐', 'रेगिस्तानी लोमड़ी'],
    description: ['تورد Visit Dubai الثعالب ضمن الحياة البرية الممكنة حول بحيرات القدرة. الظهور غالباً عابر؛ تجنب تحويله إلى فرصة إطعام أو تصوير قريب.', 'Visit Dubai lists foxes among wildlife that may be seen around Al Qudra Lakes. Encounters are usually brief; do not turn one into feeding or close photography.', 'Visit Dubai cite les renards parmi la faune visible autour des lacs. L’observation est souvent brève ; évitez nourrissage et photos rapprochées.', '迪拜旅游局把狐狸列为库德拉湖周边可能出现的野生动物。相遇通常短暂；不要投喂或近距离拍摄。', 'दुबई पर्यटन कुद्रा झीलों के पास दिख सकने वाले वन्यजीवों में लोमड़ी बताता है। मुलाकात छोटी हो सकती है; भोजन या नजदीकी तस्वीर न लें।'],
    precaution: ['أغلق الطعام والمخلفات جيداً؛ اقتراب الثعالب علامة على أن إدارة الطعام تحتاج تصحيحاً.', 'Seal food and waste; foxes coming close usually means food management needs correcting.', 'Fermez nourriture et déchets ; un renard qui approche signale souvent une mauvaise gestion des aliments.', '收好食物和垃圾；狐狸靠近通常说明食物管理需要改进。', 'भोजन और कचरा बंद रखें; लोमड़ी पास आए तो भोजन प्रबंधन सुधारें।'],
    sourceIds: ['uae-al-marmoom-qudra-lakes'],
    coverage: 'local',
  },
  {
    id: 'uae-al-marmoom-flamingo',
    name: ['الفلامنغو', 'Flamingo', 'Flamant', '火烈鸟', 'फ्लेमिंगो'],
    description: ['تذكر Visit Dubai الفلامنغو ضمن حياة البحيرات، وتذكر صفحة المحمية أنواع طيور عديدة في المنطقة. استخدم منظاراً ولا تعتمد على موسم واحد.', 'Visit Dubai mentions flamingos at the lakes and many bird species in the reserve area. Use binoculars and do not rely on a single season.', 'Visit Dubai mentionne les flamants aux lacs et de nombreuses espèces d’oiseaux dans la réserve. Utilisez des jumelles, sans compter sur une seule saison.', '迪拜旅游局提到湖区有火烈鸟，保护区一带有多种鸟类。请用望远镜观察，不要只依赖某一个季节。', 'दुबई पर्यटन झीलों पर फ्लेमिंगो और क्षेत्र में अनेक पक्षी बताता है। दूरबीन रखें और केवल एक मौसम पर निर्भर न रहें।'],
    precaution: ['ابق على حافة المشاهدة ولا تدخل الماء أو مناطق الأعشاش؛ القرب الزائد يفسد الرصد ويزعج الطيور.', 'Stay on viewing edges and do not enter water or nesting areas; close approach spoils watching and disturbs birds.', 'Restez aux points d’observation, sans entrer dans l’eau ni les nids ; l’approche dérange les oiseaux.', '请在观赏边界停留，不要进入水域或筑巢区；靠太近会干扰鸟类。', 'देखने की सीमा पर रहें, पानी या घोंसले वाले भाग में न जाएँ; पास जाना पक्षियों को परेशान करता है।'],
    sourceIds: ['uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-visit-reserve'],
    coverage: 'local',
  },
  {
    id: 'uae-al-marmoom-horned-viper',
    name: ['الأفعى المقرنة', 'Horned viper', 'Vipère à cornes', '角蝰', 'सींगदार वाइपर'],
    description: ['توثق صفحة الحياة البرية في مناطق دبي المحمية هذا النوع في محمية صحراوية أخرى؛ لذلك يرد هنا مثالاً صحراوياً لا سجلاً مؤكداً للموقع.', 'Dubai Municipality documents this species in another Dubai desert reserve; here it is a terrain example, not a confirmed record for Al Marmoom.', 'La Municipalité de Dubaï le documente dans une autre réserve désertique ; ici, c’est un exemple de terrain, non un relevé confirmé.', '迪拜市政部门在另一处沙漠保护区记录了此类蛇；此处仅作沙漠地形示例，并非本地确认记录。', 'दुबई नगरपालिका इसे एक अन्य रेगिस्तानी अभयारण्य में दर्ज करती है; यहाँ यह भूभाग का उदाहरण है, स्थानीय प्रमाण नहीं।'],
    precaution: ['لا تضع يداً في جحر أو تحت حجر، واستعمل مصباحاً ليلاً. عند اللدغ اتصل بالإسعاف ولا تحاول العلاج الميداني.', 'Do not put hands in holes or under stones, and use a light at night. If bitten, call ambulance services and avoid field treatment.', 'Ne mettez pas les mains dans les trous ou sous les pierres ; utilisez une lampe la nuit. En cas de morsure, appelez les secours.', '不要把手伸入洞穴或石下，夜间用灯。若被咬，请呼叫救护，避免现场自行处理。', 'बिल या पत्थर के नीचे हाथ न डालें और रात में रोशनी रखें। काटने पर एम्बुलेंस बुलाएँ, खुद इलाज न करें।'],
    sourceIds: ['uae-al-marmoom-dm-wildlife', 'uae-emergency'],
    coverage: 'terrain-example',
  },
  {
    id: 'uae-al-marmoom-scorpion',
    name: ['العقرب الصحراوي', 'Desert scorpion', 'Scorpion du désert', '沙漠蝎', 'रेगिस्तानी बिच्छू'],
    description: ['لم نجد في المصادر المقروءة سجلاً رسمياً للعقارب في الموقع نفسه. يرد هنا كتذكير عام ببيئات الرمال الجافة، لا كضمان وجود.', 'The fetched sources did not give an official scorpion record for this exact place. This is a dry-sand terrain reminder, not a guaranteed presence.', 'Les sources lues ne donnent pas de relevé officiel au site. C’est un rappel lié au sable sec, sans garantir la présence.', '已读来源未给出此地蝎子的官方记录。这里仅作干燥沙地提醒，不保证存在。', 'पढ़े गए स्रोतों में इस स्थान पर बिच्छू का आधिकारिक रिकॉर्ड नहीं मिला। यह सूखी रेत का सामान्य स्मरण है, उपस्थिति की गारंटी नहीं।'],
    precaution: ['انفض الحذاء والفرش قبل الاستخدام، ولا تمش حافياً قرب المخيم بعد الغروب.', 'Shake shoes and bedding before use, and do not walk barefoot near camp after sunset.', 'Secouez chaussures et couchage avant usage, et ne marchez pas pieds nus près du camp après le coucher du soleil.', '使用前抖动鞋子和寝具，日落后不要在营地附近赤脚行走。', 'जूते और बिस्तर उपयोग से पहले झाड़ें, सूर्यास्त के बाद शिविर के पास नंगे पाँव न चलें।'],
    sourceIds: ['uae-al-marmoom-dm-wildlife'],
    coverage: 'terrain-example',
  },
];

export const destination: Destination = {
  id: 'al-marmoom',
  country: UAE,
  terrainId: 'desert',
  terrainIndex: 0,
  lat: 24.8401159,
  lon: 55.35163,
  timezone: UAE_TZ,
  names: ['محمية المرموم وبحيرات القدرة', 'Al Marmoom and Al Qudra Lakes', 'Al Marmoom et lacs Al Qudra', '阿勒马尔穆姆与库德拉湖', 'अल मरमूम और अल कुद्रा झीलें'],
  summary: ['محمية صحراوية وبحيرات اصطناعية قرب دبي؛ للطيور وركوب الدراجات والتخييم المنظم مع تحقق يومي من القواعد والطقس.', 'Dubai desert reserve and man-made lakes for birdwatching, cycling and regulated camping, with same-day checks on rules and weather.', 'Réserve désertique et lacs artificiels de Dubaï, pour oiseaux, vélo et camping encadré, avec vérification le jour même.', '迪拜沙漠保护区与人工湖，可观鸟、骑行和按规定露营，出发当天核对规则与天气。', 'दुबई का रेगिस्तानी अभयारण्य और कृत्रिम झीलें; पक्षी, साइकिलिंग और नियमबद्ध शिविर, उसी दिन मौसम व नियम जाँचें।'],
  image: '/images/desert.jpg',
  imageIsIllustrative: true,
  sourceIds: ['uae-al-marmoom-visit-reserve', 'uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-qudra-cycling', 'uae-al-marmoom-dm-protected-areas'],
  species,
  sections: [
    section('place', ['تقع بحيرات القدرة داخل نطاق محمية المرموم الصحراوية كما تذكر Visit Dubai، وتعرض البلدية المحمية ضمن شبكة مناطق دبي الطبيعية. مؤشر الخريطة عند البحيرات تقريبي للمنطقة وليس بداية مسار أو موقفاً مضموناً؛ الصورة توضيحية. تحقق من حالة الوصول في يوم الزيارة.', 'Visit Dubai places Al Qudra Lakes in the Al Marmoom reserve area, and Dubai Municipality lists the reserve in Dubai’s protected-areas network. The map point is an approximate area marker, not a trailhead or guaranteed parking place; the image is illustrative. Check access on the day.', 'Visit Dubai situe les lacs Al Qudra dans la réserve d’Al Marmoom, que la Municipalité inscrit au réseau des espaces protégés. Le point de carte est approximatif, pas un départ de sentier ni un stationnement garanti ; image illustrative. Vérifiez l’accès le jour même.', '迪拜旅游局将库德拉湖列在马尔穆姆保护区范围内，迪拜市政部门也把该保护区列入自然保护地网络。地图点只是大致区域标记，不是步道入口或保证停车点；图片为示意。当天核实通行情况。', 'दुबई पर्यटन कुद्रा झीलों को मरमूम अभयारण्य क्षेत्र में बताता है और नगरपालिका इसे संरक्षित क्षेत्रों के नेटवर्क में रखती है। नक्शे का बिंदु केवल अनुमानित क्षेत्र है, पगडंडी या पक्की पार्किंग नहीं; चित्र उदाहरणात्मक है। उसी दिन पहुँच जाँचें।'], ['uae-al-marmoom-visit-reserve', 'uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-dm-protected-areas']),
    section('equipment', ['استنتاج عملي: لأن Visit Dubai تعرض بحيرات ونشاطاً صحراوياً ومسار دراجات، جهز ماءً احتياطياً وملاحة وهاتفاً مشحوناً ومصباحاً. للركوب، لا تفترض توفر الدراجة أو أدوات الإصلاح رغم ذكر التأجير ومحطات التوقف؛ أكد ساعات المشغل قبل الانطلاق.', 'Practical inference: because Visit Dubai describes lakes, desert activity and a cycle track, carry spare water, navigation, a charged phone and a light. For cycling, do not assume a bike or repair kit is available even where rentals and rest stops are mentioned; confirm operator hours before departure.', 'Déduction pratique : Visit Dubai décrit lacs, activités désertiques et piste cyclable ; prévoyez eau de réserve, navigation, téléphone chargé et lampe. Pour le vélo, ne supposez pas location ou réparation disponibles malgré les points cités ; confirmez les horaires.', '实用推断：迪拜旅游局介绍湖区、沙漠活动和骑行道，因此应带备用水、导航、充满电的手机和照明。骑行时，即使资料提到租车和休息点，也不要假定一定有车或维修工具；出发前确认营业时间。', 'व्यावहारिक निष्कर्ष: दुबई पर्यटन झीलें, रेगिस्तानी गतिविधि और साइकिल ट्रैक बताता है, इसलिए अतिरिक्त पानी, दिशा साधन, चार्ज फोन और रोशनी रखें। किराया और विश्राम स्थल लिखे हों तब भी साइकिल या मरम्मत सामान मानकर न चलें; समय पहले पूछें।'], ['uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-qudra-cycling', 'uae-al-marmoom-ncm-weather']),
    section('clothing', ['نصيحة عامة وليست قاعدة محلية: اختر ملابس فاتحة تغطي الجلد وقبعة ونظارة، مع طبقة خفيفة للمساء إذا طال البقاء. للمشي على الرمل استخدم حذاءً مغلقاً، وللدراجات ملابس مرئية وقفازات مناسبة. عدّل الخطة حسب توقعات مركز الأرصاد.', 'General advice, not a local requirement: use light-coloured clothing that covers skin, a hat and sunglasses, with a light layer for a longer evening stay. For sand, wear closed shoes; for cycling, use visible clothing and suitable gloves. Adjust the plan to NCM forecasts.', 'Conseil général, sans obligation locale : vêtements clairs couvrants, chapeau et lunettes, avec une couche légère si la soirée se prolonge. Chaussures fermées sur le sable ; vêtements visibles et gants pour le vélo. Adaptez selon la météo du NCM.', '一般建议，并非当地规定：穿浅色遮蔽衣物，戴帽子和太阳镜；若停留到夜间，备轻薄外层。沙地穿包脚鞋；骑行穿醒目衣物并戴合适手套。按国家气象中心预报调整计划。', 'सामान्य सलाह, स्थानीय नियम नहीं: हल्के रंग के ढकने वाले कपड़े, टोपी और चश्मा रखें; शाम तक रुकें तो हल्की परत लें। रेत में बंद जूते, साइकिलिंग में दिखने वाले कपड़े और दस्ताने रखें। मौसम केंद्र के पूर्वानुमान से योजना बदलें।'], ['uae-al-marmoom-ncm-weather', 'uae-al-marmoom-qudra-cycling']),
    section('transport', ['تذكر Visit Dubai أن الوصول إلى المحمية أسهل بالسيارة، وأن بحيرات القدرة يمكن بلوغها بسيارة عادية أو دفع رباعي لأن الرمل مضغوط قرب مناطق الوصول. لا تعامل ذلك إذناً للقيادة خارج المسارات؛ رتّب العودة والوقود، ولا تعتمد على مركبة واحدة بلا خطة اتصال.', 'Visit Dubai says the reserve is easiest by car and that Al Qudra Lakes can be reached by regular car or 4×4 where sand is compacted near access areas. This is not permission to drive off-track; plan return transport and fuel, and avoid relying on one vehicle without a contact plan.', 'Visit Dubai indique que l’accès est plus simple en voiture et que les lacs sont atteignables en voiture ordinaire ou 4×4 sur sable compacté. Ce n’est pas une autorisation hors piste ; prévoyez retour, carburant et contact.', '迪拜旅游局说明驾车前往较方便，库德拉湖在压实沙地接近区可用普通车或四驱车到达。这不等于允许越野行驶；请安排返程和燃油，不要在无联络计划下只依赖一辆车。', 'दुबई पर्यटन के अनुसार कार से पहुँचना आसान है और दबे हुए रेत वाले पहुँच भागों तक सामान्य कार या चार पहिया वाहन जा सकता है। यह ऑफ ट्रैक चलाने की अनुमति नहीं है; वापसी, ईंधन और संपर्क योजना रखें।'], ['uae-al-marmoom-visit-reserve', 'uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-event-environment']),
    section('season', ['الصيف والحرارة يغيران صلاحية النشاط بسرعة. لا نورد رقماً غير ثابت هنا؛ استخدم توقعات مركز الأرصاد في اليوم نفسه، ويفضل تقديم المشي أو الدراجات إلى الصباح الباكر كما تنصح صفحة المسار. الرياح والغبار قد يلغيان الرصد حتى مع سماء صافية.', 'Summer heat can change whether an activity is sensible. No fixed temperature threshold is given here; use the NCM forecast on the day, and favour early starts as the cycle-track page advises. Wind or dust can make birdwatching or riding unsuitable even under clear skies.', 'La chaleur estivale peut rendre une activité déraisonnable. Aucun seuil fixe ici : consultez le NCM le jour même et privilégiez le départ tôt conseillé pour la piste cyclable. Vent ou poussière peuvent annuler l’observation ou le vélo.', '夏季高温会迅速改变活动是否合适。这里不设固定温度阈值；请在当天查看国家气象中心预报，并按骑行道页面建议尽量早出发。即使晴天，风沙也可能使观鸟或骑行不适宜。', 'गर्मी गतिविधि को जल्दी अनुपयुक्त बना सकती है। यहाँ कोई निश्चित ताप सीमा नहीं दी गई; उसी दिन मौसम केंद्र देखें और साइकिल पृष्ठ की तरह जल्दी शुरुआत चुनें। हवा या धूल साफ आसमान में भी पक्षी दर्शन या सवारी रोक सकती है।'], ['uae-al-marmoom-ncm-weather', 'uae-al-marmoom-qudra-cycling']),
    section('nature', ['تركز المصادر على الحياة البرية والطيور حول البحيرات، وتذكر البلدية أن منصة المحميات تعرض الأنواع والموائل وتدعم الرصد والتعليم. حدود التعرف: لا نؤكد نوعاً من صورة أو أثر بلا دليل؛ استخدم منظاراً، ولا تجمع نباتات أو عيداناً أو صخوراً.', 'The sources emphasise wildlife and birds around the lakes, and Dubai Municipality says the protected-areas platform covers species, habitats, monitoring and education. Identification limit: do not confirm a species from a photo or track alone; use binoculars and do not collect plants, sticks or rocks.', 'Les sources soulignent faune et oiseaux autour des lacs, et la Municipalité indique que la plateforme couvre espèces, habitats, suivi et éducation. Limite d’identification : ne confirmez pas une espèce par photo ou trace seule ; utilisez des jumelles et ne prélevez rien.', '资料强调湖区周边的野生动物和鸟类；迪拜市政部门说明保护地平台涵盖物种、栖息地、监测和教育。识别限制：不要仅凭照片或足迹确认物种；使用望远镜，不采集植物、枝条或石块。', 'स्रोत झीलों के आसपास वन्यजीव और पक्षियों पर जोर देते हैं, और नगरपालिका बताती है कि मंच प्रजाति, आवास, निगरानी और शिक्षा देता है। पहचान सीमा: केवल फोटो या पदचिह्न से प्रजाति न मानें; दूरबीन उपयोग करें और पौधे, लकड़ी या पत्थर न लें।'], ['uae-al-marmoom-visit-reserve', 'uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-dm-protected-areas', 'uae-al-marmoom-event-environment']),
    section('hazard', ['المخاطر الأساسية هي الانكشاف والحرارة والضياع القصير واضطراب الحياة البرية. تؤكد قواعد الحدث عدم الإطعام، منع النار خارج المناطق المحددة، ومنع القيادة خارج المسارات. احمل ماءً واتصالاً، وللطوارئ في الإمارات: الشرطة 999، الإسعاف 998، الدفاع المدني 997.', 'Main hazards are exposure, heat, short-range disorientation and wildlife disturbance. Event rules state no feeding, no fires except designated areas, and no off-roading. Carry water and communications. In UAE emergencies call police 999, ambulance 998 or civil defence 997.', 'Les risques principaux sont l’exposition, la chaleur, une désorientation locale et le dérangement de la faune. Les règles de l’événement interdisent nourrissage, feu hors zones désignées et hors piste. Eau et communication sont nécessaires. Urgence : police 999, ambulance 998, défense civile 997.', '主要风险是暴露、高温、短距离迷失和干扰野生动物。赛事环保规则要求不投喂、只在指定区域用火、禁止越野。请携带水和通信工具。阿联酋紧急电话：警察999、救护998、民防997。', 'मुख्य जोखिम खुला भूभाग, गर्मी, छोटी दूरी में दिशा भ्रम और वन्यजीवों को परेशान करना है। आयोजन नियम भोजन देने, निर्धारित क्षेत्र से बाहर आग और ऑफ रोडिंग रोकते हैं। पानी और संपर्क साधन रखें। आपातकाल: पुलिस 999, एम्बुलेंस 998, नागरिक रक्षा 997।'], ['uae-al-marmoom-event-environment', 'uae-al-marmoom-ncm-weather', 'uae-emergency']),
    section('visit', ['اختر النشاط وفق القدرة: مراقبة طيور هادئة عند البحيرات، جولة قصيرة، ركوب على مسار القدرة، أو تخييم منظم. يذكر مسار القدرة 86 كم من المسارات؛ لا يلزمك قطعها كاملة. أكد الحجز أو التأجير وساعات المرافق، وراجع اللوحات في الموقع في اليوم نفسه.', 'Match the activity to ability: quiet birdwatching by the lakes, a short visit, riding on Al Qudra track, or regulated camping. The cycle-track page states 86 km of paths; you do not need to ride all of it. Confirm bookings, rentals and facility hours, and read signs on the day.', 'Adaptez l’activité : observation calme aux lacs, courte visite, vélo sur la piste Al Qudra ou camping encadré. La page cyclable indique 86 km de pistes ; inutile de tout parcourir. Confirmez réservations, location et horaires, puis lisez les panneaux le jour même.', '按能力选择活动：在湖边安静观鸟、短暂停留、在库德拉骑行道骑车，或按规定露营。骑行道页面说明有86公里路径；不必全部骑完。确认预订、租赁和设施时间，当天阅读现场标识。', 'क्षमता के अनुसार गतिविधि चुनें: झील किनारे शांत पक्षी दर्शन, छोटी यात्रा, कुद्रा ट्रैक पर सवारी या नियमबद्ध शिविर। साइकिल पृष्ठ 86 किमी पथ बताता है; सब पूरा करना जरूरी नहीं। बुकिंग, किराया और समय पक्का करें, उसी दिन संकेत पढ़ें।'], ['uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-qudra-cycling', 'uae-al-marmoom-visit-reserve']),
    section('rules', ['القواعد العملية الموثقة: لا تطعم الحياة البرية، لا تأخذ نباتات أو عيداناً أو صخوراً، لا تقد خارج المناطق المحددة، ولا تشعل ناراً إلا في منطقة محددة أو وعاء شواء مناسب. الطائرات المسيّرة تحتاج تحققاً من تسجيل وتصريح دبي. للتخييم، استخدم المناطق المسموح بها وتحقق في اليوم نفسه.', 'Documented practical rules: do not feed wildlife, do not take plants, sticks or rocks, do not drive outside designated areas, and do not light fires except in a designated area or suitable barbecue container. Drones require checking Dubai registration and permission. For camping, use allowed areas and check on the day.', 'Règles pratiques documentées : ne nourrissez pas la faune, ne prenez ni plantes, ni bois, ni pierres, ne conduisez pas hors zones désignées et n’allumez du feu que dans une zone ou un barbecue adapté. Pour les drones, vérifiez enregistrement et autorisation à Dubaï. Campez seulement où c’est permis.', '已记录的实用规则：不投喂野生动物，不带走植物、枝条或石块，不在指定区域外驾车；只在指定地点或合适烧烤容器中用火。无人机需核实迪拜登记和许可。露营只在允许区域，并当天确认。', 'दर्ज व्यावहारिक नियम: वन्यजीवों को भोजन न दें, पौधे, लकड़ी या पत्थर न लें, निर्धारित क्षेत्र से बाहर वाहन न चलाएँ, और आग केवल निर्धारित स्थान या उचित बारबेक्यू पात्र में जलाएँ। ड्रोन के लिए दुबई पंजीकरण व अनुमति जाँचें। शिविर केवल अनुमति वाले क्षेत्र में करें।'], ['uae-al-marmoom-event-environment', 'uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-dcaa-drones', 'uae-emergency']),
  ],
} as Destination & { country: typeof UAE };

if (destination.sections.map((item) => item.id).join(',') !== sectionOrder.join(',')) {
  throw new Error('Al Marmoom section order mismatch');
}

export const rules: PackingRule[] = [
  {
    id: 'uae-al-marmoom-water-reserve',
    version: 1,
    equipmentId: 'uae-al-marmoom-water-reserve',
    label: ['ماء احتياطي للحرارة', 'Heat water reserve', 'Réserve d’eau pour chaleur', '高温备用饮水', 'गर्मी के लिए अतिरिक्त पानी'],
    category: 'essentials',
    terrainIds: ['desert'],
    activities: ['cycling', 'camping', 'walking'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['مسار صحراوي وبحيرات مكشوفة؛ واستنتاج عملي من إرشاد البدء المبكر وتوقعات الأرصاد أن يحمل كل شخص ماءه الاحتياطي.', 'Open desert track and lakes; practical inference from early-start advice and NCM forecasts is that each person carries reserve water.', 'Piste et lacs exposés ; déduction pratique des départs tôt et de la météo NCM : chaque personne garde une réserve d’eau.', '沙漠骑行道和湖区无遮蔽；根据早出发建议和气象预报，实用推断是每人携带备用水。', 'खुला रेगिस्तानी ट्रैक और झीलें; जल्दी शुरू करने की सलाह और मौसम से निष्कर्ष है कि हर व्यक्ति अतिरिक्त पानी रखे।'],
    sourceIds: ['uae-al-marmoom-qudra-cycling', 'uae-al-marmoom-ncm-weather'],
    coverage: 'local',
    destinationIds: ['al-marmoom'],
  },
  {
    id: 'uae-al-marmoom-contained-grill',
    version: 1,
    equipmentId: 'uae-al-marmoom-contained-grill',
    label: ['وعاء شواء مرتفع', 'Raised barbecue container', 'Barbecue surélevé', '架高烧烤容器', 'ऊँचा बारबेक्यू पात्र'],
    category: 'safety',
    terrainIds: ['desert'],
    activities: ['camping'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: false,
    reason: ['تذكر Visit Dubai استخدام وعاء للشواء بدلاً من النار على الرمل، وتؤكد قواعد المرموم عدم إشعال النار إلا في مناطق محددة.', 'Visit Dubai says to use a barbecue container rather than fire on sand, and Al Marmoom rules state fires only in designated areas.', 'Visit Dubai demande un récipient de barbecue plutôt qu’un feu sur le sable, et les règles d’Al Marmoom limitent le feu aux zones désignées.', '迪拜旅游局要求用烧烤容器而不是在沙上生火，马尔穆姆规则也说明只在指定区域用火。', 'दुबई पर्यटन रेत पर आग के बजाय बारबेक्यू पात्र कहता है, और मरमूम नियम आग को निर्धारित क्षेत्रों तक सीमित रखते हैं।'],
    sourceIds: ['uae-al-marmoom-qudra-lakes', 'uae-al-marmoom-event-environment'],
    coverage: 'local',
    destinationIds: ['al-marmoom'],
  },
  {
    id: 'uae-al-marmoom-waste-bags',
    version: 1,
    equipmentId: 'uae-al-marmoom-waste-bags',
    label: ['أكياس نفايات محكمة', 'Seal-able waste bags', 'Sacs à déchets fermables', '可封口垃圾袋', 'बंद होने वाले कचरा बैग'],
    category: 'essentials',
    terrainIds: ['desert'],
    activities: ['camping', 'walking', 'cycling'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: false,
    reason: ['قواعد البيئة في المرموم تمنع رمي المخلفات، وتطلب عدم أخذ أو ترك ما يضر الموئل؛ الأكياس المحكمة تسهل إخراج الطعام والفحم البارد.', 'Al Marmoom environment rules prohibit littering and leaving or taking items that affect habitat; seal-able bags help pack out food waste and cold charcoal.', 'Les règles environnementales interdisent les déchets et les prélèvements ; des sacs fermables aident à remporter restes et charbon froid.', '马尔穆姆环保规则禁止乱扔垃圾及带走或留下影响栖息地的物品；可封口袋便于带走食物垃圾和冷炭。', 'मरमूम पर्यावरण नियम कचरा और आवास को प्रभावित करने वाली चीजें छोड़ना या लेना रोकते हैं; बंद बैग भोजन कचरा और ठंडा कोयला वापस ले जाने में मदद करते हैं।'],
    sourceIds: ['uae-al-marmoom-event-environment'],
    coverage: 'local',
    destinationIds: ['al-marmoom'],
  },
  {
    id: 'uae-al-marmoom-bike-light',
    version: 1,
    equipmentId: 'uae-al-marmoom-bike-light',
    label: ['إضاءة دراجة احتياطية', 'Spare bike light', 'Éclairage vélo de réserve', '备用自行车灯', 'अतिरिक्त साइकिल लाइट'],
    category: 'safety',
    terrainIds: ['desert'],
    activities: ['cycling'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['مسار القدرة صحراوي طويل؛ واستنتاج عملي عند البدء المبكر أو التأخر قرب الغروب أن يحمل كل راكب إضاءة لا تعتمد على التأجير.', 'Al Qudra is a long desert cycling route; practical inference for early starts or delays near sunset is that each rider carries a light independent of rentals.', 'Al Qudra est un long itinéraire désertique ; pour un départ tôt ou un retard au couchant, chaque cycliste devrait avoir sa propre lampe.', '库德拉是较长的沙漠骑行路线；若清晨出发或日落前后延误，实用推断是每名骑手携带不依赖租赁的车灯。', 'कुद्रा लंबा रेगिस्तानी साइकिल मार्ग है; जल्दी शुरुआत या सूर्यास्त के पास देरी में हर सवार किराये से अलग अपनी रोशनी रखे।'],
    sourceIds: ['uae-al-marmoom-qudra-cycling'],
    coverage: 'local',
    destinationIds: ['al-marmoom'],
  },
];

