import type { Destination, PackingRule, SourceReference, SpeciesEntry } from '../toolkit-types';
import { UAE, UAE_TZ, reviewedAt, section, sectionOrder } from './shared';

export const sources: SourceReference[] = [
  { id: 'uae-hatta-visit-hatta-main', title: 'Visit Hatta · Discover the charming natural beauty of Hatta', url: 'https://www.visithatta.com/en', reviewedAt },
  { id: 'uae-hatta-dm-trails', title: 'Dubai Municipality · Discover Hatta’s mountain trails', url: 'https://www.dm.gov.ae/dubai_more/discover-hattas-mountain-trails/', reviewedAt },
  { id: 'uae-hatta-hiking', title: 'Visit Hatta · Hiking in Hatta', url: 'https://www.visithatta.com/en/play/hiking', reviewedAt },
  { id: 'uae-hatta-mountain-biking', title: 'Visit Hatta · Mountain Biking in Hatta', url: 'https://www.visithatta.com/en/play/mount-biking', reviewedAt },
  { id: 'uae-hatta-kayak', title: 'Visit Hatta · Hatta Kayak', url: 'https://www.visithatta.com/en/play/hatta-kayak', reviewedAt },
  { id: 'uae-hatta-wadi-hub', title: 'Visit Hatta · Hatta Wadi Hub', url: 'https://www.visithatta.com/en/offer/hatta-wadi-hub', reviewedAt },
  { id: 'uae-hatta-stay', title: 'Visit Hatta · Stay in Hatta', url: 'https://www.visithatta.com/en/stay', reviewedAt },
  { id: 'uae-hatta-ncm-warnings', title: 'National Center of Meteorology · Early Warnings for All', url: 'https://ew4all.ncm.gov.ae/?lang=en', reviewedAt },
  { id: 'uae-hatta-gcaa-drones', title: 'General Civil Aviation Authority · UAS registration', url: 'https://www.gcaa.gov.ae/en/pages/UASRegistration.aspx', reviewedAt },
  { id: 'uae-hatta-honeybee-garden', title: 'Hatta Honey · Honeybee Garden', url: 'https://www.hattahoney.ae/honeybee-garden/', reviewedAt },
];

const species: SpeciesEntry[] = [
  {
    id: 'uae-hatta-honeybee',
    name: ['نحل العسل في حتا', 'Hatta honeybee', 'Abeille domestique de Hatta', '哈塔蜜蜂', 'हट्टा मधुमक्खी'],
    description: ['يوثق مصدر حديقة النحل في حتا خلايا نشطة ونباتات محلية مثل السمر والغاف والسدر؛ لذلك تسجل هذه الملاحظة كمحلية للحديقة، لا لكل مسار جبلي.', 'The Hatta Honeybee Garden source documents active hives and native trees such as samar, ghaf and sidr, so this is local to that garden, not a claim for every mountain trail.', 'La source du jardin apicole de Hatta mentionne des ruches actives et des arbres indigènes comme le samar, le ghaf et le sidr ; l’indication est locale au jardin, pas à chaque sentier.', '哈塔蜜蜂园资料记录有活跃蜂箱，以及萨马尔、加夫和枣莲木等本地树木；此记录限于该园，不代表每条山路。', 'हट्टा मधुमक्खी उद्यान स्रोत सक्रिय छत्तों और समर, गाफ तथा सिद्र जैसे स्थानीय पेड़ों का उल्लेख करता है; यह जानकारी उद्यान तक सीमित है, हर पर्वतीय पगडंडी तक नहीं।'],
    precaution: ['راقب خلايا النحل من المسافة التي يحددها المشغّل، ولا تلمس المعدات أو الأشجار المزهرة. من لديه حساسية للسعات يجب أن يحمل علاجه الموصوف.', 'Observe hives only at the operator’s distance, and do not handle equipment or flowering trees. Anyone with sting allergy should carry prescribed medicine.', 'Observez les ruches à la distance fixée par l’exploitant, sans toucher au matériel ni aux arbres en fleur. Les personnes allergiques doivent porter leur traitement prescrit.', '只在运营方规定距离外观察蜂箱，不触碰设备或开花树木。对蜇刺过敏者应携带处方药。', 'संचालक द्वारा तय दूरी से ही छत्ते देखें, उपकरण या फूलदार पेड़ों को न छुएँ। डंक से एलर्जी वाले लोग अपनी निर्धारित दवा साथ रखें।'],
    sourceIds: ['uae-hatta-honeybee-garden'],
    coverage: 'local',
  },
  {
    id: 'uae-hatta-mountain-goat',
    name: ['ماعز جبلي بري', 'Wild mountain goat', 'Chèvre sauvage de montagne', '野山羊', 'जंगली पहाड़ी बकरी'],
    description: ['مثال تضاريس فقط: الجبال والوديان الصخرية قد تلائم مجترات جبلية في المنطقة الأوسع، لكن وجود هذا الحيوان في نقطة حتا المحددة غير موثق في المصادر المقروءة.', 'Terrain example only: rocky mountains and wadis can suit wild caprids in the wider region, but presence at this exact Hatta marker is not verified by the read sources.', 'Exemple de relief seulement : les montagnes et oueds rocheux peuvent convenir aux caprinés sauvages de la région, mais leur présence à ce point de Hatta n’est pas vérifiée.', '仅为地形示例：岩石山地和干谷可能适合更广区域的野生山羊类动物，但已读资料未核实其在此哈塔标记点出现。', 'केवल भूभाग उदाहरण: चट्टानी पहाड़ और वादी व्यापक क्षेत्र की जंगली बकरी प्रजातियों के अनुकूल हो सकते हैं, पर इस हट्टा स्थान पर उपस्थिति सत्यापित नहीं है।'],
    precaution: ['لا تقترب من الحيوان أو تطعمه إن رأيته؛ اترك له ممر هروب وابتعد عن الحواف أثناء التصوير.', 'If seen, do not approach or feed it; leave an escape route and stay away from edges while photographing.', 'Si vous en voyez, ne l’approchez pas et ne le nourrissez pas ; laissez une voie de fuite et restez loin des bords pour photographier.', '如遇到，不要靠近或投喂；给它留出退路，拍照时远离崖边。', 'यदि दिखे तो पास न जाएँ और न खिलाएँ; उसे निकलने की जगह दें और फोटो लेते समय किनारों से दूर रहें।'],
    sourceIds: ['uae-hatta-hiking'],
    coverage: 'terrain-example',
  },
  {
    id: 'uae-hatta-rock-lizard',
    name: ['سحلية الصخور', 'Rock lizard', 'Lézard des rochers', '岩蜥', 'चट्टानी छिपकली'],
    description: ['مثال تضاريس فقط: الصخور والشقوق التي تذكرها إرشادات المشي في حتا قد تكون موئلاً لزواحف صغيرة، لكن النوع عند هذا الموضع غير مؤكد.', 'Terrain example only: the rocks and cracks noted in Hatta hiking guidance can be habitat for small reptiles, but this species at this marker is unconfirmed.', 'Exemple de relief seulement : les roches et fissures décrites pour la randonnée à Hatta peuvent abriter de petits reptiles, sans confirmation à ce repère.', '仅为地形示例：哈塔徒步资料提到的岩石和裂隙可能是小型爬行动物栖息地，但此标记点未确认该物种。', 'केवल भूभाग उदाहरण: हट्टा पैदल मार्ग में बताए गए पत्थर और दरारें छोटे सरीसृपों का आवास हो सकते हैं, पर इस चिह्न पर यह प्रजाति पुष्ट नहीं है।'],
    precaution: ['لا تمسك الزواحف الصغيرة ولا تقلب الحجارة بيدك. ابق على المسار المعلن لتقليل الإزعاج وخطر التعثر.', 'Do not handle small reptiles or turn stones by hand. Stay on the marked route to reduce disturbance and trip risk.', 'Ne manipulez pas les petits reptiles et ne retournez pas les pierres à la main. Restez sur l’itinéraire balisé pour limiter dérangement et chute.', '不要抓取小型爬行动物，也不要徒手翻石。留在标示路线内，减少干扰和绊倒风险。', 'छोटे सरीसृपों को न पकड़ें और हाथ से पत्थर न पलटें। व्यवधान और ठोकर के जोखिम को घटाने के लिए चिह्नित मार्ग पर रहें।'],
    sourceIds: ['uae-hatta-hiking', 'uae-hatta-dm-trails'],
    coverage: 'terrain-example',
  },
  {
    id: 'uae-hatta-scorpion',
    name: ['عقرب صحراوي أو جبلي', 'Desert or mountain scorpion', 'Scorpion désertique ou montagnard', '荒漠或山地蝎', 'मरुस्थलीय या पहाड़ी बिच्छू'],
    description: ['مثال تضاريس فقط: في المناطق الصخرية الجافة قد توجد عقارب، لكن وجودها في مخيم أو مسار محدد بحتا غير موثق هنا؛ اعتبرها خطراً احترازياً لا مشاهدة مضمونة.', 'Terrain example only: scorpions may occur in dry rocky areas, but presence at a particular Hatta camp or trail is not documented here; treat this as a precaution, not a guaranteed sighting.', 'Exemple de relief seulement : des scorpions peuvent vivre en zones rocheuses sèches, sans preuve pour un camp ou sentier précis de Hatta ; c’est une précaution, pas une observation garantie.', '仅为地形示例：干燥岩石地带可能有蝎子，但此处未记录哈塔某营地或步道存在；应作为预防风险，而非保证可见。', 'केवल भूभाग उदाहरण: सूखे चट्टानी क्षेत्रों में बिच्छू हो सकते हैं, पर हट्टा के किसी खास शिविर या पगडंडी पर उपस्थिति दर्ज नहीं है; इसे सावधानी मानें, निश्चित दर्शन नहीं।'],
    precaution: ['نصيحة عامة وليست قاعدة محلية: استخدم حذاءً مغلقاً، وانفض الحذاء والحقيبة قبل اللبس، ولا تدخل يدك تحت الصخور أو الحطب.', 'General advice, not a local requirement: use closed shoes, shake footwear and bags before use, and do not put hands under rocks or firewood.', 'Conseil général, sans obligation locale : portez des chaussures fermées, secouez chaussures et sacs avant usage, et ne mettez pas les mains sous pierres ou bois.', '一般建议，并非当地规定：穿包脚鞋，使用前抖动鞋和包，不要把手伸到石块或木柴下。', 'सामान्य सलाह, स्थानीय अनिवार्यता नहीं: बंद जूते पहनें, उपयोग से पहले जूते और थैले झाड़ें, और पत्थरों या लकड़ी के नीचे हाथ न डालें।'],
    sourceIds: ['uae-hatta-hiking'],
    coverage: 'terrain-example',
  },
];

export const destination: Destination & { country: typeof UAE } = {
  id: 'hatta',
  country: UAE,
  terrainId: 'mountain',
  terrainIndex: 1,
  lat: 24.7842,
  lon: 56.1185,
  timezone: UAE_TZ,
  names: ['حتا', 'Hatta', 'Hatta', '哈塔', 'हट्टा'],
  summary: ['منطقة جبلية في دبي حول السد والوديان ومسارات وادي هب؛ خطط حسب الطقس والحجز.', 'Dubai mountain area around the dam, wadis and Wadi Hub trails; plan by weather and booking status.', 'Zone montagneuse de Dubaï autour du barrage, des oueds et des sentiers ; vérifiez météo et réservation.', '迪拜山地目的地，含水坝、干谷和户外步道；按天气与预约状态规划。', 'दुबई का पर्वतीय क्षेत्र, बाँध, वादी और बाहरी पगडंडियाँ; मौसम और बुकिंग देखकर योजना बनाएँ।'],
  image: '/images/mountain.jpg',
  imageIsIllustrative: true,
  sourceIds: ['uae-hatta-visit-hatta-main', 'uae-hatta-dm-trails', 'uae-hatta-wadi-hub', 'uae-hatta-kayak'],
  species,
  sections: [
    section('place', ['حتا جزء جبلي من إمارة دبي قرب جبال الحجر، وتصف المصادر السد والوديان ومسارات وادي هب. مؤشر الخريطة تقريبي لمنطقة السد ووادي هب، وليس بداية مسار أو نقطة إطلاق؛ الصورة توضيحية. تحقق في يوم الزيارة من حالة الطرق والأنشطة.', 'Hatta is a mountain part of Dubai near the Hajar Mountains, with sources describing the dam, wadis and Wadi Hub trails. The map marker is an approximate area marker for the dam and Wadi Hub, not a trailhead or launch point; the image is illustrative. Check road and activity status on the day.', 'Hatta est une zone montagneuse de Dubaï près des monts Hajar ; les sources décrivent le barrage, les oueds et les sentiers de Wadi Hub. Le repère est approximatif pour le barrage et Wadi Hub, pas un départ ni une mise à l’eau ; image illustrative. Vérifiez l’état le jour même.', '哈塔是迪拜靠近哈杰尔山脉的山地区域，资料描述了水坝、干谷和瓦迪中心步道。地图标记只是水坝与瓦迪中心的大致区域，并非步道起点或下水点；图片为示意。出行当天请核对道路和活动状态。', 'हट्टा दुबई का हजर पर्वतों के पास स्थित पर्वतीय भाग है; स्रोत बाँध, वादी और वादी हब पगडंडियों का वर्णन करते हैं। नक्शे का चिन्ह बाँध और वादी हब क्षेत्र का अनुमानित संकेत है, पगडंडी आरंभ या जल प्रवेश नहीं; चित्र उदाहरणात्मक है। उसी दिन स्थिति जाँचें।'], ['uae-hatta-visit-hatta-main', 'uae-hatta-hiking', 'uae-hatta-kayak']),
    section('equipment', ['استنتاج عملي من طبيعة المسارات الملوّنة والصخور: احمل ماءً وملاحة وهاتفاً مشحوناً وإضاءة احتياطية إذا امتدت الخطة. لا تفترض أن الحجز يشمل معدات المشي أو الدراجة؛ تؤكد صفحة وادي هب توافر تأجير دراجات، لكن الشروط تتغير فاسأل المشغّل.', 'Practical inference from colour-coded trails and rocky ground: carry water, navigation, a charged phone and backup light if the plan may run long. Do not assume a booking includes hiking or cycling kit; Wadi Hub notes bike rental availability, but terms can change, so ask the operator.', 'Déduction pratique liée aux sentiers balisés et aux roches : emportez eau, navigation, téléphone chargé et lampe de secours si la sortie peut durer. Ne supposez pas que la réservation inclut matériel de marche ou vélo ; Wadi Hub mentionne la location de vélos, à confirmer.', '根据分级步道和岩石地面作出的实用推断：携带饮水、导航、已充电手机，若行程可能延长再备照明。不要默认预约包含徒步或骑行装备；瓦迪中心提到可租车，但条件可能变化，应询问运营方。', 'रंग-चिह्नित पगडंडियों और चट्टानी जमीन से व्यावहारिक निष्कर्ष: पानी, दिशा साधन, चार्ज फोन और योजना लंबी हो सकती हो तो अतिरिक्त रोशनी रखें। बुकिंग में पैदल या साइकिल सामान शामिल मानकर न चलें; वादी हब किराये की साइकिल बताता है, फिर भी पुष्टि करें।'], ['uae-hatta-dm-trails', 'uae-hatta-wadi-hub', 'uae-hatta-mountain-biking']),
    section('clothing', ['نصيحة عامة وليست قاعدة محلية: ارتد حذاءً مغلقاً ذا تماسك للصخور، وملابس خفيفة تغطي الجلد، وقبعة ونظارة شمسية. لركوب الدراجات استخدم خوذة ومعدات حماية مناسبة لما يطلبه المشغّل. افحص توقعات الحرارة والرياح قبل الانطلاق.', 'General advice, not a local requirement: wear closed shoes with grip for rock, light clothing that covers skin, a hat and sunglasses. For cycling, use a helmet and protective gear required by the operator. Check heat and wind forecasts before setting out.', 'Conseil général, sans obligation locale : chaussures fermées adhérentes sur roche, vêtements légers couvrants, chapeau et lunettes. À vélo, portez casque et protections demandés par l’exploitant. Vérifiez chaleur et vent avant le départ.', '一般建议，并非当地规定：穿有抓地力的包脚鞋、轻薄遮肤衣物，戴帽子和太阳镜。骑行时按运营方要求使用头盔和护具。出发前核对高温和风况预报。', 'सामान्य सलाह, स्थानीय अनिवार्यता नहीं: चट्टानों पर पकड़ वाले बंद जूते, त्वचा ढकने वाले हल्के कपड़े, टोपी और धूप चश्मा पहनें। साइकिल के लिए संचालक के अनुसार हेलमेट और सुरक्षा उपकरण लें। निकलने से पहले गर्मी और हवा का पूर्वानुमान देखें।'], ['uae-hatta-hiking', 'uae-hatta-mountain-biking', 'uae-hatta-ncm-warnings']),
    section('transport', ['تذكر صفحات حتا أن الموقع يبعد نحو تسعين دقيقة عن دبي، وتربطه طرق مع منطقة جبلية وحدودية. خطط للعودة قبل التعب أو الظلام، ولا تعامل المؤشر كتعليمات قيادة داخل الوديان. إذا كنت تعتمد على جولة أو سيارة أجرة، أكد نقطة اللقاء والعودة مسبقاً.', 'Visit Hatta pages state that Hatta is about ninety minutes from Dubai, reached by roads into a mountain and border area. Plan the return before fatigue or darkness, and do not treat the marker as driving directions into wadis. If using a tour or taxi, confirm pickup and return points in advance.', 'Les pages Visit Hatta indiquent environ quatre-vingt-dix minutes depuis Dubaï, par des routes vers une zone de montagne et de frontière. Prévoyez le retour avant fatigue ou nuit ; le repère n’est pas un itinéraire dans les oueds. Confirmez rendez-vous et retour avec taxi ou excursion.', '哈塔页面说明，从迪拜到哈塔约九十分钟，路线进入山地和边境附近区域。应在疲劳或天黑前安排返程，不要把标记当作驶入干谷的路线。若用旅游车或出租车，请提前确认接送点。', 'विजिट हट्टा पृष्ठ बताते हैं कि हट्टा दुबई से लगभग नब्बे मिनट दूर है और सड़कें पर्वतीय तथा सीमा क्षेत्र की ओर जाती हैं। थकान या अँधेरे से पहले वापसी रखें; चिन्ह को वादी में गाड़ी चलाने का मार्ग न मानें। यात्रा या टैक्सी हो तो मिलने और लौटने की जगह पहले तय करें।'], ['uae-hatta-visit-hatta-main', 'uae-hatta-hiking', 'uae-hatta-mountain-biking']),
    section('season', ['تعمل بعض أنشطة وادي هب صيفاً وتغلق بعض إقامات حتا موسماً بحسب المصدر، لذلك لا تجعل التقويم وحده قراراً. تحقق من الإنذارات الجوية لدى المركز الوطني للأرصاد ومن ساعات كل نشاط في يوم الزيارة، وأعد الجدولة عند الحر الشديد أو المطر.', 'Some Wadi Hub activities operate in summer while some Hatta accommodation closes seasonally, according to the sources, so do not rely on the calendar alone. Check National Center of Meteorology warnings and each activity’s hours on the day, and reschedule for severe heat or rain.', 'Certaines activités de Wadi Hub fonctionnent l’été tandis que certains hébergements ferment selon la saison ; le calendrier ne suffit donc pas. Consultez les alertes du Centre national de météorologie et les horaires le jour même ; reportez par forte chaleur ou pluie.', '资料显示，瓦迪中心部分活动夏季开放，而哈塔部分住宿按季节关闭，所以不能只看日历。当天查看国家气象中心预警和各活动时间；遇到强热或降雨应改期。', 'स्रोतों के अनुसार वादी हब की कुछ गतिविधियाँ गर्मियों में चलती हैं और कुछ हट्टा आवास मौसम अनुसार बंद होते हैं, इसलिए केवल कैलेंडर पर निर्भर न रहें। उसी दिन राष्ट्रीय मौसम केंद्र की चेतावनी और गतिविधि समय देखें; तेज गर्मी या बारिश में कार्यक्रम बदलें।'], ['uae-hatta-wadi-hub', 'uae-hatta-stay', 'uae-hatta-ncm-warnings']),
    section('nature', ['تصف المصادر جبال الحجر والوديان والصخور والنباتات المحلية في حديقة النحل، لكن التعرف على الأنواع في المسار يحتاج دليلاً ميدانياً. لا تجمع نباتات أو حطباً، ولا تطارد الحياة البرية. قائمة الأنواع هنا تفصل بين المحلي الموثق وأمثلة التضاريس غير المؤكدة.', 'Sources describe the Hajar Mountains, wadis, rocks and native flora at the honeybee garden, but species identification on a route needs a field guide. Do not collect plants or wood, and do not chase wildlife. The species list separates documented local records from unverified terrain examples.', 'Les sources décrivent les monts Hajar, les oueds, les roches et la flore indigène du jardin apicole, mais l’identification sur sentier demande un guide de terrain. Ne prélevez ni plantes ni bois et ne poursuivez pas la faune. La liste distingue local vérifié et exemples non confirmés.', '资料描述了哈杰尔山、干谷、岩石，以及蜜蜂园的本地植物；但在路线中识别物种需要野外指南。不要采集植物或木材，不追逐野生动物。本清单区分已证实本地记录和未核实地形示例。', 'स्रोत हजर पर्वत, वादी, चट्टानों और मधुमक्खी उद्यान की स्थानीय वनस्पति बताते हैं, पर मार्ग पर प्रजाति पहचान के लिए मैदानी मार्गदर्शिका चाहिए। पौधे या लकड़ी न लें और वन्यजीवों का पीछा न करें। सूची में प्रमाणित स्थानीय और अपुष्ट भूभाग उदाहरण अलग हैं।'], ['uae-hatta-hiking', 'uae-hatta-honeybee-garden']),
    section('hazard', ['استنتاج عملي: الوديان والمناطق قرب السد قد تتغير سريعاً مع المطر، والمصدر الرسمي المتاح هنا يتيح متابعة الإنذارات لا ضمان السلامة. افحص الطقس في اليوم نفسه، وتجنب مجاري الأودية عند المطر أو بعده. للطوارئ في الإمارات: الشرطة 999، الإسعاف 998، الدفاع المدني 997.', 'Practical inference: wadis and areas near the dam can change quickly with rain, and the official source here supports checking warnings, not any safety guarantee. Check weather on the day and avoid wadi channels during or after rain. UAE emergencies: police 999, ambulance 998, civil defence 997.', 'Déduction pratique : les oueds et abords du barrage peuvent changer vite sous la pluie ; la source officielle sert à consulter les alertes, sans garantie. Vérifiez la météo le jour même et évitez les lits d’oued pendant ou après la pluie. Urgences : police 999, ambulance 998, défense civile 997.', '实用推断：干谷和水坝附近在降雨时可能迅速变化；此官方来源用于查看预警，并不保证安全。当天查看天气，雨中或雨后避开干谷河道。阿联酋紧急电话：警察999，救护998，民防997。', 'व्यावहारिक निष्कर्ष: बारिश में वादी और बाँध के पास के क्षेत्र तेजी से बदल सकते हैं; यहाँ का आधिकारिक स्रोत चेतावनी जाँचने के लिए है, सुरक्षा की गारंटी नहीं। उसी दिन मौसम देखें और बारिश के दौरान या बाद में वादी मार्गों से बचें। आपातकाल: पुलिस 999, एम्बुलेंस 998, सिविल डिफेन्स 997।'], ['uae-hatta-ncm-warnings', 'uae-emergency', 'uae-hatta-kayak']),
    section('visit', ['اختر النشاط حسب القدرة: مسارات المشي والدراجات ملوّنة بدرجات صعوبة، والسد يوفر قوارب وكاياك، ووادي هب يعلن أنشطة وساعات مختلفة. احجز أو اتصل عند الحاجة، ولا تعتمد على منشور قديم للأسعار أو المواعيد. للمبتدئ، ابدأ بنشاط قصير ومشغّل معروف.', 'Choose by ability: walking and cycling trails are colour-coded by difficulty, the dam offers boats and kayaks, and Wadi Hub lists activities with differing hours. Book or call when needed, and do not rely on old posts for prices or times. Beginners should start with a short operated activity.', 'Choisissez selon votre niveau : sentiers pédestres et cyclables sont codés par difficulté, le barrage propose bateaux et kayaks, et Wadi Hub annonce des horaires variables. Réservez ou appelez si nécessaire ; ne fiez pas aux anciens tarifs ou horaires. Débutez par une courte activité encadrée.', '按能力选择活动：步行和骑行路线按难度分色，水坝提供船和皮划艇，瓦迪中心列出不同时间的活动。需要时预约或致电，不要依赖旧价格或时间信息。初学者宜选择短时运营活动。', 'क्षमता के अनुसार गतिविधि चुनें: पैदल और साइकिल मार्ग कठिनाई के रंगों से चिह्नित हैं, बाँध पर नाव और कयाक हैं, और वादी हब अलग-अलग समय वाली गतिविधियाँ बताता है। जरूरत हो तो बुक करें या फोन करें; पुराने दाम या समय पर निर्भर न रहें। शुरुआत छोटी संचालित गतिविधि से करें।'], ['uae-hatta-dm-trails', 'uae-hatta-kayak', 'uae-hatta-wadi-hub']),
    section('rules', ['استخدم المسارات والمواقع المعلنة واتبع شروط المشغّل للمشي والدراجات والكاياك والمبيت. لا نثبت هنا تصريحاً عاماً للتخييم خارج المواقع المعلنة؛ لذلك تحقق قبل نصب خيمة أو إشعال نار. للطائرات من دون طيار، تسجل هيئة الطيران المدني التسجيل والمناطق المسموحة، فاطلب الموافقة قبل التصوير.', 'Use announced trails and sites, and follow operator terms for hiking, biking, kayaking and stays. This record does not verify a general permit for camping outside announced sites, so check before pitching a tent or lighting a fire. For drones, GCAA requires registration and approved zones, so obtain permission before filming.', 'Utilisez les sentiers et sites annoncés, avec les conditions des exploitants pour marche, vélo, kayak et séjour. Cette fiche ne confirme pas de permis général hors sites annoncés ; vérifiez avant tente ou feu. Pour drones, la GCAA exige enregistrement et zones approuvées : obtenez l’accord avant de filmer.', '使用公布的步道和场地，并遵守徒步、骑行、皮划艇和住宿运营方条款。本记录未核实公告场地外的一般露营许可；搭帐篷或生火前请确认。无人机方面，民航总局要求注册并在批准区域飞行，拍摄前应获许可。', 'घोषित पगडंडियों और स्थलों का उपयोग करें तथा पैदल, साइकिल, कयाक और ठहरने के संचालक नियम मानें। यह रिकॉर्ड घोषित स्थलों के बाहर सामान्य कैंपिंग अनुमति सिद्ध नहीं करता; तंबू या आग से पहले जाँचें। ड्रोन के लिए नागरिक उड्डयन प्राधिकरण पंजीकरण और स्वीकृत क्षेत्र मांगता है, इसलिए फिल्मांकन से पहले अनुमति लें।'], ['uae-hatta-dm-trails', 'uae-hatta-stay', 'uae-hatta-gcaa-drones', 'uae-emergency']),
  ],
};

if (destination.sections.length !== sectionOrder.length) throw new Error('Hatta section count mismatch');

export const rules: PackingRule[] = [
  {
    id: 'uae-hatta-grip-shoes',
    version: 1,
    equipmentId: 'uae-hatta-grip-shoes',
    label: ['حذاء جبلي مغلق', 'Closed mountain-grip shoes', 'Chaussures fermées adhérentes', '包脚防滑山地鞋', 'बंद पकड़दार पहाड़ी जूते'],
    category: 'clothing',
    terrainIds: ['mountain'],
    activities: ['walking', 'camping'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['مسارات حتا تمر بين صخور ورمال، ومصدر دبي للبلدية يصف مسارات بدرجات مختلفة؛ الحذاء المغلق يقلل الانزلاق والجروح.', 'Hatta trails cross rock and sand, and Dubai Municipality describes routes of different grades; closed grip shoes reduce slips and cuts.', 'Les sentiers de Hatta mêlent roches et sable, avec plusieurs niveaux décrits par la municipalité ; des chaussures fermées réduisent glissades et coupures.', '哈塔步道经过岩石和沙地，迪拜市政资料说明路线难度不同；包脚防滑鞋可减少滑倒和割伤。', 'हट्टा मार्ग चट्टान और रेत से गुजरते हैं तथा दुबई नगरपालिका अलग स्तर बताती है; बंद पकड़दार जूते फिसलन और कटाव घटाते हैं।'],
    sourceIds: ['uae-hatta-dm-trails', 'uae-hatta-hiking'],
    coverage: 'local',
    destinationIds: ['hatta'],
  },
  {
    id: 'uae-hatta-warning-check',
    version: 1,
    equipmentId: 'uae-hatta-warning-check',
    label: ['فحص إنذارات الطقس', 'Weather-warning check', 'Vérification des alertes météo', '天气预警检查', 'मौसम चेतावनी जाँच'],
    category: 'safety',
    terrainIds: ['mountain'],
    activities: ['walking', 'camping', 'cycling', 'boating'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: false,
    reason: ['وجود الوديان والسد يجعل قرار الخروج مرتبطاً بالمطر والإنذارات؛ تحقق في يوم الرحلة ولا تدخل مجاري الأودية عند تغير الطقس.', 'Because wadis and the dam make the outing sensitive to rain and warnings, check on the day and avoid wadi channels when weather changes.', 'La présence d’oueds et du barrage rend la sortie dépendante de la pluie et des alertes ; vérifiez le jour même et évitez les lits d’oued si le temps change.', '因干谷和水坝使行程受降雨与预警影响，当天应检查预警，天气变化时避开干谷河道。', 'वादी और बाँध के कारण यात्रा बारिश और चेतावनी पर निर्भर होती है; उसी दिन जाँचें और मौसम बदलने पर वादी मार्गों से बचें।'],
    sourceIds: ['uae-hatta-ncm-warnings', 'uae-hatta-kayak'],
    coverage: 'local',
    destinationIds: ['hatta'],
  },
  {
    id: 'uae-hatta-helmet',
    version: 1,
    equipmentId: 'uae-hatta-helmet',
    label: ['خوذة للدرّاجة أو النشاط', 'Helmet for cycling or activity', 'Casque pour vélo ou activité', '骑行或活动头盔', 'साइकिल या गतिविधि हेलमेट'],
    category: 'safety',
    terrainIds: ['mountain'],
    activities: ['cycling'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['تعلن حتا مسارات دراجات جبلية بدرجات متعددة وأنشطة مغامرة؛ استخدم الخوذة ومعدات الحماية التي يطلبها المشغّل قبل الانطلاق.', 'Hatta lists mountain-bike routes of multiple grades and adventure activities; use the helmet and protective gear required by the operator before starting.', 'Hatta annonce des parcours VTT de plusieurs niveaux et des activités d’aventure ; utilisez le casque et les protections demandés par l’exploitant.', '哈塔列有多级山地自行车路线和冒险活动；开始前使用运营方要求的头盔和护具。', 'हट्टा कई स्तरों के माउंटेन बाइक मार्ग और साहसिक गतिविधियाँ बताता है; शुरू करने से पहले संचालक द्वारा माँगे गए हेलमेट और सुरक्षा उपकरण पहनें।'],
    sourceIds: ['uae-hatta-mountain-biking', 'uae-hatta-wadi-hub'],
    coverage: 'local',
    destinationIds: ['hatta'],
  },
  {
    id: 'uae-hatta-operator-contact',
    version: 1,
    equipmentId: 'uae-hatta-operator-contact',
    label: ['تأكيد الحجز والمشغّل', 'Operator and booking confirmation', 'Confirmation de réservation', '运营方与预约确认', 'संचालक और बुकिंग पुष्टि'],
    category: 'essentials',
    terrainIds: ['mountain'],
    activities: ['walking', 'camping', 'cycling', 'boating'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: false,
    reason: ['تعرض صفحات وادي هب والكاياك والإقامة ساعات وحجوزات موسمية؛ احتفظ بتأكيد حديث ورقم اتصال ولا تعتمد على موعد قديم.', 'Wadi Hub, kayak and stay pages show changing hours, bookings and seasons; keep a current confirmation and contact number instead of relying on old times.', 'Les pages Wadi Hub, kayak et séjour indiquent horaires, réservations et saisons variables ; gardez une confirmation récente et un numéro de contact.', '瓦迪中心、皮划艇和住宿页面显示时间、预约与季节会变化；保存最新确认和联系电话，不要依赖旧时间。', 'वादी हब, कयाक और ठहरने के पृष्ठ बदलते समय, बुकिंग और मौसम बताते हैं; पुराने समय पर भरोसा न करें, नई पुष्टि और संपर्क नंबर रखें।'],
    sourceIds: ['uae-hatta-wadi-hub', 'uae-hatta-kayak', 'uae-hatta-stay'],
    coverage: 'local',
    destinationIds: ['hatta'],
  },
];
