import type { Destination, PackingRule, SourceReference, SpeciesEntry } from '../toolkit-types';
import { UAE, UAE_TZ, reviewedAt, section } from './shared';

type UaeDestination = Destination & { country: typeof UAE };

export const sources: SourceReference[] = [
  { id: 'uae-jebel-hafeet-visit-park', title: 'Visit Abu Dhabi · Jebel Hafit Desert Park', url: 'https://visitabudhabi.ae/en/things-to-do/nature-and-wildlife/parks/jebel-hafit-desert-park', reviewedAt },
  { id: 'uae-jebel-hafeet-green-mubazzarah', title: 'Visit Abu Dhabi · Green Mubazzarah Chalets', url: 'https://visitabudhabi.ae/en/plan-your-trip/where-to-stay/green-mubazzarah-chalets', reviewedAt },
  { id: 'uae-jebel-hafeet-culture-archaeology', title: 'Abu Dhabi Culture · The Archaeology and Heritage of Jebel Hafit Desert Park', url: 'https://abudhabiculture.ae/en/cultural-resources/publications/the-archaeology-and-heritage-of-jebel-hafit-desert-park', reviewedAt },
  { id: 'uae-jebel-hafeet-unesco-al-ain', title: 'UNESCO World Heritage Centre · Cultural Sites of Al Ain', url: 'https://whc.unesco.org/en/list/1343', reviewedAt },
  { id: 'uae-jebel-hafeet-ead-factsheet', title: 'Environment Agency – Abu Dhabi · Jabal Hafeet National Park factsheet', url: 'https://ead.gov.ae/-/media/Project/EAD/EAD/Documents/Resources/JABL_HAFEET-ENG.pdf', reviewedAt },
  { id: 'uae-jebel-hafeet-ead-network', title: 'Environment Agency – Abu Dhabi · Sheikh Zayed Protected Areas Network', url: 'https://www.ead.gov.ae/en/discover-our-biodiversity/sheikh-zayed-protected-areas-network', reviewedAt },
  { id: 'uae-jebel-hafeet-ead-caracal', title: 'Environment Agency – Abu Dhabi · Arabian Caracal', url: 'https://www.ead.gov.ae/en/discover-our-biodiversity/mammals/arabian-caracal', reviewedAt },
  { id: 'uae-jebel-hafeet-ncm-weather', title: 'National Center of Meteorology · UAE weather forecasts', url: 'https://www.ncm.gov.ae/?lang=en', reviewedAt },
  { id: 'uae-jebel-hafeet-uae-aviation', title: 'UAE Government portal · Aviation safety', url: 'https://u.ae/en/information-and-services/justice-safety-and-the-law/Safety/aviation-safety', reviewedAt },
];

const species: SpeciesEntry[] = [
  {
    id: 'uae-jebel-hafeet-arabian-tahr',
    name: ['الطهر العربي', 'Arabian tahr', 'Tahr d’Arabie', '阿拉伯塔尔羊', 'अरबी तहर'],
    description: ['تذكر هيئة البيئة أبوظبي أن منتزه جبل حفيت الوطني موطن للطهر العربي النادر؛ اعتبروا الرؤية غير مضمونة، فالسجل يدل على وجوده لا على سهولة مشاهدته.', 'EAD notes Jabal Hafit National Park is home to the rare Arabian tahr; treat sightings as unguaranteed, because the record proves presence, not easy viewing.', 'L’EAD indique que le parc national du Jabal Hafit abrite le rare tahr d’Arabie ; l’observation reste incertaine, car la source atteste la présence, pas la facilité de le voir.', '环境署说明贾巴尔哈菲特国家公园有珍稀阿拉伯塔尔羊；请把目击视为不保证，因为资料只证明存在，并不表示容易看到。', 'ईएडी बताता है कि जबल हफीत राष्ट्रीय उद्यान दुर्लभ अरबी तहर का घर है; दिखना निश्चित न मानें, क्योंकि अभिलेख उपस्थिति बताता है, आसान दर्शन नहीं।'],
    precaution: ['راقبوا من بعيد ولا تطاردوا الحيوان أو تطعموه؛ ابقوا على المسارات المعلّمة حتى لا تضغطوا على الموائل الصخرية.', 'Observe from a distance and do not chase or feed it; stay on marked trails to reduce pressure on rocky habitat.', 'Observez à distance, sans poursuite ni nourrissage ; restez sur les sentiers balisés pour limiter la pression sur l’habitat rocheux.', '请远距离观察，不追逐、不投喂；留在标明路线，减少对岩石栖息地的压力。', 'दूर से देखें, पीछा या भोजन न दें; चट्टानी आवास पर दबाव घटाने के लिए चिह्नित मार्गों पर रहें।'],
    sourceIds: ['uae-jebel-hafeet-ead-network'],
    coverage: 'local',
  },
  {
    id: 'uae-jebel-hafeet-dwarf-palm',
    name: ['النخيل القزم', 'Dwarf palm', 'Palmier nain', '矮棕榈', 'बौना ताड़'],
    description: ['تذكر هيئة البيئة أن جبل حفيت موطن للنخيل القزم النادر. لا تكفي الصورة وحدها للتعرف؛ عاملوا أي نبات بري كجزء من محمية.', 'EAD lists Jabal Hafit as home to the rare dwarf palm. A photo is not enough for identification; treat any wild plant as part of a protected area.', 'L’EAD cite le Jabal Hafit comme habitat du palmier nain rare. Une photo ne suffit pas à identifier ; considérez toute plante sauvage comme élément d’une aire protégée.', '环境署列明贾巴尔哈菲特有珍稀矮棕榈。仅凭照片不足以识别；请把任何野生植物都视为保护地的一部分。', 'ईएडी जबल हफीत को दुर्लभ बौने ताड़ का घर बताता है। केवल फोटो पहचान के लिए पर्याप्त नहीं; हर जंगली पौधे को संरक्षित क्षेत्र का हिस्सा मानें।'],
    precaution: ['لا تجمعوا أوراقاً أو بذوراً ولا تمشوا فوق النباتات؛ لو احتجتم توثيقاً فالتقطوا صورة من دون لمس.', 'Do not collect leaves or seeds or walk over plants; if you need a record, take a photograph without touching.', 'Ne prélevez ni feuilles ni graines et ne piétinez pas les plantes ; pour garder une trace, photographiez sans toucher.', '不要采集叶片或种子，也不要踩踏植物；如需记录，请不触碰地拍照。', 'पत्ते या बीज न लें और पौधों पर न चलें; अभिलेख चाहिए तो बिना छुए फोटो लें।'],
    sourceIds: ['uae-jebel-hafeet-ead-network', 'uae-jebel-hafeet-ead-factsheet'],
    coverage: 'local',
  },
  {
    id: 'uae-jebel-hafeet-arabian-caracal',
    name: ['الوشق العربي', 'Arabian caracal', 'Caracal d’Arabie', '阿拉伯狞猫', 'अरबी कराकल'],
    description: ['سجلت هيئة البيئة مشاهدة للوشق العربي في منتزه جبل حفيت الوطني عام 2019 بعد غياب طويل؛ هذا يثبت حساسية الموئل لا فرصة مشاهدة متوقعة.', 'EAD recorded an Arabian caracal sighting in Jabal Hafit National Park in 2019 after a long gap; this shows habitat sensitivity, not an expected encounter.', 'L’EAD a enregistré en 2019 une observation du caracal d’Arabie au parc national du Jabal Hafit après une longue absence ; cela signale un habitat sensible, non une rencontre probable.', '环境署记录阿拉伯狞猫在长期未见后于2019年出现在贾巴尔哈菲特国家公园；这说明栖息地敏感，并非可期待邂逅。', 'ईएडी ने लंबे अंतराल के बाद 2019 में जबल हफीत राष्ट्रीय उद्यान में अरबी कराकल देखा; यह आवास की संवेदनशीलता बताता है, अपेक्षित मुलाकात नहीं।'],
    precaution: ['إذا رأيتموه فابتعدوا بهدوء ولا تحاولوا الاقتراب أو التصوير القريب؛ أبلغوا الجهة المختصة إذا طلبت اللوحات ذلك.', 'If you see one, back away calmly and do not approach for close photography; report only as local signs or authorities request.', 'Si vous en voyez un, reculez calmement et ne vous approchez pas pour une photo ; signalez seulement si les panneaux ou autorités le demandent.', '如遇见，请安静后退，不要为近拍而靠近；仅按现场标识或主管部门要求报告。', 'यदि दिखे तो शांत होकर पीछे हटें और नजदीक फोटो लेने न जाएँ; स्थानीय संकेत या अधिकारी कहें तभी सूचना दें।'],
    sourceIds: ['uae-jebel-hafeet-ead-caracal'],
    coverage: 'local',
  },
  {
    id: 'uae-jebel-hafeet-rocky-reptiles',
    name: ['زواحف المنحدرات الصخرية', 'Rocky-slope reptiles', 'Reptiles des pentes rocheuses', '岩坡爬行动物', 'चट्टानी ढलानों के सरीसृप'],
    description: ['توثق نشرة هيئة البيئة وجود زواحف في منتزه جبل حفيت الوطني، لكنها لا تكفي لتحديد نوع أمام الزائر؛ تعاملوا مع الثقوب والصخور بحذر.', 'The EAD factsheet documents reptiles in Jabal Hafeet National Park, but it is not enough to identify a species for visitors; treat holes and rocks with care.', 'La fiche de l’EAD atteste des reptiles au parc national du Jabal Hafeet, sans permettre une identification d’espèce par le visiteur ; abordez trous et rochers avec prudence.', '环境署资料证明贾巴尔哈菲特国家公园有爬行动物，但不足以让游客判定具体物种；请谨慎对待洞穴和石块。', 'ईएडी तथ्यपत्र जबल हफीत राष्ट्रीय उद्यान में सरीसृप दर्ज करता है, पर आगंतुक के लिए प्रजाति पहचानने को पर्याप्त नहीं; बिलों और पत्थरों से सावधानी रखें।'],
    precaution: ['لا تضعوا اليدين تحت الصخور أو داخل الشقوق، واستعملوا مصباحاً عند ضعف الضوء، واتركوا الحيوان يبتعد من دون إزعاج.', 'Do not put hands under rocks or into crevices; use a light when visibility is low and let the animal move away undisturbed.', 'Ne mettez pas les mains sous les pierres ni dans les fissures ; utilisez une lampe si la visibilité baisse et laissez l’animal partir.', '不要把手伸到石下或裂缝中；光线不足时用灯，让动物自行离开。', 'हाथ पत्थरों के नीचे या दरारों में न डालें; रोशनी कम हो तो टॉर्च लें और जीव को बिना छेड़े जाने दें।'],
    sourceIds: ['uae-jebel-hafeet-ead-factsheet'],
    coverage: 'local',
  },
];

export const destination: UaeDestination = {
  id: 'jebel-hafeet',
  country: UAE,
  terrainId: 'mountain',
  terrainIndex: 1,
  lat: 24.0989,
  lon: 55.7466,
  timezone: UAE_TZ,
  names: ['جبل حفيت والمبزرة الخضراء', 'Jebel Hafeet and Green Mubazzarah', 'Jebel Hafeet et Green Mubazzarah', '杰贝尔哈菲特与绿色穆巴扎拉', 'जेबेल हफीत और ग्रीन मुबज़्ज़राह'],
  summary: ['منطقة جبلية عند العين تجمع قاعدة خضراء ومحمية وتراثاً؛ خططوا للحرارة والمسارات المعلّمة.', 'A mountain area by Al Ain with a green base, protected habitat and heritage; plan for heat and marked routes.', 'Secteur montagneux près d’Al Ain, entre base verte, milieu protégé et patrimoine ; préparez chaleur et itinéraires balisés.', '艾因旁的山地，结合绿色山脚、保护栖息地和遗产；请按高温与标明路线规划。', 'अल ऐन के पास पर्वतीय क्षेत्र, हरा आधार, संरक्षित आवास और विरासत; गर्मी और चिह्नित मार्गों के लिए तैयारी करें।'],
  image: '/images/mountain.jpg',
  imageIsIllustrative: true,
  sourceIds: ['uae-jebel-hafeet-visit-park', 'uae-jebel-hafeet-green-mubazzarah', 'uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-culture-archaeology'],
  species,
  sections: [
    section('place', [
      'يمثّل جبل حفيت والمبزرة الخضراء حافة جبلية قرب العين: تذكر زيارة أبوظبي متنزه جبل حفيت الصحراوي والمبزرة عند سفح الجبل، وتربطه اليونسكو بمواقع العين الثقافية. مؤشر الخريطة تقريبي لمنطقة المبزرة، وليس بداية مسار؛ الصورة توضيحية.',
      'Jebel Hafeet and Green Mubazzarah form a mountain-edge visit near Al Ain: Visit Abu Dhabi describes Jebel Hafit Desert Park and Green Mubazzarah at the foot of the mountain, while UNESCO links the area to Al Ain cultural sites. The marker is an approximate area marker, not a trailhead; the image is illustrative.',
      'Jebel Hafeet et Green Mubazzarah forment une visite de bord montagneux près d’Al Ain : Visit Abu Dhabi décrit le parc désertique de Jebel Hafit et Green Mubazzarah au pied de la montagne, tandis que l’UNESCO rattache le secteur aux sites culturels d’Al Ain. Repère approximatif, pas un départ de sentier ; image illustrative.',
      '杰贝尔哈菲特与绿色穆巴扎拉位于艾因附近的山地边缘：阿布扎比旅游资料介绍杰贝尔哈菲特沙漠公园，以及山脚的绿色穆巴扎拉；联合国教科文组织把该区域纳入艾因文化遗址背景。标记仅示大致区域，不是步道起点；图片为示意。',
      'जेबेल हफीत और ग्रीन मुबज़्ज़राह अल ऐन के पास पर्वत किनारे की यात्रा हैं: अबू धाबी पर्यटन जेबेल हफीत डेजर्ट पार्क और पर्वत तल की ग्रीन मुबज़्ज़राह का वर्णन करता है, जबकि यूनेस्को इसे अल ऐन सांस्कृतिक स्थलों से जोड़ता है। संकेत अनुमानित क्षेत्र है, पगडंडी आरंभ नहीं; चित्र उदाहरणात्मक है।',
    ], ['uae-jebel-hafeet-visit-park', 'uae-jebel-hafeet-green-mubazzarah', 'uae-jebel-hafeet-unesco-al-ain']),
    section('equipment', [
      'استنتاج عملي: لأن الزيارة تجمع سفحاً أخضر ومسارات جبلية وموقعاً محمياً، جهّزوا ماءً كافياً وخريطة غير متصلة وبطارية هاتف. لا تفترضوا أن وجود الشاليهات أو مناطق النزهة يعني توافر معدات المشي؛ تحققوا من مزود النشاط في اليوم نفسه.',
      'Practical inference: because the visit combines a green base, mountain routes and a protected site, carry enough water, an offline map and phone power. Do not assume chalets or picnic areas provide walking equipment; confirm with the activity operator on the day.',
      'Déduction pratique : comme la visite réunit base verte, itinéraires de montagne et site protégé, emportez assez d’eau, une carte hors ligne et une batterie de téléphone. Ne supposez pas que les chalets ou aires de pique-nique fournissent du matériel de marche ; vérifiez le jour même.',
      '实用推断：这里同时有绿色山脚、山地路线和保护地，请携带足够饮水、离线地图和手机电量。不要因有木屋或野餐区就假定会提供徒步装备；当天向活动运营方确认。',
      'व्यावहारिक अनुमान: यात्रा में हरा आधार, पर्वतीय मार्ग और संरक्षित स्थल साथ हैं, इसलिए पर्याप्त पानी, ऑफलाइन नक्शा और फोन ऊर्जा रखें। शैले या पिकनिक क्षेत्र देखकर पैदल सामान उपलब्ध मानकर न चलें; उसी दिन गतिविधि संचालक से पुष्टि करें।',
    ], ['uae-jebel-hafeet-green-mubazzarah', 'uae-jebel-hafeet-ead-factsheet']),
    section('clothing', [
      'نصيحة عامة، وليست شرطاً محلياً: اختاروا حذاءً مغلقاً بثبات جيد للصخر والحصى، وملابس تغطي من الشمس وقبعة. عند ضعف الضوء أو تغير الرياح، أضيفوا طبقة خفيفة ولا تتركوا الصنادل إلا للمناطق المعبدة أو مرافق الإقامة.',
      'General advice, not a local requirement: choose closed footwear with grip for rock and gravel, plus sun-covering clothing and a hat. If light fades or wind changes, add a light layer; keep sandals only for paved areas or accommodation facilities.',
      'Conseil général, sans obligation locale : choisissez des chaussures fermées adhérentes pour roche et gravier, avec vêtements couvrants et chapeau. Si la lumière baisse ou le vent change, ajoutez une couche légère ; réservez les sandales aux zones pavées ou aux hébergements.',
      '一般建议，并非当地规定：选择抓地好的包脚鞋，应对岩石和砾石，并穿遮阳衣物、戴帽子。光线变弱或风况改变时加一层薄衣；凉鞋只适合铺装区域或住宿设施。',
      'सामान्य सलाह, स्थानीय अनिवार्यता नहीं: पत्थर और कंकड़ के लिए पकड़ वाले बंद जूते, धूप से ढकने वाले कपड़े और टोपी चुनें। रोशनी घटे या हवा बदले तो हल्की परत जोड़ें; चप्पलें केवल पक्के क्षेत्रों या आवास सुविधाओं के लिए रखें।',
    ], ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-ncm-weather']),
    section('transport', [
      'تذكر المصادر الرسمية منطقة المبزرة عند سفح الجبل والمتنزه الصحراوي على جانب جبل حفيت. خططوا للانتقال كنقطة وصول عامة لا كإرشاد قيادة تفصيلي، وتحققوا من حالة الطريق ومواقف السيارة والحجز قبل الانطلاق، خاصة إذا تغير الطقس أو كان النشاط منظماً.',
      'Official sources place Green Mubazzarah at the mountain foot and the desert park on Jebel Hafit. Plan access as a general arrival area, not turn-by-turn driving guidance, and check road status, parking and booking before departure, especially if weather changes or an activity is operated.',
      'Les sources officielles situent Green Mubazzarah au pied de la montagne et le parc désertique sur le Jebel Hafit. Préparez l’accès comme une zone d’arrivée générale, non comme un guidage routier détaillé, et vérifiez route, stationnement et réservation avant le départ, surtout si la météo change ou si l’activité est encadrée.',
      '官方资料把绿色穆巴扎拉置于山脚，把沙漠公园置于杰贝尔哈菲特。请把交通规划为一般到达区域，而非逐向驾驶指引；出发前核实道路、停车和预约，尤其在天气变化或活动由运营方安排时。',
      'आधिकारिक स्रोत ग्रीन मुबज़्ज़राह को पर्वत तल और डेजर्ट पार्क को जेबेल हफीत पर बताते हैं। पहुँच को सामान्य आगमन क्षेत्र मानकर योजना बनाएं, मोड़-दर-मोड़ ड्राइविंग निर्देश नहीं; रवाना होने से पहले सड़क, पार्किंग और बुकिंग जाँचें, खासकर मौसम बदले या गतिविधि संचालित हो।',
    ], ['uae-jebel-hafeet-green-mubazzarah', 'uae-jebel-hafeet-visit-park', 'uae-jebel-hafeet-ncm-weather']),
    section('season', [
      'للموسم الحار، استخدموا توقعات المركز الوطني للأرصاد بدلاً من الاعتماد على متوسطات عامة، وبدلوا وقت المشي أو ألغوه إذا ظهرت حرارة شديدة أو رياح أو ضعف رؤية. قرار التخطيط اليومي أهم من اسم الموسم؛ تحققوا في اليوم نفسه.',
      'For hot-season planning, use National Center of Meteorology forecasts rather than broad averages, and change or cancel walking if severe heat, wind or poor visibility is forecast. The day-specific decision matters more than the season name; check on the day.',
      'Pour la saison chaude, utilisez les prévisions du Centre national de météorologie plutôt que des moyennes générales, et modifiez ou annulez la marche si chaleur forte, vent ou mauvaise visibilité sont prévus. La décision du jour compte plus que le nom de la saison ; vérifiez le jour même.',
      '炎热季节规划时，请使用国家气象中心预报，而不要依赖笼统平均值；若预报有强热、风或能见度差，应调整或取消步行。当天判断比季节名称更重要；请当天再核实。',
      'गरम मौसम की योजना में सामान्य औसत की बजाय राष्ट्रीय मौसम विज्ञान केंद्र का पूर्वानुमान देखें, और तेज गर्मी, हवा या कम दृश्यता हो तो पैदल कार्यक्रम बदलें या रद्द करें। मौसम के नाम से अधिक उसी दिन का निर्णय मायने रखता है; उसी दिन जाँचें।',
    ], ['uae-jebel-hafeet-ncm-weather']),
    section('nature', [
      'تصف هيئة البيئة جبل حفيت كمنطقة محمية جبلية ذات تنوع في الثدييات والطيور والزواحف والنباتات واللافقاريات، وتذكر الطهر العربي والنخيل القزم. حدود التعرف مهمة: لا تجعلوا هذه القائمة وعداً بالمشاهدة، ولا تجمعوا نباتات أو عينات.',
      'EAD describes Jabal Hafeet as a protected mountain area with mammals, birds, reptiles, plants and invertebrates, and notes Arabian tahr and dwarf palm. Identification limits matter: do not treat this list as a sighting promise, and do not collect plants or specimens.',
      'L’EAD décrit Jabal Hafeet comme une aire montagneuse protégée avec mammifères, oiseaux, reptiles, plantes et invertébrés, et cite le tahr d’Arabie et le palmier nain. Les limites d’identification comptent : cette liste ne promet aucune observation, et ne prélevez ni plantes ni spécimens.',
      '环境署把杰贝尔哈菲特描述为山地保护区，记录有哺乳动物、鸟类、爬行动物、植物和无脊椎动物，并提到阿拉伯塔尔羊和矮棕榈。识别有局限：不要把清单当成目击保证，也不要采集植物或样本。',
      'ईएडी जेबेल हफीत को स्तनधारियों, पक्षियों, सरीसृपों, पौधों और अकशेरुकी जीवों वाला संरक्षित पर्वतीय क्षेत्र बताता है, और अरबी तहर व बौने ताड़ का उल्लेख करता है। पहचान की सीमाएँ महत्वपूर्ण हैं: इस सूची को दर्शन का वादा न मानें, और पौधे या नमूने न लें।',
    ], ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-ead-network']),
    section('hazard', [
      'احتياطات الزيارة تبدأ بالحرارة والانكشاف والصخر. استنتاج عملي: ابقوا على المسارات المعلّمة ولا تدخلوا الشقوق أو الأودية عند تغير الطقس. في الطوارئ داخل الإمارات اتصلوا بالشرطة 999 أو الإسعاف 998 أو الدفاع المدني 997، واذكروا أقرب معلم معروف.',
      'Visit precautions start with heat, exposure and rock. Practical inference: stay on marked trails and do not enter crevices or wadis when weather changes. In UAE emergencies call police 999, ambulance 998 or civil defence 997, and give the nearest known landmark.',
      'Les précautions commencent par la chaleur, l’exposition et la roche. Déduction pratique : restez sur les sentiers balisés et n’entrez pas dans les fissures ou oueds si la météo change. En urgence aux Émirats, appelez police 999, ambulance 998 ou défense civile 997, puis donnez le repère connu le plus proche.',
      '游览注意事项首先是高温、暴露和岩石。实用推断：留在标明路线；天气变化时不要进入裂缝或河谷。阿联酋紧急情况请拨打警察999、救护998或民防997，并说明最近的已知地标。',
      'यात्रा सावधानियाँ गर्मी, खुलेपन और चट्टान से शुरू होती हैं। व्यावहारिक अनुमान: चिह्नित मार्गों पर रहें और मौसम बदलने पर दरारों या वादियों में न जाएँ। यूएई में आपात स्थिति में पुलिस 999, एम्बुलेंस 998 या सिविल डिफेंस 997 पर कॉल करें और निकटतम प्रसिद्ध स्थल बताएं।',
    ], ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-ncm-weather', 'uae-emergency']),
    section('visit', [
      'اختيار النشاط يعتمد على قدرتكم والوقت المتاح: تذكر زيارة أبوظبي النزهات العائلية في المبزرة، والمبيت في خيام عند القاعدة، والمشي أو التجربة داخل متنزه جبل حفيت. للمبتدئين، ابدؤوا بنشاط قصير ومعلن، وتحققوا من الحجز والطقس في اليوم نفسه.',
      'Choose the activity by ability and available time: Visit Abu Dhabi mentions family outings at Green Mubazzarah, tent stays at the base, and walking or experiences in Jebel Hafit Desert Park. For beginners, start with a short advertised activity, and check booking and weather on the day.',
      'Choisissez l’activité selon votre niveau et le temps disponible : Visit Abu Dhabi mentionne sorties familiales à Green Mubazzarah, nuit sous tente à la base, et marche ou expériences au parc désertique de Jebel Hafit. Débutants : commencez par une activité courte annoncée, puis vérifiez réservation et météo le jour même.',
      '按能力和可用时间选择活动：阿布扎比旅游资料提到绿色穆巴扎拉的家庭出游、山脚帐篷过夜，以及杰贝尔哈菲特沙漠公园内的步行或体验。初学者可从公开说明的短活动开始，并在当天核实预约和天气。',
      'गतिविधि अपनी क्षमता और उपलब्ध समय से चुनें: अबू धाबी पर्यटन ग्रीन मुबज़्ज़राह में पारिवारिक पिकनिक, आधार पर तंबू में रात और जेबेल हफीत डेजर्ट पार्क में पैदल या अन्य अनुभव बताता है। शुरुआती लोग छोटी घोषित गतिविधि से शुरू करें, और उसी दिन बुकिंग व मौसम जाँचें।',
    ], ['uae-jebel-hafeet-green-mubazzarah', 'uae-jebel-hafeet-visit-park', 'uae-jebel-hafeet-ncm-weather']),
    section('rules', [
      'القواعد المحلية مهمة لأن المنطقة تجمع محمية وتراثاً: نشرة هيئة البيئة تمنع النار، التغذية، قطع الأشجار، الكتابة على الصخور، تلويث التربة أو الماء، والمشي خارج المسارات، وتطلب إذناً للتخييم والطائرات المسيّرة. قواعد الطيران المدني تطلب التسجيل ومناطق مسموحة للطائرات المسيّرة؛ تحققوا في اليوم نفسه.',
      'Local rules matter because the area combines protection and heritage: the EAD factsheet says no fires, feeding, tree cutting, graffiti, soil or water pollution, or walking off marked trails, and requires permission for camping and drones. Civil aviation rules require drone registration and approved zones; check on the day.',
      'Les règles locales sont essentielles car le secteur mêle protection et patrimoine : la fiche EAD interdit feux, nourrissage, coupe d’arbres, graffiti, pollution du sol ou de l’eau et marche hors sentier, et exige une permission pour camping et drones. Les règles aériennes exigent enregistrement et zones autorisées ; vérifiez le jour même.',
      '本地规则很重要，因为这里兼具保护地和遗产价值：环境署资料禁止生火、投喂、砍树、涂写、污染土壤或水体以及离开标明路线，并要求露营和无人机取得许可。民航规则要求无人机登记并在许可区域飞行；当天请再核实。',
      'स्थानीय नियम महत्वपूर्ण हैं क्योंकि क्षेत्र संरक्षण और विरासत दोनों से जुड़ा है: ईएडी तथ्यपत्र आग, भोजन देना, पेड़ काटना, भित्तिलेखन, मिट्टी या जल प्रदूषण और चिह्नित मार्ग से बाहर चलना रोकता है, तथा कैंपिंग व ड्रोन के लिए अनुमति मांगता है। नागरिक उड्डयन नियम ड्रोन पंजीकरण और स्वीकृत क्षेत्र मांगते हैं; उसी दिन जाँचें।',
    ], ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-uae-aviation', 'uae-jebel-hafeet-culture-archaeology', 'uae-emergency']),
  ],
};

export const rules: PackingRule[] = [
  {
    id: 'uae-jebel-hafeet-water-sun',
    version: 1,
    equipmentId: 'uae-jebel-hafeet-water-sun',
    label: ['ماء وحماية من الشمس', 'Water and sun protection', 'Eau et protection solaire', '饮水和防晒', 'पानी और धूप से बचाव'],
    category: 'essentials',
    terrainIds: ['mountain'],
    activities: ['walking', 'camping', 'cycling'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['استنتاج عملي من تضاريس جبلية مكشوفة وتوقعات الطقس الرسمية: احملوا ماءً وحماية للشمس، وبدلوا الخطة عند الحر الشديد.', 'Practical inference from exposed mountain terrain and official weather forecasts: carry water and sun protection, and change the plan in severe heat.', 'Déduction pratique liée au relief exposé et aux prévisions officielles : emportez eau et protection solaire, et modifiez le plan en cas de forte chaleur.', '根据暴露山地和官方天气预报作出的实用推断：携带饮水和防晒用品，强热时调整计划。', 'खुले पर्वतीय भूभाग और आधिकारिक मौसम पूर्वानुमान से व्यावहारिक अनुमान: पानी और धूप से बचाव रखें, और तेज गर्मी में योजना बदलें।'],
    sourceIds: ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-ncm-weather'],
    coverage: 'local',
    destinationIds: ['jebel-hafeet'],
  },
  {
    id: 'uae-jebel-hafeet-closed-shoes',
    version: 1,
    equipmentId: 'uae-jebel-hafeet-closed-shoes',
    label: ['حذاء جبلي مغلق', 'Closed mountain footwear', 'Chaussures de montagne fermées', '包脚山地鞋', 'बंद पर्वतीय जूते'],
    category: 'clothing',
    terrainIds: ['mountain'],
    activities: ['walking'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: true,
    reason: ['المحمية تطلب البقاء على المسارات المعلّمة، والتضاريس صخرية؛ الحذاء المغلق يقلل الانزلاق والجروح عند المشي.', 'The protected area requires staying on marked trails, and the terrain is rocky; closed footwear reduces slips and cuts while walking.', 'L’aire protégée demande de rester sur les sentiers balisés et le terrain est rocheux ; des chaussures fermées limitent glissades et coupures.', '保护地要求留在标明路线，地形多岩石；包脚鞋可降低步行时滑倒和划伤风险。', 'संरक्षित क्षेत्र चिह्नित मार्गों पर रहने को कहता है और भूभाग चट्टानी है; बंद जूते चलते समय फिसलन और कटने का जोखिम घटाते हैं।'],
    sourceIds: ['uae-jebel-hafeet-ead-factsheet'],
    coverage: 'local',
    destinationIds: ['jebel-hafeet'],
  },
  {
    id: 'uae-jebel-hafeet-permission-check',
    version: 1,
    equipmentId: 'uae-jebel-hafeet-permission-check',
    label: ['قائمة تحقق للتصاريح', 'Permission checklist', 'Liste de vérification des permissions', '许可核对清单', 'अनुमति जाँच सूची'],
    category: 'safety',
    terrainIds: ['mountain'],
    activities: ['camping'],
    months: [],
    minDays: 0,
    transport: [],
    baseQuantity: 1,
    perPerson: false,
    reason: ['تطلب نشرة هيئة البيئة إذناً للتخييم والطائرات المسيّرة، وتطلب قواعد الدولة تسجيل الطائرات ومناطق مسموحة؛ تحققوا قبل المغادرة.', 'The EAD factsheet requires permission for camping and drones, and UAE rules require drone registration and approved zones; check before leaving.', 'La fiche EAD exige une permission pour camping et drones, et les règles nationales exigent enregistrement et zones autorisées ; vérifiez avant le départ.', '环境署资料要求露营和无人机取得许可，阿联酋规则要求无人机登记并在许可区域飞行；出发前核实。', 'ईएडी तथ्यपत्र कैंपिंग और ड्रोन के लिए अनुमति मांगता है, और यूएई नियम ड्रोन पंजीकरण व स्वीकृत क्षेत्र मांगते हैं; निकलने से पहले जाँचें।'],
    sourceIds: ['uae-jebel-hafeet-ead-factsheet', 'uae-jebel-hafeet-uae-aviation'],
    coverage: 'local',
    destinationIds: ['jebel-hafeet'],
  },
];
